ProgrammableWaveData_1::
	.incbin "sound/programmable_wave_samples/01.pcm"

ProgrammableWaveData_2::
	.incbin "sound/programmable_wave_samples/02.pcm"

ProgrammableWaveData_3::
	.incbin "sound/programmable_wave_samples/03.pcm"

ProgrammableWaveData_4::
	.incbin "sound/programmable_wave_samples/04.pcm"

ProgrammableWaveData_5::
	.incbin "sound/programmable_wave_samples/05.pcm"

ProgrammableWaveData_6::
	.incbin "sound/programmable_wave_samples/06.pcm"

ProgrammableWaveData_7::
	.incbin "sound/programmable_wave_samples/07.pcm"

ProgrammableWaveData_8::
	.incbin "sound/programmable_wave_samples/08.pcm"

ProgrammableWaveData_9::
	.incbin "sound/programmable_wave_samples/09.pcm"

ProgrammableWaveData_10::
	.incbin "sound/programmable_wave_samples/10.pcm"

ProgrammableWaveData_11::
	.incbin "sound/programmable_wave_samples/11.pcm"

ProgrammableWaveData_12::
	.incbin "sound/programmable_wave_samples/12.pcm"

ProgrammableWaveData_13::
	.incbin "sound/programmable_wave_samples/13.pcm"

ProgrammableWaveData_14::
	.incbin "sound/programmable_wave_samples/14.pcm"

ProgrammableWaveData_15::
	.incbin "sound/programmable_wave_samples/15.pcm"

ProgrammableWaveData_16::
	.incbin "sound/programmable_wave_samples/16.pcm"

@ Unused
ProgrammableWaveData_17::
	.incbin "sound/programmable_wave_samples/17.pcm"

@ Unused
ProgrammableWaveData_18::
	.incbin "sound/programmable_wave_samples/18.pcm"

@ Unused
ProgrammableWaveData_19::
	.incbin "sound/programmable_wave_samples/19.pcm"

@ Unused
ProgrammableWaveData_20::
	.incbin "sound/programmable_wave_samples/20.pcm"

ProgrammableWaveData_21::
	.incbin "sound/programmable_wave_samples/21.pcm"

ProgrammableWaveData_22::
	.incbin "sound/programmable_wave_samples/22.pcm"

ProgrammableWaveData_23::
	.incbin "sound/programmable_wave_samples/23.pcm"

ProgrammableWaveData_24::
	.incbin "sound/programmable_wave_samples/24.pcm"

ProgrammableWaveData_25::
	.incbin "sound/programmable_wave_samples/25.pcm"

ProgrammableWaveData_thpprf_pcm15::
	.incbin "sound/programmable_wave_samples/thpprf_pcm15.pcm"

ProgrammableWaveData_thpprf_pcm82::
	.incbin "sound/programmable_wave_samples/thpprf_pcm82.pcm"

ProgrammableWaveData_thpprf_pcm83::
	.incbin "sound/programmable_wave_samples/thpprf_pcm83.pcm"

ProgrammableWaveData_thpprf_pcm84::
	.incbin "sound/programmable_wave_samples/thpprf_pcm84.pcm"

ProgrammableWaveData_thpprf_pcm85::
	.incbin "sound/programmable_wave_samples/thpprf_pcm85.pcm"

ProgrammableWaveData_thpprf_pcm86::
	.incbin "sound/programmable_wave_samples/thpprf_pcm86.pcm"

ProgrammableWaveData_thpprf_pcm87::
	.incbin "sound/programmable_wave_samples/thpprf_pcm87.pcm"

ProgrammableWaveData_thpprf_pcm88::
	.incbin "sound/programmable_wave_samples/thpprf_pcm88.pcm"

ProgrammableWaveData_thpprf_pcm89::
	.incbin "sound/programmable_wave_samples/thpprf_pcm89.pcm"

ProgrammableWaveData_thpprf_pcm92::
	.incbin "sound/programmable_wave_samples/thpprf_pcm92.pcm"

ProgrammableWaveData_thpprf_pcm96::
	.incbin "sound/programmable_wave_samples/thpprf_pcm96.pcm"

ProgrammableWaveData_thpprf_pcm97::
	.incbin "sound/programmable_wave_samples/thpprf_pcm97.pcm"

ProgrammableWaveData_thpprf_pcm98::
	.incbin "sound/programmable_wave_samples/thpprf_pcm98.pcm"

