    .align 2
ProgrammableWaveData_1::
	.incbin "sound/programmable_wave_samples/01.pcm"

    .align 2
ProgrammableWaveData_2::
	.incbin "sound/programmable_wave_samples/02.pcm"

    .align 2
ProgrammableWaveData_3::
	.incbin "sound/programmable_wave_samples/03.pcm"

    .align 2
ProgrammableWaveData_4::
	.incbin "sound/programmable_wave_samples/04.pcm"

    .align 2
ProgrammableWaveData_5::
	.incbin "sound/programmable_wave_samples/05.pcm"

    .align 2
ProgrammableWaveData_6::
	.incbin "sound/programmable_wave_samples/06.pcm"

    .align 2
ProgrammableWaveData_7::
	.incbin "sound/programmable_wave_samples/07.pcm"

    .align 2
ProgrammableWaveData_8::
	.incbin "sound/programmable_wave_samples/08.pcm"

    .align 2
ProgrammableWaveData_9::
	.incbin "sound/programmable_wave_samples/09.pcm"

    .align 2
ProgrammableWaveData_10::
	.incbin "sound/programmable_wave_samples/10.pcm"

    .align 2
ProgrammableWaveData_11::
	.incbin "sound/programmable_wave_samples/11.pcm"

    .align 2
ProgrammableWaveData_12::
	.incbin "sound/programmable_wave_samples/12.pcm"

    .align 2
ProgrammableWaveData_13::
	.incbin "sound/programmable_wave_samples/13.pcm"

    .align 2
ProgrammableWaveData_14::
	.incbin "sound/programmable_wave_samples/14.pcm"

    .align 2
ProgrammableWaveData_15::
	.incbin "sound/programmable_wave_samples/15.pcm"

    .align 2
ProgrammableWaveData_16::
	.incbin "sound/programmable_wave_samples/16.pcm"

@ Unused
    .align 2
ProgrammableWaveData_17::
	.incbin "sound/programmable_wave_samples/17.pcm"

@ Unused
    .align 2
ProgrammableWaveData_18::
	.incbin "sound/programmable_wave_samples/18.pcm"

@ Unused
    .align 2
ProgrammableWaveData_19::
	.incbin "sound/programmable_wave_samples/19.pcm"

@ Unused
    .align 2
ProgrammableWaveData_20::
	.incbin "sound/programmable_wave_samples/20.pcm"

    .align 2
ProgrammableWaveData_21::
	.incbin "sound/programmable_wave_samples/21.pcm"

    .align 2
ProgrammableWaveData_22::
	.incbin "sound/programmable_wave_samples/22.pcm"

    .align 2
ProgrammableWaveData_23::
	.incbin "sound/programmable_wave_samples/23.pcm"

    .align 2
ProgrammableWaveData_24::
	.incbin "sound/programmable_wave_samples/24.pcm"

    .align 2
ProgrammableWaveData_25::
	.incbin "sound/programmable_wave_samples/25.pcm"

    .align 2
ProgrammableWaveData_pc_fwpcmh_wave_0827e8::
	.incbin "sound/programmable_wave_samples/pc_fwpcmh_wave_0827e8.pcm"

    .align 2
ProgrammableWaveData_pc_fwpcmh_wave_082858::
	.incbin "sound/programmable_wave_samples/pc_fwpcmh_wave_082858.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8653C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8653C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8654C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8654C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8655C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8655C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8656C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8656C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8657C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8657C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8658C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8658C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8659C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8659C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E865AC::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E865AC.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E865BC::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E865BC.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E865CC::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E865CC.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E865DC::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E865DC.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E865EC::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E865EC.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E865FC::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E865FC.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8660C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8660C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8661C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8661C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8662C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8662C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8663C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8663C.pcm"

    .align 2
ProgrammableWaveData_pmd_pcm_1E8664C::
	.incbin "sound/programmable_wave_samples/pmd_pcm_1E8664C.pcm"

    .align 2
ProgrammableWaveData_GoldenSun2pcm001::
    .incbin "sound/programmable_wave_samples/golden_sun_2_pcm_001.pcm"

    .align 2
ProgrammableWaveData_GoldenSun2pcm002::
    .incbin "sound/programmable_wave_samples/golden_sun_2_pcm_002.pcm"

    .align 2
ProgrammableWaveData_PkmnGSCRGBY00::
    .incbin "sound/programmable_wave_samples/gscrgby00.pcm"

    .align 2
ProgrammableWaveData_PkmnGSCRGBY01::
    .incbin "sound/programmable_wave_samples/gscrgby01.pcm"

    .align 2
ProgrammableWaveData_PkmnGSCRGBY02::
    .incbin "sound/programmable_wave_samples/gscrgby02.pcm"

    .align 2
ProgrammableWaveData_PkmnGSCRGBY03::
    .incbin "sound/programmable_wave_samples/gscrgby03.pcm"

    .align 2
ProgrammableWaveData_PkmnGSCRGBY04::
    .incbin "sound/programmable_wave_samples/gscrgby04.pcm"

    .align 2
ProgrammableWaveData_PkmnRGBY05::
    .incbin "sound/programmable_wave_samples/rgby05.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC05::
    .incbin "sound/programmable_wave_samples/gsc05.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC06::
    .incbin "sound/programmable_wave_samples/gsc06.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC07::
    .incbin "sound/programmable_wave_samples/gsc07.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC08::
    .incbin "sound/programmable_wave_samples/gsc08.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC09::
    .incbin "sound/programmable_wave_samples/gsc09.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC10::
    .incbin "sound/programmable_wave_samples/gsc10.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC11::
    .incbin "sound/programmable_wave_samples/gsc11.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC12::
    .incbin "sound/programmable_wave_samples/gsc12.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC13::
    .incbin "sound/programmable_wave_samples/gsc13.pcm"

    .align 2
ProgrammableWaveData_PkmnGSC14::
    .incbin "sound/programmable_wave_samples/gsc14.pcm"

    .align 2
ProgrammableWaveData_thppme_pcm_fff6f0::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff6f0.pcm"

    .align 2
ProgrammableWaveData_thppme_pcm_fff700::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff700.pcm"

    .align 2
ProgrammableWaveData_thppme_pcm_fff710::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff710.pcm"

    .align 2
ProgrammableWaveData_thppme_pcm_fff720::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff720.pcm"

    .align 2
ProgrammableWaveData_thppme_pcm_fff730::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff730.pcm"

    .align 2
ProgrammableWaveData_thppme_pcm_fff740::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff740.pcm"

    .align 2
ProgrammableWaveData_DgmnBS_37FB44::
	.incbin "sound/programmable_wave_samples/dgmnbs_37FB44.pcm"

    .align 2
ProgrammableWaveData_DgmnBS_37FB54::
	.incbin "sound/programmable_wave_samples/dgmnbs_37FB54.pcm"

    .align 2
ProgrammableWaveData_DgmnBS_37FB64::
	.incbin "sound/programmable_wave_samples/dgmnbs_37FB64.pcm"

    .align 2
ProgrammableWaveData_DgmnBS_37FB74::
	.incbin "sound/programmable_wave_samples/dgmnbs_37FB74.pcm"
