.include "sound/voicegroups/dummy.inc"

@ drumsets
.include "sound/voicegroups/drumsets/rs.inc"
.include "sound/voicegroups/drumsets/frlg.inc"
.include "sound/voicegroups/drumsets/emerald_1.inc"
.include "sound/voicegroups/drumsets/emerald_2.inc"

@ key splits
.include "sound/voicegroups/keysplits/piano.inc"
.include "sound/voicegroups/keysplits/strings.inc"
.include "sound/voicegroups/keysplits/trumpet.inc"
.include "sound/voicegroups/unused.inc"
.include "sound/voicegroups/keysplits/tuba.inc"
.include "sound/voicegroups/keysplits/french_horn.inc"

.include "sound/voicegroups/route110.inc"
.include "sound/voicegroups/route101.inc"
.include "sound/voicegroups/fanfare.inc"
.include "sound/voicegroups/gym.inc"
.include "sound/voicegroups/route120.inc"
.include "sound/voicegroups/petalburg.inc"
.include "sound/voicegroups/drumsets/petalburg.inc"
.include "sound/voicegroups/surf.inc"
.include "sound/voicegroups/petalburg_woods.inc"
.include "sound/voicegroups/oldale.inc"
.include "sound/voicegroups/lilycove_museum.inc"
.include "sound/voicegroups/route122.inc"
.include "sound/voicegroups/drumsets/route101.inc"
.include "sound/voicegroups/oceanic_museum.inc"
.include "sound/voicegroups/victory_gym_leader.inc"
.include "sound/voicegroups/victory_wild.inc"
.include "sound/voicegroups/evolution.inc"
.include "sound/voicegroups/encounter_girl.inc"
.include "sound/voicegroups/encounter_male.inc"
.include "sound/voicegroups/victory_league.inc"
.include "sound/voicegroups/abandoned_ship.inc"
.include "sound/voicegroups/drumsets/route110.inc"
.include "sound/voicegroups/fortree.inc"
.include "sound/voicegroups/birch_lab.inc"
.include "sound/voicegroups/littleroot_test.inc"
.include "sound/voicegroups/b_tower_rs.inc"
.include "sound/voicegroups/encounter_swimmer.inc"
.include "sound/voicegroups/cave_of_origin.inc"
.include "sound/voicegroups/roulette.inc"
.include "sound/voicegroups/link_contest_p1.inc"
.include "sound/voicegroups/link_contest_p2.inc"
.include "sound/voicegroups/link_contest_p3.inc"
.include "sound/voicegroups/link_contest_p4.inc"
.include "sound/voicegroups/encounter_rich.inc"
.include "sound/voicegroups/verdanturf.inc"
.include "sound/voicegroups/rustboro.inc"
.include "sound/voicegroups/poke_center.inc"
.include "sound/voicegroups/route104.inc"
.include "sound/voicegroups/route119.inc"
.include "sound/voicegroups/cycling.inc"
.include "sound/voicegroups/poke_mart.inc"
.include "sound/voicegroups/littleroot.inc"
.include "sound/voicegroups/mt_chimney.inc"
.include "sound/voicegroups/encounter_female.inc"
.include "sound/voicegroups/lilycove.inc"
.include "sound/voicegroups/route111.inc"
.include "sound/voicegroups/help.inc"
.include "sound/voicegroups/underwater.inc"
.include "sound/voicegroups/victory_trainer.inc"
.include "sound/voicegroups/title.inc"
.include "sound/voicegroups/intro.inc"
.include "sound/voicegroups/encounter_may.inc"
.include "sound/voicegroups/encounter_intense.inc"
.include "sound/voicegroups/encounter_cool.inc"
.include "sound/voicegroups/route113.inc"
.include "sound/voicegroups/encounter_aqua.inc"
.include "sound/voicegroups/follow_me.inc"
.include "sound/voicegroups/encounter_brendan.inc"
.include "sound/voicegroups/ever_grande.inc"
.include "sound/voicegroups/encounter_suspicious.inc"
.include "sound/voicegroups/victory_aqua_magma.inc"
.include "sound/voicegroups/cable_car.inc"
.include "sound/voicegroups/game_corner.inc"
.include "sound/voicegroups/dewford.inc"
.include "sound/voicegroups/safari_zone.inc"
.include "sound/voicegroups/victory_road.inc"
.include "sound/voicegroups/aqua_magma_hideout.inc"
.include "sound/voicegroups/sailing.inc"
.include "sound/voicegroups/mt_pyre.inc"
.include "sound/voicegroups/slateport.inc"
.include "sound/voicegroups/mt_pyre_exterior.inc"
.include "sound/voicegroups/school.inc"
.include "sound/voicegroups/hall_of_fame.inc"
.include "sound/voicegroups/fallarbor.inc"
.include "sound/voicegroups/sealed_chamber.inc"
.include "sound/voicegroups/contest_winner.inc"
.include "sound/voicegroups/contest.inc"
.include "sound/voicegroups/encounter_magma.inc"
.include "sound/voicegroups/intro_battle.inc"
.include "sound/voicegroups/abnormal_weather.inc"
.include "sound/voicegroups/weather_groudon.inc"
.include "sound/voicegroups/sootopolis.inc"
.include "sound/voicegroups/contest_results.inc"
.include "sound/voicegroups/hall_of_fame_room.inc"
.include "sound/voicegroups/trick_house.inc"
.include "sound/voicegroups/encounter_twins.inc"
.include "sound/voicegroups/encounter_elite_four.inc"
.include "sound/voicegroups/encounter_hiker.inc"
.include "sound/voicegroups/contest_lobby.inc"
.include "sound/voicegroups/encounter_interviewer.inc"
.include "sound/voicegroups/encounter_champion.inc"
.include "sound/voicegroups/credits.inc"
.include "sound/voicegroups/end.inc"
.include "sound/voicegroups/b_frontier.inc"
.include "sound/voicegroups/b_arena.inc"
.include "sound/voicegroups/register_match_call.inc"
.include "sound/voicegroups/b_pyramid.inc"
.include "sound/voicegroups/b_pyramid_top.inc"
.include "sound/voicegroups/b_palace.inc"
.include "sound/voicegroups/rayquaza_appears.inc"
.include "sound/voicegroups/b_tower.inc"
.include "sound/voicegroups/b_dome.inc"
.include "sound/voicegroups/b_pike.inc"
.include "sound/voicegroups/b_factory.inc"
.include "sound/voicegroups/vs_rayquaza.inc"
.include "sound/voicegroups/vs_frontier_brain.inc"
.include "sound/voicegroups/vs_mew.inc"
.include "sound/voicegroups/vs_wild.inc"
.include "sound/voicegroups/vs_aqua_magma.inc"
.include "sound/voicegroups/vs_trainer.inc"
.include "sound/voicegroups/vs_gym_leader.inc"
.include "sound/voicegroups/vs_champion.inc"
.include "sound/voicegroups/vs_regi.inc"
.include "sound/voicegroups/vs_kyogre_groudon.inc" @ duplicate of vs_rayquaza
.include "sound/voicegroups/vs_rival.inc"
.include "sound/voicegroups/vs_elite_four.inc"
.include "sound/voicegroups/vs_aqua_magma_leader.inc"
.include "sound/voicegroups/rs_sfx_1.inc"
.include "sound/voicegroups/rs_sfx_2.inc"
.include "sound/cry_tables.inc"
.include "sound/voicegroups/frlg_sfx.inc"
.include "sound/voicegroups/bard.inc"
.include "sound/voicegroups/unused_2.inc" @ used by unused GSC radio tower takeover test track in RS

@ FRLG
.include "sound/voicegroups/rg_follow_me.inc"
.include "sound/voicegroups/rg_game_corner.inc"
.include "sound/voicegroups/rg_rocket_hideout.inc"
.include "sound/voicegroups/rg_gym.inc"
.include "sound/voicegroups/rg_jigglypuff.inc"
.include "sound/voicegroups/rg_intro_fight.inc"
.include "sound/voicegroups/rg_title.inc"
.include "sound/voicegroups/rg_cinnabar.inc"
.include "sound/voicegroups/rg_lavender.inc"
.include "sound/voicegroups/rg_heal.inc"
.include "sound/voicegroups/rg_cycling.inc"
.include "sound/voicegroups/rg_encounter_rocket.inc"
.include "sound/voicegroups/rg_encounter_girl.inc"
.include "sound/voicegroups/rg_encounter_boy.inc"
.include "sound/voicegroups/rg_hall_of_fame.inc"
.include "sound/voicegroups/rg_viridian_forest.inc"
.include "sound/voicegroups/rg_mt_moon.inc"
.include "sound/voicegroups/rg_poke_mansion.inc"
.include "sound/voicegroups/rg_credits.inc"
.include "sound/voicegroups/rg_route1.inc"
.include "sound/voicegroups/rg_route24.inc"
.include "sound/voicegroups/rg_route3.inc"
.include "sound/voicegroups/rg_route11.inc"
.include "sound/voicegroups/rg_victory_road.inc"
.include "sound/voicegroups/rg_vs_gym_leader.inc"
.include "sound/voicegroups/rg_vs_trainer.inc"
.include "sound/voicegroups/rg_vs_wild.inc"
.include "sound/voicegroups/rg_vs_champion.inc"
.include "sound/voicegroups/rg_pallet.inc"
.include "sound/voicegroups/rg_oak_lab.inc"
.include "sound/voicegroups/rg_oak.inc"
.include "sound/voicegroups/rg_poke_center.inc"
.include "sound/voicegroups/rg_ss_anne.inc"
.include "sound/voicegroups/rg_surf.inc"
.include "sound/voicegroups/rg_poke_tower.inc"
.include "sound/voicegroups/rg_silph.inc"
.include "sound/voicegroups/rg_fuchsia.inc"
.include "sound/voicegroups/rg_celadon.inc"
.include "sound/voicegroups/rg_victory_trainer.inc"
.include "sound/voicegroups/rg_victory_wild.inc"
.include "sound/voicegroups/rg_victory_gym_leader.inc"
.include "sound/voicegroups/rg_vermillion.inc"
.include "sound/voicegroups/rg_pewter.inc"
.include "sound/voicegroups/rg_encounter_rival.inc"
.include "sound/voicegroups/rg_unused.inc"
.include "sound/voicegroups/rg_unused_2.inc"
.include "sound/voicegroups/rg_dex_rating.inc"
.include "sound/voicegroups/drumsets/frlg_fanfare_2.inc"
.include "sound/voicegroups/drumsets/frlg_fanfare_1.inc"
.include "sound/voicegroups/rg_obtain_key_item.inc"
.include "sound/voicegroups/rg_caught_intro.inc"
.include "sound/voicegroups/rg_photo.inc"
.include "sound/voicegroups/rg_game_freak.inc"
.include "sound/voicegroups/rg_new_game.inc"
.include "sound/voicegroups/rg_mystery_gift.inc"
.include "sound/voicegroups/rg_encounter_deoxys.inc"
.include "sound/voicegroups/rg_vs_deoxys.inc"
.include "sound/voicegroups/rg_teachy_tv_menu.inc"
.include "sound/voicegroups/rg_sevii_route.inc"
.include "sound/voicegroups/rg_sevii_45.inc"
.include "sound/voicegroups/rg_sevii_67.inc"
.include "sound/voicegroups/drumsets/rg_credits.inc"

@ Start custom keysplit instruments setting
.include "sound/voicegroups/voicegroup191.inc" @ Modified voicegroup001
.include "sound/voicegroups/voicegroup192.inc" @ Modified voicegroup002
.include "sound/voicegroups/voicegroup193.inc" @ Modified voicegroup003
.include "sound/voicegroups/voicegroup194.inc" @ Modified voicegroup004
.include "sound/voicegroups/voicegroup195.inc" @ Modified voicegroup005
.include "sound/voicegroups/voicegroup196.inc" @ Modified voicegroup006
.include "sound/voicegroups/voicegroup197.inc" @ Modified voicegroup007
.include "sound/voicegroups/voicegroup198.inc" @ Modified voicegroup008
.include "sound/voicegroups/voicegroup199.inc" @ Modified voicegroup009
@ End custom keysplit instruments setting

@ Start custom voicegroups
.include "sound/voicegroups/voicegroup200.inc" @ Custom GBA instrument only
.include "sound/voicegroups/voicegroup201.inc" @ [Main] Custom mixed instrument (GBA-HGSS-THPPRF)
.include "sound/voicegroups/voicegroup202.inc" @ Custom HGSS Base
.include "sound/voicegroups/voicegroup203.inc" @ DP voicegroup, based on copy of HGSS instrument
.include "sound/voicegroups/voicegroup204.inc" @ [Main] Custom 4
.include "sound/voicegroups/voicegroup205.inc" @ [Main] Custom 5
.include "sound/voicegroups/voicegroup206.inc" @ Simulated GB/GBC
.include "sound/voicegroups/voicegroup207.inc" @ Experimental
.include "sound/voicegroups/voicegroup208.inc" @ DirectSound Synth Test
.include "sound/voicegroups/voicegroup209.inc" @ DirectSound Synth
.include "sound/voicegroups/voicegroup210.inc" @ [Main] THPPRF custom
.include "sound/voicegroups/voicegroup211.inc" @ [Main] THPPZGS custom


@ After a custom voicegroup hits voicegroup215, please jump to voicegroup500+

@ --Start HGSS Voicegroups--
.include "sound/voicegroups/voicegroup216.inc"
.include "sound/voicegroups/voicegroup219.inc"
.include "sound/voicegroups/voicegroup220.inc"
.include "sound/voicegroups/voicegroup229.inc" @ [Main] HGSS-only instruments
.include "sound/voicegroups/voicegroup230.inc"
.include "sound/voicegroups/voicegroup231.inc"
.include "sound/voicegroups/voicegroup232.inc"
.include "sound/voicegroups/voicegroup233.inc"
.include "sound/voicegroups/voicegroup234.inc"
.include "sound/voicegroups/voicegroup235.inc"
.include "sound/voicegroups/voicegroup236.inc"
.include "sound/voicegroups/voicegroup237.inc"
.include "sound/voicegroups/voicegroup238.inc"
.include "sound/voicegroups/voicegroup239.inc"
.include "sound/voicegroups/voicegroup240.inc"
.include "sound/voicegroups/voicegroup241.inc"
.include "sound/voicegroups/voicegroup242.inc"
.include "sound/voicegroups/voicegroup243.inc"
.include "sound/voicegroups/voicegroup244.inc"
.include "sound/voicegroups/voicegroup245.inc"
.include "sound/voicegroups/voicegroup246.inc"
.include "sound/voicegroups/voicegroup247.inc"
.include "sound/voicegroups/voicegroup248.inc"
.include "sound/voicegroups/voicegroup249.inc"
.include "sound/voicegroups/voicegroup250.inc"
.include "sound/voicegroups/voicegroup251.inc"
.include "sound/voicegroups/voicegroup252.inc"
.include "sound/voicegroups/voicegroup253.inc"
.include "sound/voicegroups/voicegroup254.inc"
.include "sound/voicegroups/voicegroup255.inc"
.include "sound/voicegroups/voicegroup256.inc"
.include "sound/voicegroups/voicegroup257.inc"
.include "sound/voicegroups/voicegroup258.inc"
.include "sound/voicegroups/voicegroup259.inc"
.include "sound/voicegroups/voicegroup260.inc"
.include "sound/voicegroups/voicegroup261.inc"
.include "sound/voicegroups/voicegroup262.inc"
.include "sound/voicegroups/voicegroup263.inc"
.include "sound/voicegroups/voicegroup264.inc"
.include "sound/voicegroups/voicegroup265.inc"
.include "sound/voicegroups/voicegroup266.inc"
.include "sound/voicegroups/voicegroup267.inc"
.include "sound/voicegroups/voicegroup268.inc"
.include "sound/voicegroups/voicegroup269.inc"
.include "sound/voicegroups/voicegroup270.inc"
.include "sound/voicegroups/voicegroup271.inc"
.include "sound/voicegroups/voicegroup272.inc"
.include "sound/voicegroups/voicegroup273.inc"
@ --End HGSS Voicegroups--

@ --BW Voicegroup Mapping using HGSS/RSE Instruments
.include "sound/voicegroups/voicegroup274.inc"
.include "sound/voicegroups/voicegroup275.inc"
.include "sound/voicegroups/voicegroup276.inc"
.include "sound/voicegroups/voicegroup277.inc"
.include "sound/voicegroups/voicegroup278.inc"
.include "sound/voicegroups/voicegroup279.inc"
.include "sound/voicegroups/voicegroup280.inc"
.include "sound/voicegroups/voicegroup281.inc"
.include "sound/voicegroups/voicegroup282.inc"
.include "sound/voicegroups/voicegroup283.inc"
.include "sound/voicegroups/voicegroup284.inc"
.include "sound/voicegroups/voicegroup285.inc"
.include "sound/voicegroups/voicegroup286.inc"

.include "sound/voicegroups/voicegroup500.inc" @ --Blank voicegroup--

@ --Start Futari wa Precure MH GBA Voicegroups--
.include "sound/voicegroups/voicegroup501.inc" @ [Main] Futari wa Precure MH GBA instruments
.include "sound/voicegroups/voicegroup502.inc" @ Futari wa Precure MH GBA drum set 1
.include "sound/voicegroups/voicegroup503.inc" @ Futari wa Precure MH GBA drum set 2
@ --End Futari wa Precure MH GBA Voicegroups--

@ --Start PMD GBA Voicegroups--
.include "sound/voicegroups/voicegroup504.inc" @ [Main] PMD GBA main 1 instruments for squence 1 - 99
.include "sound/voicegroups/voicegroup505.inc" @ [Main] PMD GBA main 2 instruments for squence 100 - 199
.include "sound/voicegroups/voicegroup506.inc" @ PMD GBA Drum 1
.include "sound/voicegroups/voicegroup507.inc" @ PMD GBA Drum 2
.include "sound/voicegroups/voicegroup508.inc"
.include "sound/voicegroups/voicegroup509.inc"
.include "sound/voicegroups/voicegroup510.inc"
.include "sound/voicegroups/voicegroup511.inc"
.include "sound/voicegroups/voicegroup512.inc"
.include "sound/voicegroups/voicegroup513.inc"
.include "sound/voicegroups/voicegroup514.inc"
.include "sound/voicegroups/voicegroup515.inc"
.include "sound/voicegroups/voicegroup516.inc"
.include "sound/voicegroups/voicegroup517.inc"
.include "sound/voicegroups/voicegroup518.inc"
.include "sound/voicegroups/voicegroup519.inc"
.include "sound/voicegroups/voicegroup520.inc"
.include "sound/voicegroups/voicegroup521.inc"
.include "sound/voicegroups/voicegroup522.inc"
.include "sound/voicegroups/voicegroup523.inc"
.include "sound/voicegroups/voicegroup524.inc"
.include "sound/voicegroups/voicegroup525.inc"
.include "sound/voicegroups/voicegroup526.inc"
.include "sound/voicegroups/voicegroup527.inc"
.include "sound/voicegroups/voicegroup528.inc"
.include "sound/voicegroups/voicegroup529.inc"
.include "sound/voicegroups/voicegroup530.inc"
@ --End PMD GBA Voicegroups--

.include "sound/voicegroups/voicegroup601.inc" @ [Main] GBA Golden Sun
.include "sound/voicegroups/voicegroup602.inc" @ GBA Golden Sun Drum

.include "sound/voicegroups/voicegroup701.inc" @ Modified voicegroup191 GBA Drum 1
.include "sound/voicegroups/voicegroup702.inc" @ Modified voicegroup192 GBA Drum 2
.include "sound/voicegroups/voicegroup703.inc" @ Modified voicegroup193 GBA Drum 3
.include "sound/voicegroups/voicegroup704.inc" @ Modified voicegroup194 
.include "sound/voicegroups/voicegroup705.inc" @ Modified voicegroup195
.include "sound/voicegroups/voicegroup706.inc" @ Modified voicegroup196
.include "sound/voicegroups/voicegroup707.inc" @ Modified voicegroup197
.include "sound/voicegroups/voicegroup708.inc" @ Modified voicegroup198
.include "sound/voicegroups/voicegroup709.inc" @ Modified voicegroup199

.include "sound/voicegroups/voicegroup710.inc" @ Modified voicegroup191 HGSS Drum
.include "sound/voicegroups/voicegroup711.inc" @ Modified voicegroup192 HGSS Taiko Drum
.include "sound/voicegroups/voicegroup712.inc" @ Modified voicegroup193 HGSS Taiko Drum 2
.include "sound/voicegroups/voicegroup713.inc" @ Modified HGSS Music Box Multi Sample
.include "sound/voicegroups/voicegroup714.inc" @ Modified HGSS Piano Multi Sample

.include "sound/voicegroups/voicegroup801.inc" @ Game corner expansion
.include "sound/voicegroups/voicegroup802.inc" @ ラフィーニャ / ジャスミン / @redspinelj
.include "sound/voicegroups/voicegroup803.inc" @ Velo: IFM
.include "sound/voicegroups/voicegroup804.inc" @ Velo: IFM Drum
.include "sound/voicegroups/voicegroup805.inc" @ Megaman Battle Network 6 Mapping (Partial)
.include "sound/voicegroups/voicegroup806.inc" @ Megaman Battle Network 6 Drum Mapping (Partial)
.include "sound/voicegroups/voicegroup807.inc" @ THPP Music Expansion Drum 1
.include "sound/voicegroups/voicegroup808.inc" @ THPP Music Expansion Drum 2
.include "sound/voicegroups/voicegroup809.inc" @ THPP Music Expansion Main 1 - Mr. Unknown's
.include "sound/voicegroups/voicegroup810.inc" @ THPP Music Expansion Main 2 - Reincarnation
.include "sound/voicegroups/voicegroup811.inc" @ THPP Music Expansion Main 3 - Uda's
.include "sound/voicegroups/voicegroup812.inc" @ Shizukana Shizukana Native Faith
.include "sound/voicegroups/voicegroup813.inc" @ Shizukana Shizukana Native Faith Piano Split
.include "sound/voicegroups/voicegroup814.inc" @ Climax Jump
.include "sound/voicegroups/voicegroup815.inc" @ THPP Zoku Gensokyo - Main Voicegroup
.include "sound/voicegroups/voicegroup816.inc" @ THPP Zoku Gensokyo - Drum Kit
.include "sound/voicegroups/voicegroup817.inc" @ THPP Zoku Gensokyo - Custom voicegroup156
.include "sound/voicegroups/voicegroup818.inc" @ THPP Zoku Gensokyo - Custom voicegroup143
.include "sound/voicegroups/voicegroup819.inc" @ THPP Zoku Gensokyo - Custom voicegroup157
.include "sound/voicegroups/voicegroup820.inc" @ THPP Zoku Gensokyo - Custom voicegroup158
.include "sound/voicegroups/voicegroup821.inc" @ THPP Zoku Gensokyo - Custom voicegroup026
.include "sound/voicegroups/voicegroup822.inc" @ THPP Zoku Gensokyo - Custom voicegroup133
.include "sound/voicegroups/voicegroup823.inc" @ THPP Zoku Gensokyo - Custom voicegroup137
.include "sound/voicegroups/voicegroup824.inc" @ THPP Zoku Gensokyo - Custom voicegroup142
.include "sound/voicegroups/voicegroup825.inc" @ THPP Zoku Gensokyo - Custom voicegroup165
.include "sound/voicegroups/voicegroup826.inc" @ THPP Zoku Gensokyo - Custom voicegroup162

.include "sound/voicegroups/voicegroup900.inc" @ New Sound Effects
.include "sound/voicegroups/voicegroup901.inc" @ CtC G Free

.include "sound/voicegroups/voicegroup999.inc" @ Test Instrument

