voice_group climax_jump
	voice_keysplit_all voicegroup_allkeysplit_thppme_drum_1                                                      @ 000 | Direct | Drum | FLRG Drum
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 001 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 002 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 003 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 249, 0, 188  @ 004 | Direct | GBA Electric Piano 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 005 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 006 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 007 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 008 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 009 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 010 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 011 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 012 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 013 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 014 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 015 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 016 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 017 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 018 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 019 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 020 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 021 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 022 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 023 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 249, 25, 204   @ 024 | Direct | GBA Nylon Guitar 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 165, 128, 204  @ 025 | Direct | GBA Nylon Guitar 2
	voice_keysplit voicegroup_keysplit_hgss_martin_guitar, keysplit_hgss_guitar                                         @ 026 | Direct | Multi | HGSS Martin Guitar
	voice_keysplit voicegroup_keysplit_hgss_clean_guitar, keysplit_hgss_guitar                                         @ 027 | Direct | Multi | HGSS Clean Guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 028 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 029 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 030 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 031 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 032 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 033 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 034 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 035 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 036 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 037 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 146     @ 038 | Direct | GBA Synth Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 039 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 040 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 041 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 042 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 043 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 044 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 045 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 046 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 047 | --- | 
	voice_keysplit voicegroup_keysplit_strings_custom, keysplit_strings                                          @ 048 | Direct | Multi | GBA String
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 049 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 050 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 051 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 052 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 053 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 054 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 055 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 056 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 057 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 058 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 059 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 060 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 061 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 062 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 063 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 064 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 065 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 066 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 067 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 068 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 069 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 070 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 071 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 072 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 073 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 074 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 075 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 076 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 077 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 078 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 079 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 080 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 081 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 082 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 083 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 084 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 085 | --- | 
	voice_square_2_alt 60, 0, 3, 0, 1, 4, 1                                               @ 086 | Square2 | GBA
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 087 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 088 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 089 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 094 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 096 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 097 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 098 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 099 | --- | 
	stream_directsound 60, 0, DirectSoundWaveData_se_etc_zeronos, 255, 0, 255, 0          @ 100 | Direct Compressed | Zeronos Effect
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 101 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 102 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 103 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 106 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 107 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 110 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 111 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 112 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 113 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 115 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 116 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16         @ 119 | Direct | HGSS Reverse Cymbal
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum                                                      @ 120 | Direct | Drum | HGSS Drum
	voice_keysplit_all voicegroup_allkeysplit_hgss_taiko_drum                                                      @ 121 | Direct | Drum | HGSS Taiko Drum
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 216  @ 122 | Direct | GBA Cymbal 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216  @ 123 | Direct | GBA Cymbal 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127       @ 124 | Direct | GBA Hand Clap
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171             @ 125 | Direct | HGSS Sawtooth
	voice_noise_alt 60, 0, 0, 0, 2, 6, 2                                                           @ 126 | Noise | GBA Noise 1
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0                                                  @ 127 | Noise | GBA Noise 2
