voice_group custom_204_experimental
	voice_keysplit_all voicegroup_allkeysplit_frlg_custom_drum                                                                         @ 000 | Drum | GBA Pokemon Emerald Drum
	voice_keysplit voicegroup_keysplit_piano_custom, keysplit_piano                                                             @ 001 | Direct | GBA Pokemon Emerald Piano 1
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 128, 204, 51, 242                         @ 002 | Direct | GBA Pokemon Emerald Piano 2
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 206, 242                         @ 003 | Direct | GBA Pokemon Emerald Koto 2
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 249, 0, 188            @ 004 | Direct | GBA Pokemon Emerald Electric Piano 1
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 188, 103, 165         @ 005 | Direct | GBA Pokemon Emerald Electric Piano 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0                                   @ 006 | Wave | GBA Programmable Wave 1
	voice_square_2_alt 60, 0, 3, 0, 3, 4, 0                                                                  @ 007 | Square-2 |
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_celesta, 255, 0, 255, 165                      @ 008 | Direct | GBA Golden Sun 2 Celesta
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242                     @ 009 | Direct | GBA Pokemon Emerald Glockenspiel
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0                   @ 010 | Direct | GBA Pokemon Emerald Flavours Atarigane
	voice_directsound 60, 0, DirectSoundWaveData_heart_of_asia_gamelan, 255, 188, 139, 239                   @ 011 | Direct | GBA Pokemon Emerald Gamelan
	voice_directsound 60, 0, DirectSoundWaveData_unknown_bell, 255, 235, 0, 204                              @ 012 | Direct | GBA Pokemon Emerald Unknown Bell
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204                         @ 013 | Direct | GBA Pokemon Emerald Xylophone
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 216                     @ 014 | Direct | GBA Pokemon Emerald Tubular Bell
	voice_keysplit voicegroup_keysplit_hgss_drawbar_organ, keysplit_hgss_organ_accordion_harp_timpani                                                            @ 015 | Direct | HGSS drawbar organ
	voice_keysplit voicegroup_keysplit_hgss_jazz_organ, keysplit_hgss_organ_accordion_harp_timpani                                                            @ 016 | Direct | HGSS jazz organ
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127                            @ 017 | Direct | GBA Pokemon Emerald Organ
	voice_keysplit voicegroup_keysplit_hgss_music_box, keysplit_hgss_marimba_music_box_sampled_square                                                            @ 018 | Direct | HGSS Music Box
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188                @ 019 | Direct | GBA Pokemon Emerald Crunch Organ 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188               @ 020 | Direct | GBA Pokemon Emerald Crunch Organ 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165                         @ 021 | Direct | GBA Pokemon Emerald Accordian
	voice_keysplit voicegroup_keysplit_hgss_jazz_organ, keysplit_hgss_organ_accordion_harp_timpani                                                            @ 022 | Direct | HGSS Jazz Organ
	voice_keysplit voicegroup_keysplit_hgss_accordion, keysplit_hgss_organ_accordion_harp_timpani                                                            @ 023 | Direct | HGSS Accordion
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 249, 25, 204                 @ 024 | Direct | GBA Pokemon Emerald Nylon Guitar 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 165, 128, 204                @ 025 | Direct | GBA Pokemon Emerald Nylon Guitar 2
	voice_keysplit voicegroup_keysplit_hgss_nylon_guitar, keysplit_hgss_guitar                                                            @ 026 | Direct | HGSS Nylon Guitar
	voice_keysplit voicegroup_keysplit_hgss_martin_guitar, keysplit_hgss_guitar                                                            @ 027 | Direct | HGSS Martin Guitar
	voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 0, 255, 127       @ 028 | Direct | GBA Pokemon Emerald Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127           @ 029 | Direct | GBA Pokemon Emerald Overdrive Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 165, 154, 165   @ 030 | Direct | GBA Pokemon Emerald Distortion Guitar 1
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 195                 @ 031 | Direct | GBA Pokemon Emerald Special Scream Drive
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149                     @ 032 | Direct | GBA Pokemon Emerald Fretless Bass 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149                     @ 033 | Direct | GBA Pokemon Emerald Fingered Bass
	voice_directsound 60, 0, DirectSoundWaveData_unknown_snare, 255, 253, 0, 149                             @ 034 | Direct | GBA Pokemon Emerald Snare
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 198                     @ 035 | Direct | GBA Pokemon Emerald Fretless Bass 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 115                       @ 036 | Direct | GBA Pokemon Emerald Slap Bass
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 180, 216              @ 037 | Direct | GBA Pokemon Emerald Unison Bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 146                        @ 038 | Direct | GBA Pokemon Emerald Synth Bass
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_16, 0, 7, 15, 1                                  @ 039 | Wave | GBA Wave Sound 16
	voice_keysplit voicegroup_keysplit_hgss_violin, keysplit_hgss_violin                                                            @ 040 | Direct | HGSS Violin
	voice_keysplit voicegroup_keysplit_hgss_upright_bass, keysplit_hgss_upright_bass                                                            @ 041 | Direct | HGSS Upright Bass
	voice_keysplit voicegroup_keysplit_hgss_cello, keysplit_hgss_cello_trombone                                                            @ 042 | Direct | HGSS Cello
	voice_keysplit voicegroup_keysplit_hgss_rhodes_1, keysplit_dp_rhodes                                                             @ 043 | Direct | HGSS Rhodes 1
	voice_keysplit voicegroup_keysplit_hgss_rhodes_2, keysplit_dp_rhodes                                                             @ 044 | Direct | HGSS Rhodes 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165                 @ 045 | Direct | GBA Pokemon Emerald Pizzicato
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 51, 242                             @ 046 | Direct | GBA Pokemon Emerald Harp
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226                           @ 047 | Direct | GBA Pokemon Emerald Timpani
	voice_keysplit voicegroup_keysplit_strings_custom, keysplit_strings                                                             @ 048 | Direct | GBA Pokemon Emerald Strings Ensemble
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_string_ensemble, 255, 0, 255, 165              @ 049 | Direct | GBA Golden Sun String Ensemble
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                                                            @ 050 | Direct | HGSS Strings
	voice_keysplit voicegroup_keysplit_hgss_fingered_bass, keysplit_hgss_fingered_bass                                                            @ 051 | Direct | HGSS Fingered Bass
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 128, 165, 128, 188              @ 052 | Direct | GBA Pokemon Emerald Choir Ahhs
	voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 128, 165, 128, 204                    @ 053 | Direct | GBA Pokemon Emerald Female Voice Ahhs
	voice_directsound 60, 0, DirectSoundWaveData_unused_unknown_male_voice, 128, 165, 128, 188               @ 054 | Direct | GBA Pokemon Emerald Male Voice Ahhs
	voice_keysplit voicegroup_keysplit_hgss_orchestral_hit, keysplit_hgss_orchestral_hit                                                            @ 055 | Direct | HGSS Orchestra Hit
	voice_keysplit voicegroup_keysplit_trumpet_custom, keysplit_trumpet                                                             @ 056 | Direct | GBA Pokemon Emerald Trumpet
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 165, 154, 127                       @ 057 | Direct | GBA Pokemon Emerald Trinity Big Boned
	voice_keysplit voicegroup_keysplit_tuba_custom, keysplit_tuba                                                             @ 058 | Direct | GBA Pokemon Emerald Tuba
	voice_directsound 60, 0, DirectSoundWaveData_unknown_18, 255, 0, 206, 204                                @ 059 | Direct | GBA Pokemon Emerald Unknown Instrument 18
	voice_keysplit voicegroup_keysplit_french_horn_custom, keysplit_french_horn                                                             @ 060 | Direct | GBA Pokemon Emerald French Horn
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_brass, 255, 0, 255, 165                        @ 061 | Direct | GBA Golden Sun 2 Brass Section
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 165, 180, 165    @ 062 | Direct | GBA Pokemon Emerald Distortion Guitar 2
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_hgss_distortion_guitar                                                            @ 063 | Direct | HGSS Distortion Guitar 1
	voice_keysplit voicegroup_keysplit_hgss_clean_guitar, keysplit_hgss_guitar                                                            @ 064 | Direct | HGSS Clean Guitar
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                        @ 065 | Direct | HGSS Altosax
	voice_keysplit voicegroup_keysplit_hgss_trombone, keysplit_hgss_cello_trombone                                                            @ 066 | Direct | HGSS Trombones
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_romantic_trumpet, 240, 200, 245, 220                 @ 067 | Direct | RF Romantic Trumpet 1
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165                      @ 068 | Direct | GBA Pokemon Emerald Oboe 1
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 43, 165, 103, 165                         @ 069 | Direct | GBA Pokemon Emerald Oboe 2
	voice_keysplit voicegroup_keysplit_hgss_bassoon, keysplit_hgss_bassoon                                                            @ 070 | Direct | HGSS Bassoon
	voice_keysplit voicegroup_keysplit_hgss_clarinet, keysplit_hgss_clarinet                                                            @ 071 | Direct | HGSS Clarinet
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_piccolo, 255, 0, 255, 165                      @ 072 | Direct | GBA Golden Sun 2 Piccolo
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127                           @ 073 | Direct | GBA Pokemon Emerald Flute
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0                                   @ 074 | Wave | GBA Programmable Wave 6
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165                @ 075 | Direct | GBA Pokemon Emerald Delay Shaku
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_pan_flute, 255, 0, 255, 165                    @ 076 | Direct | GBA Golden Sun 2 Pan Flute
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204                 @ 077 | Direct | GBA Pokemon Emerald Shakuhachi
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 43, 76, 103, 216                    @ 078 | Direct | GBA Pokemon Emerald Whistle
	voice_keysplit voicegroup_keysplit_hgss_flute, keysplit_hgss_flute                                                            @ 079 | Direct | HGSS Flute
	voice_square_2_alt 60, 0, 2, 0, 2, 4, 1                                                                  @ 080 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 4, 1                                                               @ 081 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0                                   @ 082 | Wave | GBA Programmable Wave 1
	voice_square_2_alt 60, 0, 3, 0, 3, 6, 2                                                                  @ 083 | Square-2 |
	voice_square_2_alt 60, 0, 0, 0, 2, 6, 5                                                                  @ 084 | Square-2 |
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 4, 1                                                               @ 085 | Square-1 |
	voice_square_2_alt 60, 0, 3, 0, 1, 4, 1                                                                  @ 086 | Square-2 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_21, 0, 7, 15, 1                                  @ 087 | Wave | GBA Programmable Wave 21
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0                                   @ 088 | Wave | GBA Programmable Wave 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_15, 0, 1, 9, 2                                   @ 089 | Wave | GBA Programmable Wave 15
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127                         @ 090 | Direct | GBA Pokemon Emerald Trinity Big Boned
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0                  @ 091 | Direct | GBA Pokemon Emerald Choir Ahhs 2
	voice_square_2_alt 60, 0, 2, 0, 2, 6, 3                                                                  @ 092 | Square-2 |
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 251, 0, 171                         @ 093 | Direct | HGSS Wood Bass
	voice_keysplit voicegroup_keysplit_hgss_koto, keysplit_hgss_koto                                                            @ 094 | Direct | HGSS Koto
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                       @ 095 | Direct | HGSS Sawtooth
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_church_organ, 170, 180, 160, 235                     @ 096 | Direct | RF Church Organ
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_choir_ohhs, 255, 188, 220, 243                       @ 097 | Direct | RF Choir Ohhs
	voice_directsound 60, 65, DirectSoundWaveData_thpprf_choir_ahhs, 255, 205, 220, 243                      @ 098 | Direct | RF Choir Ahhs
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_applause, 170, 160, 180, 210                         @ 099 | Direct | RF Applause 1
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_music_box, 255, 0, 255, 235                          @ 100 | Direct | RF Music Box
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_overdrive_guitar, 250, 250, 250, 190                 @ 101 | Direct | RF Overdrive Guitar
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_applause2, 170, 160, 180, 210                        @ 102 | Direct | RF Applause 2
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_thpprf_unison_slap, 255, 165, 180, 216               @ 103 | Direct | RF Unison Slap Bass
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_square_wave, 255, 0, 255, 127                        @ 104 | Direct | RF Sampled Square Wave
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_xylophone, 255, 235, 103, 178                  @ 105 | Direct | GBA Golden Sun Xylophone / Gamelan
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_indian_raag_effect, 255, 242, 103, 178         @ 106 | Direct | GBA Golden Sun Indian Raag Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_wood_block, 255, 0, 255, 165                   @ 107 | Direct | GBA Golden Sun Wood Block
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_woh_voice_effect, 255, 0, 255, 165             @ 108 | Direct | GBA Golden Sun Woh Voice Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_asian_gamelan_part1, 255, 0, 255, 165          @ 109 | Direct | GBA Golden Sun Gamelan Part 1
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_asian_gamelan_part2, 255, 235, 103, 178        @ 110 | Direct | GBA Golden Sun Gamelan Part 2
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_indian_sarod, 255, 0, 255, 165                 @ 111 | Direct | GBA Golden Sun Indian Sarod
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_beat_loop1, 255, 0, 255, 165                   @ 112 | Direct | GBA Golden Sun Drum Beat Loop
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_beat_loop2, 255, 0, 255, 165                   @ 113 | Direct | GBA Golden Sun Jungle Beat Loop
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_tropical_piano, 255, 235, 103, 178             @ 114 | Direct | GBA Golden Sun Tropical Piano
	voice_directsound 80, 0, DirectSoundWaveData_golden_sun_2_taiko, 255, 0, 255, 0                          @ 115 | Direct | GBA Golden Sun Taiko?
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 7, 15, 0                                   @ 116 | Wave | GBA Programmable Wave 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_18, 0, 7, 15, 0                                  @ 117 | Wave | GBA Programmable Wave 18
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_2, 1, 7, 2, 15                                   @ 118 | Wave | GBA Programmable Wave 2
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16                            @ 119 | Direct | HGSS Reverse Cymbal
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum                                                                         @ 120 | Drum | HGSS Drum
	voice_keysplit_all voicegroup_allkeysplit_hgss_taiko_drum                                                                         @ 121 | Drum | HGSS Taiko Drum
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 216            @ 122 | Direct | GBA Pokemon Emerald Cymbal 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216            @ 123 | Direct | GBA Pokemon Emerald Cymbal 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127                 @ 124 | Direct | GBA Pokemon Emerald Hand Clap
	voice_keysplit_all voicegroup_allkeysplit_golden_sun_2_drum                                                                         @ 125 | Drum | GBA Golden Sun 2 Drum
	voice_noise_alt 60, 0, 0, 0, 2, 6, 2                                                                     @ 126 | Noise |
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0                                                                     @ 127 | Noise |

