voice_group gbc_2_experimental
	voice_keysplit_all voicegroup_allkeysplit_frlg_custom_2_drum                                                      @ 000 | Direct | RSE Drum 1 | VVVVV
	voice_square_1_alt 60, 0, 0, 2, 0, 3, 10, 4                                           @ 001 | GB Square1 | Pewter GBC Ch. 1
	voice_square_2_alt 60, 0, 1, 0, 7, 11, 7                                              @ 002 | GB Square2 | Pewter GBC Ch. 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_PkmnGSCRGBY03, 0, 7, 12, 0    @ 003 | GB Wave    | Pewter GBC Ch. 3
	voice_square_1_alt 60, 0, 0, 2, 0, 5, 12, 7                                           @ 004 | GB Square1 | Ecruteak GBC Ch. 1.1.1 duty_cycle 2 vibrato 18, 2, 5 note_type 12, 5, 7
	voice_square_1_alt 60, 0, 0, 2, 0, 6, 6, 7                                            @ 005 | GB Square1 | Ecruteak GBC Ch. 1.2.1 duty_cycle 2 note_type 6, 6, 7
	voice_square_1_alt 60, 0, 0, 0, 0, 5, 12, 7                                           @ 006 | GB Square1 | Ecruteak GBC Ch. 1.1.2 duty_cycle 0 vibrato 18, 2, 5 note_type 12, 5, 7
	voice_square_1_alt 60, 0, 0, 0, 0, 6, 6, 7                                            @ 007 | GB Square1 | Ecruteak GBC Ch. 1.2.2 duty_cycle 0 note_type 6, 6, 7
	voice_square_2_alt 60, 0, 3, 0, 6, 6, 7                                               @ 008 | GB Square2 | Ecruteak GBC Ch. 2.1.1 duty_cycle 3 vibrato 18, 2, 5 note_type 6, 6, 7
	voice_square_2_alt 60, 0, 3, 0, 7, 12, 7                                              @ 009 | GB Square2 | Ecruteak GBC Ch. 2.2 duty_cycle 3 note_type 12, 7, 7
	voice_square_2_alt 60, 0, 2, 0, 3, 9, 7                                               @ 010 | GB Square2 | Ecruteak GBC Ch. 2.3.1 duty_cycle 2 note_type 6, 9, 3
	voice_square_2_alt 60, 0, 0, 0, 3, 9, 7                                               @ 011 | GB Square2 | Ecruteak GBC Ch. 2.3.2 duty_cycle 0 note_type 6, 9, 3
	voice_square_2_alt 60, 0, 1, 0, 3, 9, 7                                               @ 012 | GB Square2 | Ecruteak GBC Ch. 2.3.3 duty_cycle 1 note_type 6, 9, 3
	voice_square_2_alt 60, 0, 1, 0, 8, 12, 3                                              @ 013 | GB Square2 | Ecruteak GBC Ch. 2.4 note_type 12, 8, 3
	voice_square_2_alt 60, 0, 1, 0, 8, 12, 0                                              @ 014 | GB Square2 | Ecruteak GBC Ch. 2.5 note_type 6, 8, 0
	voice_square_2_alt 60, 0, 1, 0, 8, 12, 7                                              @ 015 | GB Square2 | Ecruteak GBC Ch. 2.6 note_type 12, 8, 7
	voice_square_2_alt 60, 0, 1, 0, 6, 6, 7                                               @ 016 | GB Square2 | Ecruteak GBC Ch. 2.1.2 duty_cycle 1 vibrato 18, 2, 5 note_type 6, 6, 7
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_PkmnGSC05, 0, 2, 12, 7        @ 017 | GB Wave    | Ecruteak GBC Ch. 3.1 vibrato 18, 2, 5 note_type 12, 2, 5
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_PkmnGSC05, 0, 2, 12, 7        @ 018 | GB Wave    | Ecruteak GBC Ch. 3.2 note_type 12, 2, 5
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_PkmnGSC05, 0, 2, 6, 7         @ 019 | GB Wave    | Ecruteak GBC Ch. 3.3 note_type 6, 2, 5
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 5, 2                                            @ 020 | GB Square1 | Trainer Battle GBC Ch. 1.1 duty_cycle 3 vibrato 18, 1, 5 note_type 12, 9, 2
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 7, 3                                            @ 021 | GB Square1 | Trainer Battle GBC Ch. 1.2 duty_cycle 3 vibrato 0, 0, 0 note_type 12, 10, 3
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 3                                               @ 022 | GB Square2 | Trainer Battle GBC Ch. 2 duty_cycle 1 vibrato 8, 3, 6 note_type 12, 12, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 2, 7, 3                 @ 023 | GB Wave    | Trainer Battle GBC Ch. 3.1 vibrato 0, 0, 0 note_type 12, 1, 9
	voice_directsound 60, 0, DirectSoundSynth_Type_01, 255, 0, 255, 165                   @ 024 | Synth | Reincarnation GBC Ch. 1
	voice_directsound 60, 0, DirectSoundSynth_Type_02, 85, 165, 193, 178                  @ 025 | Synth | Reincarnation GBC Ch. 2
	voice_directsound 60, 0, DirectSoundSynth_Type_00_Custom4, 85, 165, 193, 178          @ 026 | Synth | Reincarnation GBC Ch. 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 027 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 028 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 029 | ---
	voice_directsound 60, 0, DirectSoundSynth_Type_01, 255, 0, 255, 165                   @ 030 | Synth | Faith is for the Transient People GBC Ch. 1
	voice_directsound 60, 0, DirectSoundSynth_Type_00_Custom4, 85, 165, 193, 178          @ 031 | Synth | Faith is for the Transient People GBC Ch. 2.1
	voice_directsound 60, 0, DirectSoundSynth_Type_01, 85, 165, 193, 178                  @ 032 | Synth | Faith is for the Transient People GBC Ch. 3
	voice_directsound 60, 0, DirectSoundSynth_Type_00_Custom5, 128, 165, 193, 178         @ 033 | Synth | Faith is for the Transient People GBC Ch. 2.2
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 7, 3                                            @ 034 | GB Square1 | Street GBC Ch. 1
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 3                                               @ 035 | GB Square2 | Street GBC Ch. 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 2, 7, 3                 @ 036 | GB Wave    | Street GBC Ch. 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 037 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 038 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 039 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 040 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 041 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 042 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 043 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 044 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 045 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 046 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 047 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 048 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 049 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 050 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 051 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 052 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 053 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 054 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 055 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 056 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 057 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 058 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 059 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 060 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 061 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 062 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 063 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 064 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 065 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 066 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 067 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 068 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 069 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 070 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 071 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 072 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 073 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 074 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 075 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 076 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 077 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 078 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 079 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 080 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 081 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 082 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 083 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 084 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 085 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 086 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 087 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 088 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 089 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 094 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 096 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 097 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 098 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 099 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 100 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 101 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 102 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 103 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 106 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 107 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 110 | ---
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 5, 2                                            @ 111 | GB Square1 | Generic GBC Ch. 1
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 4                                               @ 112 | GB Square2 | Generic GBC Ch. 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0                @ 113 | GB Wave    | Generic GBC Ch. 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 115 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 116 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16         @ 119 | Direct | HGSS Reverse Cymbal
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum_custom                                                      @ 120 | Direct | Drum | HGSS Drum | VVVVV
	voice_keysplit_all voicegroup_allkeysplit_hgss_taiko_drum                                                      @ 121 | Direct | Drum | HGSS Taiko Drum
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum_kick_and_snare                                                      @ 122 | Direct | Drum | HGSS synth kick+snare
	voice_keysplit voicegroup_keysplit_piano_custom_2, keysplit_piano_custom                            @ 123 | Direct | RSE Piano 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 124 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 125 | ---
	voice_noise_alt 60, 0, 0, 0, 2, 6, 2                                                  @ 126 | Noise | RSE Noise 2
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0                                                  @ 127 | Noise | RSE Noise 1
