voice_group golden_sun_2_main
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 000 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 001 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 002 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 003 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 004 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 005 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 006 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 007 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_celesta, 255, 0, 255, 165                       @ 008 | Direct | GBA Golden Sun Celesta
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 009 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 010 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 011 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 012 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 013 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 014 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 015 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 016 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 017 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 018 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 019 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 020 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 021 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 022 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 023 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_nylon_guitar, 255, 0, 255, 165                  @ 024 | Direct | GBA Golden Sun Nylon Guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 025 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 026 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 027 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 028 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 029 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 030 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 031 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 032 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_fingered_bass, 255, 0, 255, 165                 @ 033 | Direct | GBA Golden Sun Fingered Bass
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_GoldenSun2pcm001, 0, 2, 3, 3                      @ 034 | Wave | GBA Programmable Wave GS 1 2, 3, 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 035 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 036 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 037 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 038 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 039 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 040 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 041 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 042 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 043 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 044 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_pizzicato_strings, 255, 0, 255, 165             @ 045 | Direct | GBA Golden Sun Pizzicato Strings
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_harp, 255, 0, 255, 165                          @ 046 | Direct | GBA Golden Sun Harp
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_timpani, 255, 0, 255, 165                       @ 047 | Direct | GBA Golden Sun Timpani
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_string_ensemble, 255, 0, 255, 165               @ 048 | Direct | GBA Golden Sun String Ensemble
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 049 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 050 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 051 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_choir, 255, 0, 255, 165                         @ 052 | Direct | GBA Golden Sun Choir Aahs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 053 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 054 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 055 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_trumpet, 255, 0, 255, 165                       @ 056 | Direct | GBA Golden Sun Trumpet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 057 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 058 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 059 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 060 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_brass, 255, 0, 255, 165                         @ 061 | Direct | GBA Golden Sun Brass Section
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 062 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 063 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 064 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 065 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 066 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 067 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_oboe, 255, 0, 255, 165                          @ 068 | Direct | GBA Golden Sun Oboe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 069 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 070 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 071 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_piccolo, 255, 0, 255, 165                       @ 072 | Direct | GBA Golden Sun Piccolo
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_flute, 255, 0, 255, 165                         @ 073 | Direct | GBA Golden Sun Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 074 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_pan_flute, 255, 0, 255, 165                     @ 075 | Direct | GBA Golden Sun Pan Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 076 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 077 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 078 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 079 | ---
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 85, 165, 193, 178                              @ 080 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 85, 165, 193, 178                              @ 081 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 85, 165, 193, 178                              @ 082 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_04, 85, 165, 167, 178                              @ 083 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_05, 85, 127, 218, 165                              @ 084 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 22, 165, 193, 195                              @ 085 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 22, 165, 193, 195                              @ 086 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 22, 165, 193, 195                              @ 087 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_04, 22, 165, 167, 195                              @ 088 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_05, 22, 127, 218, 165                              @ 089 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 255, 235, 90, 178                              @ 090 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 255, 235, 90, 178                              @ 091 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 255, 235, 90, 178                              @ 092 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_04, 255, 235, 103, 178                             @ 093 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_05, 255, 235, 103, 165                             @ 094 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 255, 127, 90, 165                              @ 095 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 255, 127, 90, 165                              @ 096 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 255, 127, 90, 165                              @ 097 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_04, 255, 127, 90, 165                              @ 098 | Direct | GBA Golden Sun Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_05, 255, 127, 103, 165                             @ 099 | Direct | GBA Golden Sun Synth
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 7, 0                                                                @ 100 | Square-1 |
	voice_square_2_alt 60, 0, 3, 0, 1, 7, 0                                                                   @ 101 | Square-2 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 102 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 103 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 104 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_xylophone, 255, 235, 103, 178                   @ 105 | Direct | GBA Golden Sun Xylophone / Gamelan
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_indian_raag_effect, 255, 242, 103, 178          @ 106 | Direct | GBA Golden Sun Indian Raag Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_wood_block, 255, 0, 255, 165                    @ 107 | Direct | GBA Golden Sun Wood Block
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_woh_voice_effect, 255, 0, 255, 165              @ 108 | Direct | GBA Golden Sun Woh Voice Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_asian_gamelan_part1, 255, 0, 255, 165           @ 109 | Direct | GBA Golden Sun Gamelan Part 1
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_asian_gamelan_part2, 255, 235, 103, 178         @ 110 | Direct | GBA Golden Sun Gamelan Part 2
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_indian_sarod, 255, 0, 255, 165                  @ 111 | Direct | GBA Golden Sun Indian Sarod
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_beat_loop1, 255, 0, 255, 165                    @ 112 | Direct | GBA Golden Sun Drum Beat Loop
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_beat_loop2, 255, 0, 255, 165                    @ 113 | Direct | GBA Golden Sun Jungle Beat Loop
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_tropical_piano, 255, 235, 103, 178              @ 114 | Direct | GBA Golden Sun Tropical Piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 115 | ---
	voice_directsound 80, 0, DirectSoundWaveData_golden_sun_2_taiko, 255, 0, 255, 0                           @ 116 | Direct | GBA Golden Sun Taiko?
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 117 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 118 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 119 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 120 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 121 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 122 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 123 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 124 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 125 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 126 | ---
	voice_keysplit_all voicegroup_allkeysplit_golden_sun_2_drum                                               @ 127 | Drum | GBA Golden Sun Drum

