voice_group hgss_main
	voice_keysplit voicegroup_keysplit_hgss_piano_1, keysplit_hgss_piano_1    @ piano
	voice_keysplit voicegroup_keysplit_hgss_piano_2, keysplit_hgss_piano_2_vibraphone_glockglockenspiel    @ piano 2
	voice_keysplit voicegroup_keysplit_hgss_piano_3, keysplit_hgss_piano_3    @ piano octave
	voice_keysplit voicegroup_keysplit_hgss_rhodes_1, keysplit_dp_rhodes     @ rhodes 1
	voice_keysplit voicegroup_keysplit_hgss_rhodes_2, keysplit_dp_rhodes     @ rhodes 2
	voice_keysplit voicegroup_keysplit_hgss_vibraphone, keysplit_hgss_piano_2_vibraphone_glockglockenspiel    @ vibraphone
	voice_keysplit voicegroup_keysplit_hgss_marimba, keysplit_hgss_marimba_music_box_sampled_square    @ marimba
	voice_keysplit voicegroup_keysplit_hgss_xylophone, keysplit_hgss_xylophone_trumpet    @ xylophone
	voice_keysplit voicegroup_keysplit_hgss_tubular_bell, keysplit_dp_tubular_bell    @ tubular bell
	voice_keysplit voicegroup_keysplit_hgss_glockenspiel, keysplit_hgss_piano_2_vibraphone_glockglockenspiel    @ glockenspiel
	voice_keysplit voicegroup_keysplit_hgss_music_box, keysplit_hgss_marimba_music_box_sampled_square    @ music box
	voice_keysplit voicegroup_keysplit_hgss_drawbar_organ, keysplit_hgss_organ_accordion_harp_timpani    @ drawbar organ
	voice_keysplit voicegroup_keysplit_hgss_jazz_organ, keysplit_hgss_organ_accordion_harp_timpani    @ jazz organ
	voice_keysplit voicegroup_keysplit_hgss_accordion, keysplit_hgss_organ_accordion_harp_timpani    @ accordion
	voice_keysplit voicegroup_keysplit_hgss_nylon_guitar, keysplit_hgss_guitar    @ nylon guitar
	voice_keysplit voicegroup_keysplit_hgss_martin_guitar, keysplit_hgss_guitar    @ martin guitar
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_hgss_distortion_guitar    @ distortion guitar 1
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_2, keysplit_hgss_distortion_guitar    @ distortion guitar 2
	voice_keysplit voicegroup_keysplit_hgss_clean_guitar, keysplit_hgss_guitar    @ clean guitar
	voice_keysplit voicegroup_keysplit_hgss_upright_bass, keysplit_hgss_upright_bass    @ upright bass
	voice_keysplit voicegroup_keysplit_hgss_fingered_bass, keysplit_hgss_fingered_bass    @ fingered bass
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 192
	voice_keysplit voicegroup_keysplit_hgss_synth_bass, keysplit_hgss_synth_bass    @ synth bass
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings    @ strings
	voice_keysplit voicegroup_keysplit_hgss_violin, keysplit_hgss_violin    @ violin
	voice_keysplit voicegroup_keysplit_hgss_cello, keysplit_hgss_cello_trombone    @ cello
	voice_keysplit voicegroup_keysplit_hgss_pizzicato, keysplit_hgss_pizzicato    @ pizzicato
	voice_keysplit voicegroup_keysplit_hgss_harp, keysplit_hgss_organ_accordion_harp_timpani    @ harp
	voice_keysplit voicegroup_keysplit_hgss_timpani, keysplit_hgss_organ_accordion_harp_timpani    @ timpani
	voice_keysplit voicegroup_keysplit_hgss_trumpet, keysplit_hgss_xylophone_trumpet    @ trumpets
	voice_keysplit voicegroup_keysplit_hgss_trombone, keysplit_hgss_cello_trombone    @ trombones
	voice_keysplit voicegroup_keysplit_hgss_french_horn_solo, keysplit_hgss_french_horn_solo    @ french horn solo
	voice_keysplit voicegroup_keysplit_hgss_french_horn, keysplit_hgss_french_horn    @ french horns
	voice_keysplit voicegroup_keysplit_hgss_oboe, keysplit_hgss_oboe    @ oboe
	voice_keysplit voicegroup_keysplit_hgss_clarinet, keysplit_hgss_clarinet    @ clarinet
	voice_keysplit voicegroup_keysplit_hgss_flute, keysplit_hgss_flute    @ flute
	voice_keysplit voicegroup_keysplit_hgss_bassoon, keysplit_hgss_bassoon    @ bassoon
	voice_keysplit voicegroup_keysplit_hgss_orchestral_hit, keysplit_hgss_orchestral_hit    @ orchestra hit
	voice_keysplit voicegroup_keysplit_hgss_sampled_square, keysplit_hgss_marimba_music_box_sampled_square    @ square wave
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum				 @ drums
	voice_keysplit_all voicegroup_allkeysplit_hgss_taiko_drum				 @ taiko drums
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 251, 0, 171
	voice_keysplit voicegroup_keysplit_hgss_koto, keysplit_hgss_koto    @ koto
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 40, 211
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 67, 243, 155, 224
	voice_directsound 60, 0, DirectSoundWaveData_dp_explosion, 67, 255, 0, 245
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 250, 0, 171 @ 1 octave too low
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0  @ also 066 in BATTLE4 and DUNGEON4
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 252, 0, 96
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 250, 0, 220
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 220
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 192
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 42, 0, 57, 192
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 240, 242, 0, 192
@	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192	@ remaining voices wrap around
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16		@ to the next voice group, so
@	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 167, 235, 171		@ have some dittos
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_37, 80, 234, 191, 220
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_12, 80, 234, 191, 220
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 197, 255, 171						@ 60
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 197, 255, 171						@ 61
@	voice_keysplit_all voicegroup_allkeysplit_hgss_drum_kick_and_snare				 @ synth kick+snare										@ 62
@	voice_keysplit voicegroup_keysplit_dp_timpani, keysplit_dp_timpani    @ DPPt timpani											@ 63
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 42, 255, 192						@ 64
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220						@ 65
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171						@ 66
@	voice_keysplit voicegroup_keysplit_hgss_shamisen, keysplit_hgss_shamisen    @ shamisen												@ 67
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hyoshigi, 255, 0, 255, 171								@ 68
@	voice_directsound 60, 0, DirectSoundWaveData_hg_kodaiko, 255, 0, 255, 171								@ 69
@	voice_directsound 60, 0, DirectSoundWaveData_hg_tsuzumi, 255, 0, 255, 171								@ 70
@	voice_directsound 60, 0, DirectSoundWaveData_hg_jinglebell, 255, 0, 255, 171							@ 71
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hoohclap, 255, 0, 255, 0								@ 72
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171						@ 73
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 197, 255, 171						@ 74
@	voice_directsound 60, 0, DirectSoundWaveData_hg_choirc5, 255, 197, 255, 171 @ 1 octave too low			@ 75
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 197, 255, 171 @ 1 octave too high	@ 76
@	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32						@ 77
@	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192						@ 78
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 171							@ 79
@	voice_keysplit voicegroup_keysplit_hgss_piano_4, keysplit_hgss_piano_4    @ piano (national park)								@ 80
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32								@ 81
@	voice_keysplit voicegroup_keysplit_dp_trumpet, keysplit_dp_trumpet    @ dp trumpets (arceus)									@ 82
@	voice_keysplit voicegroup_keysplit_dp_trombone, keysplit_dp_trombone    @ dp trombone (arceus)									@ 83
