voice_group hgss_custom
	voice_keysplit voicegroup_keysplit_hgss_piano_1, keysplit_hgss_piano_1                                   @ 000 | Direct | HGSS Piano 1
	voice_keysplit voicegroup_keysplit_hgss_piano_2, keysplit_hgss_piano_2_vibraphone_glockglockenspiel      @ 001 | Direct | HGSS Piano 2
	voice_keysplit voicegroup_keysplit_hgss_piano_3, keysplit_hgss_piano_3                                   @ 002 | Direct | HGSS Piano 3 (Piano Octave)
	voice_keysplit voicegroup_keysplit_hgss_rhodes_1, keysplit_dp_rhodes                                     @ 003 | Direct | HGSS Rhodes 1
	voice_keysplit voicegroup_keysplit_hgss_rhodes_2, keysplit_dp_rhodes                                     @ 004 | Direct | HGSS Rhodes 2
	voice_keysplit voicegroup_keysplit_hgss_vibraphone, keysplit_hgss_piano_2_vibraphone_glockglockenspiel   @ 005 | Direct | HGSS Vibraphone
	voice_keysplit voicegroup_keysplit_hgss_marimba, keysplit_hgss_marimba_music_box_sampled_square          @ 006 | Direct | HGSS Marimba
	voice_keysplit voicegroup_keysplit_hgss_xylophone, keysplit_hgss_xylophone_trumpet                       @ 007 | Direct | HGSS Xylophone
	voice_keysplit voicegroup_keysplit_hgss_tubular_bell, keysplit_dp_tubular_bell                           @ 008 | Direct | HGSS Tubular Bell
	voice_keysplit voicegroup_keysplit_hgss_glockenspiel, keysplit_hgss_piano_2_vibraphone_glockglockenspiel @ 009 | Direct | HGSS Glockenspiel
	voice_keysplit voicegroup_keysplit_hgss_music_box, keysplit_hgss_marimba_music_box_sampled_square        @ 010 | Direct | HGSS Music Box
	voice_keysplit voicegroup_keysplit_hgss_drawbar_organ, keysplit_hgss_organ_accordion_harp_timpani        @ 011 | Direct | HGSS Drawbar Organ
	voice_keysplit voicegroup_keysplit_hgss_jazz_organ, keysplit_hgss_organ_accordion_harp_timpani           @ 012 | Direct | HGSS Jazz Organ
	voice_keysplit voicegroup_keysplit_hgss_accordion, keysplit_hgss_organ_accordion_harp_timpani            @ 013 | Direct | HGSS Accordion
	voice_keysplit voicegroup_keysplit_hgss_nylon_guitar, keysplit_hgss_guitar                               @ 014 | Direct | HGSS Nylon Guitar
	voice_keysplit voicegroup_keysplit_hgss_martin_guitar, keysplit_hgss_guitar                              @ 015 | Direct | HGSS Martin Guitar
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_hgss_distortion_guitar             @ 016 | Direct | HGSS Distortion Guitar 1
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_2, keysplit_hgss_distortion_guitar             @ 017 | Direct | HGSS Distortion Guitar 2
	voice_keysplit voicegroup_keysplit_hgss_clean_guitar, keysplit_hgss_guitar                               @ 018 | Direct | HGSS Clean Guitar
	voice_keysplit voicegroup_keysplit_hgss_upright_bass, keysplit_hgss_upright_bass                         @ 019 | Direct | HGSS Upright Bass
	voice_keysplit voicegroup_keysplit_hgss_fingered_bass, keysplit_hgss_fingered_bass                       @ 020 | Direct | HGSS Fingered Bass
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 192                         @ 021 | Direct | HGSS Slap Bass
	voice_keysplit voicegroup_keysplit_hgss_synth_bass, keysplit_hgss_synth_bass                             @ 022 | Direct | HGSS Synth Bass
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                                   @ 023 | Direct | HGSS Strings
	voice_keysplit voicegroup_keysplit_hgss_violin, keysplit_hgss_violin                                     @ 024 | Direct | HGSS Violin
	voice_keysplit voicegroup_keysplit_hgss_cello, keysplit_hgss_cello_trombone                              @ 025 | Direct | HGSS Cello
	voice_keysplit voicegroup_keysplit_hgss_pizzicato, keysplit_hgss_pizzicato                               @ 026 | Direct | HGSS Pizzicato
	voice_keysplit voicegroup_keysplit_hgss_harp, keysplit_hgss_organ_accordion_harp_timpani                 @ 027 | Direct | HGSS Harp
	voice_keysplit voicegroup_keysplit_hgss_timpani, keysplit_hgss_organ_accordion_harp_timpani              @ 028 | Direct | HGSS Timpani
	voice_keysplit voicegroup_keysplit_hgss_trumpet, keysplit_hgss_xylophone_trumpet                         @ 029 | Direct | HGSS Trumpets
	voice_keysplit voicegroup_keysplit_hgss_trombone, keysplit_hgss_cello_trombone                           @ 030 | Direct | HGSS Trombones
	voice_keysplit voicegroup_keysplit_hgss_french_horn_solo, keysplit_hgss_french_horn_solo                 @ 031 | Direct | HGSS French Horn Solo
	voice_keysplit voicegroup_keysplit_hgss_french_horn, keysplit_hgss_french_horn                           @ 032 | Direct | HGSS French Horns
	voice_keysplit voicegroup_keysplit_hgss_oboe, keysplit_hgss_oboe                                         @ 033 | Direct | HGSS Oboe
	voice_keysplit voicegroup_keysplit_hgss_clarinet, keysplit_hgss_clarinet                                 @ 034 | Direct | HGSS Clarinet
	voice_keysplit voicegroup_keysplit_hgss_flute, keysplit_hgss_flute                                       @ 035 | Direct | HGSS Flute
	voice_keysplit voicegroup_keysplit_hgss_bassoon, keysplit_hgss_bassoon                                   @ 036 | Direct | HGSS Bassoon
	voice_keysplit voicegroup_keysplit_hgss_orchestral_hit, keysplit_hgss_orchestral_hit                     @ 037 | Direct | HGSS Orchestral Hit
	voice_keysplit voicegroup_keysplit_hgss_sampled_square, keysplit_hgss_marimba_music_box_sampled_square   @ 038 | Direct | HGSS Sampled Square Wave
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum				                                         @ 039 | Drum | HGSS Drums
	voice_keysplit_all voicegroup_allkeysplit_hgss_taiko_drum				                                 @ 040 | Drum | HGSS Taiko Drums
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 251, 0, 171                         @ 041 | Direct | HGSS Wood Bass
	voice_keysplit voicegroup_keysplit_hgss_koto, keysplit_hgss_koto                                         @ 042 | Direct | HGSS Koto
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 40, 211                            @ 043 | Direct | HGSS Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 67, 243, 155, 224                             @ 044 | Direct | HGSS Wind Effect
	voice_directsound 60, 0, DirectSoundWaveData_dp_explosion, 67, 255, 0, 245                               @ 045 | Direct | HGSS Explosion Effect
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 250, 0, 171                       @ 046 | Direct | HGSS Sampled Square Wave | 1 octave too low
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 0                             @ 047 | Direct | HGSS Bubble Effect
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0                              @ 048 | Direct | HGSS Sampled Square Wave 50% | also 066 in BATTLE4 and DUNGEON4
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 252, 0, 96                              @ 049 | Direct | HGSS Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 250, 0, 220                             @ 050 | Direct | HGSS Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 220                           @ 051 | Direct | HGSS Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 192                           @ 052 | Direct | HGSS Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 42, 0, 57, 192                                   @ 053 | Direct | HGSS Sampled Noise 1
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 240, 242, 0, 19                                  @ 054 | Direct | HGSS Sampled Noise 2
@	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192	                     @ 055 | Direct | DP Whistle | remaining voices wrap around
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16                            @ 056 | Direct | DP Reverse Cymbal | to the next voice group, so
@	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 167, 235, 171		                     @ 057 | Direct | DP Organ | have some dittos
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_37, 80, 234, 191, 220                            @ 058 | Direct | HGSS Sampled Square Wave 37.5%
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_12, 80, 234, 191, 220                            @ 059 | Direct | HGSS Sampled Square Wave 12.5%
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 197, 255, 171                       @ 060 | Direct | DP Orchestral Hit Major
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 197, 255, 171                       @ 061 | Direct | DP Orchestral Hit Minor
@	voice_keysplit_all voicegroup_allkeysplit_hgss_drum_kick_and_snare                                       @ 062 | Drum | HGSS Synth Kick + Snare
@	voice_keysplit voicegroup_keysplit_dp_timpani, keysplit_dp_timpani                                       @ 063 | Direct | DP Timpani
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 42, 255, 192                        @ 064 | Direct | DP Synth Bass 1
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220                         @ 065 | Direct | DP Synth Bass 2
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                       @ 066 | Direct | DP Sawtooth
@	voice_keysplit voicegroup_keysplit_hgss_shamisen, keysplit_hgss_shamisen                                 @ 067 | Direct | HGSS Shamisen
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hyoshigi, 255, 0, 255, 171                               @ 068 | Direct | HGSS Hyoshigi
@	voice_directsound 60, 0, DirectSoundWaveData_hg_kodaiko, 255, 0, 255, 171                                @ 069 | Direct | HGSS Kodaiko
@	voice_directsound 60, 0, DirectSoundWaveData_hg_tsuzumi, 255, 0, 255, 171                                @ 070 | Direct | HGSS Tsuzumi
@	voice_directsound 60, 0, DirectSoundWaveData_hg_jinglebell, 255, 0, 255, 171                             @ 071 | Direct | HGSS Jingle Bell
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hoohclap, 255, 0, 255, 0                                 @ 072 | Direct | HGSS Clap (Ho-Oh)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171                         @ 073 | Direct | DP Tenor Choir
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 197, 255, 171                       @ 074 | Direct | DP Soprano Choir
@	voice_directsound 60, 0, DirectSoundWaveData_hg_choirc5, 255, 197, 255, 171                              @ 075 | Direct | HGSS Choir | 1 octave too low
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 197, 255, 171                         @ 076 | Direct | DP Reverse Cymbal | 1 octave too high
@	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32                       @ 077 | Direct | DP Wind Effect (Spear Pillar)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                        @ 078 | Direct | DP Altosax
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 171                             @ 079 | Direct | DP Synth Snare
@	voice_keysplit voicegroup_keysplit_hgss_piano_4, keysplit_hgss_piano_4                                   @ 080 | Direct | HGSS Piano 4 (National Park)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32                                 @ 081 | Direct | DP Tom
@	voice_keysplit voicegroup_keysplit_dp_trumpet, keysplit_dp_trumpet                                       @ 082 | Direct | DP Trumpet (Arceus)
@	voice_keysplit voicegroup_keysplit_dp_trombone, keysplit_dp_trombone                                     @ 083 | Direct | DP Trombone (Arceus)
	voice_keysplit voicegroup_keysplit_piano_custom, keysplit_piano                                          @ 084 | Direct | Multi | GBA Emerald Piano 1
	voice_keysplit voicegroup_keysplit_strings_custom, keysplit_strings                                      @ 085 | Direct | Multi | GBA Emerald String Ensemble
	voice_keysplit voicegroup_keysplit_trumpet_custom, keysplit_trumpet                                      @ 086 | Direct | Multi | GBA Emerald Trumpet
	voice_keysplit voicegroup_keysplit_tuba_custom, keysplit_tuba                                            @ 087 | Direct | Multi | GBA Emerald Tuba
	voice_keysplit voicegroup_keysplit_french_horn_custom, keysplit_french_horn                              @ 088 | Direct | Multi | GBA Emerald French Horn
	voice_square_2_alt 60, 0, 0, 0, 2, 5, 2                                                                  @ 089 | Square-2 | Note off with noise 12.5% 0 2 5 2
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 5, 2                                                               @ 090 | Square-1 | Note off with noise 12.5% 0 2 5 2
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 3                                                                  @ 091 | Square-2 | Note off with noise 75.0% 0 2 7 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 4, 6, 0                                    @ 092 | Wave | Note off with noise 0 4 6 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_2, 1, 7, 0, 6                                    @ 093 | Wave | Note off with noise 1 7 0 6
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_16, 0, 4, 6, 0                                   @ 094 | Wave | Note off with noise 0 4 6 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 2, 9, 0                                    @ 095 | Wave | Note off with noise 0 2 9 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 1, 5, 0, 3                                    @ 096 | Wave | Note off with noise 1 5 0 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 7, 15, 1                                   @ 097 | Wave | Note off with noise 0 7 15 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0                                   @ 098 | Wave | Note off with noise 0 7 15 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_15, 0, 1, 9, 2                                   @ 099 | Wave | Note off with noise 0 1 9 2
	voice_directsound 60, 0, DirectSoundWaveData_thppme_puresquare50, 255, 240, 128, 64                      @ 100 | Direct | THPP Pure Square 50
	voice_directsound 60, 0, DirectSoundWaveData_thppme_puresquare25, 255, 240, 128, 64                      @ 101 | Direct | THPP Pure Square 25
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_2, 0, 2, 9, 1                                    @ 102 | Wave | Note off with noise 0 2 9 1
	voice_square_2_alt 60, 0, 3, 0, 3, 7, 1                                                                  @ 103 | Square-2 | Note off with noise 75.0% 0 3 7 1
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 7, 3                                                               @ 104 | Square-1 | Note off with noise 75.0% 0 2 7 3
	voice_square_2_alt 60, 0, 1, 0, 2, 9, 1                                                                  @ 105 | Square-2 | Note off with noise 25.0% 0 2 9 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 3, 7, 2                                    @ 106 | Wave | Note off with noise 0 3 7 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_thppme_pcm_fff740, 0, 2, 7, 3                    @ 107 | Wave | Note off with noise 0 2 7 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 2, 7, 3                                    @ 108 | Wave | Note off with noise 0 2 7 3
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_church_organ, 170, 180, 160, 235                     @ 109 | Direct | RF Church Organ
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_choir_ohhs, 255, 188, 220, 243                       @ 110 | Direct | RF Choir Ohhs
	voice_directsound 60, 65, DirectSoundWaveData_thpprf_choir_ahhs, 255, 205, 220, 243                      @ 111 | Direct | RF Choir Ahhs
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_applause, 170, 160, 180, 210                         @ 112 | Direct | RF Applause 1
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_music_box, 255, 0, 255, 235                          @ 113 | Direct | RF Music Box
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_overdrive_guitar, 250, 250, 250, 190                 @ 114 | Direct | RF Overdrive Guitar
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_applause2, 170, 160, 180, 210                        @ 115 | Direct | RF Applause 2
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_thpprf_unison_slap, 255, 165, 180, 216               @ 116 | Direct | RF Unison Slap Bass
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_square_wave, 255, 0, 255, 127                        @ 117 | Direct | RF Sampled Square Wave
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_orchestra_hit, 255, 0, 255, 0                     @ 118 | Direct | GBA Precure Orchestral Hit
	voice_keysplit_all voicegroup_allkeysplit_frlg_custom_drum                                               @ 119 | Direct | Drum | GBA Emerald Drum
	voice_keysplit_all voicegroup_allkeysplit_pmdred_drum_1                                                  @ 120 | Direct | Drum | GBA PMD Drum 1
	voice_keysplit_all voicegroup_allkeysplit_pmdred_drum_2                                                  @ 121 | Direct | Drum | GBA PMD Drum 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 216            @ 122 | Direct | GBA Emerald Cymbal 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216            @ 123 | Direct | GBA Emerald Cymbal 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127                 @ 124 | Direct | GBA Emerald Hand Clap
	voice_noise_alt 60, 0, 0, 0, 0, 15, 0                                                                    @ 125 | Noise | GBA Noise 0 0 15 0
	voice_noise_alt 60, 0, 0, 0, 2, 6, 2                                                                     @ 126 | Noise | GBA Noise 0 2 6 2
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0                                                                     @ 127 | Noise | GBA Noise 0 1 6 0
