voice_group pc_ds1fwpcmh_main
	voice_keysplit voicegroup_keysplit_hgss_piano_1, keysplit_hgss_piano_1                              @ 000 | HGSS Piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 001 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 002 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 003 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 004 | ---
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 188, 103, 165    @ 005 | RSE Electric Piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 006 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 007 | ---
	voice_keysplit voicegroup_keysplit_hgss_vibraphone, keysplit_hgss_piano_2_vibraphone_glockglockenspiel @ 008 | HGSS Vibraphone
	voice_keysplit voicegroup_keysplit_hgss_music_box, keysplit_hgss_marimba_music_box_sampled_square   @ 009 | HGSS Music Box
	voice_keysplit voicegroup_keysplit_hgss_music_box, keysplit_hgss_marimba_music_box_sampled_square   @ 010 | HGSS Music Box
	voice_keysplit voicegroup_keysplit_hgss_music_box, keysplit_hgss_marimba_music_box_sampled_square   @ 011 | HGSS Music Box
	voice_keysplit voicegroup_keysplit_hgss_vibraphone, keysplit_hgss_piano_2_vibraphone_glockglockenspiel @ 012 | HGSS Vibraphone
	voice_keysplit voicegroup_keysplit_hgss_xylophone, keysplit_hgss_xylophone_trumpet                  @ 013 | HGSS Xylophone
	voice_keysplit voicegroup_keysplit_hgss_marimba, keysplit_hgss_marimba_music_box_sampled_square     @ 014 | HGSS Marimba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 015 | ---
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188           @ 016 | RSE Church Organ 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 017 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 018 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 019 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 020 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 021 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 022 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 023 | ---
	voice_keysplit voicegroup_keysplit_hgss_nylon_guitar, keysplit_hgss_guitar                          @ 024 | HGSS Nylon Guitar
	voice_keysplit voicegroup_keysplit_hgss_martin_guitar, keysplit_hgss_guitar                         @ 025 | HGSS Martin Guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 026 | ---
	voice_keysplit voicegroup_keysplit_hgss_clean_guitar, keysplit_hgss_guitar                          @ 027 | HGSS Clean Guitar
	voice_keysplit voicegroup_keysplit_hgss_clean_guitar, keysplit_hgss_guitar                          @ 028 | HGSS Clean Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127      @ 029 | RSE OD Guitar
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_hgss_distortion_guitar        @ 030 | HGSS Dist. Guitar 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 031 | ---
	voice_keysplit voicegroup_keysplit_hgss_upright_bass, keysplit_hgss_upright_bass                    @ 032 | HGSS Upright Bass
	voice_keysplit voicegroup_keysplit_hgss_fingered_bass, keysplit_hgss_fingered_bass                  @ 033 | HGSS Fingered Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 034 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 035 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 036 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 192                    @ 037 | HGSS Slap Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 038 | ---
	voice_keysplit voicegroup_keysplit_hgss_synth_bass, keysplit_hgss_synth_bass                        @ 039 | HGSS Synth Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 040 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 041 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 042 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 043 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 044 | ---
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165            @ 045 | RSE Pizzacito
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 51, 242                        @ 046 | RSE Harp
	voice_keysplit voicegroup_keysplit_hgss_timpani, keysplit_hgss_organ_accordion_harp_timpani         @ 047 | HGSS Timpani
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                              @ 048 | HGSS Strings
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings_custom                                 @ 049 | RSE Strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 050 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 051 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171                    @ 052 | HGSS Tenor Choir
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 053 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 054 | ---
	voice_keysplit voicegroup_keysplit_hgss_orchestral_hit, keysplit_hgss_orchestral_hit                @ 055 | HGSS Orchestral Hit
	voice_keysplit voicegroup_trumpet_keysplit, keysplit_trumpet_custom                                 @ 056 | RSE Trumpet
	voice_keysplit voicegroup_keysplit_hgss_trumpet, keysplit_hgss_xylophone_trumpet                    @ 057 | HGSS Trumpet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 058 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 059 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 060 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_brass, 255, 0, 255, 165                   @ 061 | GS2 Brass Section
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 062 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 063 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                   @ 064 | HGSS Alto Sax
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                   @ 065 | HGSS Alto Sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 066 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 067 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 068 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 069 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 070 | ---
	voice_keysplit voicegroup_keysplit_hgss_clarinet, keysplit_hgss_clarinet                            @ 071 | HGSS Clarinet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 072 | ---
	voice_keysplit voicegroup_keysplit_hgss_flute, keysplit_hgss_flute                                  @ 073 | HGSS Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 074 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_pan_flute, 255, 0, 255, 165               @ 075 | GS2 Pan Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 076 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 077 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 078 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192                    @ 079 | HGSS Whistle
	voice_square_2_alt 60, 0, 3, 0, 1, 7, 0                                                             @ 080 | Sq-2
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                  @ 081 | HGSS Sawtooth
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 082 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 083 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 084 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 085 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 086 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 087 | ---
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_choir_ohhs, 255, 188, 220, 243                  @ 088 | RF Voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 089 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 090 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 091 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 092 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 093 | ---
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_choir_ohhs, 255, 188, 220, 243                  @ 094 | RF Voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 095 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 096 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 097 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 098 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 099 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 100 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 101 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 102 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 103 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 104 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 105 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 106 | ---
	voice_keysplit voicegroup_keysplit_hgss_koto, keysplit_hgss_koto                                    @ 107 | HGSS Koto
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 108 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 109 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 110 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 111 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 112 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 113 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 114 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 115 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 116 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 117 | ---
	voice_directsound 60, 0, DirectSoundWaveData_hg_138tom, 255, 0, 255, 171                            @ 118 | HGSS Tom
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 119 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 120 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 121 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 122 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 123 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 124 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32                  @ 125 | HGSS Wind
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 126 | ---
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum                                                 @ 127 | HGSS Drum
