voice_group pmdred_main_2
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E922E4, 255, 0, 255, 0            @ 000 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E90FA0, 255, 0, 255, 0            @ 001 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_14, KeySplitTablePMD07                 @ 002 | Direct | Multi |
	voice_keysplit voicegroup_keysplit_pmdred_sample_15, KeySplitTablePMD06                 @ 003 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 188        @ 004 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_16, KeySplitTablePMD05                 @ 005 | Direct | Multi |
	voice_keysplit voicegroup_keysplit_pmdred_sample_17, KeySplitTablePMD04                 @ 006 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8D478, 255, 165, 154, 16         @ 007 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E94D0C, 255, 0, 255, 0            @ 008 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E94D0C, 255, 165, 0, 127          @ 009 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA24B8, 255, 226, 0, 127          @ 010 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_18, KeySplitTablePMD06                 @ 011 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 180, 127        @ 012 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EE6B60, 255, 188, 180, 127        @ 013 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8E6D8, 255, 249, 25, 204         @ 014 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9E4CC, 13, 0, 255, 127           @ 015 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_19, KeySplitTablePMD09                 @ 016 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8C5DC, 255, 0, 255, 149          @ 017 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97110, 255, 0, 255, 127          @ 018 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_20, KeySplitTablePMD02                 @ 019 | Direct | Multi |
	voice_keysplit voicegroup_keysplit_pmdred_sample_21, KeySplitTablePMD02                 @ 020 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E99740, 255, 0, 255, 0            @ 021 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E98378, 37, 0, 255, 0             @ 022 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_22, KeySplitTablePMD01                 @ 023 | Direct | Multi |
	voice_keysplit voicegroup_keysplit_pmdred_sample_23, KeySplitTablePMD08                 @ 024 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 255, 188, 103, 165        @ 025 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA536C, 64, 249, 0, 165           @ 026 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E899A0, 64, 204, 103, 188         @ 027 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E926DC, 64, 235, 255, 0           @ 028 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9BD98, 255, 235, 255, 188        @ 029 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 64, 0, 103, 0             @ 030 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E922E4, 64, 0, 255, 0             @ 031 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EE6CB8, 255, 204, 51, 165         @ 032 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9F53C, 255, 0, 255, 127          @ 033 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8E6D8, 255, 204, 51, 0           @ 034 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_19, KeySplitTablePMD10                 @ 035 | Multi |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 036 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 037 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 038 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 039 | Unused
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EE714C, 64, 255, 0, 0             @ 040 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EE8C98, 37, 0, 255, 0             @ 041 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EEB4C4, 37, 0, 255, 0             @ 042 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EED93C, 37, 0, 255, 0             @ 043 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EEFFCC, 37, 0, 255, 0             @ 044 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EF14D8, 64, 0, 255, 0             @ 045 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EFA50C, 64, 249, 25, 127          @ 046 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E926DC, 128, 235, 255, 242        @ 047 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EF4248, 64, 0, 255, 0             @ 048 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EF5698, 255, 0, 255, 127          @ 049 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8FEEC, 255, 0, 255, 127          @ 050 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8FEEC, 255, 216, 0, 127          @ 051 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E88420, 255, 188, 77, 242         @ 052 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 053 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 054 | Unused
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA345C, 255, 216, 0, 165          @ 055 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA40B0, 255, 0, 255, 127          @ 056 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA421C, 255, 188, 154, 127        @ 057 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 15, 0, 255, 204           @ 058 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 19, 165, 206, 216         @ 059 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 26, 165, 206, 0           @ 060 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 26, 0, 255, 204           @ 061 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 37, 165, 206, 204         @ 062 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 063 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 064 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 065 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 066 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 067 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 068 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 069 | Unused
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0                                                @ 070 | Square-2 |
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0                                                @ 071 | Square-2 |
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0                                                @ 072 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 1, 0, 1                                                 @ 073 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 2, 1, 0                                                 @ 074 | Square-2 |
	voice_square_2_alt 60, 0, 1, 0, 1, 0, 1                                                 @ 075 | Square-2 |
	voice_square_2_alt 60, 0, 1, 0, 2, 1, 0                                                 @ 076 | Square-2 |
	voice_square_2_alt 60, 0, 0, 0, 1, 0, 1                                                 @ 077 | Square-2 |
	voice_square_2_alt 60, 0, 0, 0, 2, 1, 0                                                 @ 078 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 3, 3, 0                                                 @ 079 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 1, 3, 12, 1                                             @ 080 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 1, 0, 15, 0                                             @ 081 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0                                             @ 082 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0                                             @ 083 | Square-1 |
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0                                             @ 084 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 0, 1                                              @ 085 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 1, 0                                              @ 086 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 0, 1                                              @ 087 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 1, 0                                              @ 088 | Square-1 |
	voice_square_1_alt 60, 0, 0, 0, 0, 1, 0, 1                                              @ 089 | Square-1 |
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 1, 0                                              @ 090 | Square-1 |
	voice_square_2_alt 60, 0, 2, 1, 1, 0, 0                                                 @ 091 | Square-2 |
	voice_square_2_alt 60, 0, 1, 1, 1, 0, 0                                                 @ 092 | Square-2 |
	voice_square_2_alt 60, 0, 0, 1, 1, 0, 0                                                 @ 093 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 1, 1, 0, 0                                              @ 094 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 1, 1, 0, 0                                              @ 095 | Square-1 |
	voice_square_1_alt 60, 0, 0, 0, 1, 1, 0, 0                                              @ 096 | Square-1 |
	voice_square_2_alt 60, 0, 2, 1, 3, 12, 1                                                @ 097 | Square-2 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 098 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 099 | Unused
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8655C, 0, 0, 15, 0    @ 100 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8663C, 0, 0, 15, 0    @ 101 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8654C, 0, 0, 15, 0    @ 102 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8657C, 0, 0, 15, 0    @ 103 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8664C, 0, 0, 15, 0    @ 104 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865EC, 0, 0, 15, 0    @ 105 | Wave |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 106 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 107 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 108 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 109 | Unused
	voice_noise_alt 60, 0, 0, 1, 0, 7, 0                                                    @ 110 | Noise |
	voice_noise_alt 60, 0, 0, 0, 4, 3, 2                                                    @ 111 | Noise |
	voice_noise_alt 60, 0, 0, 0, 5, 0, 0                                                    @ 112 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 113 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 114 | Unused
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECAAD4, 255, 0, 255, 0            @ 115 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EADC80, 255, 0, 255, 127          @ 116 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECBB2C, 255, 0, 255, 127          @ 117 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECAAD4, 10, 0, 255, 127           @ 118 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EACEDC, 255, 0, 255, 127          @ 119 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EBA840, 255, 0, 255, 127          @ 120 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 242, 0, 127          @ 121 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 0, 255, 0            @ 122 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECAAD4, 255, 0, 255, 242          @ 123 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EB94B8, 255, 0, 255, 127          @ 124 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECC450, 255, 0, 255, 0            @ 125 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECAAD4, 255, 255, 0, 204          @ 126 | Direct |
	voice_keysplit_all voicegroup_allkeysplit_pmdred_drum_2                                 @ 127 | Direct | Drum | PMD Drum 2
