voice_group pmdred_main_1
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E88420, 64, 165, 206, 226         @ 000 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E899A0, 64, 204, 103, 188         @ 001 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8FEEC, 64, 242, 51, 216          @ 002 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E88420, 64, 235, 25, 239          @ 003 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8B520, 51, 188, 206, 226         @ 004 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E88420, 255, 188, 77, 204         @ 005 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8C5DC, 255, 0, 255, 149          @ 006 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8D478, 255, 165, 154, 165        @ 007 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8E6D8, 255, 249, 25, 204         @ 008 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_07, KeySplitTablePMD07                 @ 009 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8FEEC, 255, 242, 128, 216        @ 010 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E90FA0, 255, 0, 255, 127          @ 011 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_06, KeySplitTablePMD06                 @ 012 | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E922E4, 255, 0, 255, 165          @ 013 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E926DC, 128, 235, 255, 242        @ 014 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_10, KeySplitTablePMD07                 @ 015 | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E94D0C, 255, 0, 255, 127          @ 016 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E94D0C, 51, 216, 128, 149         @ 017 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97110, 255, 0, 255, 127          @ 018 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_01, KeySplitTablePMD02                 @ 019 | Direct | Multi |
	voice_keysplit voicegroup_keysplit_pmdred_sample_08, KeySplitTablePMD01                 @ 020 | Direct | Multi |
	voice_keysplit voicegroup_keysplit_pmdred_sample_02, KeySplitTablePMD02                 @ 021 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 15, 0, 255, 204           @ 022 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 19, 165, 206, 216         @ 023 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E98378, 37, 0, 255, 0             @ 024 | Direct |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8654C, 0, 0, 15, 0    @ 025 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8655C, 0, 0, 15, 0    @ 026 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8656C, 0, 0, 15, 0    @ 027 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8657C, 0, 0, 15, 0    @ 028 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8658C, 0, 0, 15, 0    @ 029 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8659C, 0, 0, 15, 0    @ 030 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865AC, 0, 0, 15, 0    @ 031 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865BC, 0, 0, 15, 0    @ 032 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865CC, 0, 0, 15, 0    @ 033 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865DC, 0, 0, 15, 0    @ 034 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865EC, 0, 0, 15, 0    @ 035 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865FC, 0, 0, 15, 0    @ 036 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8660C, 0, 0, 15, 0    @ 037 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8661C, 0, 0, 15, 0    @ 038 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8662C, 0, 0, 15, 0    @ 039 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8663C, 0, 0, 15, 0    @ 040 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8659C, 0, 0, 15, 0    @ 041 | Wave |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E99740, 255, 216, 128, 165        @ 042 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 255, 188, 103, 165        @ 043 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_12, KeySplitTablePMD08                 @ 044 | Direct | Multi |
	voice_keysplit voicegroup_keysplit_pmdred_sample_03, KeySplitTablePMD03                 @ 045 | Direct | Multi |
	voice_keysplit voicegroup_keysplit_pmdred_sample_04, KeySplitTablePMD04                 @ 046 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 255, 188, 103, 0          @ 047 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8E6D8, 255, 249, 25, 0           @ 048 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 255, 188, 103, 216        @ 049 | Direct |
	voice_keysplit voicegroup_keysplit_pmdred_sample_09, KeySplitTablePMD06                 @ 050 | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9BD98, 255, 235, 180, 188        @ 051 | Direct |
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 0                                                 @ 052 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 0                                              @ 053 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 3, 5                                              @ 054 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 3, 5                                              @ 055 | Square-1 |
	voice_square_2_alt 60, 0, 0, 0, 2, 3, 5                                                 @ 056 | Square-2 |
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 3, 5                                              @ 057 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 3                                                 @ 058 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 3                                              @ 059 | Square-1 |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9E4CC, 255, 165, 154, 149        @ 060 | Direct |
	voice_square_2_alt 60, 0, 2, 2, 0, 7, 4                                                 @ 061 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 2, 0, 7, 4                                              @ 062 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 3                                                 @ 063 | Square-2 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 7, 3                                              @ 064 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8660C, 0, 0, 15, 1    @ 065 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8654C, 0, 0, 15, 2    @ 066 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8655C, 0, 0, 15, 0    @ 067 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8656C, 0, 0, 15, 2    @ 068 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8656C, 0, 0, 15, 4    @ 069 | Wave |
	voice_square_2_alt 60, 0, 1, 0, 0, 7, 3                                                 @ 070 | Square-2 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 7, 3                                              @ 071 | Square-1 |
	voice_keysplit voicegroup_keysplit_pmdred_sample_13, KeySplitTablePMD03                 @ 072 | Direct | Multi |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8655C, 0, 0, 15, 0    @ 073 | Wave |
	voice_square_2_alt 60, 0, 3, 0, 2, 3, 5                                                 @ 074 | Square-2 |
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 3, 5                                              @ 075 | Square-1 |
	voice_keysplit voicegroup_keysplit_pmdred_sample_05, KeySplitTablePMD05                 @ 076 | Direct | Multi |
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 3                                                 @ 077 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 3                                              @ 078 | Square-1 |
	voice_square_2_alt 60, 0, 3, 0, 2, 3, 5                                                 @ 079 | Square-2 |
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 3, 5                                              @ 080 | Square-1 |
	voice_square_2_alt 60, 0, 2, 2, 0, 7, 3                                                 @ 081 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 2, 0, 7, 3                                              @ 082 | Square-1 |
	voice_square_2_alt 60, 0, 2, 1, 1, 15, 3                                                @ 083 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 1, 1, 15, 3                                             @ 084 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8653C, 2, 0, 15, 2    @ 085 | Wave |
	voice_square_1_alt 60, 0, 0, 1, 1, 1, 15, 0                                             @ 086 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 1, 15, 0                                                @ 087 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 15, 0                                             @ 088 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0                                                @ 089 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0                                             @ 090 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8653C, 0, 0, 15, 2    @ 091 | Wave |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9F53C, 255, 0, 255, 188          @ 092 | Direct |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8659C, 0, 0, 15, 0    @ 093 | Wave |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 22, 188, 206, 204         @ 094 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 204        @ 095 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA24B8, 255, 245, 0, 204          @ 096 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 115        @ 097 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 64, 204, 154, 204         @ 098 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 255, 165, 206, 188        @ 099 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA345C, 255, 216, 0, 165          @ 100 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA40B0, 255, 0, 255, 127          @ 101 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA421C, 255, 188, 154, 127        @ 102 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA536C, 64, 0, 0, 165             @ 103 | Direct |
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0                                                @ 104 | Square-2 |
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0                                                @ 105 | Square-2 |
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0                                             @ 106 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0                                             @ 107 | Square-1 |
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0                                                @ 108 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0                                                @ 109 | Square-2 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0                                             @ 110 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0                                             @ 111 | Square-1 |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9E4CC, 255, 226, 103, 188        @ 112 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 255, 188, 180, 188        @ 113 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 226        @ 114 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 255, 204, 154, 204        @ 115 | Direct |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8664C, 0, 0, 15, 0    @ 116 | Wave |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0                                             @ 117 | Unused
	voice_keysplit voicegroup_keysplit_pmdred_sample_11, KeySplitTablePMD03                 @ 118 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 29, 204, 154, 204         @ 119 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 249, 25, 226         @ 120 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 0, 255, 0            @ 121 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 122 | Unused
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EACEDC, 255, 0, 255, 0            @ 123 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EADC80, 255, 0, 255, 216          @ 124 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EB0490, 255, 0, 255, 127          @ 125 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                 @ 126 | Unused
	voice_keysplit_all voicegroup_allkeysplit_pmdred_drum_1                                 @ 127 | Direct | Drum | PMD Drum 1

