voice_group puyofever_main
	voice_square_1 60, 0, 0, 0, 0, 0, 12, 0
	voice_square_1 60, 0, 0, 1, 0, 0, 12, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 12, 0
	voice_square_1 60, 0, 0, 3, 0, 0, 12, 0
	voice_square_1 60, 0, 0, 0, 0, 4, 4, 0
	voice_square_1 60, 0, 0, 1, 0, 4, 4, 0
	voice_square_1 60, 0, 0, 2, 0, 4, 4, 0
	voice_square_1 60, 0, 0, 0, 0, 3, 0, 0
	voice_square_1 60, 0, 0, 1, 0, 3, 0, 0
	voice_square_1 60, 0, 0, 2, 0, 3, 0, 0
	voice_square_2 60, 0, 0, 0, 0, 12, 0
	voice_square_2 60, 0, 1, 0, 0, 12, 0
	voice_square_2 60, 0, 2, 0, 0, 12, 0
	voice_square_2 60, 0, 3, 0, 0, 12, 0
	voice_square_2 60, 0, 0, 0, 4, 4, 0
	voice_square_2 60, 0, 1, 0, 4, 4, 0
	voice_square_2 60, 0, 2, 0, 4, 4, 0
	voice_square_2 60, 0, 0, 0, 3, 0, 0
	voice_square_2 60, 0, 1, 0, 3, 0, 0
	voice_square_2 60, 0, 2, 0, 3, 0, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A0908, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A0918, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A0938, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A08C8, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A08D8, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A08E8, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A08F8, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A0928, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A0948, 0, 1, 12, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A08C8, 0, 4, 4, 0
	voice_noise 60, 0, 1, 0, 1, 7, 0
	voice_noise 60, 0, 0, 0, 1, 7, 0
	voice_square_1 60, 0, 0, 2, 0, 3, 0, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A0908, 0, 4, 6, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A0918, 0, 4, 6, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A0938, 0, 4, 6, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A08C8, 0, 4, 6, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A0928, 0, 4, 6, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A08E8, 0, 4, 6, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_PuyoFever_A08F8, 0, 4, 6, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_A3678, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_A58D4, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_A7250, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_A9DE8, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_AA5E4, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_AF8B8, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B1640, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B3E4C, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B478C, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6490, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B67BC, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B67E4, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B680C, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6834, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B68BC, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B68F8, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B67E4, 255, 226, 128, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B680C, 255, 226, 128, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6834, 255, 226, 128, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B68BC, 255, 226, 128, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6938, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6974, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B69B0, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B69EC, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6B04, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6B54, 255, 0, 231, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6974, 255, 226, 128, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B69B0, 255, 226, 128, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B69EC, 255, 226, 128, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6B04, 255, 226, 128, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B6BB8, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B8420, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_AF8B8, 255, 216, 103, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B9774, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_BBE38, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_BE330, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_C0CDC, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_C3018, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B3E4C, 255, 0, 255, 132
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_C6680, 255, 0, 255, 132
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_C87FC, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_CABA0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_BE330, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_C0CDC, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_C3018, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_B3E4C, 255, 0, 255, 132
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_CC000, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_D0498, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_D25B4, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_D3BA8, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_D81F0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_DA7B4, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_DD10C, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_DEB64, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E0DCC, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E32C0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E5794, 255, 0, 255, 132
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E8B74, 255, 0, 255, 132
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E9D88, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup_allkeysplit_puyofever_drum
