voice_group rafinia_custom
	voice_keysplit_all voicegroup_allkeysplit_frlg_custom_drum                                    @ 000 | Direct | Drum | GBA Drum
	voice_keysplit voicegroup_keysplit_piano_custom, keysplit_piano                               @ 001 | Direct | Multi | GBA Piano 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 002 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 003 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 249, 0, 188 @ 004 | GBA Electric Piano 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 005 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 006 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 007 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 008 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 009 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 010 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 011 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 012 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 013 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 014 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 015 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 016 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 017 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 018 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 019 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 020 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 021 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 022 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 023 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 024 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 025 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 026 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 027 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 028 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 029 | --- | 
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_2, keysplit_hgss_distortion_guitar  @ 030 | Direct | HGSS distortion guitar 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 031 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 032 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 033 | --- | 
	voice_keysplit voicegroup_keysplit_hgss_upright_bass, keysplit_hgss_upright_bass              @ 034 | Direct | HGSS upright bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 035 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 036 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 037 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 146             @ 038 | Direct | GBA Synth Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 039 | --- | 
	voice_keysplit voicegroup_keysplit_hgss_violin, keysplit_hgss_violin                          @ 040 | Direct | Multi | HGSS Violin
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 041 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 042 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 043 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 044 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 045 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 046 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 047 | --- | 
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                        @ 048 | Direct | HGSS strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 049 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 050 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 051 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 052 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 053 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 054 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 055 | --- | 
	voice_keysplit voicegroup_keysplit_hgss_trumpet, keysplit_hgss_xylophone_trumpet              @ 056 | Direct | HGSS trumpets
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 057 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 058 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 059 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 060 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 061 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 062 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 063 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 064 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 065 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 066 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 067 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 068 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 069 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 070 | --- | 
	voice_keysplit voicegroup_keysplit_hgss_clarinet, keysplit_hgss_clarinet                      @ 071 | Direct | HGSS clarinet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 072 | --- | 
	voice_keysplit voicegroup_keysplit_hgss_flute, keysplit_hgss_flute                            @ 073 | Direct | Multi | HGSS Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 074 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 075 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 076 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 077 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 078 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 079 | --- | 
	voice_square_2_alt 60, 0, 2, 0, 2, 4, 1                                                       @ 080 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 4, 1                                                    @ 081 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0                        @ 082 | Wave | GBA Programmable Wave 1
	voice_square_2_alt 60, 0, 3, 0, 3, 6, 2                                                       @ 083 | Square-2 |
	voice_square_2_alt 60, 0, 0, 0, 2, 6, 5                                                       @ 084 | Square-2 |
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 4, 1                                                    @ 085 | Square-1 |
	voice_square_2_alt 60, 0, 3, 0, 1, 4, 1                                                       @ 086 | Square-2 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_21, 0, 7, 15, 1                       @ 087 | Wave | GBA Programmable Wave 21
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0                        @ 088 | Wave | GBA Programmable Wave 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_15, 0, 1, 9, 2                        @ 089 | Wave | GBA Programmable Wave 15
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 090 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 091 | --- | 
	voice_square_2_alt 60, 0, 2, 0, 2, 6, 3                                                       @ 092 | Square-2 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 093 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 094 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 095 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 096 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 097 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 098 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 099 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 100 | --- | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 7, 15, 0                        @ 101 | Wave | GBA Programmable Wave 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_18, 0, 7, 15, 0                       @ 102 | Wave | GBA Programmable Wave 18
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 103 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 104 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 105 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 106 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 107 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 108 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 109 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 110 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 111 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 112 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 113 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 114 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 115 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 116 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 117 | --- | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_2, 1, 7, 2, 15                        @ 118 | Wave | GBA Programmable Wave 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 119 | --- | 
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum				                              @ 120 | Direct | Drum | HGSS drums
	voice_keysplit_all voicegroup_allkeysplit_hgss_taiko_drum				                      @ 121 | Direct | Drum | HGSS taiko drums
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 122 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 123 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 124 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 125 | --- | 
	voice_noise_alt 60, 0, 0, 0, 2, 6, 2                                                          @ 126 | Noise | GBA Noise 1
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0                                                          @ 127 | Noise | GBA Noise 2
