voice_group taiketsu_ultra_hero
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano_custom                                     @ 000 | Direct | RSE Piano
	voice_keysplit voicegroup_keysplit_hgss_piano_1, keysplit_hgss_piano_1                              @ 001 | Direct | HGSS Piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127                       @ 002 | Direct | GBA Organ
	voice_keysplit voicegroup_keysplit_hgss_marimba, keysplit_hgss_marimba_music_box_sampled_square     @ 003 | Direct | HGSS marimba
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 249, 25, 204            @ 004 | Direct | GBA Nylon Guitar 1
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_hgss_distortion_guitar        @ 005 | Direct | HGSS Distortion Guitar 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149                @ 006 | Direct | GBA Fretless Bass 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149                @ 007 | Direct | GBA Fingered Bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226                      @ 008 | Direct | GBA Timpani
	voice_keysplit voicegroup_keysplit_strings_custom, keysplit_strings_custom                          @ 009 | Direct | Multi | GBA String
	voice_keysplit voicegroup_keysplit_trumpet_custom, keysplit_trumpet_custom                          @ 010 | Direct | Multi | GBA Trumpet
	voice_keysplit voicegroup_keysplit_hgss_trumpet, keysplit_hgss_xylophone_trumpet                    @ 011 | Direct | Multi | HGSS Trumpet
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165                 @ 012 | Direct | GBA Oboe 1
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_brass, 255, 0, 255, 165                   @ 013 | Direct | GBA Golden Sun Brass Section
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                  @ 014 | Direct | HGSS Sawtooth
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127                      @ 015 | Direct | GBA Flute
	voice_keysplit voicegroup_keysplit_strings_custom, keysplit_strings_custom                          @ 016 | Direct | Multi | GBA String
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                              @ 017 | Direct | Multi | HGSS String
	voice_keysplit voicegroup_keysplit_hgss_violin, keysplit_hgss_violin                                @ 018 | Direct | Multi | HGSS Violin
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 019 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 020 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 021 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 022 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 023 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 024 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 025 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 026 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 027 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 028 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 029 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 030 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 031 | ---
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum				                                    @ 032 | Direct | Drum | HGSS drums
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum				                                    @ 033 | Direct | Drum | HGSS drums
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum				                                    @ 034 | Direct | Drum | HGSS drums
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 035 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 036 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 037 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 038 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 039 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 040 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 041 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 042 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 043 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 044 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 045 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 046 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 047 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 048 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 049 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 050 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 051 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 052 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 053 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 054 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 055 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 056 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 057 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 058 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 059 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 060 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 061 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 062 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 063 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 064 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 065 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 066 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 067 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 068 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 069 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 070 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 071 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 072 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 073 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 074 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 075 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 076 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 077 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 078 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 079 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 080 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 081 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 082 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 083 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 084 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 085 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 086 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 087 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 088 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 089 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 090 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 091 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 092 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 093 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 094 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 095 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 096 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 097 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 098 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 099 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 100 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 101 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 102 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 103 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 104 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 105 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 106 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 107 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 108 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 109 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 110 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 111 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 112 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 113 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 114 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 115 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 116 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 117 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 118 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 119 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 120 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 121 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 122 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 123 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 124 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 125 | ---
	voice_directsound 60, 0, DirectSoundWaveData_hg_062chh, 255, 242, 0, 171                            @ 126 | HGSS Open Hit Hat
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum                                                 @ 127 | HGSS Drum
