voice_group tsubasa_reservoir_chronicle
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 249, 0, 188       @ 000 | Direct | RSE Electric Piano 1
	voice_keysplit voicegroup_keysplit_hgss_violin, keysplit_hgss_violin                                                       @ 001 | Direct | Multi | HGSS Violin
	voice_keysplit voicegroup_keysplit_hgss_violin, keysplit_hgss_violin                                                       @ 002 | Direct | Multi | HGSS Violin
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings_custom                                  @ 003 | Direct | Multi | RSE Strings
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                  @ 004 | Direct | HGSS Sawtooth
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                                                       @ 005 | Direct | Multi | HGSS String
	voice_keysplit voicegroup_trumpet_keysplit, keysplit_trumpet_custom                                         @ 006 | Direct | Multi | RSE Trumpets
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                   @ 007 | Direct | HGSS Altosax
	voice_keysplit voicegroup_keysplit_hgss_piano_1, keysplit_hgss_piano_1                                                       @ 008 | Direct | HGSS piano
	voice_keysplit voicegroup_keysplit_hgss_piano_2, keysplit_hgss_piano_2_vibraphone_glockglockenspiel                                                       @ 009 | Direct | HGSS piano 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 010 | --- | 
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano_custom                                          @ 011 | Direct | Multi | RSE Piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 249, 25, 204            @ 012 | Direct | RSE Nylon Guitar 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165            @ 013 | Direct | RSE Pizzicato
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 51, 242                        @ 014 | Direct | RSE Harp
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0                              @ 015 | Wave | GBA Programmable Wave 1
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_choir_ohhs, 255, 188, 220, 243                  @ 016 | Direct | RF Choir Ohhs
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127                       @ 017 | Direct | RSE Organ
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188           @ 018 | Direct | RSE Crunch Organ 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188          @ 019 | Direct | RSE Crunch Organ 2
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc55_tom, 255, 210, 77, 204                     @ 020 | Direct | RSE Unknown Tom
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226                      @ 021 | Direct | RSE Timpani
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 251, 0, 171                    @ 022 | Direct | HGSS Wood Bass
	voice_directsound 42, 0, DirectSoundWaveData_sd90_solo_snare, 255, 180, 175, 228                    @ 023 | Direct | RSE Solo Snare
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 165, 154, 127                  @ 024 | Direct | RSE Trinity Big Boned
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                  @ 025 | Direct | HGSS Sawtooth
	voice_keysplit voicegroup_keysplit_strings_custom, keysplit_strings_custom                                                        @ 026 | Direct | RSE Strings
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings_custom                                  @ 027 | Direct | Multi | RSE Strings
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242 @ 028 | Direct | RSE Orchestra Snare
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204                    @ 029 | Direct | RSE Xylophone
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 115                  @ 030 | Direct | RSE Slap Bass
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_hgss_distortion_guitar                                                       @ 031 | Direct | Multi | HGSS Distortion Guitar 1
	voice_keysplit voicegroup_keysplit_hgss_clean_guitar, keysplit_hgss_guitar                                                       @ 032 | Direct | Multi | HGSS Clean Guitar
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0                                                                @ 033 | Noise | GB Noise 2
	voice_keysplit voicegroup_keysplit_hgss_pizzicato, keysplit_hgss_pizzicato                                                       @ 034 | Direct | Multi | HGSS Pizzicato
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc55_tom, 255, 210, 77, 204                     @ 035 | Direct | RSE Unknown Tom
	voice_square_2_alt 60, 0, 2, 0, 2, 4, 1                                                             @ 036 | Square2 | GB Square-2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 037 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 038 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 039 | --- | 
	voice_keysplit voicegroup_keysplit_hgss_music_box, keysplit_hgss_marimba_music_box_sampled_square                                                       @ 040 | Direct | Multi | HGSS Music Box 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 041 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 042 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 043 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 044 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 045 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 046 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 047 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 048 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 049 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 050 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 051 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 052 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 053 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 054 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 055 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 056 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 057 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 058 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 059 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 060 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 061 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 062 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 063 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 064 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 065 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 066 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 067 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 068 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 069 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 070 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 071 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 072 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 073 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 074 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 075 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 076 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 077 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 078 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 079 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 080 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 081 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 082 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 083 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 084 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 085 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 086 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 087 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 088 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 089 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 090 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 091 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 092 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 093 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 094 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 095 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 096 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 097 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 098 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 099 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 100 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 101 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 102 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 103 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 104 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 105 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 106 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 107 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 108 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 109 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 110 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 111 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 112 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 113 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 114 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 115 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 116 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 117 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 118 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 119 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 120 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 121 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 122 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 123 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 124 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 125 | --- | 
	voice_keysplit_all voicegroup_allkeysplit_frlg_custom_drum                                          @ 126 | Direct | Drum | FRLG Drum Custom
	voice_keysplit_all voicegroup_allkeysplit_bw_drum_2                                                                    @ 127 | Direct | Drum | BW Drumset 2 Mapping
