	.align 2
voicegroup305::
    voice_directsound 60, 0, DirectSoundWaveData_MMBAS40, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_MMBAS43, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_MMBAS62, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_MMBAS62, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SINE_A0A, 255, 0, 255, 127

