	.align 2
voicegroup341::
    voice_directsound 60, 0, DirectSoundWaveData_FLUTE65A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FLUTE73A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FLUTE79A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FLUTE88A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FLUTE96A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FLUTEA5A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OCARI96A, 255, 0, 255, 127
