	.align 2
voicegroup339::
    voice_directsound 60, 0, DirectSoundWaveData_SYNCL55, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SYNCL64, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SYNCL70, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SYNCL75, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SYNCL87, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA8, 255, 0, 255, 127
