	.align 2
voicegroup338::
    voice_directsound 60, 0, DirectSoundWaveData_BASSN44, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BASSN69, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BASSN69, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_B_SAXB0A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAXA8, 255, 0, 255, 127
