	.align 2
voicegroup295::
    voice_directsound 60, 0, DirectSoundWaveData_BANDO64, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BANDO64, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BANDO74, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG88, 255, 0, 255, 127
