	.align 2
voicegroup342::
    voice_directsound 60, 0, DirectSoundWaveData_RECDR66A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_RECDR75A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_RECDR83A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_RECDR93A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_RECDRA3A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OCARI96A, 255, 0, 255, 127
