	.align 2
voicegroup309::
    voice_directsound 60, 0, DirectSoundWaveData_SLPMT52A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SLPMT52A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SLPBS43, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SLPBS84, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_STLGT84B, 255, 0, 255, 127
