	.align 2
voicegroup345::
    voice_directsound 60, 0, DirectSoundWaveData_SHAKU63, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SHAKU70, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SHAKU78, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PICLO84, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OCARI96A, 255, 0, 255, 127
