	.align 2
voicegroup327::
    voice_directsound 60, 0, DirectSoundWaveData_MUTTP64B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_MUTTP73B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_MUTTP79B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_MUTTP86B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPT92, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPTA1, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA8, 255, 0, 255, 127

