	.align 2
voicegroup358::
    voice_directsound 60, 0, DirectSoundWaveData_POLY_48A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_POLY_60A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_POLY_72A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_POLY_84A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_POLY_96A, 255, 0, 255, 127
