	.align 2
voicegroup373::
    voice_directsound 60, 0, DirectSoundWaveData_SHAMI53, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SHAMI53, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SHAMI65, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SHAMI77, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SHAMI89, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG88, 255, 0, 255, 127
