	.align 2
voicegroup355::
    voice_directsound 60, 0, DirectSoundWaveData_BS_LD48, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BS_LD48, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BS_LD72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BS_LD72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BS_LD96, 255, 0, 255, 127
