	.align 2
voicegroup314::
    voice_directsound 60, 0, DirectSoundWaveData_CONBS28, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CONBL41, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CONBH41, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HARMO76, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HARMO84, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HARMO92, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HARMOA0, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HARMOA8, 255, 0, 255, 127
