	.align 2
voicegroup334::
    voice_directsound 60, 0, DirectSoundWaveData_T_SAX46, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAX57, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAX63, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAX68, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAX74, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAX81, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAX89, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAX97, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAXA8, 255, 0, 255, 127
