	.align 2
voicegroup306::
    voice_directsound 60, 0, DirectSoundWaveData_PCKBS30A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PCKBS40A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PCKBS50A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT84A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT93A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGTA1A, 255, 0, 255, 127
