	.align 2
voicegroup332::
    voice_directsound 60, 0, DirectSoundWaveData_S_SAX70, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAX76, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAX82, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAX88, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAX95, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA2, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA8, 255, 0, 255, 127
