	.align 2
voicegroup202::
    voice_keysplit voicegroup274, KeySplitTableGS6                                @ 000 | Direct | GS Acoustic Grand
    voice_keysplit voicegroup274, KeySplitTableGS7                                @ 001 | Direct | GS Bright Accoustic
    voice_keysplit voicegroup274, KeySplitTableGS8                                @ 002 | Direct | GS Electric Grand
    voice_keysplit voicegroup275, KeySplitTableGS9                                @ 003 | Direct | GS Honky-Tonk
    voice_keysplit voicegroup276, KeySplitTableGS10                               @ 004 | Direct | GS Electric Piano 1
    voice_keysplit voicegroup277, KeySplitTableGS11                               @ 005 | Direct | GS Electric Piano 2
    voice_keysplit voicegroup278, KeySplitTableGS12                               @ 006 | Direct | GS Harpsichord
    voice_keysplit voicegroup279, KeySplitTableGS13                               @ 007 | Direct | GS Clav
    voice_keysplit voicegroup280, KeySplitTableGS14                               @ 008 | Direct | GS Celesta
    voice_keysplit voicegroup281, KeySplitTableGS15                               @ 009 | Direct | GS Glockenspiel
    voice_keysplit voicegroup282, KeySplitTableGS16                               @ 010 | Direct | GS Music Box
    voice_keysplit voicegroup283, KeySplitTableGS17                               @ 011 | Direct | GS Vibraphone
    voice_keysplit voicegroup284, KeySplitTableGS18                               @ 012 | Direct | GS Marimba
    voice_keysplit voicegroup285, KeySplitTableGS19                               @ 013 | Direct | GS Xylophone
    voice_keysplit voicegroup286, KeySplitTableGS20                               @ 014 | Direct | GS Tabular Bell
    voice_keysplit voicegroup287, KeySplitTableGS21                               @ 015 | Direct | GS Dulcimer
    voice_keysplit voicegroup288, KeySplitTableGS22                               @ 016 | Direct | GS Drawbar Organ
    voice_keysplit voicegroup289, KeySplitTableGS23                               @ 017 | Direct | GS Percussive Organ
    voice_keysplit voicegroup290, KeySplitTableGS24                               @ 018 | Direct | GS Rock Organ
    voice_keysplit voicegroup291, KeySplitTableGS25                               @ 019 | Direct | GS Church Organ
    voice_keysplit voicegroup292, KeySplitTableGS26                               @ 020 | Direct | GS Reed Organ
    voice_keysplit voicegroup293, KeySplitTableGS27                               @ 021 | Direct | GS Accordian
    voice_keysplit voicegroup294, KeySplitTableGS28                               @ 022 | Direct | GS Harmonica
    voice_keysplit voicegroup295, KeySplitTableGS29                               @ 023 | Direct | GS Tango Accodion
    voice_keysplit voicegroup296, KeySplitTableGS30                               @ 024 | Direct | GS Acoustic Guitar Nylon
    voice_keysplit voicegroup297, KeySplitTableGS31                               @ 025 | Direct | GS Acoustic Guitar Steel
    voice_keysplit voicegroup298, KeySplitTableGS32                               @ 026 | Direct | GS Electric Guitar Jazz
    voice_keysplit voicegroup299, KeySplitTableGS33                               @ 027 | Direct | GS Electric Guitar Clean
    voice_keysplit voicegroup300, KeySplitTableGS34                               @ 028 | Direct | GS Electric Guitar Muted
    voice_keysplit voicegroup301, KeySplitTableGS35                               @ 029 | Direct | GS Overdriven Guitar
    voice_keysplit voicegroup302, KeySplitTableGS36                               @ 030 | Direct | GS Distortion Guitar
    voice_keysplit voicegroup303, KeySplitTableGS37                               @ 031 | Direct | GS Guitar Harmonics
    voice_keysplit voicegroup304, KeySplitTableGS38                               @ 032 | Direct | GS Acoustic Bass
    voice_keysplit voicegroup305, KeySplitTableGS39                               @ 033 | Direct | GS Electric Bass Finger
    voice_keysplit voicegroup306, KeySplitTableGS40                               @ 034 | Direct | GS Electric Bass Pick
    voice_keysplit voicegroup307, KeySplitTableGS41                               @ 035 | Direct | GS Fretless Bass
    voice_keysplit voicegroup308, KeySplitTableGS42                               @ 036 | Direct | GS Slap Bass 1
    voice_keysplit voicegroup309, KeySplitTableGS43                               @ 037 | Direct | GS Slap Bass 2
    voice_keysplit voicegroup310, KeySplitTableGS44                               @ 038 | Direct | GS Synth Bass 1
    voice_keysplit voicegroup311, KeySplitTableGS45                               @ 039 | Direct | GS Synth Bass 2
    voice_keysplit voicegroup312, KeySplitTableGS46                               @ 040 | Direct | GS Violin
    voice_keysplit voicegroup312, KeySplitTableGS47                               @ 041 | Direct | GS Viola
    voice_keysplit voicegroup313, KeySplitTableGS48                               @ 042 | Direct | GS Cello
    voice_keysplit voicegroup314, KeySplitTableGS49                               @ 043 | Direct | GS Contrabass
    voice_keysplit voicegroup315, KeySplitTableGS50                               @ 044 | Direct | GS Tremolo Strings
    voice_keysplit voicegroup316, KeySplitTableGS51                               @ 045 | Direct | GS Pizzicato Strings
    voice_keysplit voicegroup317, KeySplitTableGS52                               @ 046 | Direct | GS Orchestral Strings
    voice_keysplit voicegroup318, KeySplitTableGS53                               @ 047 | Direct | GS Timpani
    voice_keysplit voicegroup319, KeySplitTableGS54                               @ 048 | Direct | GS String Ensemble 1
    voice_keysplit voicegroup319, KeySplitTableGS54                               @ 049 | Direct | GS String Ensemble 2
    voice_keysplit voicegroup320, KeySplitTableGS55                               @ 050 | Direct | GS Synth String 1
    voice_keysplit voicegroup320, KeySplitTableGS56                               @ 051 | Direct | GS Synth String 2
    voice_keysplit voicegroup321, KeySplitTableGS57                               @ 052 | Direct | GS Choir Aahs
    voice_keysplit voicegroup322, KeySplitTableGS58                               @ 053 | Direct | GS Voice Oohs
    voice_keysplit voicegroup323, KeySplitTableGS59                               @ 054 | Direct | GS Synth Voice
    voice_directsound 60, 0, DirectSoundWaveData_O_HIT68, 255, 0, 255, 127        @ 055 | Direct | GS Orchestra Hit
    voice_keysplit voicegroup324, KeySplitTableGS60                               @ 056 | Direct | GS Trumpet
    voice_keysplit voicegroup325, KeySplitTableGS61                               @ 057 | Direct | GS Trombone
    voice_keysplit voicegroup326, KeySplitTableGS62                               @ 058 | Direct | GS Tuba
    voice_keysplit voicegroup327, KeySplitTableGS63                               @ 059 | Direct | GS Muted Trumpet
    voice_keysplit voicegroup328, KeySplitTableGS64                               @ 060 | Direct | GS French Horn
    voice_keysplit voicegroup329, KeySplitTableGS65                               @ 061 | Direct | GS Brass Section
    voice_keysplit voicegroup330, KeySplitTableGS66                               @ 062 | Direct | GS Synth Brass 1
    voice_keysplit voicegroup331, KeySplitTableGS67                               @ 063 | Direct | GS Synth Brass 2
    voice_keysplit voicegroup332, KeySplitTableGS68                               @ 064 | Direct | GS Soprano Sax
    voice_keysplit voicegroup333, KeySplitTableGS69                               @ 065 | Direct | GS Alto Sax
    voice_keysplit voicegroup334, KeySplitTableGS70                               @ 066 | Direct | GS Tenor Sax
    voice_keysplit voicegroup335, KeySplitTableGS71                               @ 067 | Direct | GS Baritone Sax
    voice_keysplit voicegroup336, KeySplitTableGS72                               @ 068 | Direct | GS Oboe
    voice_keysplit voicegroup337, KeySplitTableGS73                               @ 069 | Direct | GS English Horn
    voice_keysplit voicegroup338, KeySplitTableGS74                               @ 070 | Direct | GS Bassoon
    voice_keysplit voicegroup339, KeySplitTableGS75                               @ 071 | Direct | GS Clarinet
    voice_keysplit voicegroup340, KeySplitTableGS76                               @ 072 | Direct | GS Piccolo
    voice_keysplit voicegroup341, KeySplitTableGS77                               @ 073 | Direct | GS Flute
    voice_keysplit voicegroup342, KeySplitTableGS78                               @ 074 | Direct | GS Recorder
    voice_keysplit voicegroup343, KeySplitTableGS79                               @ 075 | Direct | GS Pan Flute
    voice_keysplit voicegroup344, KeySplitTableGS80                               @ 076 | Direct | GS Blown Bottle
    voice_keysplit voicegroup345, KeySplitTableGS81                               @ 077 | Direct | GS Skakuhachi
    voice_keysplit voicegroup346, KeySplitTableGS82                               @ 078 | Direct | GS Whistle
    voice_keysplit voicegroup347, KeySplitTableGS83                               @ 079 | Direct | GS Oracina
    voice_keysplit voicegroup348, KeySplitTableGS84                               @ 080 | Direct | GS Lead 1 Square
    voice_keysplit voicegroup349, KeySplitTableGS85                               @ 081 | Direct | GS Lead 2 Sawtooth
    voice_keysplit voicegroup350, KeySplitTableGS86                               @ 082 | Direct | GS Lead 3 Calliope
    voice_keysplit voicegroup351, KeySplitTableGS87                               @ 083 | Direct | GS Lead 4 Chiff
    voice_keysplit voicegroup352, KeySplitTableGS88                               @ 084 | Direct | GS Lead 5 Charang
    voice_keysplit voicegroup353, KeySplitTableGS89                               @ 085 | Direct | GS Lead 6 Voice
    voice_keysplit voicegroup354, KeySplitTableGS90                               @ 086 | Direct | GS Lead 7 Fifths
    voice_keysplit voicegroup355, KeySplitTableGS91                               @ 087 | Direct | GS Lead 8 Bass
    voice_keysplit voicegroup356, KeySplitTableGS92                               @ 088 | Direct | GS Pad 1 New Age
    voice_keysplit voicegroup357, KeySplitTableGS93                               @ 089 | Direct | GS Pad 2 Warm
    voice_keysplit voicegroup358, KeySplitTableGS94                               @ 090 | Direct | GS Pad 3 Polysynth
    voice_keysplit voicegroup359, KeySplitTableGS95                               @ 091 | Direct | GS Pad 4 Choir
    voice_keysplit voicegroup360, KeySplitTableGS96                               @ 092 | Direct | GS Pad 5 Bowed
    voice_keysplit voicegroup361, KeySplitTableGS97                               @ 093 | Direct | GS Pad 6 Metallic
    voice_keysplit voicegroup362, KeySplitTableGS98                               @ 094 | Direct | GS Pad 7 Halo
    voice_keysplit voicegroup363, KeySplitTableGS99                               @ 095 | Direct | GS Pad 8 Sweep
    voice_keysplit voicegroup364, KeySplitTableGS100                              @ 096 | Direct | GS FX 1 Rain
    voice_keysplit voicegroup365, KeySplitTableGS101                              @ 097 | Direct | GS FX 2 Soundtrack
    voice_keysplit voicegroup366, KeySplitTableGS102                              @ 098 | Direct | GS FX 3 Crystal
    voice_keysplit voicegroup367, KeySplitTableGS103                              @ 099 | Direct | GS FX 4 Atmosphere
    voice_keysplit voicegroup368, KeySplitTableGS104                              @ 100 | Direct | GS FX 5 Brightness
    voice_directsound 60, 0, DirectSoundWaveData_GOBLN84A, 255, 0, 255, 127       @ 101 | Direct | GS FX 6 Goblins
    voice_keysplit voicegroup369, KeySplitTableGS105                              @ 102 | Direct | GS FX 7 Echoes
    voice_keysplit voicegroup370, KeySplitTableGS106                              @ 103 | Direct | GS FX 8 Sci-fi
    voice_keysplit voicegroup371, KeySplitTableGS107                              @ 104 | Direct | GS Sitar
    voice_keysplit voicegroup372, KeySplitTableGS110                              @ 105 | Direct | GS Banjo
    voice_keysplit voicegroup373, KeySplitTableGS108                              @ 106 | Direct | GS Shamisen
    voice_keysplit voicegroup374, KeySplitTableGS109                              @ 107 | Direct | GS Koto
    voice_keysplit voicegroup375, KeySplitTableGS111                              @ 108 | Direct | GS Kalimba
    voice_keysplit voicegroup376, KeySplitTableGS112                              @ 109 | Direct | GS Bagpipe
    voice_keysplit voicegroup377, KeySplitTableGS113                              @ 110 | Direct | GS Fiddle
    voice_keysplit voicegroup378, KeySplitTableGS114                              @ 111 | Direct | GS Shanai
    voice_keysplit voicegroup379, KeySplitTableGS115                              @ 112 | Direct | GS Tinkle Bell
    voice_directsound 60, 0, DirectSoundWaveData_AGOGO60, 255, 0, 255, 127        @ 113 | Direct | GS Agogo
    voice_keysplit voicegroup380, KeySplitTableGS116                              @ 114 | Direct | GS Steel Drums Part
    voice_directsound 60, 0, DirectSoundWaveData_WODBK60, 255, 0, 255, 127        @ 115 | Direct | GS Woodblock
    voice_directsound 60, 0, DirectSoundWaveData_SURDO60, 255, 0, 255, 127        @ 116 | Direct | GS Taiko Drum Part
    voice_directsound 60, 0, DirectSoundWaveData_TOM__60, 255, 0, 255, 127        @ 117 | Direct | GS Melodic Tom Part
    voice_directsound 60, 0, DirectSoundWaveData_SYNDR56, 255, 0, 255, 127        @ 118 | Direct | GS Synth Drum Part
    voice_directsound 60, 0, DirectSoundWaveData_CRASH60B, 255, 0, 255, 127       @ 119 | Direct | GS Reverse Cymbal
    voice_directsound 60, 0, DirectSoundWaveData_GFRET69, 255, 0, 255, 127        @ 120 | Direct | GS Guitar Fret Noise
    voice_keysplit voicegroup381, KeySplitTableGS117                              @ 121 | Direct | GS Breath Noise
    voice_directsound 60, 0, DirectSoundWaveData_SEA__60, 255, 0, 255, 127        @ 122 | Direct | GS Seashore
    voice_directsound 60, 0, DirectSoundWaveData_BIRD_60, 255, 0, 255, 127        @ 123 | Direct | GS Bird Tweet
    voice_directsound 60, 0, DirectSoundWaveData_TELE_60, 255, 0, 255, 127        @ 124 | Direct | GS Telephone Ring 1
    voice_directsound 60, 0, DirectSoundWaveData_TELE260, 255, 0, 255, 127        @ 125 | Direct | GS Telephone Ring 2
    voice_directsound 60, 0, DirectSoundWaveData_APPLS64A, 255, 0, 255, 127       @ 126 | Direct | GS Applause
    voice_directsound 60, 0, DirectSoundWaveData_PISTL60, 255, 0, 255, 127        @ 127 | Direct | GS Gunshot
