	.align 2
voicegroup307::
    voice_directsound 60, 0, DirectSoundWaveData_FRTLS36A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FRTLS48A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FRTLS60A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT84A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT93A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGTA1A, 255, 0, 255, 127
