	.align 2
voicegroup274::
    voice_directsound 60, 0, DirectSoundWaveData_PIANO36, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PIANO41, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PIANO48, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PIANO56, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PIANO64, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PIANO73, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PIANO78, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PIANO84, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PIANO92, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_PIANOA3, 255, 0, 255, 127
