	.align 2
voicegroup283::
    voice_directsound 60, 0, DirectSoundWaveData_VIBE_52A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIBE_64A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIBE_76A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIBE_88A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIBE_A0A, 255, 0, 255, 127
