	.align 2
voicegroup277::
    voice_directsound 60, 0, DirectSoundWaveData_ELP2_60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP2_68, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP2_76, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP2_84, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP2_92, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP2_A0, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP2_A8, 255, 0, 255, 127
