	.align 2
voicegroup372::
    voice_directsound 60, 0, DirectSoundWaveData_BANJO60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BANJO60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BANJO70, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BANJO83, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HRPSI87A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG88, 255, 0, 255, 127
