	.align 2
voicegroup374::
    voice_directsound 60, 0, DirectSoundWaveData_KOTO_57, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_KOTO_57, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_KOTO_80, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HRPSI87A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG88, 255, 0, 255, 127
