	.align 2
voicegroup376::
    voice_directsound 60, 0, DirectSoundWaveData_BAGPP53A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BAGPP64A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BAGPP74A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BAGPP84A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BAGPP93A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA2, 255, 0, 255, 127
