	.align 2
voicegroup301::
    voice_directsound 60, 0, DirectSoundWaveData_OVDRV44, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OVDRV49, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OVDRV60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OVDRV60A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OVDRV70, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OVDRV73, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OVDRV77, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OVDRV89, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OVDRV96, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OVDRVA6, 255, 0, 255, 127
