	.align 2
voicegroup299::
    voice_directsound 60, 0, DirectSoundWaveData_CLNGT48, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CLNGT60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CLNGT67, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CLNGT72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CLNGT84, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_STLGT84B, 255, 0, 255, 127
