	.align 2
voicegroup333::
    voice_directsound 60, 0, DirectSoundWaveData_A_SAX53, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_A_SAX59, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_A_SAX63, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_A_SAX69, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_A_SAX77, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_A_SAX87, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_A_SAX96, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_A_SAXA5, 255, 0, 255, 127
