	.align 2
voicegroup335::
    voice_directsound 60, 0, DirectSoundWaveData_B_SAX38, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_B_SAX48, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_B_SAX59, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_B_SAX86, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_B_SAXB0A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_T_SAXA8, 255, 0, 255, 127
