	.align 2
voicegroup302::
    voice_directsound 60, 0, DirectSoundWaveData_DSTGT48, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_DSTGT54, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_DSTGT59, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_DSTGT64, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_DSTGT71, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_DSTGT77, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_DSTGT92, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_DSTGTA1, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_DSTGTA9, 255, 0, 255, 127
