	.align 2
voicegroup361::
    voice_directsound 60, 0, DirectSoundWaveData_HONKY42A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HONKY62B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HONKY71A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HONKY84A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HONKY96A, 255, 0, 255, 127
