	.align 2
voicegroup346::
    voice_directsound 60, 0, DirectSoundWaveData_SINE_52, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SINE_64, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SINE_76, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SINE_88, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OCARI96A, 255, 0, 255, 127
