	.align 2
voicegroup279::
    voice_directsound 60, 0, DirectSoundWaveData_CLAVI48, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CLAVI60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CLAVI72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CLAVI84, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_KOTO_A2A, 255, 0, 255, 127
