	.align 2
voicegroup296::
    voice_directsound 60, 0, DirectSoundWaveData_NYLON48A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_NYLON57A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_NYLON70A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_NYLON79A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_NYLON88A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_NYLON97A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGTA1A, 255, 0, 255, 127
