	.align 2
voicegroup365::
    voice_directsound 60, 0, DirectSoundWaveData_SOUND60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SOUND60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SOUND60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SOUND84, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SOUND84, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SOUND84, 255, 0, 255, 127
