	.align 2
voicegroup349::
    voice_directsound 60, 0, DirectSoundWaveData_SAW0_48, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SAW0_60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SAW0_72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SSTR186A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SBRS296, 255, 0, 255, 127
