	.align 2
voicegroup377::
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN68, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN70, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN76, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN80, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN86, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN95, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLNA4, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA2, 255, 0, 255, 127
