	.align 2
voicegroup292::
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG53, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG53, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_R_ORG88, 255, 0, 255, 127
