	.align 2
voicegroup336::
    voice_directsound 60, 0, DirectSoundWaveData_OBOE_61A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OBOE_69A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OBOE_77A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OBOE_85A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_OBOE_81, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPTB1A, 255, 0, 255, 127
