	.align 2
voicegroup313::
    voice_directsound 60, 0, DirectSoundWaveData_CELLO28, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CELLO41, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CELLL64, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CELLH64, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_CELLO76, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLNA4, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SAW__A7A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HARMOA8, 255, 0, 255, 127
