	.align 2
voicegroup312::
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN68, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN70, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN76, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN80, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN86, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLN95, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_VIOLNA4, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SAW__A7A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA8, 255, 0, 255, 127
