	.align 2
voicegroup325::
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN40A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN48A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN55A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN62A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN68A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN77A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN86A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN93A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPTA1, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA8, 255, 0, 255, 127
