	.align 2
voicegroup337::
    voice_directsound 60, 0, DirectSoundWaveData_EHORN53A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_EHORN61A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_EHORN70A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_EHORN82A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAX95, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA2, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA8, 255, 0, 255, 127
