	.align 2
voicegroup297::
    voice_directsound 60, 0, DirectSoundWaveData_STLGT41B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_STLGT49B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_STLGT57B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_STLGT65B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_STLGT74B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_STLGT84B, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_STLGT84B, 255, 0, 255, 127
