	.align 2
voicegroup328::
    voice_directsound 60, 0, DirectSoundWaveData_FHORN60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FHORN60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FHORN72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_FHORN72, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA8, 255, 0, 255, 127
