	.align 2
voicegroup318::
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127
