	.align 2
voicegroup378::
    voice_directsound 60, 0, DirectSoundWaveData_BAGPP64A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BAGPP74A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BAGPP84A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_BAGPP93A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HARMOA8, 255, 0, 255, 127
