	.align 2
voicegroup324::
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN40A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN40A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMBN55A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPT65, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPT73, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPT81, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPT86, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPT92, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TRMPTA1, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_S_SAXA8, 255, 0, 255, 127
