	.align 2
voicegroup604::
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 249, 0, 188 @ 000 | Brave Heart | Direct | RSE Electric Piano
	voice_keysplit voicegroup248, KeySplitTable41                                                 @ 001 | Brave Heart | Direct | HGSS Martin Guitar 
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 002 | Brave Heart | GB-Noise
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 146             @ 003 | Brave Heart | Direct | RSE Synth Bass
	voice_keysplit voicegroup261, KeySplitTable39                                                 @ 004 | Beat Hit    | Direct | HGSS Trumpet
	voice_keysplit voicegroup248, KeySplitTable41                                                 @ 005 | Beat Hit    | Direct | HGSS Martin Guitar 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 146             @ 006 | Beat Hit    | Direct | RSE Synth Bass
	voice_keysplit voicegroup196, KeySplitTable2                                                  @ 007 | EVO         | Direct | RSE Strings
	voice_keysplit voicegroup255, KeySplitTable45                                                 @ 008 | EVO         | Direct | HGSS Strings
	voice_keysplit voicegroup239, KeySplitTable38                                                 @ 009 | EVO         | Direct | HGSS Marimba
	voice_keysplit voicegroup256, KeySplitTable46                                                 @ 010 | EVO         | Direct | HGSS Violin 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 146             @ 011 | EVO         | Direct | RSE Synth Bass
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 012 | EVO         | GB-Noise
	voice_square_2_alt 60, 0, 2, 0, 6, 1, 0                                                       @ 013 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 11, 0                                                   @ 014 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB64, 0, 3, 7, 0             @ 015 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 0, 15, 0            @ 016 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0                                                   @ 017 | 
	voice_square_2_alt 60, 0, 0, 0, 2, 0, 1                                                       @ 018 | 
	voice_square_2_alt 60, 0, 1, 0, 0, 13, 0                                                      @ 019 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 020 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 021 | 
	voice_square_2_alt 60, 0, 1, 0, 0, 13, 0                                                      @ 022 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 12, 0                                                      @ 023 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 024 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 025 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 13, 0                                                      @ 026 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 3, 2                                                    @ 027 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 028 | 
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 029 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0                                                      @ 030 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0                                                   @ 031 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 032 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 12, 0                                                      @ 033 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 0, 0                                                    @ 034 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 035 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 12, 0                                                      @ 036 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 037 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 038 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB74, 0, 0, 15, 0            @ 039 | 
	voice_square_2_alt 60, 0, 1, 0, 4, 5, 0                                                       @ 040 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 041 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 13, 0                                                      @ 042 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 043 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 044 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 13, 0                                                      @ 045 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 046 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 047 | 
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 048 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 13, 0                                                      @ 049 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 050 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 051 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 13, 0                                                      @ 052 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 053 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 054 | 
	voice_square_2_alt 60, 0, 2, 0, 4, 5, 0                                                       @ 055 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 4, 5, 0                                                    @ 056 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB64, 0, 3, 7, 0             @ 057 | 
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 058 | 
	voice_noise_alt 60, 0, 1, 0, 0, 15, 0                                                         @ 059 | 
	voice_square_2_alt 60, 0, 0, 0, 1, 3, 0                                                       @ 060 | 
	voice_square_2_alt 60, 0, 1, 0, 1, 3, 2                                                       @ 061 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 062 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 1, 2                                                    @ 063 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB64, 0, 2, 1, 0             @ 064 | 
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 065 | 
	voice_square_2_alt 60, 0, 2, 0, 2, 6, 1                                                       @ 066 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 3, 2                                                    @ 067 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 068 | 
	voice_square_2_alt 60, 0, 2, 0, 2, 6, 1                                                       @ 069 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 6, 1                                                    @ 070 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB64, 0, 2, 1, 0             @ 071 | 
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 072 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 11, 1                                                      @ 073 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 6, 1                                                    @ 074 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 0, 15, 0            @ 075 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 11, 0                                                   @ 076 | 
	voice_square_2_alt 60, 0, 2, 0, 1, 8, 0                                                       @ 077 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB64, 0, 2, 1, 0             @ 078 | 
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 079 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 11, 0                                                      @ 080 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 081 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB64, 0, 0, 15, 0            @ 082 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 11, 0                                                      @ 083 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 12, 0                                                   @ 084 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 085 | 
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 086 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 11, 0                                                      @ 087 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 8, 0                                                    @ 088 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 089 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 13, 0                                                      @ 090 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 12, 0                                                   @ 091 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 0, 15, 0            @ 092 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 13, 0                                                      @ 093 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                                   @ 094 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_DgmnBS_37FB54, 0, 3, 7, 0             @ 095 | 
	voice_noise_alt 60, 0, 0, 0, 2, 0, 1                                                          @ 096 | 
	voice_keysplit voicegroup245, KeySplitTable40                                                 @ 097 | Evolution   | Direct | HGSS Jazz Organ
	voice_keysplit voicegroup236, KeySplitTable9                                                  @ 098 | Evolution   | Direct | HGSS Rhodes
	voice_keysplit voicegroup254, KeySplitTable44                                                 @ 099 | Evolution   | Direct | HGSS Synth Bass
	voice_square_1 60, 0, 0, 1, 0, 0, 15, 0                                                       @ 100 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 13, 0                                                   @ 101 | 
	voice_square_1 60, 0, 0, 0, 0, 0, 15, 0                                                       @ 102 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 103 | 
	voice_noise_alt 60, 0, 0, 0, 0, 15, 0                                                         @ 104 | 
	voice_square_1 60, 0, 0, 0, 0, 0, 15, 0                                                       @ 105 | 
	voice_noise 60, 0, 0, 0, 0, 15, 0                                                             @ 106 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 107 | 
	voice_noise_alt 60, 0, 0, 0, 0, 15, 1                                                         @ 108 | 
	voice_noise 60, 0, 1, 0, 0, 12, 0                                                             @ 109 | 
	voice_noise_alt 60, 0, 0, 0, 0, 15, 0                                                         @ 110 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 111 | 
	voice_square_1 60, 0, 0, 0, 0, 0, 15, 0                                                       @ 112 | 
	voice_square_1 60, 0, 0, 1, 0, 0, 15, 0                                                       @ 113 | 
	voice_noise_alt 60, 0, 0, 0, 3, 5, 1                                                          @ 114 | 
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0                                                      @ 115 | 
	voice_noise_alt 60, 0, 0, 0, 0, 13, 0                                                         @ 116 | 
	voice_square_1 60, 0, 0, 1, 0, 0, 15, 0                                                       @ 117 | 
	voice_square_1 60, 0, 0, 0, 0, 1, 8, 0                                                        @ 118 | 
	voice_square_1 60, 0, 0, 0, 0, 1, 13, 0                                                       @ 119 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 120 | 
	voice_noise 60, 0, 0, 0, 2, 10, 1                                                             @ 121 | 
	voice_square_1 60, 0, 0, 0, 0, 0, 14, 0                                                       @ 122 | 
	voice_noise 60, 0, 0, 0, 2, 10, 1                                                             @ 123 | 
	voice_square_2_alt 60, 0, 2, 0, 1, 8, 0                                                       @ 124 | 
	voice_noise_alt 60, 0, 0, 0, 3, 9, 2                                                          @ 125 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 126 | 
	voice_noise_alt 60, 0, 0, 0, 3, 9, 2                                                          @ 127 | 
