	.align 2
voicegroup304::
    voice_directsound 60, 0, DirectSoundWaveData_ACOBS32A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ACOBS43A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ACOBS60A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ACOBS60A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HARP_83A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HARP_96A, 255, 0, 255, 127
