	.align 2
voicegroup200::
	voice_keysplit_all voicegroup192 //000 Drum
	voice_keysplit voicegroup195, KeySplitTable1 //001 Grand Accoustic
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 128, 204, 51, 242 //002
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 206, 242 //003
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 249, 0, 188 //004
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 188, 103, 165 //005
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0 //006
	voice_square_2_alt 60, 0, 3, 0, 3, 4, 0 //007
	voice_square_1_alt 60, 0, 0, 3, 0, 3, 4, 0 //008
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242 //009
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0 //010
	voice_directsound 60, 0, DirectSoundWaveData_heart_of_asia_gamelan, 255, 188, 139, 239 //011
	voice_directsound 60, 0, DirectSoundWaveData_unknown_bell, 255, 235, 0, 204 //012
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204 //013
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 216 //014
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //015
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //016
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127 //017
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //018
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188 //019
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188 //020
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165 //021
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //022
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //023
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 249, 25, 204 //024
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 165, 128, 204 //025
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //026
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //027
	voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 0, 255, 127 //028
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127 //029
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 165, 154, 165 //030
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 195 //031
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149 //032
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149 //033
	voice_directsound 60, 0, DirectSoundWaveData_unknown_snare, 255, 253, 0, 149 //034
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 198 //035
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 115 //036
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 180, 216 //037
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 146 //038
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_16, 0, 7, 15, 1 //039
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //040
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //041
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //042
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //043
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //044
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165 //045
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 51, 242 //046
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226 //047
	voice_keysplit voicegroup196, KeySplitTable2 //048 String Ensemble
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //049
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //050
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //051
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 128, 165, 128, 188 //052
	voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 128, 165, 128, 204 //053
	voice_directsound 60, 0, DirectSoundWaveData_unused_unknown_male_voice, 128, 165, 128, 188 //054
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //055
	voice_keysplit voicegroup197, KeySplitTable3 //056 Trumpet
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 165, 154, 127 //057
	voice_keysplit voicegroup198, KeySplitTable4 //058 Tuba
	voice_directsound 60, 0, DirectSoundWaveData_unknown_18, 255, 0, 206, 204 //059
	voice_keysplit voicegroup199, KeySplitTable5 //060 French Horn
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //061
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 165, 180, 165 //062
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //063
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //064
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //065
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //066
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //067
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165 //068
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 43, 165, 103, 165 //069
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //070
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //071
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //072
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127 //073
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0 //074
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165 //075
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //076
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204 //077
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 43, 76, 103, 216 //078
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //079
	voice_square_2_alt 60, 0, 2, 0, 2, 4, 1 //080
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 4, 1 //081
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0 //082
	voice_square_2_alt 60, 0, 3, 0, 3, 6, 2 //083
	voice_square_2_alt 60, 0, 0, 0, 2, 6, 5 //084
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 4, 1 //085
	voice_square_2_alt 60, 0, 3, 0, 1, 4, 1 //086
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_21, 0, 7, 15, 1 //087
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0 //088
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_15, 0, 1, 9, 2 //089
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127 //090
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0 //091
	voice_square_2_alt 60, 0, 2, 0, 2, 6, 3 //092
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //093
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //094
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //095
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 165 //096
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 226, 0, 165 //097
	voice_keysplit_all voicegroup128 //098
	voice_keysplit_all voicegroup129 //099
	voice_keysplit_all voicegroup130 //100
	voice_directsound 60, 0, DirectSoundWaveData_unknown_synth_snare, 255, 249, 103, 165 //101
	voice_directsound 60, 0, DirectSoundWaveData_unknown_1, 128, 249, 25, 204 //102
	voice_directsound 60, 0, DirectSoundWaveData_unknown_2, 128, 249, 25, 204 //103
	voice_directsound 60, 0, DirectSoundWaveData_unknown_3, 128, 249, 25, 204 //104
	voice_directsound 60, 0, DirectSoundWaveData_unknown_4, 128, 249, 25, 204 //105
	voice_directsound 60, 0, DirectSoundWaveData_unknown_5, 128, 249, 25, 204 //106
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242 //107
	voice_directsound 60, 0, DirectSoundWaveData_unknown_6, 128, 249, 25, 204 //108
	voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass, 128, 249, 25, 204 //109
	voice_directsound 60, 0, DirectSoundWaveData_unknown_7, 128, 249, 25, 204 //110
	voice_directsound 60, 0, DirectSoundWaveData_unknown_8, 128, 249, 25, 204 //111
	voice_directsound 60, 0, DirectSoundWaveData_unknown_9, 128, 249, 25, 204 //112
	voice_directsound 60, 0, DirectSoundWaveData_unknown_11, 128, 249, 25, 204 //113
	voice_directsound 60, 0, DirectSoundWaveData_unknown_12, 128, 249, 25, 204 //114
	voice_directsound 60, 0, DirectSoundWaveData_unknown_13, 128, 249, 25, 204 //115
	voice_directsound 60, 0, DirectSoundWaveData_unknown_14, 128, 249, 25, 204 //116
	voice_directsound 60, 0, DirectSoundWaveData_unknown_15, 128, 249, 25, 204 //117
	voice_directsound 60, 0, DirectSoundWaveData_unknown_16, 128, 249, 25, 204 //118
	voice_directsound 60, 0, DirectSoundWaveData_unknown_17, 128, 249, 25, 204 //119
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 165 //120
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 //121
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 216 //122
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216 //123
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127 //124
	voice_directsound 60, 0, DirectSoundWaveData_unknown_10, 255, 255, 255, 127 //125
	voice_noise_alt 60, 0, 0, 0, 2, 6, 2 //126
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0 //127

