	.align 2
voicegroup311::
    voice_directsound 60, 0, DirectSoundWaveData_SYBS233, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SYBS248A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SYBS272A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SYBS272A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_STLGT84B, 255, 0, 255, 127
