	.align 2
voicegroup901::
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree000, 255, 0, 255, 0 @ 0 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree001, 255, 0, 255, 0 @ 1 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree002, 255, 0, 255, 0 @ 2 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree003, 255, 0, 255, 0 @ 3 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree004, 255, 0, 255, 0 @ 4 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree005, 255, 0, 255, 0 @ 5 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree006, 255, 0, 255, 0 @ 6 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree007, 255, 0, 255, 0 @ 7 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree008, 255, 0, 255, 0 @ 8 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree009, 255, 0, 255, 0 @ 9 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree010, 255, 0, 255, 0 @ 10 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree011, 255, 0, 255, 0 @ 11 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree012, 255, 0, 255, 0 @ 12 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree013, 255, 0, 255, 0 @ 13 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree014, 255, 0, 255, 0 @ 14 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree015, 255, 0, 255, 0 @ 15 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree016, 255, 0, 255, 0 @ 16 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree017, 255, 0, 255, 0 @ 17 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree018, 255, 0, 255, 0 @ 18 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree019, 255, 0, 255, 0 @ 19 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree020, 255, 0, 255, 0 @ 20 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree021, 255, 0, 255, 0 @ 21 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree022, 255, 0, 255, 0 @ 22 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree023, 255, 0, 255, 0 @ 23 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree024, 255, 0, 255, 0 @ 24 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree025, 255, 0, 255, 0 @ 25 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree026, 255, 0, 255, 0 @ 26 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree027, 255, 0, 255, 0 @ 27 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree028, 255, 0, 255, 0 @ 28 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree029, 255, 0, 255, 0 @ 29 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree030, 255, 0, 255, 0 @ 30 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree031, 255, 0, 255, 0 @ 31 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree032, 255, 0, 255, 0 @ 32 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree033, 255, 0, 255, 0 @ 33 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree034, 255, 0, 255, 0 @ 34 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree035, 255, 0, 255, 0 @ 35 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree036, 255, 0, 255, 0 @ 36 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree037, 255, 0, 255, 0 @ 37 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree038, 255, 0, 255, 0 @ 38 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree039, 255, 0, 255, 0 @ 39 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree040, 255, 0, 255, 0 @ 40 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree041, 255, 0, 255, 0 @ 41 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree042, 255, 0, 255, 0 @ 42 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree043, 255, 0, 255, 0 @ 43 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree044, 255, 0, 255, 0 @ 44 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree045, 255, 0, 255, 0 @ 45 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree046, 255, 0, 255, 0 @ 46 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree047, 255, 0, 255, 0 @ 47 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree048, 255, 0, 255, 0 @ 48 | Direct |
	stream_directsound 60, 0, DirectSoundWaveData_SongSampleTHCtCGFree049, 255, 0, 255, 0 @ 49 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 050 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 051 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 052 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 053 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 054 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 055 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 056 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 057 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 058 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 059 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 060 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 061 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 062 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 063 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 064 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 065 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 066 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 067 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 068 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 069 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 070 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 071 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 072 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 073 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 074 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 075 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 076 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 077 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 078 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 079 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 080 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 081 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 082 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 083 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 084 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 085 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 086 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 087 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 088 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 089 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 094 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 096 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 097 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 098 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 099 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 100 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 101 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 102 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 103 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 106 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 107 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 110 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 111 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 112 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 113 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 115 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 116 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 119 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 120 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 121 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 122 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 123 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 124 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 125 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 126 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 127 | Square-1 | 
