	.align 2
voicegroup278::
    voice_directsound 60, 0, DirectSoundWaveData_HRPSI48A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HRPSI60A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HRPSI72A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HRPSI87A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_HRPSI87A, 255, 0, 255, 127
