	.align 2
voicegroup348::
    voice_directsound 60, 0, DirectSoundWaveData_SQUAR41, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SQUAR48, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SQUAR60, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SQUAR67, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SQUAR79, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_SQUAR96, 255, 0, 255, 127
