	.align 2
voicegroup803::
	voice_keysplit_all voicegroup804                                                      @ 000 | GBA Drum | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 001 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 002 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 003 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 249, 0, 188    @ 004 | RSE Electric Piano | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 005 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 006 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 007 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample001, 255, 0, 255, 165  @ 008 | GS2 Celesta | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 009 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 010 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 011 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 012 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204      @ 013 | RSE Xylophone | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 014 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 015 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 016 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127         @ 017 | RSE Organ 2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 018 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 019 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 020 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 021 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 022 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 023 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 249, 25, 204   @ 024 | RSE Nylon Guitar | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 025 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 026 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 027 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 028 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 128, 0, 255, 214     @ 029 | RSE Overdrive Guitar | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 030 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 031 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 224  @ 032 | RSE Fretless Bass | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 033 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 034 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 035 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 036 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 037 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115     @ 038 | RSE Synth Bass | Vs Mewtwo
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 039 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 040 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 041 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 042 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 043 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 044 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165    @ 045 | RSE Pizzicato | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 51, 242          @ 046 | RSE Harp | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 047 | --- | 
	voice_keysplit voicegroup196, KeySplitTable2                                          @ 048 | RSE Strings | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 049 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 050 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 051 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_4, 255, 188, 220, 243             @ 052 | RSE Voice Ahhs | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 053 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 054 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 055 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 056 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 057 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 058 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 059 | --- | 
	voice_keysplit voicegroup199, KeySplitTable5                                          @ 060 | RSE French Horn | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 061 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 062 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 063 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 064 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 065 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 066 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 067 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 068 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 069 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 070 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 071 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 072 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 073 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 074 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 075 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 076 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 077 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 078 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 079 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 080 | --- | 
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 12, 2                                           @ 081 | GB Square-1 | 
	voice_directsound 60, 0, DirectSoundSynth_Type_02, 255, 0, 255, 127                   @ 082 | GBA Synth | 
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 5, 2                                            @ 083 | GB Square-1 | 
	voice_square_2_alt 60, 0, 0, 0, 2, 5, 2                                               @ 086 | GB Square-2 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_4, 0, 7, 15, 0                @ 085 | GB Wave | 
	voice_square_2_alt 60, 0, 2, 0, 7, 7, 3                                               @ 086 | GB Square-2 | 
	voice_directsound 60, 0, DirectSoundSynth_Type_01, 127, 0, 127, 64                    @ 087 | GBA Synth | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_9, 0, 7, 15, 0                @ 088 | GB Wave | voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 7, 15, 0                @ 089 | GB Wave | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 094 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 096 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 097 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 098 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 099 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 100 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 101 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 102 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 103 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 106 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 107 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 110 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 111 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 112 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 113 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 115 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 116 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 119 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 120 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EEFFCC, 37, 0, 255, 0           @ 121 | PMD Water Current 2 |
	voice_directsound 60, 0, DirectSoundWaveData_bw_seashorec4, 37, 0, 80, 0              @ 122 | BW Seashore | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 123 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 124 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 125 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 126 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 127 | --- | 
