	.align 2
voicegroup602::
	voice_directsound 80, 0, DirectSoundWaveData_GoldenSun2InstrumentSample018, 255, 235, 103, 178 @ 0 | Direct |
	voice_directsound 80, 0, DirectSoundWaveData_GoldenSun2InstrumentSample019, 255, 235, 103, 165 @ 1 | Direct |
	voice_directsound 80, 0, DirectSoundWaveData_GoldenSun2InstrumentSample015, 255, 127, 90, 165 @ 2 | Direct |
	voice_directsound 80, 0, DirectSoundWaveData_GoldenSun2InstrumentSample015, 255, 127, 90, 165 @ 3 | Direct |
	voice_directsound 80, 0, DirectSoundWaveData_GoldenSun2InstrumentSample017, 255, 127, 90, 165 @ 4 | Direct |
	voice_directsound 80, 0, DirectSoundWaveData_GoldenSun2InstrumentSample018, 255, 127, 90, 165 @ 5 | Direct |
	voice_directsound 80, 0, DirectSoundWaveData_GoldenSun2InstrumentSample019, 255, 127, 103, 165 @ 6 | Direct |
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 7, 0 @ 7 | Square-1 |
	voice_square_2_alt 60, 0, 3, 0, 1, 7, 0 @ 8 | Square-2 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 9 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 10 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 11 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample021, 255, 235, 103, 178 @ 12 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample022, 255, 242, 103, 178 @ 13 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample023, 255, 0, 255, 165 @ 14 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample024, 255, 0, 255, 165 @ 15 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample025, 255, 0, 255, 165 @ 16 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample026, 255, 235, 103, 178 @ 17 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample027, 255, 0, 255, 165 @ 18 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample028, 255, 0, 255, 165 @ 19 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample029, 255, 0, 255, 165 @ 20 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample030, 255, 235, 103, 178 @ 21 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 22 | Square-1 | --
	voice_directsound 80, 0, DirectSoundWaveData_GoldenSun2InstrumentSample031, 255, 0, 255, 0 @ 23 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 24 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 25 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 26 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 27 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 28 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 29 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 30 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 31 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 32 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 33 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 34 | Square-1 | --
	voice_directsound 60, 64, DirectSoundWaveData_GoldenSun2InstrumentSample032, 255, 0, 255, 165 @ 35 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_GoldenSun2InstrumentSample033, 255, 0, 255, 216 @ 36 | Direct |
	voice_directsound 60, 69, DirectSoundWaveData_GoldenSun2InstrumentSample034, 255, 0, 255, 165 @ 37 | Direct |
	voice_directsound_no_resample 60, 69, DirectSoundWaveData_GoldenSun2InstrumentSample035, 255, 0, 255, 216 @ 38 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_GoldenSun2InstrumentSample036, 255, 0, 255, 216 @ 39 | Direct |
	voice_directsound_no_resample 60, 69, DirectSoundWaveData_GoldenSun2InstrumentSample037, 255, 0, 255, 216 @ 40 | Direct |
	voice_directsound 50, 24, DirectSoundWaveData_GoldenSun2InstrumentSample038, 128, 0, 255, 216 @ 41 | Direct |
	voice_directsound_no_resample 60, 74, DirectSoundWaveData_GoldenSun2InstrumentSample039, 255, 0, 255, 216 @ 42 | Direct |
	voice_directsound 55, 44, DirectSoundWaveData_GoldenSun2InstrumentSample038, 255, 0, 255, 216 @ 43 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_GoldenSun2InstrumentSample038, 255, 0, 255, 216 @ 44 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_GoldenSun2InstrumentSample038, 255, 0, 255, 216 @ 45 | Direct |
	voice_directsound_no_resample 60, 74, DirectSoundWaveData_GoldenSun2InstrumentSample040, 255, 0, 255, 165 @ 46 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_GoldenSun2InstrumentSample038, 255, 0, 255, 216 @ 47 | Direct |
	voice_directsound 65, 84, DirectSoundWaveData_GoldenSun2InstrumentSample038, 255, 0, 255, 216 @ 48 | Direct |
	voice_directsound_no_resample 60, 74, DirectSoundWaveData_GoldenSun2InstrumentSample041, 255, 252, 0, 165 @ 49 | Direct |
	voice_directsound 70, 104, DirectSoundWaveData_GoldenSun2InstrumentSample038, 255, 0, 255, 216 @ 50 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_GoldenSun2InstrumentSample042, 255, 249, 0, 165 @ 51 | Direct |
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 4 @ 52 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 2 @ 53 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 0 @ 54 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 7, 15, 7 @ 55 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 4 @ 56 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 2 @ 57 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 0 @ 58 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 7, 15, 7 @ 59 | Square-2 |
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 9, 4 @ 60 | Square-1 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 61 | Square-1 | --
	voice_square_1_alt 60, 0, 0, 3, 0, 4, 0, 4 @ 62 | Square-1 |
	voice_square_1_alt 60, 0, 0, 3, 0, 4, 0, 2 @ 63 | Square-1 |
	voice_square_1_alt 60, 0, 0, 3, 0, 4, 0, 0 @ 64 | Square-1 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 65 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 66 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 67 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 68 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 69 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 70 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 71 | Square-1 | --
	voice_noise_alt 60, 0, 0, 0, 4, 0, 4 @ 72 | Noise |
	voice_noise_alt 60, 0, 0, 0, 4, 0, 2 @ 73 | Noise |
	voice_noise_alt 60, 0, 0, 0, 4, 0, 0 @ 74 | Noise |
	voice_noise_alt 60, 0, 0, 0, 7, 15, 7 @ 75 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 76 | Square-1 | --
	voice_noise_alt 60, 0, 1, 0, 4, 0, 4 @ 77 | Noise |
	voice_noise_alt 60, 0, 1, 0, 4, 0, 2 @ 78 | Noise |
	voice_noise_alt 60, 0, 1, 0, 4, 0, 0 @ 79 | Noise |
	voice_noise_alt 60, 0, 1, 0, 7, 15, 7 @ 80 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 81 | Square-1 | --
	voice_noise_alt 60, 0, 1, 0, 4, 0, 4 @ 82 | Noise |
	voice_noise_alt 60, 0, 1, 0, 4, 0, 2 @ 83 | Noise |
	voice_noise_alt 60, 0, 1, 0, 4, 0, 0 @ 84 | Noise |
	voice_noise_alt 60, 0, 0, 0, 7, 15, 7 @ 85 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 86 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 87 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 88 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 89 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 90 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 91 | Square-1 | --
	voice_square_1_alt 60, 0, 0, 2, 1, 6, 0, 6 @ 92 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_GoldenSun2pcm002, 0, 4, 0, 2 @ 93 | Wave |
	voice_noise_alt 60, 0, 0, 2, 7, 10, 7 @ 94 | Noise |
	voice_noise_alt 60, 0, 0, 0, 7, 4, 3 @ 95 | Noise |
	voice_noise_alt 60, 0, 0, 5, 2, 6, 6 @ 96 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 97 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 98 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 99 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 100 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 101 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample043, 255, 0, 255, 0 @ 102 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample044, 255, 0, 255, 204 @ 103 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample045, 255, 0, 255, 216 @ 104 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample046, 255, 0, 255, 216 @ 105 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample047, 255, 0, 255, 216 @ 106 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample048, 255, 0, 255, 188 @ 107 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample049, 255, 0, 255, 204 @ 108 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample050, 255, 0, 255, 204 @ 109 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample051, 255, 0, 255, 204 @ 110 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample052, 255, 188, 154, 226 @ 111 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample017, 64, 232, 0, 232 @ 112 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample017, 64, 232, 0, 195 @ 113 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample017, 64, 232, 0, 0 @ 114 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample017, 64, 0, 255, 0 @ 115 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample016, 64, 0, 255, 0 @ 116 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample016, 64, 232, 0, 232 @ 117 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample016, 64, 232, 0, 195 @ 118 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample015, 64, 232, 0, 0 @ 119 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample016, 64, 0, 255, 0 @ 120 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample015, 64, 0, 255, 0 @ 121 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample016, 255, 0, 255, 204 @ 122 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample053, 255, 242, 28, 165 @ 123 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample054, 255, 0, 255, 226 @ 124 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 125 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 126 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 127 | Square-1 | --
