	.align 2
voicegroup502::
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_215504, 255, 0, 255, 0            @ 000 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_215504, 255, 0, 255, 0            @ 001 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_219b54, 255, 0, 255, 0            @ 002 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_219b54, 255, 0, 255, 0            @ 003 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_21e6b4, 255, 0, 255, 0            @ 004 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_21e6b4, 255, 0, 255, 0            @ 005 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_221568, 255, 0, 255, 0            @ 006 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_221568, 255, 0, 255, 0            @ 007 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_22647c, 255, 0, 255, 0            @ 008 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_22647c, 255, 0, 255, 0            @ 009 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_22b19c, 255, 0, 255, 0            @ 010 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_22b19c, 255, 0, 255, 0            @ 011 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_231334, 255, 0, 255, 0            @ 012 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_231334, 255, 0, 255, 0            @ 013 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_2367b4, 255, 0, 255, 0            @ 014 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_2367b4, 255, 0, 255, 0            @ 015 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_23b584, 255, 0, 255, 0            @ 016 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_23b584, 255, 0, 255, 0            @ 017 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_23fdd8, 255, 0, 255, 0            @ 018 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_23fdd8, 255, 0, 255, 0            @ 019 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_242ad8, 255, 0, 255, 0            @ 020 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_242ad8, 255, 0, 255, 0            @ 021 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_245688, 255, 0, 255, 0            @ 022 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_245688, 255, 0, 255, 0            @ 023 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_24ad9c, 255, 0, 255, 0            @ 024 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_24ad9c, 255, 0, 255, 0            @ 025 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_24e70c, 255, 0, 255, 0            @ 026 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_24e70c, 255, 0, 255, 0            @ 027 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_0a6350, 255, 0, 255, 0                                               @ 028 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_0a6350, 255, 0, 255, 0                                               @ 029 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_0a6350, 255, 0, 255, 0                                               @ 030 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 031 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 032 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_09e45c, 255, 0, 255, 0                                               @ 033 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_09e45c, 255, 0, 255, 0                                               @ 034 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_09e45c, 255, 0, 255, 0                                               @ 035 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 036 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 037 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 038 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 039 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 040 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 041 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_0a6350, 255, 0, 255, 0                                               @ 042 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 043 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 044 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 045 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 046 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 047 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 048 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_09e45c, 255, 0, 255, 0                                               @ 049 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 050 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_251bec, 255, 0, 255, 0                                               @ 051 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_09e45c, 255, 0, 255, 0                                               @ 052 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_09e45c, 255, 0, 255, 0                                               @ 053 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_09e45c, 255, 0, 255, 0                                               @ 054 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_09e45c, 255, 0, 255, 0                                               @ 055 | Direct |
	voice_directsound_no_resample 60, 60, DirectSoundWaveData_pc_fwpcmh_directsound_drumset_09e45c, 255, 0, 255, 0                                               @ 056 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 057 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 058 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 059 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 060 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 061 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 062 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 063 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 064 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 065 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 066 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 067 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 068 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 069 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 070 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 071 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 072 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 073 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 074 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 075 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 076 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 077 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 078 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 079 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 080 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 081 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 082 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 083 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 084 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 085 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 086 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 087 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 088 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 089 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 094 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 096 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 097 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 098 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 099 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 100 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 101 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 102 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 103 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 106 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 107 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 110 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 111 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 112 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 113 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 115 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 116 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 119 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 120 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 121 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 122 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 123 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 124 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 125 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 126 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 127 | Square-1 | 
