	.align 2
voicegroup300::
    voice_directsound 60, 0, DirectSoundWaveData_MUTGT43, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_MUTGT64, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_MUTGT81, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_NYLON88A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_NYLON97A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGTA1A, 255, 0, 255, 127
