	.align 2
voicegroup203::
    voice_keysplit voicegroup274, KeySplitTableGS6                                @ 000 | Direct | GS Piano 1
    voice_keysplit voicegroup274, KeySplitTableGS7                                @ 001 | Direct | GS Piano 2
    voice_keysplit voicegroup274, KeySplitTableGS8                                @ 002 | Direct | GS Piano 3
	voice_directsound 60, 0, DirectSoundWaveData_HONKY62B, 255, 0, 255, 127       @ 003 | Direct | GS Honky-Tonk
	voice_directsound 60, 0, DirectSoundWaveData_ELP1_56, 255, 0, 255, 127        @ 004 | Direct | GS Electric Piano 1
	voice_directsound 60, 0, DirectSoundWaveData_ELP2_60, 255, 0, 255, 127        @ 005 | Direct | GS Electric Piano 2
	voice_directsound 60, 0, DirectSoundWaveData_HRPSI60A, 255, 0, 255, 127       @ 006 | Direct | GS Harpsichord
	voice_directsound 60, 0, DirectSoundWaveData_CLAVI60, 255, 0, 255, 127        @ 007 | Direct | GS Clav
	voice_directsound 60, 0, DirectSoundWaveData_CELST77, 255, 0, 255, 127        @ 008 | Direct | GS Celesta
	voice_directsound 60, 0, DirectSoundWaveData_GLKN285, 255, 0, 255, 127        @ 009 | Direct | GS Glockenspiel
	voice_directsound 60, 0, DirectSoundWaveData_M_BOX82, 255, 0, 255, 127        @ 010 | Direct | GS Music Box
	voice_directsound 60, 0, DirectSoundWaveData_VIBE_64A, 255, 0, 255, 127       @ 011 | Direct | GS Vibraphone
	voice_directsound 60, 0, DirectSoundWaveData_MRMBA62, 255, 0, 255, 127        @ 012 | Direct | GS Marimba
	voice_directsound 60, 0, DirectSoundWaveData_XYLO_72, 255, 0, 255, 127        @ 013 | Direct | GS Xylophone
	voice_directsound 60, 0, DirectSoundWaveData_TUBLR84, 255, 0, 255, 127        @ 014 | Direct | GS Tubular Bell
	voice_directsound 60, 0, DirectSoundWaveData_SANTR74, 255, 0, 255, 127        @ 015 | Direct | GS Dulcimer
	voice_directsound 60, 0, DirectSoundWaveData_EORG173, 255, 0, 255, 127        @ 016 | Direct | GS Drawbar Organ
	voice_directsound 60, 0, DirectSoundWaveData_EORG253, 255, 0, 255, 127        @ 017 | Direct | GS Percussive Organ
	voice_directsound 60, 0, DirectSoundWaveData_EORG367, 255, 0, 255, 127        @ 018 | Direct | GS Rock Organ
	voice_directsound 60, 0, DirectSoundWaveData_C_ORG56A, 255, 0, 255, 127       @ 019 | Direct | GS Church Organ
	voice_directsound 60, 0, DirectSoundWaveData_R_ORG53, 255, 0, 255, 127        @ 020 | Direct | GS Reed Organ
	voice_directsound 60, 0, DirectSoundWaveData_ACCFR68A, 255, 0, 255, 127       @ 021 | Direct | GS Accordian
	voice_directsound 60, 0, DirectSoundWaveData_HARMO68, 255, 0, 255, 127        @ 022 | Direct | GS Harmonica
	voice_directsound 60, 0, DirectSoundWaveData_BANDO64, 255, 0, 255, 127        @ 023 | Direct | GS Tango Accodion
	voice_directsound 60, 0, DirectSoundWaveData_NYLON57A, 255, 0, 255, 127       @ 024 | Direct | GS Acoustic Guitar Nylon
	voice_directsound 60, 0, DirectSoundWaveData_STLGT57B, 255, 0, 255, 127       @ 025 | Direct | GS Acoustic Guitar Steel
	voice_directsound 60, 0, DirectSoundWaveData_JAZGT59A, 255, 0, 255, 127       @ 026 | Direct | GS Electric Guitar Jazz
	voice_directsound 60, 0, DirectSoundWaveData_CLNGT60, 255, 0, 255, 127        @ 027 | Direct | GS Electric Guitar Clean
	voice_directsound 60, 0, DirectSoundWaveData_MUTGT64, 255, 0, 255, 127        @ 028 | Direct | GS Electric Guitar Muted
	voice_directsound 60, 0, DirectSoundWaveData_OVDRV60, 255, 0, 255, 127        @ 029 | Direct | GS Overdriven Guitar
	voice_directsound 60, 0, DirectSoundWaveData_DSTGT59, 255, 0, 255, 127        @ 030 | Direct | GS Distortion Guitar
	voice_directsound 60, 0, DirectSoundWaveData_HRMGT52, 255, 0, 255, 127        @ 031 | Direct | GS Guitar Harmonics
	voice_directsound 60, 0, DirectSoundWaveData_ACOBS60A, 255, 0, 255, 127       @ 032 | Direct | GS Acoustic Bass
	voice_directsound 60, 0, DirectSoundWaveData_MMBAS62, 255, 0, 255, 127        @ 033 | Direct | GS Electric Bass Finger
	voice_directsound 60, 0, DirectSoundWaveData_PCKBS50A, 255, 0, 255, 127       @ 034 | Direct | GS Electric Bass Pick
	voice_directsound 60, 0, DirectSoundWaveData_FRTLS60A, 255, 0, 255, 127       @ 035 | Direct | GS Fretless Bass
	voice_directsound 60, 0, DirectSoundWaveData_SLPBS43, 255, 0, 255, 127        @ 036 | Direct | GS Slap Bass 1
	voice_directsound 60, 0, DirectSoundWaveData_SLPMT52A, 255, 0, 255, 127       @ 037 | Direct | GS Slap Bass 2
	voice_directsound 60, 0, DirectSoundWaveData_SYBS148A, 255, 0, 255, 127       @ 038 | Direct | GS Synth Bass 1
	voice_directsound 60, 0, DirectSoundWaveData_SYBS248A, 255, 0, 255, 127       @ 039 | Direct | GS Synth Bass 2
    voice_keysplit voicegroup312, KeySplitTableGS46                               @ 040 | Direct | GS Violin
    voice_keysplit voicegroup312, KeySplitTableGS47                               @ 041 | Direct | GS Viola
	voice_directsound 60, 0, DirectSoundWaveData_CELLL64, 255, 0, 255, 127        @ 042 | Direct | GS Cello
	voice_directsound 60, 0, DirectSoundWaveData_CONBL41, 255, 0, 255, 127        @ 043 | Direct | GS Contrabass
	voice_directsound 60, 0, DirectSoundWaveData_STRNG52B, 255, 0, 255, 127       @ 044 | Direct | GS Tremolo Strings
	voice_directsound 60, 0, DirectSoundWaveData_PIZZ_71, 255, 0, 255, 127        @ 045 | Direct | GS Pizzicato Strings
	voice_directsound 60, 0, DirectSoundWaveData_HARP_57A, 255, 0, 255, 127       @ 046 | Direct | GS Orchestral Strings
	voice_directsound 60, 0, DirectSoundWaveData_TMPNI47, 255, 0, 255, 127        @ 047 | Direct | GS Timpani
    voice_keysplit voicegroup319, KeySplitTableGS54                               @ 048 | Direct | GS String Ensemble 1
    voice_keysplit voicegroup319, KeySplitTableGS54                               @ 049 | Direct | GS String Ensemble 2
    voice_keysplit voicegroup320, KeySplitTableGS55                               @ 050 | Direct | GS Synth String 1
    voice_keysplit voicegroup320, KeySplitTableGS56                               @ 051 | Direct | GS Synth String 2
	voice_directsound 60, 0, DirectSoundWaveData_CHOIR65A, 255, 0, 255, 127       @ 052 | Direct | GS Choir Aahs
	voice_directsound 60, 0, DirectSoundWaveData_POPVX64A, 255, 0, 255, 127       @ 053 | Direct | GS Voice Oohs
	voice_directsound 60, 0, DirectSoundWaveData_SYNVX70, 255, 0, 255, 127        @ 054 | Direct | GS Synth Voice
    voice_directsound 60, 0, DirectSoundWaveData_O_HIT68, 255, 0, 255, 127        @ 055 | Direct | GS Orchestra Hit
    voice_keysplit voicegroup324, KeySplitTableGS60                               @ 056 | Direct | GS Trumpet
    voice_keysplit voicegroup325, KeySplitTableGS61                               @ 057 | Direct | GS Trombone
    voice_keysplit voicegroup326, KeySplitTableGS62                               @ 058 | Direct | GS Tuba
    voice_keysplit voicegroup327, KeySplitTableGS63                               @ 059 | Direct | GS Muted Trumpet
    voice_keysplit voicegroup328, KeySplitTableGS64                               @ 060 | Direct | GS French Horn
	voice_directsound 60, 0, DirectSoundWaveData_BRASS64, 255, 0, 255, 127        @ 061 | Direct | GS Brass Section
	voice_directsound 60, 0, DirectSoundWaveData_SBRS160A, 255, 0, 255, 127       @ 062 | Direct | GS Synth Brass 1
	voice_directsound 60, 0, DirectSoundWaveData_SBRS255, 255, 0, 255, 127        @ 063 | Direct | GS Synth Brass 2
	voice_directsound 60, 0, DirectSoundWaveData_S_SAX70, 255, 0, 255, 127        @ 064 | Direct | GS Soprano Sax
	voice_directsound 60, 0, DirectSoundWaveData_A_SAX59, 255, 0, 255, 127        @ 065 | Direct | GS Alto Sax
	voice_directsound 60, 0, DirectSoundWaveData_T_SAX57, 255, 0, 255, 127        @ 066 | Direct | GS Tenor Sax
	voice_directsound 60, 0, DirectSoundWaveData_B_SAX59, 255, 0, 255, 127        @ 067 | Direct | GS Baritone Sax
	voice_directsound 60, 0, DirectSoundWaveData_OBOE_61A, 255, 0, 255, 127       @ 068 | Direct | GS Oboe
    voice_keysplit voicegroup337, KeySplitTableGS73                               @ 069 | Direct | GS English Horn
	voice_directsound 60, 0, DirectSoundWaveData_BASSN69, 255, 0, 255, 127        @ 070 | Direct | GS Bassoon
	voice_directsound 60, 0, DirectSoundWaveData_SYNCL64, 255, 0, 255, 127        @ 071 | Direct | GS Clarinet
	voice_directsound 60, 0, DirectSoundWaveData_PICLO79, 255, 0, 255, 127        @ 072 | Direct | GS Piccolo
	voice_directsound 60, 0, DirectSoundWaveData_FLUTE65A, 255, 0, 255, 127       @ 073 | Direct | GS Flute
	voice_directsound 60, 0, DirectSoundWaveData_RECDR66A, 255, 0, 255, 127       @ 074 | Direct | GS Recorder
	voice_directsound 60, 0, DirectSoundWaveData_PNFLT72, 255, 0, 255, 127        @ 075 | Direct | GS Pan Flute
	voice_directsound 60, 0, DirectSoundWaveData_BOTTL72, 255, 0, 255, 127        @ 076 | Direct | GS Blown Bottle
	voice_directsound 60, 0, DirectSoundWaveData_SHAKU63, 255, 0, 255, 127        @ 077 | Direct | GS Skakuhachi
	voice_directsound 60, 0, DirectSoundWaveData_SINE_64, 255, 0, 255, 127        @ 078 | Direct | GS Whistle
	voice_directsound 60, 0, DirectSoundWaveData_OCARI72A, 255, 0, 255, 127       @ 079 | Direct | GS Oracina
	voice_directsound 60, 0, DirectSoundWaveData_SQUAR60, 255, 0, 255, 127        @ 080 | Direct | GS Lead 1 Square
	voice_directsound 60, 0, DirectSoundWaveData_SAW0_60, 255, 0, 255, 127        @ 081 | Direct | GS Lead 2 Sawtooth
	voice_directsound 60, 0, DirectSoundWaveData_CALLI72, 255, 0, 255, 127        @ 082 | Direct | GS Lead 3 Calliope
	voice_directsound 60, 0, DirectSoundWaveData_CHFFR72A, 255, 0, 255, 127       @ 083 | Direct | GS Lead 4 Chiff
	voice_directsound 60, 0, DirectSoundWaveData_CHRNG60, 255, 0, 255, 127        @ 084 | Direct | GS Lead 5 Charang
	voice_directsound 60, 0, DirectSoundWaveData_FMVOX66A, 255, 0, 255, 127       @ 085 | Direct | GS Lead 6 Voice
	voice_directsound 60, 0, DirectSoundWaveData_5_SAW81, 255, 0, 255, 127        @ 086 | Direct | GS Lead 7 Fifths
	voice_directsound 60, 0, DirectSoundWaveData_BS_LD72, 255, 0, 255, 127        @ 087 | Direct | GS Lead 8 Bass
	voice_directsound 60, 0, DirectSoundWaveData_FANTA53, 255, 0, 255, 127        @ 088 | Direct | GS Pad 1 New Age
	voice_directsound 60, 0, DirectSoundWaveData_WRMPD72A, 255, 0, 255, 127       @ 089 | Direct | GS Pad 2 Warm
	voice_directsound 60, 0, DirectSoundWaveData_POLY_60A, 255, 0, 255, 127       @ 090 | Direct | GS Pad 3 Polysynth
	voice_directsound 60, 0, DirectSoundWaveData_SPACE79, 255, 0, 255, 127        @ 091 | Direct | GS Pad 4 Choir
	voice_directsound 60, 0, DirectSoundWaveData_ELP1_56, 255, 0, 255, 127        @ 092 | Direct | GS Pad 5 Bowed
	voice_directsound 60, 0, DirectSoundWaveData_HONKY84A, 255, 0, 255, 127       @ 093 | Direct | GS Pad 6 Metallic XX
	voice_directsound 60, 0, DirectSoundWaveData_CHOIR65A, 255, 0, 255, 127       @ 094 | Direct | GS Pad 7 Halo XX
	voice_directsound 60, 0, DirectSoundWaveData_SSTR162A, 255, 0, 255, 127       @ 095 | Direct | GS Pad 8 Sweep
	voice_directsound 60, 0, DirectSoundWaveData_ICE__60A, 255, 0, 255, 127       @ 096 | Direct | GS FX 1 Rain
	voice_directsound 60, 0, DirectSoundWaveData_SOUND60, 255, 0, 255, 127        @ 097 | Direct | GS FX 2 Soundtrack
	voice_directsound 60, 0, DirectSoundWaveData_FNTBL53C, 255, 0, 255, 127       @ 098 | Direct | GS FX 3 Crystal
	voice_directsound 60, 0, DirectSoundWaveData_ATMOS60A, 255, 0, 255, 127       @ 099 | Direct | GS FX 4 Atmosphere
	voice_directsound 60, 0, DirectSoundWaveData_FMVOX66A, 255, 0, 255, 127       @ 100 | Direct | GS FX 5 Brightness
    voice_directsound 60, 0, DirectSoundWaveData_GOBLN84A, 255, 0, 255, 127       @ 101 | Direct | GS FX 6 Goblins
	voice_directsound 60, 0, DirectSoundWaveData_CHOIR65A, 255, 0, 255, 127       @ 102 | Direct | GS FX 7 Echoes XX
	voice_directsound 60, 0, DirectSoundWaveData_STAR_60A, 255, 0, 255, 127       @ 103 | Direct | GS FX 8 Sci-fi
	voice_directsound 60, 0, DirectSoundWaveData_SITAR60, 255, 0, 255, 127        @ 104 | Direct | GS Sitar
	voice_directsound 60, 0, DirectSoundWaveData_BANJO60, 255, 0, 255, 127        @ 105 | Direct | GS Banjo
	voice_directsound 60, 0, DirectSoundWaveData_SHAMI53, 255, 0, 255, 127        @ 106 | Direct | GS Shamisen
	voice_directsound 60, 0, DirectSoundWaveData_KOTO_57, 255, 0, 255, 127        @ 107 | Direct | GS Koto
	voice_directsound 60, 0, DirectSoundWaveData_KLMBA70, 255, 0, 255, 127        @ 108 | Direct | GS Kalimba
	voice_directsound 60, 0, DirectSoundWaveData_BAGPP64A, 255, 0, 255, 127       @ 109 | Direct | GS Bagpipe
	voice_directsound 60, 0, DirectSoundWaveData_VIOLN68, 255, 0, 255, 127        @ 110 | Direct | GS Fiddle XX
	voice_directsound 60, 0, DirectSoundWaveData_BAGPP64A, 255, 0, 255, 127       @ 111 | Direct | GS Shanai XX
	voice_directsound 60, 0, DirectSoundWaveData_TNKBLA5, 255, 0, 255, 127        @ 112 | Direct | GS Tinkle Bell
    voice_directsound 60, 0, DirectSoundWaveData_AGOGO60, 255, 0, 255, 127        @ 113 | Direct | GS Agogo
	voice_directsound 60, 0, DirectSoundWaveData_STLDR72, 255, 0, 255, 127        @ 114 | Direct | GS Steel Drums Part
    voice_directsound 60, 0, DirectSoundWaveData_WODBK60, 255, 0, 255, 127        @ 115 | Direct | GS Woodblock
    voice_directsound 60, 0, DirectSoundWaveData_SURDO60, 255, 0, 255, 127        @ 116 | Direct | GS Taiko Drum Part
    voice_directsound 60, 0, DirectSoundWaveData_TOM__60, 255, 0, 255, 127        @ 117 | Direct | GS Melodic Tom Part
    voice_directsound 60, 0, DirectSoundWaveData_SYNDR56, 255, 0, 255, 127        @ 118 | Direct | GS Synth Drum Part
    voice_directsound 60, 0, DirectSoundWaveData_CRASH60B, 255, 0, 255, 127       @ 119 | Direct | GS Reverse Cymbal
    voice_directsound 60, 0, DirectSoundWaveData_GFRET69, 255, 0, 255, 127        @ 120 | Direct | GS Guitar Fret Noise
	voice_directsound 60, 0, DirectSoundWaveData_PANNS84, 255, 0, 255, 127        @ 121 | Direct | GS Breath Noise
    voice_directsound 60, 0, DirectSoundWaveData_SEA__60, 255, 0, 255, 127        @ 122 | Direct | GS Seashore
    voice_directsound 60, 0, DirectSoundWaveData_BIRD_60, 255, 0, 255, 127        @ 123 | Direct | GS Bird Tweet
    voice_directsound 60, 0, DirectSoundWaveData_TELE_60, 255, 0, 255, 127        @ 124 | Direct | GS Telephone Ring 1
    voice_directsound 60, 0, DirectSoundWaveData_TELE260, 255, 0, 255, 127        @ 125 | Direct | GS Telephone Ring 2
    voice_directsound 60, 0, DirectSoundWaveData_APPLS64A, 255, 0, 255, 127       @ 126 | Direct | GS Applause
    voice_directsound 60, 0, DirectSoundWaveData_PISTL60, 255, 0, 255, 127        @ 127 | Direct | GS Gunshot
