	.align 2
voicegroup501::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 000 |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_083204, 255, 0, 255, 0            @ 001 | Direct | Piano
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_085a14, 255, 0, 255, 0            @ 002 | Direct | Tubular Bell
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_0888a8, 255, 0, 255, 0            @ 003 | Direct | Overdriven Guitar ?
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_089d10, 255, 0, 255, 0            @ 004 | Direct | Fingered Bass ?
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_08d118, 255, 0, 255, 0            @ 005 | Direct | Slap Bass ?
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_08ff6c, 255, 0, 255, 0            @ 006 | Direct | String ?
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_09263c, 255, 0, 255, 0            @ 007 | Direct | Orchestral Hit
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_094448, 255, 0, 255, 0            @ 008 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_096888, 255, 0, 255, 0            @ 009 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_09a15c, 255, 0, 255, 0            @ 010 | Direct | Music Box
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_09c1b0, 255, 0, 255, 0            @ 011 | Direct | Sawtooth ?
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_09e45c, 255, 0, 255, 0            @ 012 | Direct | Drum part
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_0a01e0, 255, 0, 255, 0            @ 013 | Direct | Electric Piano 1 ?
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_0a1730, 255, 0, 255, 0            @ 014 | Direct | Electric Piano 2 ?
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_0a3118, 255, 0, 255, 0            @ 015 | Direct | Drum part
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_0a4a98, 255, 0, 255, 0            @ 016 | Direct | Organ ?
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_0a6350, 255, 0, 255, 0            @ 017 | Direct | Drum part
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 018 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 019 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 020 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 021 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 022 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 023 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 024 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 025 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 026 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 027 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 028 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 029 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 030 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 031 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 032 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 033 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 034 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 035 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 036 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 037 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 038 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 039 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 040 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 041 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 042 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 043 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 044 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 045 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 046 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 047 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 048 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 049 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 050 |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_vocal_dualaurawave, 255, 0, 255, 0    @ 051 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_vocal_cureblack, 255, 0, 255, 0       @ 052 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_vocal_curewhite, 255, 0, 255, 0       @ 053 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_vocal_shiningstream, 255, 0, 255, 0   @ 054 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_vocal_kagayakuinochi, 255, 0, 255, 0  @ 055 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_vocal_extreme, 255, 0, 255, 0         @ 056 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_directsound_vocal_luminario, 255, 0, 255, 0       @ 057 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 058 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 059 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 060 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 061 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 062 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 063 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 064 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 065 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 066 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 067 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 068 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 069 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 070 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 071 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 072 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 073 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 074 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 075 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 076 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 077 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 078 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 079 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 7, 2                                                           @ 080 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 9, 1                                                           @ 081 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 9, 2                                                           @ 082 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 3, 7, 2                                                           @ 083 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 3, 7, 3                                                           @ 084 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 3, 9, 2                                                           @ 085 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 12, 2                                                          @ 086 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 10, 1                                                          @ 087 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 7, 3                                                           @ 088 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 9, 1                                                           @ 089 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 9, 2                                                           @ 090 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 9, 3                                                           @ 091 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 3, 7, 3                                                           @ 092 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 2, 7, 2                                                              @ 093 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 2, 9, 1                                                              @ 094 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 2, 9, 2                                                              @ 095 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 3, 7, 2                                                              @ 096 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 3, 7, 3                                                              @ 097 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 3, 9, 2                                                              @ 098 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 1, 12, 2                                                             @ 099 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 2, 7, 3                                                              @ 100 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 2, 9, 1                                                              @ 101 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 2, 9, 2                                                              @ 102 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 2, 9, 3                                                              @ 103 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 3, 7, 3                                                              @ 104 | Square-2 |
	voice_square_2_alt 60, 0, 2, 1, 2, 10, 1                                                             @ 105 | Square-2 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pc_fwpcmh_wave_0827e8, 1, 2, 10, 1           @ 106 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pc_fwpcmh_wave_082858, 0, 1, 12, 2           @ 107 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pc_fwpcmh_wave_082858, 0, 3, 7, 3            @ 108 | Wave |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 109 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 110 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 111 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 112 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 113 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 114 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 115 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 116 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 117 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 118 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 119 |
	voice_keysplit_all voicegroup502                                                                     @ 120 | Drum |
	voice_keysplit_all voicegroup503                                                                     @ 121 | Drum |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 122 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 123 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 124 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 125 |
	voice_noise_alt 60, 0, 0, 0, 2, 6, 2                                                                 @ 126 | Noise |
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0                                                                 @ 127 | Noise |
