	.align 2
voicegroup291::
    voice_directsound 60, 0, DirectSoundWaveData_C_ORG46A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_C_ORG56A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_C_ORG66A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_C_ORG78A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_C_ORG90A, 255, 0, 255, 127
