	.align 2
voicegroup379::
    voice_directsound 60, 0, DirectSoundWaveData_TNKBLA5, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TNKBLA5, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TNKBLA5, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TNKBLA5, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TNKBLA5, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TNKBLA5, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TNKBLA5, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_TNKBLA5, 255, 0, 255, 127
