	.align 2
voicegroup298::
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT50A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT59A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT68A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT74A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT84A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGT93A, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_JAZGTA1A, 255, 0, 255, 127
