	.align 2
voicegroup276::
    voice_directsound 60, 0, DirectSoundWaveData_ELP1_49, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP1_56, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP1_67, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP1_80, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_ELP1_97, 255, 0, 255, 127
