#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H


//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/heal_locations.json and Inja template src/data/heal_locations.constants.json.txt
//


enum {
    HEAL_LOCATION_NONE,
    HEAL_LOCATION_JOHTO_TWINRIVER_CITY_MC_HOUSE_2F_MALE,
    HEAL_LOCATION_JOHTO_TWINRIVER_CITY_MC_HOUSE_2F_FEMALE,
    HEAL_LOCATION_JOHTO_OLIVINE_CITY,
    HEAL_LOCATION_JOHTO_ECRUTEAK_CITY,
    HEAL_LOCATION_JOHTO_MAHOGANY_TOWN,
    HEAL_LOCATION_JOHTO_LAKE_OF_RAGE,
    HEAL_LOCATION_JOHTO_BLACKTHORN_CITY,
    HEAL_LOCATION_JOHTO_MT_SILVER,
    HEAL_LOCATION_JOHTO_INDIGO_PLATEAU,
    HEAL_LOCATION_JOHTO_MORIYA_SHRINE,
    HEAL_LOCATION_JOHTO_SPACE_HYPER_VESSEL_FRONT,
    HEAL_LOCATION_JOHTO_TWINRIVER_CITY_MC_HOUSE_MALE,
    HEAL_LOCATION_JOHTO_TWINRIVER_CITY_MC_HOUSE_FEMALE,
    HEAL_LOCATION_JOHTO_NEW_BARK_TOWN,
    HEAL_LOCATION_JOHTO_CHERRYGROVE_CITY,
    HEAL_LOCATION_JOHTO_VIOLET_CITY,
    HEAL_LOCATION_JOHTO_AZALEA_TOWN,
    HEAL_LOCATION_JOHTO_CIANWOOD_CITY,
    HEAL_LOCATION_JOHTO_GOLDENROD_CITY,
    HEAL_LOCATION_JOHTO_SPACE_HYPER_VESSEL_EMBEDDED_TOWER,
    HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR,
    HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST,
    HEAL_LOCATION_GENSOKYO_HAKUREI_SHRINE,
    HEAL_LOCATION_GENSOKYO_HUMAN_VILLAGE,
    HEAL_LOCATION_GENSOKYO_KOURINDOU,
    HEAL_LOCATION_GENSOKYO_MUENZUKA,
    HEAL_LOCATION_GENSOKYO_HAKUGYOKUROU,
    HEAL_LOCATION_GENSOKYO_MORIYA_SHRINE,
    HEAL_LOCATION_GENSOKYO_SCARLET_DEVIL_MANSION,
    HEAL_LOCATION_GENSOKYO_CHIREIDEN,
    HEAL_LOCATION_GENSOKYO_PALENQUIN_SHIP,
    HEAL_LOCATION_GENSOKYO_SANZU_RIVER,
    HEAL_LOCATION_GENSOKYO_GARDEN_OF_THE_SUN,
    HEAL_LOCATION_JAVA_KEMBANG_TOWN,
    HEAL_LOCATION_GENSOKYO_EIENTEI,
    HEAL_LOCATION_GENSOKYO_ANIMAL_REALM,
    HEAL_LOCATION_JAVA_NEO_BANJAR_CITY,
    HEAL_LOCATION_GENSOKYO_FANTASY_WORLD,
    HEAL_LOCATION_GENSOKYO_DREAM_WORLD,
    HEAL_LOCATION_GENSOKYO_MAKAI,
    HEAL_LOCATION_GENSOKYO_LUNAR_CAPITAL,
    HEAL_LOCATION_GENSOKYO_FANTASY_LEAGUE,
    HEAL_LOCATION_YYYI_SEA_OF_TREES1,
    HEAL_LOCATION_YYYI_SEA_OF_FLAME1,
    HEAL_LOCATION_KEY_ILLUSIONARY_WORLD1,
    HEAL_LOCATION_JAVA_YOGYAKARTA,
    HEAL_LOCATION_JAVA_SOLO,
    HEAL_LOCATION_JAVA_SEMARANG,
    HEAL_LOCATION_JAVA_SURABAYA,
    HEAL_LOCATION_JAVA_JAKARTA,
    HEAL_LOCATION_JOHTO_ROUTE_48_POKEMON_CENTER,
    HEAL_LOCATION_JOHTO_NOBELESSE_CITY,
    HEAL_LOCATION_JAVA_MALANG,
    HEAL_LOCATION_JAVA_DEVATA_ISLETS,
    HEAL_LOCATION_JAVA_KASEPUHAN_TOWN,
    HEAL_LOCATION_JAVA_CILA_PRISON_TOWN,
    NUM_HEAL_LOCATIONS
};

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
