#ifndef GUARD_TRAINERS_H
#define GUARD_TRAINERS_H

#include "constants/opponents.h"
#include "constants/battle_frontier_trainers.h"

// Special Trainer Ids.
//      0-299 are frontier trainers
#define TRAINER_RECORD_MIXING_FRIEND        FRONTIER_TRAINERS_COUNT
#define TRAINER_RECORD_MIXING_APPRENTICE    400
#define TRAINER_EREADER                     500
#define TRAINER_FRONTIER_BRAIN              1022
#define TRAINER_PLAYER                      1023
#define TRAINER_SECRET_BASE                 1024
#define TRAINER_LINK_OPPONENT               2048
#define TRAINER_UNION_ROOM                  3072

#define TRAINER_PIC_HIKER                  0
#define TRAINER_PIC_AQUA_GRUNT_M           1
#define TRAINER_PIC_POKEMON_BREEDER_F      2
#define TRAINER_PIC_COOLTRAINER_M          3
#define TRAINER_PIC_BIRD_KEEPER            4
#define TRAINER_PIC_COLLECTOR              5
#define TRAINER_PIC_AQUA_GRUNT_F           6
#define TRAINER_PIC_SWIMMER_M              7
#define TRAINER_PIC_MAGMA_GRUNT_M          8
#define TRAINER_PIC_EXPERT_M               9
#define TRAINER_PIC_AQUA_ADMIN_M          10
#define TRAINER_PIC_BLACK_BELT            11
#define TRAINER_PIC_AQUA_ADMIN_F          12
#define TRAINER_PIC_AQUA_LEADER_ARCHIE    13
#define TRAINER_PIC_HEX_MANIAC            14
#define TRAINER_PIC_AROMA_LADY            15
#define TRAINER_PIC_RUIN_MANIAC           16
#define TRAINER_PIC_INTERVIEWER           17
#define TRAINER_PIC_TUBER_F               18
#define TRAINER_PIC_TUBER_M               19
#define TRAINER_PIC_COOLTRAINER_F         20
#define TRAINER_PIC_LADY                  21
#define TRAINER_PIC_BEAUTY                22
#define TRAINER_PIC_RICH_BOY              23
#define TRAINER_PIC_EXPERT_F              24
#define TRAINER_PIC_POKEMANIAC            25
#define TRAINER_PIC_MAGMA_GRUNT_F         26
#define TRAINER_PIC_GUITARIST             27
#define TRAINER_PIC_KINDLER               28
#define TRAINER_PIC_CAMPER                29
#define TRAINER_PIC_PICNICKER             30
#define TRAINER_PIC_BUG_MANIAC            31
#define TRAINER_PIC_POKEMON_BREEDER_M     32
#define TRAINER_PIC_PSYCHIC_M             33
#define TRAINER_PIC_PSYCHIC_F             34
#define TRAINER_PIC_GENTLEMAN             35
#define TRAINER_PIC_ELITE_FOUR_SIDNEY     36
#define TRAINER_PIC_ELITE_FOUR_PHOEBE     37
#define TRAINER_PIC_ELITE_FOUR_GLACIA     38
#define TRAINER_PIC_ELITE_FOUR_DRAKE      39
#define TRAINER_PIC_LEADER_ROXANNE        40
#define TRAINER_PIC_LEADER_BRAWLY         41
#define TRAINER_PIC_LEADER_WATTSON        42
#define TRAINER_PIC_LEADER_FLANNERY       43
#define TRAINER_PIC_LEADER_NORMAN         44
#define TRAINER_PIC_LEADER_WINONA         45
#define TRAINER_PIC_LEADER_TATE_AND_LIZA  46
#define TRAINER_PIC_LEADER_JUAN           47
#define TRAINER_PIC_SCHOOL_KID_M          48
#define TRAINER_PIC_SCHOOL_KID_F          49
#define TRAINER_PIC_SR_AND_JR             50
#define TRAINER_PIC_POKEFAN_M             51
#define TRAINER_PIC_POKEFAN_F             52
#define TRAINER_PIC_YOUNGSTER             53
#define TRAINER_PIC_CHAMPION_WALLACE      54
#define TRAINER_PIC_FISHERMAN             55
#define TRAINER_PIC_CYCLING_TRIATHLETE_M  56
#define TRAINER_PIC_CYCLING_TRIATHLETE_F  57
#define TRAINER_PIC_RUNNING_TRIATHLETE_M  58
#define TRAINER_PIC_RUNNING_TRIATHLETE_F  59
#define TRAINER_PIC_SWIMMING_TRIATHLETE_M 60
#define TRAINER_PIC_SWIMMING_TRIATHLETE_F 61
#define TRAINER_PIC_DRAGON_TAMER          62
#define TRAINER_PIC_NINJA_BOY             63
#define TRAINER_PIC_BATTLE_GIRL           64
#define TRAINER_PIC_PARASOL_LADY          65
#define TRAINER_PIC_SWIMMER_F             66
#define TRAINER_PIC_TWINS                 67
#define TRAINER_PIC_SAILOR                68
#define TRAINER_PIC_MAGMA_ADMIN           69
#define TRAINER_PIC_WALLY                 70
#define TRAINER_PIC_BRENDAN               71
#define TRAINER_PIC_MAY                   72
#define TRAINER_PIC_BUG_CATCHER           73
#define TRAINER_PIC_POKEMON_RANGER_M      74
#define TRAINER_PIC_POKEMON_RANGER_F      75
#define TRAINER_PIC_MAGMA_LEADER_MAXIE    76
#define TRAINER_PIC_LASS                  77
#define TRAINER_PIC_YOUNG_COUPLE          78
#define TRAINER_PIC_OLD_COUPLE            79
#define TRAINER_PIC_SIS_AND_BRO           80
#define TRAINER_PIC_STEVEN                81
#define TRAINER_PIC_SALON_MAIDEN_ANABEL   82
#define TRAINER_PIC_DOME_ACE_TUCKER       83
#define TRAINER_PIC_PALACE_MAVEN_SPENSER  84
#define TRAINER_PIC_ARENA_TYCOON_GRETA    85
#define TRAINER_PIC_FACTORY_HEAD_NOLAND   86
#define TRAINER_PIC_PIKE_QUEEN_LUCY       87
#define TRAINER_PIC_PYRAMID_KING_BRANDON  88
#define TRAINER_PIC_RED                   89
#define TRAINER_PIC_LEAF                  90
#define TRAINER_PIC_RS_BRENDAN            91
#define TRAINER_PIC_RS_MAY                92
#define TRAINER_PIC_93                    93
#define TRAINER_PIC_94                    94
#define TRAINER_PIC_95                    95
#define TRAINER_PIC_96                    96
#define TRAINER_PIC_97                    97
#define TRAINER_PIC_98                    98
#define TRAINER_PIC_99                    99
#define TRAINER_PIC_100                   100
#define TRAINER_PIC_101                   101
#define TRAINER_PIC_102                   102
#define TRAINER_PIC_103                   103
#define TRAINER_PIC_104                   104
#define TRAINER_PIC_105                   105
#define TRAINER_PIC_106                   106
#define TRAINER_PIC_107                   107
#define TRAINER_PIC_108                   108
#define TRAINER_PIC_109                   109
#define TRAINER_PIC_110                   110
#define TRAINER_PIC_111                   111
#define TRAINER_PIC_112                   112
#define TRAINER_PIC_113                   113
#define TRAINER_PIC_114                   114
#define TRAINER_PIC_115                   115
#define TRAINER_PIC_116                   116
#define TRAINER_PIC_117                   117
#define TRAINER_PIC_118                   118
#define TRAINER_PIC_119                   119
#define TRAINER_PIC_120                   120
#define TRAINER_PIC_121                   121
#define TRAINER_PIC_122                   122
#define TRAINER_PIC_123                   123
#define TRAINER_PIC_124                   124
#define TRAINER_PIC_125                   125
#define TRAINER_PIC_126                   126
#define TRAINER_PIC_127                   127
#define TRAINER_PIC_128                   128
#define TRAINER_PIC_129                   129
#define TRAINER_PIC_130                   130
#define TRAINER_PIC_131                   131
#define TRAINER_PIC_132                   132
#define TRAINER_PIC_133                   133
#define TRAINER_PIC_134                   134
#define TRAINER_PIC_135                   135
#define TRAINER_PIC_136                   136
#define TRAINER_PIC_137                   137
#define TRAINER_PIC_138                   138
#define TRAINER_PIC_139                   139
#define TRAINER_PIC_140                   140
#define TRAINER_PIC_141                   141
#define TRAINER_PIC_142                   142
#define TRAINER_PIC_143                   143
#define TRAINER_PIC_144                   144
#define TRAINER_PIC_145                   145
#define TRAINER_PIC_146                   146
#define TRAINER_PIC_147                   147
#define TRAINER_PIC_148                   148
#define TRAINER_PIC_149                   149
#define TRAINER_PIC_150                   150
#define TRAINER_PIC_151                   151
#define TRAINER_PIC_152                   152
#define TRAINER_PIC_153                   153
#define TRAINER_PIC_154                   154
#define TRAINER_PIC_155                   155
#define TRAINER_PIC_156                   156
#define TRAINER_PIC_157                   157
#define TRAINER_PIC_158                   158
#define TRAINER_PIC_159                   159
#define TRAINER_PIC_160                   160
#define TRAINER_PIC_161                   161
#define TRAINER_PIC_162                   162
#define TRAINER_PIC_163                   163
#define TRAINER_PIC_164                   164
#define TRAINER_PIC_165                   165
#define TRAINER_PIC_166                   166
#define TRAINER_PIC_167                   167
#define TRAINER_PIC_168                   168
#define TRAINER_PIC_169                   169
#define TRAINER_PIC_170                   170
#define TRAINER_PIC_171                   171
#define TRAINER_PIC_172                   172
#define TRAINER_PIC_173                   173
#define TRAINER_PIC_174                   174
#define TRAINER_PIC_175                   175
#define TRAINER_PIC_176                   176
#define TRAINER_PIC_177                   177
#define TRAINER_PIC_178                   178
#define TRAINER_PIC_179                   179
#define TRAINER_PIC_180                   180
#define TRAINER_PIC_181                   181
#define TRAINER_PIC_182                   182
#define TRAINER_PIC_183                   183
#define TRAINER_PIC_184                   184
#define TRAINER_PIC_185                   185
#define TRAINER_PIC_186                   186
#define TRAINER_PIC_187                   187
#define TRAINER_PIC_188                   188
#define TRAINER_PIC_189                   189
#define TRAINER_PIC_190                   190
#define TRAINER_PIC_191                   191
#define TRAINER_PIC_192                   192
#define TRAINER_PIC_193                   193
#define TRAINER_PIC_194                   194
#define TRAINER_PIC_195                   195
#define TRAINER_PIC_196                   196
#define TRAINER_PIC_197                   197
#define TRAINER_PIC_198                   198
#define TRAINER_PIC_199                   199
#define TRAINER_PIC_200                   200
#define TRAINER_PIC_201                   201
#define TRAINER_PIC_202                   202
#define TRAINER_PIC_203                   203
#define TRAINER_PIC_204                   204
#define TRAINER_PIC_205                   205
#define TRAINER_PIC_206                   206
#define TRAINER_PIC_207                   207
#define TRAINER_PIC_208                   208
#define TRAINER_PIC_209                   209
#define TRAINER_PIC_210                   210
#define TRAINER_PIC_211                   211
#define TRAINER_PIC_212                   212
#define TRAINER_PIC_213                   213
#define TRAINER_PIC_214                   214
#define TRAINER_PIC_215                   215
#define TRAINER_PIC_216                   216
#define TRAINER_PIC_217                   217
#define TRAINER_PIC_218                   218
#define TRAINER_PIC_219                   219
#define TRAINER_PIC_220                   220
#define TRAINER_PIC_221                   221
#define TRAINER_PIC_222                   222
#define TRAINER_PIC_223                   223
#define TRAINER_PIC_224                   224
#define TRAINER_PIC_225                   225
#define TRAINER_PIC_226                   226
#define TRAINER_PIC_227                   227
#define TRAINER_PIC_228                   228
#define TRAINER_PIC_229                   229
#define TRAINER_PIC_230                   230
#define TRAINER_PIC_231                   231
#define TRAINER_PIC_232                   232
#define TRAINER_PIC_233                   233
#define TRAINER_PIC_234                   234
#define TRAINER_PIC_235                   235
#define TRAINER_PIC_236                   236
#define TRAINER_PIC_237                   237
#define TRAINER_PIC_238                   238
#define TRAINER_PIC_239                   239
#define TRAINER_PIC_240                   240
#define TRAINER_PIC_241                   241
#define TRAINER_PIC_242                   242
#define TRAINER_PIC_243                   243
#define TRAINER_PIC_244                   244
#define TRAINER_PIC_245                   245
#define TRAINER_PIC_246                   246
#define TRAINER_PIC_247                   247
#define TRAINER_PIC_248                   248
#define TRAINER_PIC_249                   249
#define TRAINER_PIC_250                   250
#define TRAINER_PIC_251                   251
#define TRAINER_PIC_252                   252
#define TRAINER_PIC_253                   253
#define TRAINER_PIC_254                   254
#define TRAINER_PIC_COUNT                 255

// Alias
#define TRAINER_PIC_LEADER_FALKNER        TRAINER_PIC_LEADER_ROXANNE
#define TRAINER_PIC_LEADER_BUGSY          TRAINER_PIC_LEADER_BRAWLY
#define TRAINER_PIC_LEADER_WHITNEY        TRAINER_PIC_LEADER_WATTSON
#define TRAINER_PIC_LEADER_MORTY          TRAINER_PIC_LEADER_FLANNERY
#define TRAINER_PIC_LEADER_CHUCK          TRAINER_PIC_LEADER_NORMAN
#define TRAINER_PIC_LEADER_JASMINE        TRAINER_PIC_LEADER_WINONA
#define TRAINER_PIC_LEADER_PRYCE          TRAINER_PIC_LEADER_TATE_AND_LIZA
#define TRAINER_PIC_LEADER_CLAIR          TRAINER_PIC_LEADER_JUAN
#define TRAINER_PIC_ELITE_FOUR_WILL       TRAINER_PIC_ELITE_FOUR_SIDNEY
#define TRAINER_PIC_ELITE_FOUR_KOGA       TRAINER_PIC_ELITE_FOUR_PHOEBE
#define TRAINER_PIC_ELITE_FOUR_BRUNO      TRAINER_PIC_ELITE_FOUR_GLACIA
#define TRAINER_PIC_ELITE_FOUR_KAREN      TRAINER_PIC_ELITE_FOUR_DRAKE
#define TRAINER_PIC_CHAMPION_LANCE        TRAINER_PIC_CHAMPION_WALLACE
#define TRAINER_PIC_TH_YUYUKO             TRAINER_PIC_93
#define TRAINER_PIC_TH_YUKARI             TRAINER_PIC_94
#define TRAINER_PIC_C_KRIS                TRAINER_PIC_95
#define TRAINER_PIC_GS_GOLD               TRAINER_PIC_96
#define TRAINER_PIC_C_GOLD                TRAINER_PIC_97
#define TRAINER_PIC_GUEST_STELLAR         TRAINER_PIC_98
#define TRAINER_PIC_GUEST_REIMUFATE       TRAINER_PIC_98
#define TRAINER_PIC_ETC_DECADE            TRAINER_PIC_100
#define TRAINER_PIC_ETC_DIEND             TRAINER_PIC_101
#define TRAINER_PIC_TH_RENKO_BIG          TRAINER_PIC_102
#define TRAINER_PIC_TH_MARIBEL_BIG        TRAINER_PIC_103
#define TRAINER_PIC_TH_RENKO_SMALL        TRAINER_PIC_104
#define TRAINER_PIC_TH_MARIBEL_SMALL      TRAINER_PIC_105
#define TRAINER_PIC_TH_RENKO_CLASSIC      TRAINER_PIC_106
#define TRAINER_PIC_TH_MARIBEL_CLASSIC    TRAINER_PIC_107
#define TRAINER_PIC_TH_REIMU              TRAINER_PIC_108
#define TRAINER_PIC_TH_MARISA             TRAINER_PIC_109
#define TRAINER_PIC_SH_VIVIT_ANDROID      TRAINER_PIC_110
#define TRAINER_PIC_SH_VIVIT_LADY         TRAINER_PIC_111
#define TRAINER_PIC_ETC_ILLYASVIEL        TRAINER_PIC_112
#define TRAINER_PIC_ETC_CHLOE             TRAINER_PIC_113
#define TRAINER_PIC_ETC_HATSUNE_MIKU      TRAINER_PIC_114
#define TRAINER_PIC_TH_REIMU_CTC          TRAINER_PIC_115
#define TRAINER_PIC_TH_SAKUYA             TRAINER_PIC_116
#define TRAINER_PIC_TH_YOUMU              TRAINER_PIC_117
#define TRAINER_PIC_TH_SANAE              TRAINER_PIC_118
#define TRAINER_PIC_TH_MIMA               TRAINER_PIC_119
#define TRAINER_PIC_TH_YUUKA              TRAINER_PIC_120
#define TRAINER_PIC_TH_AYA                TRAINER_PIC_121
#define TRAINER_PIC_TH_SHINKI             TRAINER_PIC_122
#define TRAINER_PIC_TH_FLANDRE            TRAINER_PIC_123
#define TRAINER_PIC_TH_REMILIA            TRAINER_PIC_124
#define TRAINER_PIC_TH_LILY_WHITE         TRAINER_PIC_125
#define TRAINER_PIC_TH_FAIRY              TRAINER_PIC_125
#define TRAINER_PIC_TH_SPIRIT             TRAINER_PIC_126
#define TRAINER_PIC_TH_MEILING            TRAINER_PIC_127
#define TRAINER_PIC_TH_MOKOU              TRAINER_PIC_128
#define TRAINER_PIC_TH_KAGUYA             TRAINER_PIC_129
#define TRAINER_PIC_TH_EIRIN              TRAINER_PIC_130
#define TRAINER_PIC_TH_GHOST              TRAINER_PIC_131
#define TRAINER_PIC_TH_ZUN                TRAINER_PIC_132
#define TRAINER_PIC_TH_TEWI               TRAINER_PIC_133
#define TRAINER_PIC_PC_CURE_BLACK         TRAINER_PIC_134
#define TRAINER_PIC_PC_CURE_WHITE         TRAINER_PIC_135
#define TRAINER_PIC_PC_SHINY_LUMINOUS     TRAINER_PIC_136
#define TRAINER_PIC_PC_FWPC               TRAINER_PIC_137
#define TRAINER_PIC_PC_CURE_BLOOM         TRAINER_PIC_138
#define TRAINER_PIC_PC_CURE_EGRET         TRAINER_PIC_139
#define TRAINER_PIC_PC_CURE_DREAM         TRAINER_PIC_140
#define TRAINER_PIC_PC_CURE_PEACH         TRAINER_PIC_141
#define TRAINER_PIC_PC_CURE_BLOSSOM       TRAINER_PIC_142
#define TRAINER_PIC_PC_CURE_MELODY        TRAINER_PIC_143
#define TRAINER_PIC_PC_CURE_HAPPY         TRAINER_PIC_144
#define TRAINER_PIC_PC_CURE_HEART         TRAINER_PIC_145
#define TRAINER_PIC_PC_CURE_ECHO          TRAINER_PIC_146
#define TRAINER_PIC_PC_CURE_UNION         TRAINER_PIC_147
#define TRAINER_PIC_BGHS_MIKI             TRAINER_PIC_148
#define TRAINER_PIC_BGHS_MISAKI           TRAINER_PIC_149
#define TRAINER_PIC_BGHS_SADONE           TRAINER_PIC_150
#define TRAINER_PIC_BGHS_KANON            TRAINER_PIC_151
#define TRAINER_PIC_BGHS_SHIHO            TRAINER_PIC_152
#define TRAINER_PIC_BGHS_KURUMI           TRAINER_PIC_153
#define TRAINER_PIC_BGHS_KURUMI_ALTER     TRAINER_PIC_154
#define TRAINER_PIC_BGHS_HINATA           TRAINER_PIC_155
#define TRAINER_PIC_BHGS_HINATA_ALTER     TRAINER_PIC_156
#define TRAINER_PIC_BHGS_ANKO             TRAINER_PIC_157
#define TRAINER_PIC_BHGS_ANKO_ALTER       TRAINER_PIC_158
#define TRAINER_PIC_BHGS_EVINA            TRAINER_PIC_159
#define TRAINER_PIC_BHGS_MARI             TRAINER_PIC_160
#define TRAINER_PIC_BHGS_ERIS             TRAINER_PIC_161
#define TRAINER_PIC_BHGS_AOI              TRAINER_PIC_162
#define TRAINER_PIC_BHGS_FURAN            TRAINER_PIC_163
#define TRAINER_PIC_BHGS_BOTAN            TRAINER_PIC_164
#define TRAINER_PIC_YYYI_WAKABA           TRAINER_PIC_165
#define TRAINER_PIC_YYYI_TAKASHIMA_YUUNA  TRAINER_PIC_166
#define TRAINER_PIC_YYYI_CHIKAGE          TRAINER_PIC_167
#define TRAINER_PIC_YYYI_ANZU             TRAINER_PIC_168
#define TRAINER_PIC_YYYI_TAMAKO           TRAINER_PIC_169
#define TRAINER_PIC_YYYI_HINA             TRAINER_PIC_170
#define TRAINER_PIC_YYYI_UTANO            TRAINER_PIC_171
#define TRAINER_PIC_YYYI_MITO             TRAINER_PIC_172
#define TRAINER_PIC_YYYI_YUUKI_YUUNA      TRAINER_PIC_173
#define TRAINER_PIC_YYYI_MEBUKI           TRAINER_PIC_174
#define TRAINER_PIC_YYYI_SUMI             TRAINER_PIC_175
#define TRAINER_PIC_YYYI_SEKKA            TRAINER_PIC_176
#define TRAINER_PIC_YYYI_NATSUME          TRAINER_PIC_177
#define TRAINER_PIC_YYYI_AKAMINE_YUUNA    TRAINER_PIC_178
#define TRAINER_PIC_YYYI_TENMA            TRAINER_PIC_179
#define TRAINER_PIC_YYYI_HIME             TRAINER_PIC_180
#define TRAINER_PIC_YYYI_FUYOU_YUUNA      TRAINER_PIC_181
#define TRAINER_PIC_YYYI_YUZUKI_YUUNA     TRAINER_PIC_182
#define TRAINER_PIC_KEY_TOMOYA            TRAINER_PIC_183
#define TRAINER_PIC_KEY_NAGISA            TRAINER_PIC_184
#define TRAINER_PIC_KEY_USHIO             TRAINER_PIC_185
#define TRAINER_PIC_KEY_ILLUSIONARY_GIRL  TRAINER_PIC_186
#define TRAINER_PIC_KEY_KYOU              TRAINER_PIC_187
#define TRAINER_PIC_KEY_RYOU              TRAINER_PIC_188
#define TRAINER_PIC_KEY_KOTOMI            TRAINER_PIC_189
#define TRAINER_PIC_KEY_TOMOYO            TRAINER_PIC_190
#define TRAINER_PIC_KEY_FUUKO             TRAINER_PIC_191
#define TRAINER_PIC_KEY_YOUHEI            TRAINER_PIC_192
#define TRAINER_PIC_KEY_ILLUSIONARY_ROBOT TRAINER_PIC_193
#define TRAINER_PIC_TEACHER               TRAINER_PIC_194
#define TRAINER_PIC_GSC_TEACHER           TRAINER_PIC_195

// The player back pics are assumed to alternate according to the gender values (MALE/FEMALE)
#define TRAINER_BACK_PIC_BRENDAN                0
#define TRAINER_BACK_PIC_MAY                    1
#define TRAINER_BACK_PIC_RED                    2
#define TRAINER_BACK_PIC_LEAF                   3
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_BRENDAN  4
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_MAY      5
#define TRAINER_BACK_PIC_WALLY                  6
#define TRAINER_BACK_PIC_STEVEN                 7
#define TRAINER_BACK_PIC_TH_RENKO_BIG           8
#define TRAINER_BACK_PIC_TH_MARIBEL_BIG         9
#define TRAINER_BACK_PIC_TH_RENKO_SMALL         10
#define TRAINER_BACK_PIC_TH_MARIBEL_SMALL       11
#define TRAINER_BACK_PIC_TH_RENKO_CLASSIC       12
#define TRAINER_BACK_PIC_TH_MARIBEL_CLASSIC     13
#define TRAINER_BACK_PIC_TH_REIMU               14
#define TRAINER_BACK_PIC_TH_MARISA              15

#define FACILITY_CLASS_HIKER                 0x0
#define FACILITY_CLASS_AQUA_GRUNT_M          0x1
#define FACILITY_CLASS_PKMN_BREEDER_F        0x2
#define FACILITY_CLASS_COOLTRAINER_M         0x3
#define FACILITY_CLASS_BIRD_KEEPER           0x4
#define FACILITY_CLASS_COLLECTOR             0x5
#define FACILITY_CLASS_AQUA_GRUNT_F          0x6
#define FACILITY_CLASS_SWIMMER_M             0x7
#define FACILITY_CLASS_MAGMA_GRUNT_M         0x8
#define FACILITY_CLASS_EXPERT_M              0x9
#define FACILITY_CLASS_BLACK_BELT            0xa
#define FACILITY_CLASS_AQUA_LEADER_ARCHIE    0xb
#define FACILITY_CLASS_HEX_MANIAC            0xc
#define FACILITY_CLASS_AROMA_LADY            0xd
#define FACILITY_CLASS_RUIN_MANIAC           0xe
#define FACILITY_CLASS_INTERVIEWER           0xf
#define FACILITY_CLASS_TUBER_F               0x10
#define FACILITY_CLASS_TUBER_M               0x11
#define FACILITY_CLASS_COOLTRAINER_F         0x12
#define FACILITY_CLASS_LADY                  0x13
#define FACILITY_CLASS_BEAUTY                0x14
#define FACILITY_CLASS_RICH_BOY              0x15
#define FACILITY_CLASS_EXPERT_F              0x16
#define FACILITY_CLASS_POKEMANIAC            0x17
#define FACILITY_CLASS_MAGMA_GRUNT_F         0x18
#define FACILITY_CLASS_GUITARIST             0x19
#define FACILITY_CLASS_KINDLER               0x1a
#define FACILITY_CLASS_CAMPER                0x1b
#define FACILITY_CLASS_PICNICKER             0x1c
#define FACILITY_CLASS_BUG_MANIAC            0x1d
#define FACILITY_CLASS_PSYCHIC_M             0x1e
#define FACILITY_CLASS_PSYCHIC_F             0x1f
#define FACILITY_CLASS_GENTLEMAN             0x20
#define FACILITY_CLASS_ELITE_FOUR_SIDNEY     0x21
#define FACILITY_CLASS_ELITE_FOUR_PHOEBE     0x22
#define FACILITY_CLASS_LEADER_ROXANNE        0x23
#define FACILITY_CLASS_LEADER_BRAWLY         0x24
#define FACILITY_CLASS_LEADER_TATE_AND_LIZA  0x25
#define FACILITY_CLASS_SCHOOL_KID_M          0x26
#define FACILITY_CLASS_SCHOOL_KID_F          0x27
#define FACILITY_CLASS_SR_AND_JR             0x28
#define FACILITY_CLASS_POKEFAN_M             0x29
#define FACILITY_CLASS_POKEFAN_F             0x2a
#define FACILITY_CLASS_YOUNGSTER             0x2b
#define FACILITY_CLASS_CHAMPION_WALLACE      0x2c
#define FACILITY_CLASS_FISHERMAN             0x2d
#define FACILITY_CLASS_CYCLING_TRIATHLETE_M  0x2e
#define FACILITY_CLASS_CYCLING_TRIATHLETE_F  0x2f
#define FACILITY_CLASS_RUNNING_TRIATHLETE_M  0x30
#define FACILITY_CLASS_RUNNING_TRIATHLETE_F  0x31
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_M 0x32
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_F 0x33
#define FACILITY_CLASS_DRAGON_TAMER          0x34
#define FACILITY_CLASS_NINJA_BOY             0x35
#define FACILITY_CLASS_BATTLE_GIRL           0x36
#define FACILITY_CLASS_PARASOL_LADY          0x37
#define FACILITY_CLASS_SWIMMER_F             0x38
#define FACILITY_CLASS_TWINS                 0x39
#define FACILITY_CLASS_SAILOR                0x3a
#define FACILITY_CLASS_WALLY                 0x3b
#define FACILITY_CLASS_BRENDAN               0x3c
#define FACILITY_CLASS_BRENDAN_2             0x3d
#define FACILITY_CLASS_BRENDAN_3             0x3e
#define FACILITY_CLASS_MAY                   0x3f
#define FACILITY_CLASS_MAY_2                 0x40
#define FACILITY_CLASS_MAY_3                 0x41
#define FACILITY_CLASS_PKMN_BREEDER_M        0x42
#define FACILITY_CLASS_BUG_CATCHER           0x43
#define FACILITY_CLASS_PKMN_RANGER_M         0x44
#define FACILITY_CLASS_PKMN_RANGER_F         0x45
#define FACILITY_CLASS_MAGMA_LEADER_MAXIE    0x46
#define FACILITY_CLASS_LASS                  0x47
#define FACILITY_CLASS_YOUNG_COUPLE          0x48
#define FACILITY_CLASS_OLD_COUPLE            0x49
#define FACILITY_CLASS_SIS_AND_BRO           0x4a
#define FACILITY_CLASS_STEVEN                0x4b
#define FACILITY_CLASS_SALON_MAIDEN_ANABEL   0x4c
#define FACILITY_CLASS_DOME_ACE_TUCKER       0x4d
#define FACILITY_CLASS_RED                   0x4e
#define FACILITY_CLASS_LEAF                  0x4f
#define FACILITY_CLASS_RS_BRENDAN            0x50
#define FACILITY_CLASS_RS_MAY                0x51

#define FACILITY_CLASSES_COUNT               0x52

#define RS_FACILITY_CLASS_AQUA_LEADER_ARCHIE    0x0
#define RS_FACILITY_CLASS_AQUA_GRUNT_M          0x1
#define RS_FACILITY_CLASS_AQUA_GRUNT_F          0x2
#define RS_FACILITY_CLASS_AROMA_LADY            0x3
#define RS_FACILITY_CLASS_RUIN_MANIAC           0x4
#define RS_FACILITY_CLASS_INTERVIEWER           0x5
#define RS_FACILITY_CLASS_TUBER_F               0x6
#define RS_FACILITY_CLASS_TUBER_M               0x7
#define RS_FACILITY_CLASS_COOLTRAINER_M         0x8
#define RS_FACILITY_CLASS_COOLTRAINER_F         0x9
#define RS_FACILITY_CLASS_HEX_MANIAC            0xA
#define RS_FACILITY_CLASS_LADY                  0xB
#define RS_FACILITY_CLASS_BEAUTY                0xC
#define RS_FACILITY_CLASS_RICH_BOY              0xD
#define RS_FACILITY_CLASS_POKEMANIAC            0xE
#define RS_FACILITY_CLASS_SWIMMER_M             0xF
#define RS_FACILITY_CLASS_BLACK_BELT            0x10
#define RS_FACILITY_CLASS_GUITARIST             0x11
#define RS_FACILITY_CLASS_KINDLER               0x12
#define RS_FACILITY_CLASS_CAMPER                0x13
#define RS_FACILITY_CLASS_BUG_MANIAC            0x14
#define RS_FACILITY_CLASS_PSYCHIC_M             0x15
#define RS_FACILITY_CLASS_PSYCHIC_F             0x16
#define RS_FACILITY_CLASS_GENTLEMAN             0x17
#define RS_FACILITY_CLASS_ELITE_FOUR_M          0x18
#define RS_FACILITY_CLASS_ELITE_FOUR_F          0x19
#define RS_FACILITY_CLASS_LEADER_F              0x1A
#define RS_FACILITY_CLASS_LEADER_M              0x1B
#define RS_FACILITY_CLASS_LEADER_MF             0x1C
#define RS_FACILITY_CLASS_SCHOOL_KID_M          0x1D
#define RS_FACILITY_CLASS_SCHOOL_KID_F          0x1E
#define RS_FACILITY_CLASS_SR_AND_JR             0x1F
#define RS_FACILITY_CLASS_POKEFAN_M             0x20
#define RS_FACILITY_CLASS_POKEFAN_F             0x21
#define RS_FACILITY_CLASS_EXPERT_M              0x22
#define RS_FACILITY_CLASS_EXPERT_F              0x23
#define RS_FACILITY_CLASS_YOUNGSTER             0x24
#define RS_FACILITY_CLASS_CHAMPION              0x25
#define RS_FACILITY_CLASS_FISHERMAN             0x26
#define RS_FACILITY_CLASS_CYCLING_TRIATHLETE_M  0x27
#define RS_FACILITY_CLASS_CYCLING_TRIATHLETE_F  0x28
#define RS_FACILITY_CLASS_RUNNING_TRIATHLETE_M  0x29
#define RS_FACILITY_CLASS_RUNNING_TRIATHLETE_F  0x2A
#define RS_FACILITY_CLASS_SWIMMING_TRIATHLETE_M 0x2B
#define RS_FACILITY_CLASS_SWIMMING_TRIATHLETE_F 0x2C
#define RS_FACILITY_CLASS_DRAGON_TAMER          0x2D
#define RS_FACILITY_CLASS_BIRD_KEEPER           0x2E
#define RS_FACILITY_CLASS_NINJA_BOY             0x2F
#define RS_FACILITY_CLASS_BATTLE_GIRL           0x30
#define RS_FACILITY_CLASS_PARASOL_LADY          0x31
#define RS_FACILITY_CLASS_SWIMMER_F             0x32
#define RS_FACILITY_CLASS_PICNICKER             0x33
#define RS_FACILITY_CLASS_TWINS                 0x34
#define RS_FACILITY_CLASS_SAILOR                0x35
#define RS_FACILITY_CLASS_BOARDER_1             0x36
#define RS_FACILITY_CLASS_BOARDER_2             0x37
#define RS_FACILITY_CLASS_COLLECTOR             0x38
#define RS_FACILITY_CLASS_WALLY                 0x39
#define RS_FACILITY_CLASS_BRENDAN_1             0x3A
#define RS_FACILITY_CLASS_BRENDAN_2             0x3B
#define RS_FACILITY_CLASS_BRENDAN_3             0x3C
#define RS_FACILITY_CLASS_MAY_1                 0x3D
#define RS_FACILITY_CLASS_MAY_2                 0x3E
#define RS_FACILITY_CLASS_MAY_3                 0x3F
#define RS_FACILITY_CLASS_PKMN_BREEDER_M        0x40
#define RS_FACILITY_CLASS_PKMN_BREEDER_F        0x41
#define RS_FACILITY_CLASS_PKMN_RANGER_M         0x42
#define RS_FACILITY_CLASS_PKMN_RANGER_F         0x43
#define RS_FACILITY_CLASS_MAGMA_LEADER          0x44
#define RS_FACILITY_CLASS_MAGMA_GRUNT_M         0x45
#define RS_FACILITY_CLASS_MAGMA_GRUNT_F         0x46
#define RS_FACILITY_CLASS_LASS                  0x47
#define RS_FACILITY_CLASS_BUG_CATCHER           0x48
#define RS_FACILITY_CLASS_HIKER                 0x49
#define RS_FACILITY_CLASS_YOUNG_COUPLE          0x4A
#define RS_FACILITY_CLASS_OLD_COUPLE            0x4B
#define RS_FACILITY_CLASS_SIS_AND_BRO           0x4C

#define RS_FACILITY_CLASSES_COUNT               0x4D

enum TrainerClassID
{
    TRAINER_CLASS_PKMN_TRAINER_1, // Unused
    TRAINER_CLASS_PKMN_TRAINER_2, // Unused
    TRAINER_CLASS_HIKER,
    TRAINER_CLASS_TEAM_AQUA,
    TRAINER_CLASS_PKMN_BREEDER,
    TRAINER_CLASS_COOLTRAINER,
    TRAINER_CLASS_BIRD_KEEPER,
    TRAINER_CLASS_COLLECTOR,
    TRAINER_CLASS_SWIMMER_M,
    TRAINER_CLASS_TEAM_MAGMA,
    TRAINER_CLASS_EXPERT,
    TRAINER_CLASS_AQUA_ADMIN,
    TRAINER_CLASS_BLACK_BELT,
    TRAINER_CLASS_AQUA_LEADER,
    TRAINER_CLASS_HEX_MANIAC,
    TRAINER_CLASS_AROMA_LADY,
    TRAINER_CLASS_RUIN_MANIAC,
    TRAINER_CLASS_INTERVIEWER,
    TRAINER_CLASS_TUBER_F,
    TRAINER_CLASS_TUBER_M,
    TRAINER_CLASS_LADY,
    TRAINER_CLASS_BEAUTY,
    TRAINER_CLASS_RICH_BOY,
    TRAINER_CLASS_POKEMANIAC,
    TRAINER_CLASS_GUITARIST,
    TRAINER_CLASS_KINDLER,
    TRAINER_CLASS_CAMPER,
    TRAINER_CLASS_PICNICKER,
    TRAINER_CLASS_BUG_MANIAC,
    TRAINER_CLASS_PSYCHIC,
    TRAINER_CLASS_GENTLEMAN,
    TRAINER_CLASS_ELITE_FOUR,
    TRAINER_CLASS_LEADER,
    TRAINER_CLASS_SCHOOL_KID,
    TRAINER_CLASS_SR_AND_JR,
    TRAINER_CLASS_WINSTRATE,
    TRAINER_CLASS_POKEFAN,
    TRAINER_CLASS_YOUNGSTER,
    TRAINER_CLASS_CHAMPION,
    TRAINER_CLASS_FISHERMAN,
    TRAINER_CLASS_TRIATHLETE,
    TRAINER_CLASS_DRAGON_TAMER,
    TRAINER_CLASS_NINJA_BOY,
    TRAINER_CLASS_BATTLE_GIRL,
    TRAINER_CLASS_PARASOL_LADY,
    TRAINER_CLASS_SWIMMER_F,
    TRAINER_CLASS_TWINS,
    TRAINER_CLASS_SAILOR,
    TRAINER_CLASS_COOLTRAINER_2, // Used for only one trainer.
    TRAINER_CLASS_MAGMA_ADMIN,
    TRAINER_CLASS_RIVAL,
    TRAINER_CLASS_BUG_CATCHER,
    TRAINER_CLASS_PKMN_RANGER,
    TRAINER_CLASS_MAGMA_LEADER,
    TRAINER_CLASS_LASS,
    TRAINER_CLASS_YOUNG_COUPLE,
    TRAINER_CLASS_OLD_COUPLE,
    TRAINER_CLASS_SIS_AND_BRO,
    TRAINER_CLASS_SALON_MAIDEN,
    TRAINER_CLASS_DOME_ACE,
    TRAINER_CLASS_PALACE_MAVEN,
    TRAINER_CLASS_ARENA_TYCOON,
    TRAINER_CLASS_FACTORY_HEAD,
    TRAINER_CLASS_PIKE_QUEEN,
    TRAINER_CLASS_PYRAMID_KING,
    TRAINER_CLASS_RS_PROTAG,
	TRAINER_CLASS_0X42,
	TRAINER_CLASS_0X43,
	TRAINER_CLASS_0X44,
	TRAINER_CLASS_0X45,
	TRAINER_CLASS_0X46,
	TRAINER_CLASS_0X47,
	TRAINER_CLASS_0X48,
	TRAINER_CLASS_0X49,
	TRAINER_CLASS_0X4A,
	TRAINER_CLASS_0X4B,
	TRAINER_CLASS_0X4C,
	TRAINER_CLASS_0X4D,
	TRAINER_CLASS_0X4E,
	TRAINER_CLASS_0X4F,
	TRAINER_CLASS_0X50,
	TRAINER_CLASS_0X51,
	TRAINER_CLASS_0X52,
	TRAINER_CLASS_0X53,
	TRAINER_CLASS_0X54,
	TRAINER_CLASS_0X55,
	TRAINER_CLASS_0X56,
	TRAINER_CLASS_0X57,
	TRAINER_CLASS_0X58,
	TRAINER_CLASS_0X59,
	TRAINER_CLASS_0X5A,
	TRAINER_CLASS_0X5B,
	TRAINER_CLASS_0X5C,
	TRAINER_CLASS_0X5D,
	TRAINER_CLASS_0X5E,
	TRAINER_CLASS_0X5F,
	TRAINER_CLASS_0X60,
	TRAINER_CLASS_0X61,
	TRAINER_CLASS_0X62,
	TRAINER_CLASS_0X63,
	TRAINER_CLASS_0X64,
	TRAINER_CLASS_0X65,
	TRAINER_CLASS_0X66,
	TRAINER_CLASS_0X67,
	TRAINER_CLASS_0X68,
	TRAINER_CLASS_0X69,
	TRAINER_CLASS_0X6A,
	TRAINER_CLASS_0X6B,
	TRAINER_CLASS_0X6C,
	TRAINER_CLASS_0X6D,
	TRAINER_CLASS_0X6E,
	TRAINER_CLASS_0X6F,
	TRAINER_CLASS_0X70,
	TRAINER_CLASS_0X71,
	TRAINER_CLASS_0X72,
	TRAINER_CLASS_0X73,
	TRAINER_CLASS_0X74,
	TRAINER_CLASS_0X75,
	TRAINER_CLASS_0X76,
	TRAINER_CLASS_0X77,
	TRAINER_CLASS_0X78,
	TRAINER_CLASS_0X79,
	TRAINER_CLASS_0X7A,
	TRAINER_CLASS_0X7B,
	TRAINER_CLASS_0X7C,
	TRAINER_CLASS_0X7D,
	TRAINER_CLASS_0X7E,
	TRAINER_CLASS_0X7F,
	TRAINER_CLASS_0X80,
	TRAINER_CLASS_0X81,
	TRAINER_CLASS_0X82,
	TRAINER_CLASS_0X83,
	TRAINER_CLASS_0X84,
	TRAINER_CLASS_0X85,
	TRAINER_CLASS_0X86,
	TRAINER_CLASS_0X87,
	TRAINER_CLASS_0X88,
	TRAINER_CLASS_0X89,
	TRAINER_CLASS_0X8A,
	TRAINER_CLASS_0X8B,
	TRAINER_CLASS_0X8C,
	TRAINER_CLASS_0X8D,
	TRAINER_CLASS_0X8E,
	TRAINER_CLASS_0X8F,
	TRAINER_CLASS_0X90,
	TRAINER_CLASS_0X91,
	TRAINER_CLASS_0X92,
	TRAINER_CLASS_0X93,
	TRAINER_CLASS_0X94,
	TRAINER_CLASS_0X95,
	TRAINER_CLASS_0X96,
	TRAINER_CLASS_0X97,
	TRAINER_CLASS_0X98,
	TRAINER_CLASS_0X99,
	TRAINER_CLASS_0X9A,
	TRAINER_CLASS_0X9B,
	TRAINER_CLASS_0X9C,
	TRAINER_CLASS_0X9D,
	TRAINER_CLASS_0X9E,
	TRAINER_CLASS_0X9F,
	TRAINER_CLASS_0XA0,
	TRAINER_CLASS_0XA1,
	TRAINER_CLASS_0XA2,
	TRAINER_CLASS_0XA3,
	TRAINER_CLASS_0XA4,
	TRAINER_CLASS_0XA5,
	TRAINER_CLASS_0XA6,
	TRAINER_CLASS_0XA7,
	TRAINER_CLASS_0XA8,
	TRAINER_CLASS_0XA9,
	TRAINER_CLASS_0XAA,
	TRAINER_CLASS_0XAB,
	TRAINER_CLASS_0XAC,
	TRAINER_CLASS_0XAD,
	TRAINER_CLASS_0XAE,
	TRAINER_CLASS_0XAF,
	TRAINER_CLASS_0XB0,
	TRAINER_CLASS_0XB1,
	TRAINER_CLASS_0XB2,
	TRAINER_CLASS_0XB3,
	TRAINER_CLASS_0XB4,
	TRAINER_CLASS_0XB5,
	TRAINER_CLASS_0XB6,
	TRAINER_CLASS_0XB7,
	TRAINER_CLASS_0XB8,
	TRAINER_CLASS_0XB9,
	TRAINER_CLASS_0XBA,
	TRAINER_CLASS_0XBB,
	TRAINER_CLASS_0XBC,
	TRAINER_CLASS_0XBD,
	TRAINER_CLASS_0XBE,
	TRAINER_CLASS_0XBF,
	TRAINER_CLASS_0XC0,
	TRAINER_CLASS_0XC1,
	TRAINER_CLASS_0XC2,
	TRAINER_CLASS_0XC3,
	TRAINER_CLASS_0XC4,
	TRAINER_CLASS_0XC5,
	TRAINER_CLASS_0XC6,
	TRAINER_CLASS_0XC7,
	TRAINER_CLASS_0XC8,
	TRAINER_CLASS_0XC9,
	TRAINER_CLASS_0XCA,
	TRAINER_CLASS_0XCB,
	TRAINER_CLASS_0XCC,
	TRAINER_CLASS_0XCD,
	TRAINER_CLASS_0XCE,
	TRAINER_CLASS_0XCF,
	TRAINER_CLASS_0XD0,
	TRAINER_CLASS_0XD1,
	TRAINER_CLASS_0XD2,
	TRAINER_CLASS_0XD3,
	TRAINER_CLASS_0XD4,
	TRAINER_CLASS_0XD5,
	TRAINER_CLASS_0XD6,
	TRAINER_CLASS_0XD7,
	TRAINER_CLASS_0XD8,
	TRAINER_CLASS_0XD9,
	TRAINER_CLASS_0XDA,
	TRAINER_CLASS_0XDB,
	TRAINER_CLASS_0XDC,
	TRAINER_CLASS_0XDD,
	TRAINER_CLASS_0XDE,
	TRAINER_CLASS_0XDF,
	TRAINER_CLASS_0XE0,
	TRAINER_CLASS_0XE1,
	TRAINER_CLASS_0XE2,
	TRAINER_CLASS_0XE3,
	TRAINER_CLASS_0XE4,
	TRAINER_CLASS_0XE5,
	TRAINER_CLASS_0XE6,
	TRAINER_CLASS_0XE7,
	TRAINER_CLASS_0XE8,
	TRAINER_CLASS_0XE9,
	TRAINER_CLASS_0XEA,
	TRAINER_CLASS_0XEB,
	TRAINER_CLASS_0XEC,
	TRAINER_CLASS_0XED,
	TRAINER_CLASS_0XEE,
	TRAINER_CLASS_0XEF,
	TRAINER_CLASS_0XF0,
	TRAINER_CLASS_0XF1,
	TRAINER_CLASS_0XF2,
	TRAINER_CLASS_0XF3,
	TRAINER_CLASS_0XF4,
	TRAINER_CLASS_0XF5,
	TRAINER_CLASS_0XF6,
	TRAINER_CLASS_0XF7,
	TRAINER_CLASS_0XF8,
	TRAINER_CLASS_0XF9,
	TRAINER_CLASS_0XFA,
	TRAINER_CLASS_0XFB,
	TRAINER_CLASS_0XFC,
	TRAINER_CLASS_0XFD,
	TRAINER_CLASS_0XFE,
    TRAINER_CLASS_COUNT,
};

#define TRAINER_ENCOUNTER_MUSIC_MALE         0 // standard male encounter music
#define TRAINER_ENCOUNTER_MUSIC_FEMALE       1 // standard female encounter music
#define TRAINER_ENCOUNTER_MUSIC_GIRL         2 // used for male Tubers and Young Couples too
#define TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS   3
#define TRAINER_ENCOUNTER_MUSIC_INTENSE      4
#define TRAINER_ENCOUNTER_MUSIC_COOL         5
#define TRAINER_ENCOUNTER_MUSIC_AQUA         6
#define TRAINER_ENCOUNTER_MUSIC_MAGMA        7
#define TRAINER_ENCOUNTER_MUSIC_SWIMMER      8
#define TRAINER_ENCOUNTER_MUSIC_TWINS        9 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  10
#define TRAINER_ENCOUNTER_MUSIC_HIKER       11 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_INTERVIEWER 12
#define TRAINER_ENCOUNTER_MUSIC_RICH        13 // Rich Boys and Gentlemen

#define F_TRAINER_FEMALE (1 << 7)

// Trainer party defines
#define TRAINER_MON_MALE          1
#define TRAINER_MON_FEMALE        2
#define TRAINER_MON_RANDOM_GENDER 3

// Secret base pseudo trainer, controlled by the value of VAR_SECRET_BASE_PSEUDO_TRAINER_NUM
#define PSEUDO_TRAINER_00001                                      1
#define PSEUDO_TRAINER_ALFA                                       PSEUDO_TRAINER_00001
#define PSEUDO_TRAINER_00002                                      2
#define PSEUDO_TRAINER_BB                                         PSEUDO_TRAINER_00002

#define PSEUDO_TRAINER_MIRROR_OPPOSITE_GENDER                     1001
#define PSEUDO_TRAINER_MIRROR_SAME_GENDER                         1002
#define PSEUDO_TRAINER_MIRROR_OPPOSITE_GENDER_CHECK_PARTY_LEVEL   1003
#define PSEUDO_TRAINER_MIRROR_SAME_GENDER_CHECK_PARTY_LEVEL       1004

#endif  // GUARD_TRAINERS_H
