#ifndef GUARD_TRAINERS_H
#define GUARD_TRAINERS_H

#include "constants/opponents.h"
#include "constants/battle_frontier_trainers.h"

// Special Trainer Ids.
//      0-299 are frontier trainers
#define TRAINER_RECORD_MIXING_FRIEND        FRONTIER_TRAINERS_COUNT
#define TRAINER_RECORD_MIXING_APPRENTICE    400
#define TRAINER_EREADER                     500
#define TRAINER_FRONTIER_BRAIN              1022
#define TRAINER_PLAYER                      1023
#define TRAINER_SECRET_BASE                 1024
#define TRAINER_LINK_OPPONENT               2048
#define TRAINER_UNION_ROOM                  3072

#define TRAINER_PIC_HIKER                  0
#define TRAINER_PIC_AQUA_GRUNT_M           1
#define TRAINER_PIC_POKEMON_BREEDER_F      2
#define TRAINER_PIC_COOLTRAINER_M          3
#define TRAINER_PIC_BIRD_KEEPER            4
#define TRAINER_PIC_COLLECTOR              5
#define TRAINER_PIC_AQUA_GRUNT_F           6
#define TRAINER_PIC_SWIMMER_M              7
#define TRAINER_PIC_MAGMA_GRUNT_M          8
#define TRAINER_PIC_EXPERT_M               9
#define TRAINER_PIC_AQUA_ADMIN_M          10
#define TRAINER_PIC_BLACK_BELT            11
#define TRAINER_PIC_AQUA_ADMIN_F          12
#define TRAINER_PIC_AQUA_LEADER_ARCHIE    13
#define TRAINER_PIC_HEX_MANIAC            14
#define TRAINER_PIC_AROMA_LADY            15
#define TRAINER_PIC_RUIN_MANIAC           16
#define TRAINER_PIC_INTERVIEWER           17
#define TRAINER_PIC_TUBER_F               18
#define TRAINER_PIC_TUBER_M               19
#define TRAINER_PIC_COOLTRAINER_F         20
#define TRAINER_PIC_LADY                  21
#define TRAINER_PIC_BEAUTY                22
#define TRAINER_PIC_RICH_BOY              23
#define TRAINER_PIC_EXPERT_F              24
#define TRAINER_PIC_POKEMANIAC            25
#define TRAINER_PIC_MAGMA_GRUNT_F         26
#define TRAINER_PIC_GUITARIST             27
#define TRAINER_PIC_KINDLER               28
#define TRAINER_PIC_CAMPER                29
#define TRAINER_PIC_PICNICKER             30
#define TRAINER_PIC_BUG_MANIAC            31
#define TRAINER_PIC_POKEMON_BREEDER_M     32
#define TRAINER_PIC_PSYCHIC_M             33
#define TRAINER_PIC_PSYCHIC_F             34
#define TRAINER_PIC_GENTLEMAN             35
#define TRAINER_PIC_ELITE_FOUR_SIDNEY     36
#define TRAINER_PIC_ELITE_FOUR_PHOEBE     37
#define TRAINER_PIC_ELITE_FOUR_GLACIA     38
#define TRAINER_PIC_ELITE_FOUR_DRAKE      39
#define TRAINER_PIC_LEADER_ROXANNE        40
#define TRAINER_PIC_LEADER_BRAWLY         41
#define TRAINER_PIC_LEADER_WATTSON        42
#define TRAINER_PIC_LEADER_FLANNERY       43
#define TRAINER_PIC_LEADER_NORMAN         44
#define TRAINER_PIC_LEADER_WINONA         45
#define TRAINER_PIC_LEADER_TATE_AND_LIZA  46
#define TRAINER_PIC_LEADER_JUAN           47
#define TRAINER_PIC_SCHOOL_KID_M          48
#define TRAINER_PIC_SCHOOL_KID_F          49
#define TRAINER_PIC_SR_AND_JR             50
#define TRAINER_PIC_POKEFAN_M             51
#define TRAINER_PIC_POKEFAN_F             52
#define TRAINER_PIC_YOUNGSTER             53
#define TRAINER_PIC_CHAMPION_WALLACE      54
#define TRAINER_PIC_FISHERMAN             55
#define TRAINER_PIC_CYCLING_TRIATHLETE_M  56
#define TRAINER_PIC_CYCLING_TRIATHLETE_F  57
#define TRAINER_PIC_RUNNING_TRIATHLETE_M  58
#define TRAINER_PIC_RUNNING_TRIATHLETE_F  59
#define TRAINER_PIC_SWIMMING_TRIATHLETE_M 60
#define TRAINER_PIC_SWIMMING_TRIATHLETE_F 61
#define TRAINER_PIC_DRAGON_TAMER          62
#define TRAINER_PIC_NINJA_BOY             63
#define TRAINER_PIC_BATTLE_GIRL           64
#define TRAINER_PIC_PARASOL_LADY          65
#define TRAINER_PIC_SWIMMER_F             66
#define TRAINER_PIC_TWINS                 67
#define TRAINER_PIC_SAILOR                68
#define TRAINER_PIC_MAGMA_ADMIN           69
#define TRAINER_PIC_WALLY                 70
#define TRAINER_PIC_BRENDAN               71
#define TRAINER_PIC_MAY                   72
#define TRAINER_PIC_BUG_CATCHER           73
#define TRAINER_PIC_POKEMON_RANGER_M      74
#define TRAINER_PIC_POKEMON_RANGER_F      75
#define TRAINER_PIC_MAGMA_LEADER_MAXIE    76
#define TRAINER_PIC_LASS                  77
#define TRAINER_PIC_YOUNG_COUPLE          78
#define TRAINER_PIC_OLD_COUPLE            79
#define TRAINER_PIC_SIS_AND_BRO           80
#define TRAINER_PIC_STEVEN                81
#define TRAINER_PIC_SALON_MAIDEN_ANABEL   82
#define TRAINER_PIC_DOME_ACE_TUCKER       83
#define TRAINER_PIC_PALACE_MAVEN_SPENSER  84
#define TRAINER_PIC_ARENA_TYCOON_GRETA    85
#define TRAINER_PIC_FACTORY_HEAD_NOLAND   86
#define TRAINER_PIC_PIKE_QUEEN_LUCY       87
#define TRAINER_PIC_PYRAMID_KING_BRANDON  88
#define TRAINER_PIC_RED                   89
#define TRAINER_PIC_LEAF                  90
#define TRAINER_PIC_RS_BRENDAN            91
#define TRAINER_PIC_RS_MAY                92
#define TRAINER_PIC_93                    93
#define TRAINER_PIC_94                    94
#define TRAINER_PIC_95                    95
#define TRAINER_PIC_96                    96
#define TRAINER_PIC_97                    97
#define TRAINER_PIC_98                    98
#define TRAINER_PIC_99                    99
#define TRAINER_PIC_100                   100
#define TRAINER_PIC_101                   101
#define TRAINER_PIC_102                   102
#define TRAINER_PIC_103                   103
#define TRAINER_PIC_104                   104
#define TRAINER_PIC_105                   105
#define TRAINER_PIC_106                   106
#define TRAINER_PIC_107                   107
#define TRAINER_PIC_108                   108
#define TRAINER_PIC_109                   109
#define TRAINER_PIC_110                   110
#define TRAINER_PIC_111                   111
#define TRAINER_PIC_112                   112
#define TRAINER_PIC_113                   113
#define TRAINER_PIC_114                   114
#define TRAINER_PIC_115                   115
#define TRAINER_PIC_116                   116
#define TRAINER_PIC_117                   117
#define TRAINER_PIC_118                   118
#define TRAINER_PIC_119                   119
#define TRAINER_PIC_120                   120
#define TRAINER_PIC_121                   121
#define TRAINER_PIC_122                   122
#define TRAINER_PIC_123                   123
#define TRAINER_PIC_124                   124
#define TRAINER_PIC_125                   125
#define TRAINER_PIC_126                   126
#define TRAINER_PIC_127                   127
#define TRAINER_PIC_128                   128
#define TRAINER_PIC_129                   129
#define TRAINER_PIC_130                   130
#define TRAINER_PIC_131                   131
#define TRAINER_PIC_132                   132
#define TRAINER_PIC_133                   133
#define TRAINER_PIC_134                   134
#define TRAINER_PIC_135                   135
#define TRAINER_PIC_136                   136
#define TRAINER_PIC_137                   137
#define TRAINER_PIC_138                   138
#define TRAINER_PIC_139                   139
#define TRAINER_PIC_140                   140
#define TRAINER_PIC_141                   141
#define TRAINER_PIC_142                   142
#define TRAINER_PIC_143                   143
#define TRAINER_PIC_144                   144
#define TRAINER_PIC_145                   145
#define TRAINER_PIC_146                   146
#define TRAINER_PIC_147                   147
#define TRAINER_PIC_148                   148
#define TRAINER_PIC_149                   149
#define TRAINER_PIC_150                   150
#define TRAINER_PIC_151                   151
#define TRAINER_PIC_152                   152
#define TRAINER_PIC_153                   153
#define TRAINER_PIC_154                   154
#define TRAINER_PIC_155                   155
#define TRAINER_PIC_156                   156
#define TRAINER_PIC_157                   157
#define TRAINER_PIC_158                   158
#define TRAINER_PIC_159                   159
#define TRAINER_PIC_160                   160
#define TRAINER_PIC_161                   161
#define TRAINER_PIC_162                   162
#define TRAINER_PIC_163                   163
#define TRAINER_PIC_164                   164
#define TRAINER_PIC_165                   165
#define TRAINER_PIC_166                   166
#define TRAINER_PIC_167                   167
#define TRAINER_PIC_168                   168
#define TRAINER_PIC_169                   169
#define TRAINER_PIC_170                   170
#define TRAINER_PIC_171                   171
#define TRAINER_PIC_172                   172
#define TRAINER_PIC_173                   173
#define TRAINER_PIC_174                   174
#define TRAINER_PIC_175                   175
#define TRAINER_PIC_176                   176
#define TRAINER_PIC_177                   177
#define TRAINER_PIC_178                   178
#define TRAINER_PIC_179                   179
#define TRAINER_PIC_180                   180
#define TRAINER_PIC_181                   181
#define TRAINER_PIC_182                   182
#define TRAINER_PIC_183                   183
#define TRAINER_PIC_184                   184
#define TRAINER_PIC_185                   185
#define TRAINER_PIC_186                   186
#define TRAINER_PIC_187                   187
#define TRAINER_PIC_188                   188
#define TRAINER_PIC_189                   189
#define TRAINER_PIC_190                   190
#define TRAINER_PIC_191                   191
#define TRAINER_PIC_192                   192
#define TRAINER_PIC_193                   193
#define TRAINER_PIC_194                   194
#define TRAINER_PIC_195                   195
#define TRAINER_PIC_196                   196
#define TRAINER_PIC_197                   197
#define TRAINER_PIC_198                   198
#define TRAINER_PIC_199                   199
#define TRAINER_PIC_200                   200
#define TRAINER_PIC_201                   201
#define TRAINER_PIC_202                   202
#define TRAINER_PIC_203                   203
#define TRAINER_PIC_204                   204
#define TRAINER_PIC_205                   205
#define TRAINER_PIC_206                   206
#define TRAINER_PIC_207                   207
#define TRAINER_PIC_208                   208
#define TRAINER_PIC_209                   209
#define TRAINER_PIC_210                   210
#define TRAINER_PIC_211                   211
#define TRAINER_PIC_212                   212
#define TRAINER_PIC_213                   213
#define TRAINER_PIC_214                   214
#define TRAINER_PIC_215                   215
#define TRAINER_PIC_216                   216
#define TRAINER_PIC_217                   217
#define TRAINER_PIC_218                   218
#define TRAINER_PIC_219                   219
#define TRAINER_PIC_220                   220
#define TRAINER_PIC_221                   221
#define TRAINER_PIC_222                   222
#define TRAINER_PIC_223                   223
#define TRAINER_PIC_224                   224
#define TRAINER_PIC_225                   225
#define TRAINER_PIC_226                   226
#define TRAINER_PIC_227                   227
#define TRAINER_PIC_228                   228
#define TRAINER_PIC_229                   229
#define TRAINER_PIC_230                   230
#define TRAINER_PIC_231                   231
#define TRAINER_PIC_232                   232
#define TRAINER_PIC_233                   233
#define TRAINER_PIC_234                   234
#define TRAINER_PIC_235                   235
#define TRAINER_PIC_236                   236
#define TRAINER_PIC_237                   237
#define TRAINER_PIC_238                   238
#define TRAINER_PIC_239                   239
#define TRAINER_PIC_240                   240
#define TRAINER_PIC_241                   241
#define TRAINER_PIC_242                   242
#define TRAINER_PIC_243                   243
#define TRAINER_PIC_244                   244
#define TRAINER_PIC_245                   245
#define TRAINER_PIC_246                   246
#define TRAINER_PIC_247                   247
#define TRAINER_PIC_248                   248
#define TRAINER_PIC_249                   249
#define TRAINER_PIC_250                   250
#define TRAINER_PIC_251                   251
#define TRAINER_PIC_252                   252
#define TRAINER_PIC_253                   253
#define TRAINER_PIC_254                   254
#define TRAINER_PIC_COUNT                 255

// The player back pics are assumed to alternate according to the gender values (MALE/FEMALE)
#define TRAINER_BACK_PIC_BRENDAN                0
#define TRAINER_BACK_PIC_MAY                    1
#define TRAINER_BACK_PIC_RED                    2
#define TRAINER_BACK_PIC_LEAF                   3
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_BRENDAN  4
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_MAY      5
#define TRAINER_BACK_PIC_WALLY                  6
#define TRAINER_BACK_PIC_STEVEN                 7
#define TRAINER_BACK_PIC_TH_RENKO_BIG           8
#define TRAINER_BACK_PIC_TH_MARIBEL_BIG         9
#define TRAINER_BACK_PIC_TH_RENKO_SMALL         10
#define TRAINER_BACK_PIC_TH_MARIBEL_SMALL       11
#define TRAINER_BACK_PIC_TH_RENKO_CLASSIC       12
#define TRAINER_BACK_PIC_TH_MARIBEL_CLASSIC     13
#define TRAINER_BACK_PIC_TH_REIMU               14
#define TRAINER_BACK_PIC_TH_MARISA              15

#define FACILITY_CLASS_HIKER                 0x0
#define FACILITY_CLASS_AQUA_GRUNT_M          0x1
#define FACILITY_CLASS_PKMN_BREEDER_F        0x2
#define FACILITY_CLASS_COOLTRAINER_M         0x3
#define FACILITY_CLASS_BIRD_KEEPER           0x4
#define FACILITY_CLASS_COLLECTOR             0x5
#define FACILITY_CLASS_AQUA_GRUNT_F          0x6
#define FACILITY_CLASS_SWIMMER_M             0x7
#define FACILITY_CLASS_MAGMA_GRUNT_M         0x8
#define FACILITY_CLASS_EXPERT_M              0x9
#define FACILITY_CLASS_BLACK_BELT            0xa
#define FACILITY_CLASS_AQUA_LEADER_ARCHIE    0xb
#define FACILITY_CLASS_HEX_MANIAC            0xc
#define FACILITY_CLASS_AROMA_LADY            0xd
#define FACILITY_CLASS_RUIN_MANIAC           0xe
#define FACILITY_CLASS_INTERVIEWER           0xf
#define FACILITY_CLASS_TUBER_F               0x10
#define FACILITY_CLASS_TUBER_M               0x11
#define FACILITY_CLASS_COOLTRAINER_F         0x12
#define FACILITY_CLASS_LADY                  0x13
#define FACILITY_CLASS_BEAUTY                0x14
#define FACILITY_CLASS_RICH_BOY              0x15
#define FACILITY_CLASS_EXPERT_F              0x16
#define FACILITY_CLASS_POKEMANIAC            0x17
#define FACILITY_CLASS_MAGMA_GRUNT_F         0x18
#define FACILITY_CLASS_GUITARIST             0x19
#define FACILITY_CLASS_KINDLER               0x1a
#define FACILITY_CLASS_CAMPER                0x1b
#define FACILITY_CLASS_PICNICKER             0x1c
#define FACILITY_CLASS_BUG_MANIAC            0x1d
#define FACILITY_CLASS_PSYCHIC_M             0x1e
#define FACILITY_CLASS_PSYCHIC_F             0x1f
#define FACILITY_CLASS_GENTLEMAN             0x20
#define FACILITY_CLASS_ELITE_FOUR_SIDNEY     0x21
#define FACILITY_CLASS_ELITE_FOUR_PHOEBE     0x22
#define FACILITY_CLASS_LEADER_ROXANNE        0x23
#define FACILITY_CLASS_LEADER_BRAWLY         0x24
#define FACILITY_CLASS_LEADER_TATE_AND_LIZA  0x25
#define FACILITY_CLASS_SCHOOL_KID_M          0x26
#define FACILITY_CLASS_SCHOOL_KID_F          0x27
#define FACILITY_CLASS_SR_AND_JR             0x28
#define FACILITY_CLASS_POKEFAN_M             0x29
#define FACILITY_CLASS_POKEFAN_F             0x2a
#define FACILITY_CLASS_YOUNGSTER             0x2b
#define FACILITY_CLASS_CHAMPION_WALLACE      0x2c
#define FACILITY_CLASS_FISHERMAN             0x2d
#define FACILITY_CLASS_CYCLING_TRIATHLETE_M  0x2e
#define FACILITY_CLASS_CYCLING_TRIATHLETE_F  0x2f
#define FACILITY_CLASS_RUNNING_TRIATHLETE_M  0x30
#define FACILITY_CLASS_RUNNING_TRIATHLETE_F  0x31
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_M 0x32
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_F 0x33
#define FACILITY_CLASS_DRAGON_TAMER          0x34
#define FACILITY_CLASS_NINJA_BOY             0x35
#define FACILITY_CLASS_BATTLE_GIRL           0x36
#define FACILITY_CLASS_PARASOL_LADY          0x37
#define FACILITY_CLASS_SWIMMER_F             0x38
#define FACILITY_CLASS_TWINS                 0x39
#define FACILITY_CLASS_SAILOR                0x3a
#define FACILITY_CLASS_WALLY                 0x3b
#define FACILITY_CLASS_BRENDAN               0x3c
#define FACILITY_CLASS_BRENDAN_2             0x3d
#define FACILITY_CLASS_BRENDAN_3             0x3e
#define FACILITY_CLASS_MAY                   0x3f
#define FACILITY_CLASS_MAY_2                 0x40
#define FACILITY_CLASS_MAY_3                 0x41
#define FACILITY_CLASS_PKMN_BREEDER_M        0x42
#define FACILITY_CLASS_BUG_CATCHER           0x43
#define FACILITY_CLASS_PKMN_RANGER_M         0x44
#define FACILITY_CLASS_PKMN_RANGER_F         0x45
#define FACILITY_CLASS_MAGMA_LEADER_MAXIE    0x46
#define FACILITY_CLASS_LASS                  0x47
#define FACILITY_CLASS_YOUNG_COUPLE          0x48
#define FACILITY_CLASS_OLD_COUPLE            0x49
#define FACILITY_CLASS_SIS_AND_BRO           0x4a
#define FACILITY_CLASS_STEVEN                0x4b
#define FACILITY_CLASS_SALON_MAIDEN_ANABEL   0x4c
#define FACILITY_CLASS_DOME_ACE_TUCKER       0x4d
#define FACILITY_CLASS_RED                   0x4e
#define FACILITY_CLASS_LEAF                  0x4f
#define FACILITY_CLASS_RS_BRENDAN            0x50
#define FACILITY_CLASS_RS_MAY                0x51

#define FACILITY_CLASSES_COUNT               0x52

#define RS_FACILITY_CLASS_AQUA_LEADER_ARCHIE    0x0
#define RS_FACILITY_CLASS_AQUA_GRUNT_M          0x1
#define RS_FACILITY_CLASS_AQUA_GRUNT_F          0x2
#define RS_FACILITY_CLASS_AROMA_LADY            0x3
#define RS_FACILITY_CLASS_RUIN_MANIAC           0x4
#define RS_FACILITY_CLASS_INTERVIEWER           0x5
#define RS_FACILITY_CLASS_TUBER_F               0x6
#define RS_FACILITY_CLASS_TUBER_M               0x7
#define RS_FACILITY_CLASS_COOLTRAINER_M         0x8
#define RS_FACILITY_CLASS_COOLTRAINER_F         0x9
#define RS_FACILITY_CLASS_HEX_MANIAC            0xA
#define RS_FACILITY_CLASS_LADY                  0xB
#define RS_FACILITY_CLASS_BEAUTY                0xC
#define RS_FACILITY_CLASS_RICH_BOY              0xD
#define RS_FACILITY_CLASS_POKEMANIAC            0xE
#define RS_FACILITY_CLASS_SWIMMER_M             0xF
#define RS_FACILITY_CLASS_BLACK_BELT            0x10
#define RS_FACILITY_CLASS_GUITARIST             0x11
#define RS_FACILITY_CLASS_KINDLER               0x12
#define RS_FACILITY_CLASS_CAMPER                0x13
#define RS_FACILITY_CLASS_BUG_MANIAC            0x14
#define RS_FACILITY_CLASS_PSYCHIC_M             0x15
#define RS_FACILITY_CLASS_PSYCHIC_F             0x16
#define RS_FACILITY_CLASS_GENTLEMAN             0x17
#define RS_FACILITY_CLASS_ELITE_FOUR_M          0x18
#define RS_FACILITY_CLASS_ELITE_FOUR_F          0x19
#define RS_FACILITY_CLASS_LEADER_F              0x1A
#define RS_FACILITY_CLASS_LEADER_M              0x1B
#define RS_FACILITY_CLASS_LEADER_MF             0x1C
#define RS_FACILITY_CLASS_SCHOOL_KID_M          0x1D
#define RS_FACILITY_CLASS_SCHOOL_KID_F          0x1E
#define RS_FACILITY_CLASS_SR_AND_JR             0x1F
#define RS_FACILITY_CLASS_POKEFAN_M             0x20
#define RS_FACILITY_CLASS_POKEFAN_F             0x21
#define RS_FACILITY_CLASS_EXPERT_M              0x22
#define RS_FACILITY_CLASS_EXPERT_F              0x23
#define RS_FACILITY_CLASS_YOUNGSTER             0x24
#define RS_FACILITY_CLASS_CHAMPION              0x25
#define RS_FACILITY_CLASS_FISHERMAN             0x26
#define RS_FACILITY_CLASS_CYCLING_TRIATHLETE_M  0x27
#define RS_FACILITY_CLASS_CYCLING_TRIATHLETE_F  0x28
#define RS_FACILITY_CLASS_RUNNING_TRIATHLETE_M  0x29
#define RS_FACILITY_CLASS_RUNNING_TRIATHLETE_F  0x2A
#define RS_FACILITY_CLASS_SWIMMING_TRIATHLETE_M 0x2B
#define RS_FACILITY_CLASS_SWIMMING_TRIATHLETE_F 0x2C
#define RS_FACILITY_CLASS_DRAGON_TAMER          0x2D
#define RS_FACILITY_CLASS_BIRD_KEEPER           0x2E
#define RS_FACILITY_CLASS_NINJA_BOY             0x2F
#define RS_FACILITY_CLASS_BATTLE_GIRL           0x30
#define RS_FACILITY_CLASS_PARASOL_LADY          0x31
#define RS_FACILITY_CLASS_SWIMMER_F             0x32
#define RS_FACILITY_CLASS_PICNICKER             0x33
#define RS_FACILITY_CLASS_TWINS                 0x34
#define RS_FACILITY_CLASS_SAILOR                0x35
#define RS_FACILITY_CLASS_BOARDER_1             0x36
#define RS_FACILITY_CLASS_BOARDER_2             0x37
#define RS_FACILITY_CLASS_COLLECTOR             0x38
#define RS_FACILITY_CLASS_WALLY                 0x39
#define RS_FACILITY_CLASS_BRENDAN_1             0x3A
#define RS_FACILITY_CLASS_BRENDAN_2             0x3B
#define RS_FACILITY_CLASS_BRENDAN_3             0x3C
#define RS_FACILITY_CLASS_MAY_1                 0x3D
#define RS_FACILITY_CLASS_MAY_2                 0x3E
#define RS_FACILITY_CLASS_MAY_3                 0x3F
#define RS_FACILITY_CLASS_PKMN_BREEDER_M        0x40
#define RS_FACILITY_CLASS_PKMN_BREEDER_F        0x41
#define RS_FACILITY_CLASS_PKMN_RANGER_M         0x42
#define RS_FACILITY_CLASS_PKMN_RANGER_F         0x43
#define RS_FACILITY_CLASS_MAGMA_LEADER          0x44
#define RS_FACILITY_CLASS_MAGMA_GRUNT_M         0x45
#define RS_FACILITY_CLASS_MAGMA_GRUNT_F         0x46
#define RS_FACILITY_CLASS_LASS                  0x47
#define RS_FACILITY_CLASS_BUG_CATCHER           0x48
#define RS_FACILITY_CLASS_HIKER                 0x49
#define RS_FACILITY_CLASS_YOUNG_COUPLE          0x4A
#define RS_FACILITY_CLASS_OLD_COUPLE            0x4B
#define RS_FACILITY_CLASS_SIS_AND_BRO           0x4C

#define RS_FACILITY_CLASSES_COUNT               0x4D

#define TRAINER_CLASS_PKMN_TRAINER_1 0x0  // Unused
#define TRAINER_CLASS_PKMN_TRAINER_2 0x1  // Unused
#define TRAINER_CLASS_HIKER          0x2
#define TRAINER_CLASS_TEAM_AQUA      0x3
#define TRAINER_CLASS_PKMN_BREEDER   0x4
#define TRAINER_CLASS_COOLTRAINER    0x5
#define TRAINER_CLASS_BIRD_KEEPER    0x6
#define TRAINER_CLASS_COLLECTOR      0x7
#define TRAINER_CLASS_SWIMMER_M      0x8
#define TRAINER_CLASS_TEAM_MAGMA     0x9
#define TRAINER_CLASS_EXPERT         0xa
#define TRAINER_CLASS_AQUA_ADMIN     0xb
#define TRAINER_CLASS_BLACK_BELT     0xc
#define TRAINER_CLASS_AQUA_LEADER    0xd
#define TRAINER_CLASS_HEX_MANIAC     0xe
#define TRAINER_CLASS_AROMA_LADY     0xf
#define TRAINER_CLASS_RUIN_MANIAC    0x10
#define TRAINER_CLASS_INTERVIEWER    0x11
#define TRAINER_CLASS_TUBER_F        0x12
#define TRAINER_CLASS_TUBER_M        0x13
#define TRAINER_CLASS_LADY           0x14
#define TRAINER_CLASS_BEAUTY         0x15
#define TRAINER_CLASS_RICH_BOY       0x16
#define TRAINER_CLASS_POKEMANIAC     0x17
#define TRAINER_CLASS_GUITARIST      0x18
#define TRAINER_CLASS_KINDLER        0x19
#define TRAINER_CLASS_CAMPER         0x1a
#define TRAINER_CLASS_PICNICKER      0x1b
#define TRAINER_CLASS_BUG_MANIAC     0x1c
#define TRAINER_CLASS_PSYCHIC        0x1d
#define TRAINER_CLASS_GENTLEMAN      0x1e
#define TRAINER_CLASS_ELITE_FOUR     0x1f
#define TRAINER_CLASS_LEADER         0x20
#define TRAINER_CLASS_SCHOOL_KID     0x21
#define TRAINER_CLASS_SR_AND_JR      0x22
#define TRAINER_CLASS_WINSTRATE      0x23
#define TRAINER_CLASS_POKEFAN        0x24
#define TRAINER_CLASS_YOUNGSTER      0x25
#define TRAINER_CLASS_CHAMPION       0x26
#define TRAINER_CLASS_FISHERMAN      0x27
#define TRAINER_CLASS_TRIATHLETE     0x28
#define TRAINER_CLASS_DRAGON_TAMER   0x29
#define TRAINER_CLASS_NINJA_BOY      0x2a
#define TRAINER_CLASS_BATTLE_GIRL    0x2b
#define TRAINER_CLASS_PARASOL_LADY   0x2c
#define TRAINER_CLASS_SWIMMER_F      0x2d
#define TRAINER_CLASS_TWINS          0x2e
#define TRAINER_CLASS_SAILOR         0x2f
#define TRAINER_CLASS_COOLTRAINER_2  0x30 // Used for only one trainer.
#define TRAINER_CLASS_MAGMA_ADMIN    0x31
#define TRAINER_CLASS_RIVAL          0x32
#define TRAINER_CLASS_BUG_CATCHER    0x33
#define TRAINER_CLASS_PKMN_RANGER    0x34
#define TRAINER_CLASS_MAGMA_LEADER   0x35
#define TRAINER_CLASS_LASS           0x36
#define TRAINER_CLASS_YOUNG_COUPLE   0x37
#define TRAINER_CLASS_OLD_COUPLE     0x38
#define TRAINER_CLASS_SIS_AND_BRO    0x39
#define TRAINER_CLASS_SALON_MAIDEN   0x3a
#define TRAINER_CLASS_DOME_ACE       0x3b
#define TRAINER_CLASS_PALACE_MAVEN   0x3c
#define TRAINER_CLASS_ARENA_TYCOON   0x3d
#define TRAINER_CLASS_FACTORY_HEAD   0x3e
#define TRAINER_CLASS_PIKE_QUEEN     0x3f
#define TRAINER_CLASS_PYRAMID_KING   0x40
#define TRAINER_CLASS_RS_PROTAG      0x41
#define TRAINER_CLASS_0x42           0x42
#define TRAINER_CLASS_0x43           0x43
#define TRAINER_CLASS_0x44           0x44
#define TRAINER_CLASS_0x45           0x45
#define TRAINER_CLASS_0x46           0x46
#define TRAINER_CLASS_0x47           0x47
#define TRAINER_CLASS_0x48           0x48
#define TRAINER_CLASS_0x49           0x49
#define TRAINER_CLASS_0x4A           0x4a
#define TRAINER_CLASS_0x4B           0x4b
#define TRAINER_CLASS_0x4C           0x4c
#define TRAINER_CLASS_0x4D           0x4d
#define TRAINER_CLASS_0x4E           0x4e
#define TRAINER_CLASS_0x4F           0x4f
#define TRAINER_CLASS_0x50           0x50
#define TRAINER_CLASS_0x51           0x51
#define TRAINER_CLASS_0x52           0x52
#define TRAINER_CLASS_0x53           0x53
#define TRAINER_CLASS_0x54           0x54
#define TRAINER_CLASS_0x55           0x55
#define TRAINER_CLASS_0x56           0x56
#define TRAINER_CLASS_0x57           0x57
#define TRAINER_CLASS_0x58           0x58
#define TRAINER_CLASS_0x59           0x59
#define TRAINER_CLASS_0x5A           0x5a
#define TRAINER_CLASS_0x5B           0x5b
#define TRAINER_CLASS_0x5C           0x5c
#define TRAINER_CLASS_0x5D           0x5d
#define TRAINER_CLASS_0x5E           0x5e
#define TRAINER_CLASS_0x5F           0x5f
#define TRAINER_CLASS_0x60           0x60
#define TRAINER_CLASS_0x61           0x61
#define TRAINER_CLASS_0x62           0x62
#define TRAINER_CLASS_0x63           0x63
#define TRAINER_CLASS_0x64           0x64
#define TRAINER_CLASS_0x65           0x65
#define TRAINER_CLASS_0x66           0x66
#define TRAINER_CLASS_0x67           0x67
#define TRAINER_CLASS_0x68           0x68
#define TRAINER_CLASS_0x69           0x69
#define TRAINER_CLASS_0x6A           0x6a
#define TRAINER_CLASS_0x6B           0x6b
#define TRAINER_CLASS_0x6C           0x6c
#define TRAINER_CLASS_0x6D           0x6d
#define TRAINER_CLASS_0x6E           0x6e
#define TRAINER_CLASS_0x6F           0x6f
#define TRAINER_CLASS_0x70           0x70
#define TRAINER_CLASS_0x71           0x71
#define TRAINER_CLASS_0x72           0x72
#define TRAINER_CLASS_0x73           0x73
#define TRAINER_CLASS_0x74           0x74
#define TRAINER_CLASS_0x75           0x75
#define TRAINER_CLASS_0x76           0x76
#define TRAINER_CLASS_0x77           0x77
#define TRAINER_CLASS_0x78           0x78
#define TRAINER_CLASS_0x79           0x79
#define TRAINER_CLASS_0x7A           0x7a
#define TRAINER_CLASS_0x7B           0x7b
#define TRAINER_CLASS_0x7C           0x7c
#define TRAINER_CLASS_0x7D           0x7d
#define TRAINER_CLASS_0x7E           0x7e
#define TRAINER_CLASS_0x7F           0x7f
#define TRAINER_CLASS_0x80           0x80
#define TRAINER_CLASS_0x81           0x81
#define TRAINER_CLASS_0x82           0x82
#define TRAINER_CLASS_0x83           0x83
#define TRAINER_CLASS_0x84           0x84
#define TRAINER_CLASS_0x85           0x85
#define TRAINER_CLASS_0x86           0x86
#define TRAINER_CLASS_0x87           0x87
#define TRAINER_CLASS_0x88           0x88
#define TRAINER_CLASS_0x89           0x89
#define TRAINER_CLASS_0x8A           0x8a
#define TRAINER_CLASS_0x8B           0x8b
#define TRAINER_CLASS_0x8C           0x8c
#define TRAINER_CLASS_0x8D           0x8d
#define TRAINER_CLASS_0x8E           0x8e
#define TRAINER_CLASS_0x8F           0x8f
#define TRAINER_CLASS_0x90           0x90
#define TRAINER_CLASS_0x91           0x91
#define TRAINER_CLASS_0x92           0x92
#define TRAINER_CLASS_0x93           0x93
#define TRAINER_CLASS_0x94           0x94
#define TRAINER_CLASS_0x95           0x95
#define TRAINER_CLASS_0x96           0x96
#define TRAINER_CLASS_0x97           0x97
#define TRAINER_CLASS_0x98           0x98
#define TRAINER_CLASS_0x99           0x99
#define TRAINER_CLASS_0x9A           0x9a
#define TRAINER_CLASS_0x9B           0x9b
#define TRAINER_CLASS_0x9C           0x9c
#define TRAINER_CLASS_0x9D           0x9d
#define TRAINER_CLASS_0x9E           0x9e
#define TRAINER_CLASS_0x9F           0x9f
#define TRAINER_CLASS_0xA0           0xa0
#define TRAINER_CLASS_0xA1           0xa1
#define TRAINER_CLASS_0xA2           0xa2
#define TRAINER_CLASS_0xA3           0xa3
#define TRAINER_CLASS_0xA4           0xa4
#define TRAINER_CLASS_0xA5           0xa5
#define TRAINER_CLASS_0xA6           0xa6
#define TRAINER_CLASS_0xA7           0xa7
#define TRAINER_CLASS_0xA8           0xa8
#define TRAINER_CLASS_0xA9           0xa9
#define TRAINER_CLASS_0xAA           0xaa
#define TRAINER_CLASS_0xAB           0xab
#define TRAINER_CLASS_0xAC           0xac
#define TRAINER_CLASS_0xAD           0xad
#define TRAINER_CLASS_0xAE           0xae
#define TRAINER_CLASS_0xAF           0xaf
#define TRAINER_CLASS_0xB0           0xb0
#define TRAINER_CLASS_0xB1           0xb1
#define TRAINER_CLASS_0xB2           0xb2
#define TRAINER_CLASS_0xB3           0xb3
#define TRAINER_CLASS_0xB4           0xb4
#define TRAINER_CLASS_0xB5           0xb5
#define TRAINER_CLASS_0xB6           0xb6
#define TRAINER_CLASS_0xB7           0xb7
#define TRAINER_CLASS_0xB8           0xb8
#define TRAINER_CLASS_0xB9           0xb9
#define TRAINER_CLASS_0xBA           0xba
#define TRAINER_CLASS_0xBB           0xbb
#define TRAINER_CLASS_0xBC           0xbc
#define TRAINER_CLASS_0xBD           0xbd
#define TRAINER_CLASS_0xBE           0xbe
#define TRAINER_CLASS_0xBF           0xbf
#define TRAINER_CLASS_0xC0           0xc0
#define TRAINER_CLASS_0xC1           0xc1
#define TRAINER_CLASS_0xC2           0xc2
#define TRAINER_CLASS_0xC3           0xc3
#define TRAINER_CLASS_0xC4           0xc4
#define TRAINER_CLASS_0xC5           0xc5
#define TRAINER_CLASS_0xC6           0xc6
#define TRAINER_CLASS_0xC7           0xc7
#define TRAINER_CLASS_0xC8           0xc8
#define TRAINER_CLASS_0xC9           0xc9
#define TRAINER_CLASS_0xCA           0xca
#define TRAINER_CLASS_0xCB           0xcb
#define TRAINER_CLASS_0xCC           0xcc
#define TRAINER_CLASS_0xCD           0xcd
#define TRAINER_CLASS_0xCE           0xce
#define TRAINER_CLASS_0xCF           0xcf
#define TRAINER_CLASS_0xD0           0xd0
#define TRAINER_CLASS_0xD1           0xd1
#define TRAINER_CLASS_0xD2           0xd2
#define TRAINER_CLASS_0xD3           0xd3
#define TRAINER_CLASS_0xD4           0xd4
#define TRAINER_CLASS_0xD5           0xd5
#define TRAINER_CLASS_0xD6           0xd6
#define TRAINER_CLASS_0xD7           0xd7
#define TRAINER_CLASS_0xD8           0xd8
#define TRAINER_CLASS_0xD9           0xd9
#define TRAINER_CLASS_0xDA           0xda
#define TRAINER_CLASS_0xDB           0xdb
#define TRAINER_CLASS_0xDC           0xdc
#define TRAINER_CLASS_0xDD           0xdd
#define TRAINER_CLASS_0xDE           0xde
#define TRAINER_CLASS_0xDF           0xdf
#define TRAINER_CLASS_0xE0           0xe0
#define TRAINER_CLASS_0xE1           0xe1
#define TRAINER_CLASS_0xE2           0xe2
#define TRAINER_CLASS_0xE3           0xe3
#define TRAINER_CLASS_0xE4           0xe4
#define TRAINER_CLASS_0xE5           0xe5
#define TRAINER_CLASS_0xE6           0xe6
#define TRAINER_CLASS_0xE7           0xe7
#define TRAINER_CLASS_0xE8           0xe8
#define TRAINER_CLASS_0xE9           0xe9
#define TRAINER_CLASS_0xEA           0xea
#define TRAINER_CLASS_0xEB           0xeb
#define TRAINER_CLASS_0xEC           0xec
#define TRAINER_CLASS_0xED           0xed
#define TRAINER_CLASS_0xEE           0xee
#define TRAINER_CLASS_0xEF           0xef
#define TRAINER_CLASS_0xF0           0xf0
#define TRAINER_CLASS_0xF1           0xf1
#define TRAINER_CLASS_0xF2           0xf2
#define TRAINER_CLASS_0xF3           0xf3
#define TRAINER_CLASS_0xF4           0xf4
#define TRAINER_CLASS_0xF5           0xf5
#define TRAINER_CLASS_0xF6           0xf6
#define TRAINER_CLASS_0xF7           0xf7
#define TRAINER_CLASS_0xF8           0xf8
#define TRAINER_CLASS_0xF9           0xf9
#define TRAINER_CLASS_0xFA           0xfa
#define TRAINER_CLASS_0xFB           0xfb
#define TRAINER_CLASS_0xFC           0xfc
#define TRAINER_CLASS_0xFD           0xfd
#define TRAINER_CLASS_0xFE           0xfe
#define TRAINER_CLASS_COUNT          0xff

#define TRAINER_ENCOUNTER_MUSIC_MALE         0 // standard male encounter music
#define TRAINER_ENCOUNTER_MUSIC_FEMALE       1 // standard female encounter music
#define TRAINER_ENCOUNTER_MUSIC_GIRL         2 // used for male Tubers and Young Couples too
#define TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS   3
#define TRAINER_ENCOUNTER_MUSIC_INTENSE      4
#define TRAINER_ENCOUNTER_MUSIC_COOL         5
#define TRAINER_ENCOUNTER_MUSIC_AQUA         6
#define TRAINER_ENCOUNTER_MUSIC_MAGMA        7
#define TRAINER_ENCOUNTER_MUSIC_SWIMMER      8
#define TRAINER_ENCOUNTER_MUSIC_TWINS        9 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  10
#define TRAINER_ENCOUNTER_MUSIC_HIKER       11 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_INTERVIEWER 12
#define TRAINER_ENCOUNTER_MUSIC_RICH        13 // Rich Boys and Gentlemen

#define F_TRAINER_FEMALE (1 << 7)

// Trainer party defines
#define TRAINER_MON_MALE          1
#define TRAINER_MON_FEMALE        2
#define TRAINER_MON_RANDOM_GENDER 3

#endif  // GUARD_TRAINERS_H
