gText_Birch_Welcome::
	.string "CONGRATULATION!\p"
	.string "I knew you would be the league\n"
	.string "champion someday, but I did not\l"
	.string "expect it to be this fast.\p"
	.string "As for a present from me…\p"
	.string "$"

gText_Birch_Pokemon::
	.string "…I will give this special egg to you.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Errr…\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "What are you again…?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, I remember now!\p"
	.string "You're {PLAYER}{KUN}!\p"
	.string "Being old is not good, huh.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Anyway, do not forget to\n"
	.string "take the egg.\p"
	.string "Please drop by to the Mr Pokemon's\n"
	.string "house at Route 30, and\l"
	.string "I will be there.\p"
	.string "See you later, {PLAYER}{KUN}!"
	.string "$"
