#ifndef GUARD_GAME_CORNER_EXPANSION_H
#define GUARD_GAME_CORNER_EXPANSION_H

#define GAME_CORNER_VAR_ID_CHECK        VAR_GAME_CORNER_ID_CHECK
#define GAME_CORNER_VAR_WINNINGS        VAR_GAME_CORNER_WINNINGS

#define FLAPPY_VAR_HIGH_SCORE           VAR_FLAPPY_HIGH_SCORE

#define BLACKJACK_FLAG_INSURANCE        FLAG_BLACKJACK_INSURANCE
#define BLACKJACK_FLAG_RESET            FLAG_BLACKJACK_RESET
#define BLACKJACK_FLAG_BLACKJACK        FLAG_BLACKJACK_BLACKJACK
#define BLACKJACK_VAR_PLAYER            VAR_BLACKJACK_PLAYER
#define BLACKJACK_VAR_DEALER            VAR_BLACKJACK_DEALER
#define BLACKJACK_VAR_BET               VAR_BLACKJACK_BET
#define BLACKJACK_VAR_OPTIONS           VAR_BLACKJACK_OPTIONS
#define BLACKJACK_VAR_OPTION1_TILE      VAR_BLACKJACK_OPTION1_TILE
#define BLACKJACK_VAR_OPTION2_TILE      VAR_BLACKJACK_OPTION2_TILE
#define BLACKJACK_VAR_OPTION3_TILE      VAR_BLACKJACK_OPTION3_TILE

#define DERBY_FLAG_NICKNAME             FLAG_DERBY_NICKNAME
#define DERBY_FLAG_RESET                FLAG_DERBY_RESET
#define DERBY_VAR_RACER_NAME_1          VAR_DERBY_RACER_NAME_1
#define DERBY_VAR_RACER_NAME_2          VAR_DERBY_RACER_NAME_2
#define DERBY_VAR_RACER_NAME_3          VAR_DERBY_RACER_NAME_3
#define DERBY_VAR_RACER_NAME_4          VAR_DERBY_RACER_NAME_4
#define DERBY_VAR_RACER_NAME_5          VAR_DERBY_RACER_NAME_5
#define DERBY_VAR_RACER_NAME_6          VAR_DERBY_RACER_NAME_6
#define DERBY_VAR_RACER_1               VAR_DERBY_RACER_1
#define DERBY_VAR_RACER_2               VAR_DERBY_RACER_2
#define DERBY_VAR_RACER_3               VAR_DERBY_RACER_3
#define DERBY_VAR_RACER_4               VAR_DERBY_RACER_4
#define DERBY_VAR_RACER_5               VAR_DERBY_RACER_5
#define DERBY_VAR_RACER_6               VAR_DERBY_RACER_6

#define FLIP_VAR_LEVEL                  VAR_FLIP_LEVEL

#endif // GUARD_GAME_CORNER_EXPANSION_H
