#ifndef GUARD_CONFIG_SPECIES_ENABLED_H
#define GUARD_CONFIG_SPECIES_ENABLED_H

// Modifying the latest generation WILL change the saveblock due to Dex flags and will require a new save file.
// Generations of Pokémon are defined by the first member introduced,
// so Pikachu depends on the Gen 1 setting despite Pichu being the lowest member of the evolution tree.
// Eg: If P_GEN_2_POKEMON is set to FALSE, all members of the Sneasel Family will be disabled
// (Sneasel + Hisuian, Weavile and Sneasler).
#define P_GEN_1_POKEMON                  TRUE // Generation 1 Pokémon (RGBY)
#define P_GEN_2_POKEMON                  TRUE // Generation 2 Pokémon (GSC)
#define P_GEN_3_POKEMON                  TRUE // Generation 3 Pokémon (RSE, FRLG)
#define P_GEN_4_POKEMON                  TRUE // Generation 4 Pokémon (DPPt, HGSS)
#define P_GEN_5_POKEMON                  TRUE // Generation 5 Pokémon (BW, B2W2)
#define P_GEN_6_POKEMON                  TRUE // Generation 6 Pokémon (XY, ORAS)
#define P_GEN_7_POKEMON                  TRUE // Generation 7 Pokémon (SM, USUM, LGPE)
#define P_GEN_8_POKEMON                  TRUE // Generation 8 Pokémon (SwSh, BDSP, LA)
#define P_GEN_9_POKEMON                  TRUE // Generation 9 Pokémon (SV)

// Setting this to TRUE will add the new evolutions to the Regional Dex.
#define P_NEW_EVOS_IN_REGIONAL_DEX       TRUE

// Battle gimmick specific Forms.
#define P_MEGA_EVOLUTIONS                TRUE
#define P_PRIMAL_REVERSIONS              TRUE // Groudon and Kyogre only.
#define P_ULTRA_BURST_FORMS              TRUE // Ultra Necrozma only.
#define P_GIGANTAMAX_FORMS               TRUE
#define P_TERA_FORMS                     TRUE

#define P_GEN_9_MEGA_EVOLUTIONS          P_MEGA_EVOLUTIONS // Mega Evolutions introduced in Z-A and its DLC

// Fusion forms
#define P_FUSION_FORMS                   TRUE

// Regional Forms. Includes Regional Form evolutions, like Sirfetch'd.
#define P_REGIONAL_FORMS                 TRUE
#define P_ALOLAN_FORMS                   P_REGIONAL_FORMS
#define P_GALARIAN_FORMS                 P_REGIONAL_FORMS
#define P_HISUIAN_FORMS                  P_REGIONAL_FORMS
#define P_PALDEAN_FORMS                  P_REGIONAL_FORMS

// Big groups of forms that aren't always desired when choosing families.
#define P_PIKACHU_EXTRA_FORMS            TRUE
#define P_COSPLAY_PIKACHU_FORMS          P_PIKACHU_EXTRA_FORMS
#define P_CAP_PIKACHU_FORMS              P_PIKACHU_EXTRA_FORMS

// Cross-generation evolutions. Includes pre-evolutions.
#define P_CROSS_GENERATION_EVOS          TRUE
#define P_GEN_2_CROSS_EVOS               P_CROSS_GENERATION_EVOS
#define P_GEN_3_CROSS_EVOS               P_CROSS_GENERATION_EVOS
#define P_GEN_4_CROSS_EVOS               P_CROSS_GENERATION_EVOS
//#define P_GEN_5_CROSS_EVOS             // Gen 5 didn't introduce any cross-gen evos.
#define P_GEN_6_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Just Sylveon.
//#define P_GEN_7_CROSS_EVOS             // Alolan evolutions handled by P_ALOLAN_FORMS.
#define P_GEN_8_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Regional evolutions handled by P_GALARIAN_FORMS and P_HISUIAN_FORMS.
#define P_GEN_9_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Clodsire handled by P_PALDEAN_FORMS.

// To disable specific families, replace P_GEN_x_POKEMON with FALSE.
#define P_FAMILY_BULBASAUR               P_GEN_1_POKEMON
#define P_FAMILY_CHARMANDER              P_GEN_1_POKEMON
#define P_FAMILY_SQUIRTLE                P_GEN_1_POKEMON
#define P_FAMILY_CATERPIE                P_GEN_1_POKEMON
#define P_FAMILY_WEEDLE                  P_GEN_1_POKEMON
#define P_FAMILY_PIDGEY                  P_GEN_1_POKEMON
#define P_FAMILY_RATTATA                 P_GEN_1_POKEMON
#define P_FAMILY_SPEAROW                 P_GEN_1_POKEMON
#define P_FAMILY_EKANS                   P_GEN_1_POKEMON
#define P_FAMILY_PIKACHU                 P_GEN_1_POKEMON
#define P_FAMILY_SANDSHREW               P_GEN_1_POKEMON
#define P_FAMILY_NIDORAN                 P_GEN_1_POKEMON
#define P_FAMILY_CLEFAIRY                P_GEN_1_POKEMON
#define P_FAMILY_VULPIX                  P_GEN_1_POKEMON
#define P_FAMILY_JIGGLYPUFF              P_GEN_1_POKEMON
#define P_FAMILY_ZUBAT                   P_GEN_1_POKEMON
#define P_FAMILY_ODDISH                  P_GEN_1_POKEMON
#define P_FAMILY_PARAS                   P_GEN_1_POKEMON
#define P_FAMILY_VENONAT                 P_GEN_1_POKEMON
#define P_FAMILY_DIGLETT                 P_GEN_1_POKEMON
#define P_FAMILY_MEOWTH                  P_GEN_1_POKEMON
#define P_FAMILY_PSYDUCK                 P_GEN_1_POKEMON
#define P_FAMILY_MANKEY                  P_GEN_1_POKEMON
#define P_FAMILY_GROWLITHE               P_GEN_1_POKEMON
#define P_FAMILY_POLIWAG                 P_GEN_1_POKEMON
#define P_FAMILY_ABRA                    P_GEN_1_POKEMON
#define P_FAMILY_MACHOP                  P_GEN_1_POKEMON
#define P_FAMILY_BELLSPROUT              P_GEN_1_POKEMON
#define P_FAMILY_TENTACOOL               P_GEN_1_POKEMON
#define P_FAMILY_GEODUDE                 P_GEN_1_POKEMON
#define P_FAMILY_PONYTA                  P_GEN_1_POKEMON
#define P_FAMILY_SLOWPOKE                P_GEN_1_POKEMON
#define P_FAMILY_MAGNEMITE               P_GEN_1_POKEMON
#define P_FAMILY_FARFETCHD               P_GEN_1_POKEMON
#define P_FAMILY_DODUO                   P_GEN_1_POKEMON
#define P_FAMILY_SEEL                    P_GEN_1_POKEMON
#define P_FAMILY_GRIMER                  P_GEN_1_POKEMON
#define P_FAMILY_SHELLDER                P_GEN_1_POKEMON
#define P_FAMILY_GASTLY                  P_GEN_1_POKEMON
#define P_FAMILY_ONIX                    P_GEN_1_POKEMON
#define P_FAMILY_DROWZEE                 P_GEN_1_POKEMON
#define P_FAMILY_KRABBY                  P_GEN_1_POKEMON
#define P_FAMILY_VOLTORB                 P_GEN_1_POKEMON
#define P_FAMILY_EXEGGCUTE               P_GEN_1_POKEMON
#define P_FAMILY_CUBONE                  P_GEN_1_POKEMON
#define P_FAMILY_HITMONS                 P_GEN_1_POKEMON
#define P_FAMILY_LICKITUNG               P_GEN_1_POKEMON
#define P_FAMILY_KOFFING                 P_GEN_1_POKEMON
#define P_FAMILY_RHYHORN                 P_GEN_1_POKEMON
#define P_FAMILY_CHANSEY                 P_GEN_1_POKEMON
#define P_FAMILY_TANGELA                 P_GEN_1_POKEMON
#define P_FAMILY_KANGASKHAN              P_GEN_1_POKEMON
#define P_FAMILY_HORSEA                  P_GEN_1_POKEMON
#define P_FAMILY_GOLDEEN                 P_GEN_1_POKEMON
#define P_FAMILY_STARYU                  P_GEN_1_POKEMON
#define P_FAMILY_MR_MIME                 P_GEN_1_POKEMON
#define P_FAMILY_SCYTHER                 P_GEN_1_POKEMON
#define P_FAMILY_JYNX                    P_GEN_1_POKEMON
#define P_FAMILY_ELECTABUZZ              P_GEN_1_POKEMON
#define P_FAMILY_MAGMAR                  P_GEN_1_POKEMON
#define P_FAMILY_PINSIR                  P_GEN_1_POKEMON
#define P_FAMILY_TAUROS                  P_GEN_1_POKEMON
#define P_FAMILY_MAGIKARP                P_GEN_1_POKEMON
#define P_FAMILY_LAPRAS                  P_GEN_1_POKEMON
#define P_FAMILY_DITTO                   P_GEN_1_POKEMON
#define P_FAMILY_EEVEE                   P_GEN_1_POKEMON
#define P_FAMILY_PORYGON                 P_GEN_1_POKEMON
#define P_FAMILY_OMANYTE                 P_GEN_1_POKEMON
#define P_FAMILY_KABUTO                  P_GEN_1_POKEMON
#define P_FAMILY_AERODACTYL              P_GEN_1_POKEMON
#define P_FAMILY_SNORLAX                 P_GEN_1_POKEMON
#define P_FAMILY_ARTICUNO                P_GEN_1_POKEMON
#define P_FAMILY_ZAPDOS                  P_GEN_1_POKEMON
#define P_FAMILY_MOLTRES                 P_GEN_1_POKEMON
#define P_FAMILY_DRATINI                 P_GEN_1_POKEMON
#define P_FAMILY_MEWTWO                  P_GEN_1_POKEMON
#define P_FAMILY_MEW                     P_GEN_1_POKEMON

#define P_FAMILY_CHIKORITA               P_GEN_2_POKEMON
#define P_FAMILY_CYNDAQUIL               P_GEN_2_POKEMON
#define P_FAMILY_TOTODILE                P_GEN_2_POKEMON
#define P_FAMILY_SENTRET                 P_GEN_2_POKEMON
#define P_FAMILY_HOOTHOOT                P_GEN_2_POKEMON
#define P_FAMILY_LEDYBA                  P_GEN_2_POKEMON
#define P_FAMILY_SPINARAK                P_GEN_2_POKEMON
#define P_FAMILY_CHINCHOU                P_GEN_2_POKEMON
#define P_FAMILY_TOGEPI                  P_GEN_2_POKEMON
#define P_FAMILY_NATU                    P_GEN_2_POKEMON
#define P_FAMILY_MAREEP                  P_GEN_2_POKEMON
#define P_FAMILY_MARILL                  P_GEN_2_POKEMON
#define P_FAMILY_SUDOWOODO               P_GEN_2_POKEMON
#define P_FAMILY_HOPPIP                  P_GEN_2_POKEMON
#define P_FAMILY_AIPOM                   P_GEN_2_POKEMON
#define P_FAMILY_SUNKERN                 P_GEN_2_POKEMON
#define P_FAMILY_YANMA                   P_GEN_2_POKEMON
#define P_FAMILY_WOOPER                  P_GEN_2_POKEMON
#define P_FAMILY_MURKROW                 P_GEN_2_POKEMON
#define P_FAMILY_MISDREAVUS              P_GEN_2_POKEMON
#define P_FAMILY_UNOWN                   P_GEN_2_POKEMON
#define P_FAMILY_WOBBUFFET               P_GEN_2_POKEMON
#define P_FAMILY_GIRAFARIG               P_GEN_2_POKEMON
#define P_FAMILY_PINECO                  P_GEN_2_POKEMON
#define P_FAMILY_DUNSPARCE               P_GEN_2_POKEMON
#define P_FAMILY_GLIGAR                  P_GEN_2_POKEMON
#define P_FAMILY_SNUBBULL                P_GEN_2_POKEMON
#define P_FAMILY_QWILFISH                P_GEN_2_POKEMON
#define P_FAMILY_SHUCKLE                 P_GEN_2_POKEMON
#define P_FAMILY_HERACROSS               P_GEN_2_POKEMON
#define P_FAMILY_SNEASEL                 P_GEN_2_POKEMON
#define P_FAMILY_TEDDIURSA               P_GEN_2_POKEMON
#define P_FAMILY_SLUGMA                  P_GEN_2_POKEMON
#define P_FAMILY_SWINUB                  P_GEN_2_POKEMON
#define P_FAMILY_CORSOLA                 P_GEN_2_POKEMON
#define P_FAMILY_REMORAID                P_GEN_2_POKEMON
#define P_FAMILY_DELIBIRD                P_GEN_2_POKEMON
#define P_FAMILY_MANTINE                 P_GEN_2_POKEMON
#define P_FAMILY_SKARMORY                P_GEN_2_POKEMON
#define P_FAMILY_HOUNDOUR                P_GEN_2_POKEMON
#define P_FAMILY_PHANPY                  P_GEN_2_POKEMON
#define P_FAMILY_STANTLER                P_GEN_2_POKEMON
#define P_FAMILY_SMEARGLE                P_GEN_2_POKEMON
#define P_FAMILY_MILTANK                 P_GEN_2_POKEMON
#define P_FAMILY_RAIKOU                  P_GEN_2_POKEMON
#define P_FAMILY_ENTEI                   P_GEN_2_POKEMON
#define P_FAMILY_SUICUNE                 P_GEN_2_POKEMON
#define P_FAMILY_LARVITAR                P_GEN_2_POKEMON
#define P_FAMILY_LUGIA                   P_GEN_2_POKEMON
#define P_FAMILY_HO_OH                   P_GEN_2_POKEMON
#define P_FAMILY_CELEBI                  P_GEN_2_POKEMON

#define P_FAMILY_TREECKO                 P_GEN_3_POKEMON
#define P_FAMILY_TORCHIC                 P_GEN_3_POKEMON
#define P_FAMILY_MUDKIP                  P_GEN_3_POKEMON
#define P_FAMILY_POOCHYENA               P_GEN_3_POKEMON
#define P_FAMILY_ZIGZAGOON               P_GEN_3_POKEMON
#define P_FAMILY_WURMPLE                 P_GEN_3_POKEMON
#define P_FAMILY_LOTAD                   P_GEN_3_POKEMON
#define P_FAMILY_SEEDOT                  P_GEN_3_POKEMON
#define P_FAMILY_TAILLOW                 P_GEN_3_POKEMON
#define P_FAMILY_WINGULL                 P_GEN_3_POKEMON
#define P_FAMILY_RALTS                   P_GEN_3_POKEMON
#define P_FAMILY_SURSKIT                 P_GEN_3_POKEMON
#define P_FAMILY_SHROOMISH               P_GEN_3_POKEMON
#define P_FAMILY_SLAKOTH                 P_GEN_3_POKEMON
#define P_FAMILY_NINCADA                 P_GEN_3_POKEMON
#define P_FAMILY_WHISMUR                 P_GEN_3_POKEMON
#define P_FAMILY_MAKUHITA                P_GEN_3_POKEMON
#define P_FAMILY_NOSEPASS                P_GEN_3_POKEMON
#define P_FAMILY_SKITTY                  P_GEN_3_POKEMON
#define P_FAMILY_SABLEYE                 P_GEN_3_POKEMON
#define P_FAMILY_MAWILE                  P_GEN_3_POKEMON
#define P_FAMILY_ARON                    P_GEN_3_POKEMON
#define P_FAMILY_MEDITITE                P_GEN_3_POKEMON
#define P_FAMILY_ELECTRIKE               P_GEN_3_POKEMON
#define P_FAMILY_PLUSLE                  P_GEN_3_POKEMON
#define P_FAMILY_MINUN                   P_GEN_3_POKEMON
#define P_FAMILY_VOLBEAT_ILLUMISE        P_GEN_3_POKEMON
#define P_FAMILY_ROSELIA                 P_GEN_3_POKEMON
#define P_FAMILY_GULPIN                  P_GEN_3_POKEMON
#define P_FAMILY_CARVANHA                P_GEN_3_POKEMON
#define P_FAMILY_WAILMER                 P_GEN_3_POKEMON
#define P_FAMILY_NUMEL                   P_GEN_3_POKEMON
#define P_FAMILY_TORKOAL                 P_GEN_3_POKEMON
#define P_FAMILY_SPOINK                  P_GEN_3_POKEMON
#define P_FAMILY_SPINDA                  P_GEN_3_POKEMON
#define P_FAMILY_TRAPINCH                P_GEN_3_POKEMON
#define P_FAMILY_CACNEA                  P_GEN_3_POKEMON
#define P_FAMILY_SWABLU                  P_GEN_3_POKEMON
#define P_FAMILY_ZANGOOSE                P_GEN_3_POKEMON
#define P_FAMILY_SEVIPER                 P_GEN_3_POKEMON
#define P_FAMILY_LUNATONE                P_GEN_3_POKEMON
#define P_FAMILY_SOLROCK                 P_GEN_3_POKEMON
#define P_FAMILY_BARBOACH                P_GEN_3_POKEMON
#define P_FAMILY_CORPHISH                P_GEN_3_POKEMON
#define P_FAMILY_BALTOY                  P_GEN_3_POKEMON
#define P_FAMILY_LILEEP                  P_GEN_3_POKEMON
#define P_FAMILY_ANORITH                 P_GEN_3_POKEMON
#define P_FAMILY_FEEBAS                  P_GEN_3_POKEMON
#define P_FAMILY_CASTFORM                P_GEN_3_POKEMON
#define P_FAMILY_KECLEON                 P_GEN_3_POKEMON
#define P_FAMILY_SHUPPET                 P_GEN_3_POKEMON
#define P_FAMILY_DUSKULL                 P_GEN_3_POKEMON
#define P_FAMILY_TROPIUS                 P_GEN_3_POKEMON
#define P_FAMILY_CHIMECHO                P_GEN_3_POKEMON
#define P_FAMILY_ABSOL                   P_GEN_3_POKEMON
#define P_FAMILY_SNORUNT                 P_GEN_3_POKEMON
#define P_FAMILY_SPHEAL                  P_GEN_3_POKEMON
#define P_FAMILY_CLAMPERL                P_GEN_3_POKEMON
#define P_FAMILY_RELICANTH               P_GEN_3_POKEMON
#define P_FAMILY_LUVDISC                 P_GEN_3_POKEMON
#define P_FAMILY_BAGON                   P_GEN_3_POKEMON
#define P_FAMILY_BELDUM                  P_GEN_3_POKEMON
#define P_FAMILY_REGIROCK                P_GEN_3_POKEMON
#define P_FAMILY_REGICE                  P_GEN_3_POKEMON
#define P_FAMILY_REGISTEEL               P_GEN_3_POKEMON
#define P_FAMILY_LATIAS                  P_GEN_3_POKEMON
#define P_FAMILY_LATIOS                  P_GEN_3_POKEMON
#define P_FAMILY_KYOGRE                  P_GEN_3_POKEMON
#define P_FAMILY_GROUDON                 P_GEN_3_POKEMON
#define P_FAMILY_RAYQUAZA                P_GEN_3_POKEMON
#define P_FAMILY_JIRACHI                 P_GEN_3_POKEMON
#define P_FAMILY_DEOXYS                  P_GEN_3_POKEMON

#define P_FAMILY_TURTWIG                 P_GEN_4_POKEMON
#define P_FAMILY_CHIMCHAR                P_GEN_4_POKEMON
#define P_FAMILY_PIPLUP                  P_GEN_4_POKEMON
#define P_FAMILY_STARLY                  P_GEN_4_POKEMON
#define P_FAMILY_BIDOOF                  P_GEN_4_POKEMON
#define P_FAMILY_KRICKETOT               P_GEN_4_POKEMON
#define P_FAMILY_SHINX                   P_GEN_4_POKEMON
#define P_FAMILY_CRANIDOS                P_GEN_4_POKEMON
#define P_FAMILY_SHIELDON                P_GEN_4_POKEMON
#define P_FAMILY_BURMY                   P_GEN_4_POKEMON
#define P_FAMILY_COMBEE                  P_GEN_4_POKEMON
#define P_FAMILY_PACHIRISU               P_GEN_4_POKEMON
#define P_FAMILY_BUIZEL                  P_GEN_4_POKEMON
#define P_FAMILY_CHERUBI                 P_GEN_4_POKEMON
#define P_FAMILY_SHELLOS                 P_GEN_4_POKEMON
#define P_FAMILY_DRIFLOON                P_GEN_4_POKEMON
#define P_FAMILY_BUNEARY                 P_GEN_4_POKEMON
#define P_FAMILY_GLAMEOW                 P_GEN_4_POKEMON
#define P_FAMILY_STUNKY                  P_GEN_4_POKEMON
#define P_FAMILY_BRONZOR                 P_GEN_4_POKEMON
#define P_FAMILY_CHATOT                  P_GEN_4_POKEMON
#define P_FAMILY_SPIRITOMB               P_GEN_4_POKEMON
#define P_FAMILY_GIBLE                   P_GEN_4_POKEMON
#define P_FAMILY_RIOLU                   P_GEN_4_POKEMON
#define P_FAMILY_HIPPOPOTAS              P_GEN_4_POKEMON
#define P_FAMILY_SKORUPI                 P_GEN_4_POKEMON
#define P_FAMILY_CROAGUNK                P_GEN_4_POKEMON
#define P_FAMILY_CARNIVINE               P_GEN_4_POKEMON
#define P_FAMILY_FINNEON                 P_GEN_4_POKEMON
#define P_FAMILY_SNOVER                  P_GEN_4_POKEMON
#define P_FAMILY_ROTOM                   P_GEN_4_POKEMON
#define P_FAMILY_UXIE                    P_GEN_4_POKEMON
#define P_FAMILY_MESPRIT                 P_GEN_4_POKEMON
#define P_FAMILY_AZELF                   P_GEN_4_POKEMON
#define P_FAMILY_DIALGA                  P_GEN_4_POKEMON
#define P_FAMILY_PALKIA                  P_GEN_4_POKEMON
#define P_FAMILY_HEATRAN                 P_GEN_4_POKEMON
#define P_FAMILY_REGIGIGAS               P_GEN_4_POKEMON
#define P_FAMILY_GIRATINA                P_GEN_4_POKEMON
#define P_FAMILY_CRESSELIA               P_GEN_4_POKEMON
#define P_FAMILY_MANAPHY                 P_GEN_4_POKEMON
#define P_FAMILY_DARKRAI                 P_GEN_4_POKEMON
#define P_FAMILY_SHAYMIN                 P_GEN_4_POKEMON
#define P_FAMILY_ARCEUS                  P_GEN_4_POKEMON

#define P_FAMILY_VICTINI                 P_GEN_5_POKEMON
#define P_FAMILY_SNIVY                   P_GEN_5_POKEMON
#define P_FAMILY_TEPIG                   P_GEN_5_POKEMON
#define P_FAMILY_OSHAWOTT                P_GEN_5_POKEMON
#define P_FAMILY_PATRAT                  P_GEN_5_POKEMON
#define P_FAMILY_LILLIPUP                P_GEN_5_POKEMON
#define P_FAMILY_PURRLOIN                P_GEN_5_POKEMON
#define P_FAMILY_PANSAGE                 P_GEN_5_POKEMON
#define P_FAMILY_PANSEAR                 P_GEN_5_POKEMON
#define P_FAMILY_PANPOUR                 P_GEN_5_POKEMON
#define P_FAMILY_MUNNA                   P_GEN_5_POKEMON
#define P_FAMILY_PIDOVE                  P_GEN_5_POKEMON
#define P_FAMILY_BLITZLE                 P_GEN_5_POKEMON
#define P_FAMILY_ROGGENROLA              P_GEN_5_POKEMON
#define P_FAMILY_WOOBAT                  P_GEN_5_POKEMON
#define P_FAMILY_DRILBUR                 P_GEN_5_POKEMON
#define P_FAMILY_AUDINO                  P_GEN_5_POKEMON
#define P_FAMILY_TIMBURR                 P_GEN_5_POKEMON
#define P_FAMILY_TYMPOLE                 P_GEN_5_POKEMON
#define P_FAMILY_THROH                   P_GEN_5_POKEMON
#define P_FAMILY_SAWK                    P_GEN_5_POKEMON
#define P_FAMILY_SEWADDLE                P_GEN_5_POKEMON
#define P_FAMILY_VENIPEDE                P_GEN_5_POKEMON
#define P_FAMILY_COTTONEE                P_GEN_5_POKEMON
#define P_FAMILY_PETILIL                 P_GEN_5_POKEMON
#define P_FAMILY_BASCULIN                P_GEN_5_POKEMON
#define P_FAMILY_SANDILE                 P_GEN_5_POKEMON
#define P_FAMILY_DARUMAKA                P_GEN_5_POKEMON
#define P_FAMILY_MARACTUS                P_GEN_5_POKEMON
#define P_FAMILY_DWEBBLE                 P_GEN_5_POKEMON
#define P_FAMILY_SCRAGGY                 P_GEN_5_POKEMON
#define P_FAMILY_SIGILYPH                P_GEN_5_POKEMON
#define P_FAMILY_YAMASK                  P_GEN_5_POKEMON
#define P_FAMILY_TIRTOUGA                P_GEN_5_POKEMON
#define P_FAMILY_ARCHEN                  P_GEN_5_POKEMON
#define P_FAMILY_TRUBBISH                P_GEN_5_POKEMON
#define P_FAMILY_ZORUA                   P_GEN_5_POKEMON
#define P_FAMILY_MINCCINO                P_GEN_5_POKEMON
#define P_FAMILY_GOTHITA                 P_GEN_5_POKEMON
#define P_FAMILY_SOLOSIS                 P_GEN_5_POKEMON
#define P_FAMILY_DUCKLETT                P_GEN_5_POKEMON
#define P_FAMILY_VANILLITE               P_GEN_5_POKEMON
#define P_FAMILY_DEERLING                P_GEN_5_POKEMON
#define P_FAMILY_EMOLGA                  P_GEN_5_POKEMON
#define P_FAMILY_KARRABLAST              P_GEN_5_POKEMON
#define P_FAMILY_FOONGUS                 P_GEN_5_POKEMON
#define P_FAMILY_FRILLISH                P_GEN_5_POKEMON
#define P_FAMILY_ALOMOMOLA               P_GEN_5_POKEMON
#define P_FAMILY_JOLTIK                  P_GEN_5_POKEMON
#define P_FAMILY_FERROSEED               P_GEN_5_POKEMON
#define P_FAMILY_KLINK                   P_GEN_5_POKEMON
#define P_FAMILY_TYNAMO                  P_GEN_5_POKEMON
#define P_FAMILY_ELGYEM                  P_GEN_5_POKEMON
#define P_FAMILY_LITWICK                 P_GEN_5_POKEMON
#define P_FAMILY_AXEW                    P_GEN_5_POKEMON
#define P_FAMILY_CUBCHOO                 P_GEN_5_POKEMON
#define P_FAMILY_CRYOGONAL               P_GEN_5_POKEMON
#define P_FAMILY_SHELMET                 P_GEN_5_POKEMON
#define P_FAMILY_STUNFISK                P_GEN_5_POKEMON
#define P_FAMILY_MIENFOO                 P_GEN_5_POKEMON
#define P_FAMILY_DRUDDIGON               P_GEN_5_POKEMON
#define P_FAMILY_GOLETT                  P_GEN_5_POKEMON
#define P_FAMILY_PAWNIARD                P_GEN_5_POKEMON
#define P_FAMILY_BOUFFALANT              P_GEN_5_POKEMON
#define P_FAMILY_RUFFLET                 P_GEN_5_POKEMON
#define P_FAMILY_VULLABY                 P_GEN_5_POKEMON
#define P_FAMILY_HEATMOR                 P_GEN_5_POKEMON
#define P_FAMILY_DURANT                  P_GEN_5_POKEMON
#define P_FAMILY_DEINO                   P_GEN_5_POKEMON
#define P_FAMILY_LARVESTA                P_GEN_5_POKEMON
#define P_FAMILY_COBALION                P_GEN_5_POKEMON
#define P_FAMILY_TERRAKION               P_GEN_5_POKEMON
#define P_FAMILY_VIRIZION                P_GEN_5_POKEMON
#define P_FAMILY_TORNADUS                P_GEN_5_POKEMON
#define P_FAMILY_THUNDURUS               P_GEN_5_POKEMON
#define P_FAMILY_RESHIRAM                P_GEN_5_POKEMON
#define P_FAMILY_ZEKROM                  P_GEN_5_POKEMON
#define P_FAMILY_LANDORUS                P_GEN_5_POKEMON
#define P_FAMILY_KYUREM                  P_GEN_5_POKEMON
#define P_FAMILY_KELDEO                  P_GEN_5_POKEMON
#define P_FAMILY_MELOETTA                P_GEN_5_POKEMON
#define P_FAMILY_GENESECT                P_GEN_5_POKEMON

#define P_FAMILY_CHESPIN                 P_GEN_6_POKEMON
#define P_FAMILY_FENNEKIN                P_GEN_6_POKEMON
#define P_FAMILY_FROAKIE                 P_GEN_6_POKEMON
#define P_FAMILY_BUNNELBY                P_GEN_6_POKEMON
#define P_FAMILY_FLETCHLING              P_GEN_6_POKEMON
#define P_FAMILY_SCATTERBUG              P_GEN_6_POKEMON
#define P_FAMILY_LITLEO                  P_GEN_6_POKEMON
#define P_FAMILY_FLABEBE                 P_GEN_6_POKEMON
#define P_FAMILY_SKIDDO                  P_GEN_6_POKEMON
#define P_FAMILY_PANCHAM                 P_GEN_6_POKEMON
#define P_FAMILY_FURFROU                 P_GEN_6_POKEMON
#define P_FAMILY_ESPURR                  P_GEN_6_POKEMON
#define P_FAMILY_HONEDGE                 P_GEN_6_POKEMON
#define P_FAMILY_SPRITZEE                P_GEN_6_POKEMON
#define P_FAMILY_SWIRLIX                 P_GEN_6_POKEMON
#define P_FAMILY_INKAY                   P_GEN_6_POKEMON
#define P_FAMILY_BINACLE                 P_GEN_6_POKEMON
#define P_FAMILY_SKRELP                  P_GEN_6_POKEMON
#define P_FAMILY_CLAUNCHER               P_GEN_6_POKEMON
#define P_FAMILY_HELIOPTILE              P_GEN_6_POKEMON
#define P_FAMILY_TYRUNT                  P_GEN_6_POKEMON
#define P_FAMILY_AMAURA                  P_GEN_6_POKEMON
#define P_FAMILY_HAWLUCHA                P_GEN_6_POKEMON
#define P_FAMILY_DEDENNE                 P_GEN_6_POKEMON
#define P_FAMILY_CARBINK                 P_GEN_6_POKEMON
#define P_FAMILY_GOOMY                   P_GEN_6_POKEMON
#define P_FAMILY_KLEFKI                  P_GEN_6_POKEMON
#define P_FAMILY_PHANTUMP                P_GEN_6_POKEMON
#define P_FAMILY_PUMPKABOO               P_GEN_6_POKEMON
#define P_FAMILY_BERGMITE                P_GEN_6_POKEMON
#define P_FAMILY_NOIBAT                  P_GEN_6_POKEMON
#define P_FAMILY_XERNEAS                 P_GEN_6_POKEMON
#define P_FAMILY_YVELTAL                 P_GEN_6_POKEMON
#define P_FAMILY_ZYGARDE                 P_GEN_6_POKEMON
#define P_FAMILY_DIANCIE                 P_GEN_6_POKEMON
#define P_FAMILY_HOOPA                   P_GEN_6_POKEMON
#define P_FAMILY_VOLCANION               P_GEN_6_POKEMON

#define P_FAMILY_ROWLET                  P_GEN_7_POKEMON
#define P_FAMILY_LITTEN                  P_GEN_7_POKEMON
#define P_FAMILY_POPPLIO                 P_GEN_7_POKEMON
#define P_FAMILY_PIKIPEK                 P_GEN_7_POKEMON
#define P_FAMILY_YUNGOOS                 P_GEN_7_POKEMON
#define P_FAMILY_GRUBBIN                 P_GEN_7_POKEMON
#define P_FAMILY_CRABRAWLER              P_GEN_7_POKEMON
#define P_FAMILY_ORICORIO                P_GEN_7_POKEMON
#define P_FAMILY_CUTIEFLY                P_GEN_7_POKEMON
#define P_FAMILY_ROCKRUFF                P_GEN_7_POKEMON
#define P_FAMILY_WISHIWASHI              P_GEN_7_POKEMON
#define P_FAMILY_MAREANIE                P_GEN_7_POKEMON
#define P_FAMILY_MUDBRAY                 P_GEN_7_POKEMON
#define P_FAMILY_DEWPIDER                P_GEN_7_POKEMON
#define P_FAMILY_FOMANTIS                P_GEN_7_POKEMON
#define P_FAMILY_MORELULL                P_GEN_7_POKEMON
#define P_FAMILY_SALANDIT                P_GEN_7_POKEMON
#define P_FAMILY_STUFFUL                 P_GEN_7_POKEMON
#define P_FAMILY_BOUNSWEET               P_GEN_7_POKEMON
#define P_FAMILY_COMFEY                  P_GEN_7_POKEMON
#define P_FAMILY_ORANGURU                P_GEN_7_POKEMON
#define P_FAMILY_PASSIMIAN               P_GEN_7_POKEMON
#define P_FAMILY_WIMPOD                  P_GEN_7_POKEMON
#define P_FAMILY_SANDYGAST               P_GEN_7_POKEMON
#define P_FAMILY_PYUKUMUKU               P_GEN_7_POKEMON
#define P_FAMILY_TYPE_NULL               P_GEN_7_POKEMON
#define P_FAMILY_MINIOR                  P_GEN_7_POKEMON
#define P_FAMILY_KOMALA                  P_GEN_7_POKEMON
#define P_FAMILY_TURTONATOR              P_GEN_7_POKEMON
#define P_FAMILY_TOGEDEMARU              P_GEN_7_POKEMON
#define P_FAMILY_MIMIKYU                 P_GEN_7_POKEMON
#define P_FAMILY_BRUXISH                 P_GEN_7_POKEMON
#define P_FAMILY_DRAMPA                  P_GEN_7_POKEMON
#define P_FAMILY_DHELMISE                P_GEN_7_POKEMON
#define P_FAMILY_JANGMO_O                P_GEN_7_POKEMON
#define P_FAMILY_TAPU_KOKO               P_GEN_7_POKEMON
#define P_FAMILY_TAPU_LELE               P_GEN_7_POKEMON
#define P_FAMILY_TAPU_BULU               P_GEN_7_POKEMON
#define P_FAMILY_TAPU_FINI               P_GEN_7_POKEMON
#define P_FAMILY_COSMOG                  P_GEN_7_POKEMON
#define P_FAMILY_NIHILEGO                P_GEN_7_POKEMON
#define P_FAMILY_BUZZWOLE                P_GEN_7_POKEMON
#define P_FAMILY_PHEROMOSA               P_GEN_7_POKEMON
#define P_FAMILY_XURKITREE               P_GEN_7_POKEMON
#define P_FAMILY_CELESTEELA              P_GEN_7_POKEMON
#define P_FAMILY_KARTANA                 P_GEN_7_POKEMON
#define P_FAMILY_GUZZLORD                P_GEN_7_POKEMON
#define P_FAMILY_NECROZMA                P_GEN_7_POKEMON
#define P_FAMILY_MAGEARNA                P_GEN_7_POKEMON
#define P_FAMILY_MARSHADOW               P_GEN_7_POKEMON
#define P_FAMILY_POIPOLE                 P_GEN_7_POKEMON
#define P_FAMILY_STAKATAKA               P_GEN_7_POKEMON
#define P_FAMILY_BLACEPHALON             P_GEN_7_POKEMON
#define P_FAMILY_ZERAORA                 P_GEN_7_POKEMON
#define P_FAMILY_MELTAN                  P_GEN_7_POKEMON

#define P_FAMILY_GROOKEY                 P_GEN_8_POKEMON
#define P_FAMILY_SCORBUNNY               P_GEN_8_POKEMON
#define P_FAMILY_SOBBLE                  P_GEN_8_POKEMON
#define P_FAMILY_SKWOVET                 P_GEN_8_POKEMON
#define P_FAMILY_ROOKIDEE                P_GEN_8_POKEMON
#define P_FAMILY_BLIPBUG                 P_GEN_8_POKEMON
#define P_FAMILY_NICKIT                  P_GEN_8_POKEMON
#define P_FAMILY_GOSSIFLEUR              P_GEN_8_POKEMON
#define P_FAMILY_WOOLOO                  P_GEN_8_POKEMON
#define P_FAMILY_CHEWTLE                 P_GEN_8_POKEMON
#define P_FAMILY_YAMPER                  P_GEN_8_POKEMON
#define P_FAMILY_ROLYCOLY                P_GEN_8_POKEMON
#define P_FAMILY_APPLIN                  P_GEN_8_POKEMON
#define P_FAMILY_SILICOBRA               P_GEN_8_POKEMON
#define P_FAMILY_CRAMORANT               P_GEN_8_POKEMON
#define P_FAMILY_ARROKUDA                P_GEN_8_POKEMON
#define P_FAMILY_TOXEL                   P_GEN_8_POKEMON
#define P_FAMILY_SIZZLIPEDE              P_GEN_8_POKEMON
#define P_FAMILY_CLOBBOPUS               P_GEN_8_POKEMON
#define P_FAMILY_SINISTEA                P_GEN_8_POKEMON
#define P_FAMILY_HATENNA                 P_GEN_8_POKEMON
#define P_FAMILY_IMPIDIMP                P_GEN_8_POKEMON
#define P_FAMILY_MILCERY                 P_GEN_8_POKEMON
#define P_FAMILY_FALINKS                 P_GEN_8_POKEMON
#define P_FAMILY_PINCURCHIN              P_GEN_8_POKEMON
#define P_FAMILY_SNOM                    P_GEN_8_POKEMON
#define P_FAMILY_STONJOURNER             P_GEN_8_POKEMON
#define P_FAMILY_EISCUE                  P_GEN_8_POKEMON
#define P_FAMILY_INDEEDEE                P_GEN_8_POKEMON
#define P_FAMILY_MORPEKO                 P_GEN_8_POKEMON
#define P_FAMILY_CUFANT                  P_GEN_8_POKEMON
#define P_FAMILY_DRACOZOLT               P_GEN_8_POKEMON
#define P_FAMILY_ARCTOZOLT               P_GEN_8_POKEMON
#define P_FAMILY_DRACOVISH               P_GEN_8_POKEMON
#define P_FAMILY_ARCTOVISH               P_GEN_8_POKEMON
#define P_FAMILY_DURALUDON               P_GEN_8_POKEMON
#define P_FAMILY_DREEPY                  P_GEN_8_POKEMON
#define P_FAMILY_ZACIAN                  P_GEN_8_POKEMON
#define P_FAMILY_ZAMAZENTA               P_GEN_8_POKEMON
#define P_FAMILY_ETERNATUS               P_GEN_8_POKEMON
#define P_FAMILY_KUBFU                   P_GEN_8_POKEMON
#define P_FAMILY_ZARUDE                  P_GEN_8_POKEMON
#define P_FAMILY_REGIELEKI               P_GEN_8_POKEMON
#define P_FAMILY_REGIDRAGO               P_GEN_8_POKEMON
#define P_FAMILY_GLASTRIER               P_GEN_8_POKEMON
#define P_FAMILY_SPECTRIER               P_GEN_8_POKEMON
#define P_FAMILY_CALYREX                 P_GEN_8_POKEMON
#define P_FAMILY_ENAMORUS                P_GEN_8_POKEMON

#define P_FAMILY_SPRIGATITO              P_GEN_9_POKEMON
#define P_FAMILY_FUECOCO                 P_GEN_9_POKEMON
#define P_FAMILY_QUAXLY                  P_GEN_9_POKEMON
#define P_FAMILY_LECHONK                 P_GEN_9_POKEMON
#define P_FAMILY_TAROUNTULA              P_GEN_9_POKEMON
#define P_FAMILY_NYMBLE                  P_GEN_9_POKEMON
#define P_FAMILY_PAWMI                   P_GEN_9_POKEMON
#define P_FAMILY_TANDEMAUS               P_GEN_9_POKEMON
#define P_FAMILY_FIDOUGH                 P_GEN_9_POKEMON
#define P_FAMILY_SMOLIV                  P_GEN_9_POKEMON
#define P_FAMILY_SQUAWKABILLY            P_GEN_9_POKEMON
#define P_FAMILY_NACLI                   P_GEN_9_POKEMON
#define P_FAMILY_CHARCADET               P_GEN_9_POKEMON
#define P_FAMILY_TADBULB                 P_GEN_9_POKEMON
#define P_FAMILY_WATTREL                 P_GEN_9_POKEMON
#define P_FAMILY_MASCHIFF                P_GEN_9_POKEMON
#define P_FAMILY_SHROODLE                P_GEN_9_POKEMON
#define P_FAMILY_BRAMBLIN                P_GEN_9_POKEMON
#define P_FAMILY_TOEDSCOOL               P_GEN_9_POKEMON
#define P_FAMILY_KLAWF                   P_GEN_9_POKEMON
#define P_FAMILY_CAPSAKID                P_GEN_9_POKEMON
#define P_FAMILY_RELLOR                  P_GEN_9_POKEMON
#define P_FAMILY_FLITTLE                 P_GEN_9_POKEMON
#define P_FAMILY_TINKATINK               P_GEN_9_POKEMON
#define P_FAMILY_WIGLETT                 P_GEN_9_POKEMON
#define P_FAMILY_BOMBIRDIER              P_GEN_9_POKEMON
#define P_FAMILY_FINIZEN                 P_GEN_9_POKEMON
#define P_FAMILY_VAROOM                  P_GEN_9_POKEMON
#define P_FAMILY_CYCLIZAR                P_GEN_9_POKEMON
#define P_FAMILY_ORTHWORM                P_GEN_9_POKEMON
#define P_FAMILY_GLIMMET                 P_GEN_9_POKEMON
#define P_FAMILY_GREAVARD                P_GEN_9_POKEMON
#define P_FAMILY_FLAMIGO                 P_GEN_9_POKEMON
#define P_FAMILY_CETODDLE                P_GEN_9_POKEMON
#define P_FAMILY_VELUZA                  P_GEN_9_POKEMON
#define P_FAMILY_DONDOZO                 P_GEN_9_POKEMON
#define P_FAMILY_TATSUGIRI               P_GEN_9_POKEMON
#define P_FAMILY_GREAT_TUSK              P_GEN_9_POKEMON
#define P_FAMILY_SCREAM_TAIL             P_GEN_9_POKEMON
#define P_FAMILY_BRUTE_BONNET            P_GEN_9_POKEMON
#define P_FAMILY_FLUTTER_MANE            P_GEN_9_POKEMON
#define P_FAMILY_SLITHER_WING            P_GEN_9_POKEMON
#define P_FAMILY_SANDY_SHOCKS            P_GEN_9_POKEMON
#define P_FAMILY_IRON_TREADS             P_GEN_9_POKEMON
#define P_FAMILY_IRON_BUNDLE             P_GEN_9_POKEMON
#define P_FAMILY_IRON_HANDS              P_GEN_9_POKEMON
#define P_FAMILY_IRON_JUGULIS            P_GEN_9_POKEMON
#define P_FAMILY_IRON_MOTH               P_GEN_9_POKEMON
#define P_FAMILY_IRON_THORNS             P_GEN_9_POKEMON
#define P_FAMILY_FRIGIBAX                P_GEN_9_POKEMON
#define P_FAMILY_GIMMIGHOUL              P_GEN_9_POKEMON
#define P_FAMILY_WO_CHIEN                P_GEN_9_POKEMON
#define P_FAMILY_CHIEN_PAO               P_GEN_9_POKEMON
#define P_FAMILY_TING_LU                 P_GEN_9_POKEMON
#define P_FAMILY_CHI_YU                  P_GEN_9_POKEMON
#define P_FAMILY_ROARING_MOON            P_GEN_9_POKEMON
#define P_FAMILY_IRON_VALIANT            P_GEN_9_POKEMON
#define P_FAMILY_KORAIDON                P_GEN_9_POKEMON
#define P_FAMILY_MIRAIDON                P_GEN_9_POKEMON
#define P_FAMILY_WALKING_WAKE            P_GEN_9_POKEMON
#define P_FAMILY_IRON_LEAVES             P_GEN_9_POKEMON
#define P_FAMILY_POLTCHAGEIST            P_GEN_9_POKEMON
#define P_FAMILY_SINISTCHA               P_GEN_9_POKEMON
#define P_FAMILY_OKIDOGI                 P_GEN_9_POKEMON
#define P_FAMILY_MUNKIDORI               P_GEN_9_POKEMON
#define P_FAMILY_FEZANDIPITI             P_GEN_9_POKEMON
#define P_FAMILY_OGERPON                 P_GEN_9_POKEMON
#define P_FAMILY_GOUGING_FIRE            P_GEN_9_POKEMON
#define P_FAMILY_RAGING_BOLT             P_GEN_9_POKEMON
#define P_FAMILY_IRON_BOULDER            P_GEN_9_POKEMON
#define P_FAMILY_IRON_CROWN              P_GEN_9_POKEMON
#define P_FAMILY_TERAPAGOS               P_GEN_9_POKEMON
#define P_FAMILY_PECHARUNT               P_GEN_9_POKEMON

#define P_FAMILY_MOE_BULBASAUR TRUE
#define P_FAMILY_MOE_IVYSAUR TRUE
#define P_FAMILY_MOE_VENUSAUR TRUE
#define P_FAMILY_MOE_CHARMANDER TRUE
#define P_FAMILY_MOE_CHARMELEON TRUE
#define P_FAMILY_MOE_CHARIZARD TRUE
#define P_FAMILY_MOE_SQUIRTLE TRUE
#define P_FAMILY_MOE_WARTORTLE TRUE
#define P_FAMILY_MOE_BLASTOISE TRUE
#define P_FAMILY_MOE_CATERPIE TRUE
#define P_FAMILY_MOE_METAPOD TRUE
#define P_FAMILY_MOE_BUTTERFREE TRUE
#define P_FAMILY_MOE_WEEDLE TRUE
#define P_FAMILY_MOE_KAKUNA TRUE
#define P_FAMILY_MOE_BEEDRILL TRUE
#define P_FAMILY_MOE_PIDGEY TRUE
#define P_FAMILY_MOE_PIDGEOTTO TRUE
#define P_FAMILY_MOE_PIDGEOT TRUE
#define P_FAMILY_MOE_RATTATA TRUE
#define P_FAMILY_MOE_RATICATE TRUE
#define P_FAMILY_MOE_SPEAROW TRUE
#define P_FAMILY_MOE_FEAROW TRUE
#define P_FAMILY_MOE_EKANS TRUE
#define P_FAMILY_MOE_ARBOK TRUE
#define P_FAMILY_MOE_PIKACHU TRUE
#define P_FAMILY_MOE_RAICHU TRUE
#define P_FAMILY_MOE_SANDSHREW TRUE
#define P_FAMILY_MOE_SANDSLASH TRUE
#define P_FAMILY_MOE_NIDORAN_F TRUE
#define P_FAMILY_MOE_NIDORINA TRUE
#define P_FAMILY_MOE_NIDOQUEEN TRUE
#define P_FAMILY_MOE_NIDORAN_M TRUE
#define P_FAMILY_MOE_NIDORINO TRUE
#define P_FAMILY_MOE_NIDOKING TRUE
#define P_FAMILY_MOE_CLEFAIRY TRUE
#define P_FAMILY_MOE_CLEFABLE TRUE
#define P_FAMILY_MOE_VULPIX TRUE
#define P_FAMILY_MOE_NINETALES TRUE
#define P_FAMILY_MOE_JIGGLYPUFF TRUE
#define P_FAMILY_MOE_WIGGLYTUFF TRUE
#define P_FAMILY_MOE_ZUBAT TRUE
#define P_FAMILY_MOE_GOLBAT TRUE
#define P_FAMILY_MOE_ODDISH TRUE
#define P_FAMILY_MOE_GLOOM TRUE
#define P_FAMILY_MOE_VILEPLUME TRUE
#define P_FAMILY_MOE_PARAS TRUE
#define P_FAMILY_MOE_PARASECT TRUE
#define P_FAMILY_MOE_VENONAT TRUE
#define P_FAMILY_MOE_VENOMOTH TRUE
#define P_FAMILY_MOE_DIGLETT TRUE
#define P_FAMILY_MOE_DUGTRIO TRUE
#define P_FAMILY_MOE_MEOWTH TRUE
#define P_FAMILY_MOE_PERSIAN TRUE
#define P_FAMILY_MOE_PSYDUCK TRUE
#define P_FAMILY_MOE_GOLDUCK TRUE
#define P_FAMILY_MOE_MANKEY TRUE
#define P_FAMILY_MOE_PRIMEAPE TRUE
#define P_FAMILY_MOE_GROWLITHE TRUE
#define P_FAMILY_MOE_ARCANINE TRUE
#define P_FAMILY_MOE_POLIWAG TRUE
#define P_FAMILY_MOE_POLIWHIRL TRUE
#define P_FAMILY_MOE_POLIWRATH TRUE
#define P_FAMILY_MOE_ABRA TRUE
#define P_FAMILY_MOE_KADABRA TRUE
#define P_FAMILY_MOE_ALAKAZAM TRUE
#define P_FAMILY_MOE_MACHOP TRUE
#define P_FAMILY_MOE_MACHOKE TRUE
#define P_FAMILY_MOE_MACHAMP TRUE
#define P_FAMILY_MOE_BELLSPROUT TRUE
#define P_FAMILY_MOE_WEEPINBELL TRUE
#define P_FAMILY_MOE_VICTREEBEL TRUE
#define P_FAMILY_MOE_TENTACOOL TRUE
#define P_FAMILY_MOE_TENTACRUEL TRUE
#define P_FAMILY_MOE_GEODUDE TRUE
#define P_FAMILY_MOE_GRAVELER TRUE
#define P_FAMILY_MOE_GOLEM TRUE
#define P_FAMILY_MOE_PONYTA TRUE
#define P_FAMILY_MOE_RAPIDASH TRUE
#define P_FAMILY_MOE_SLOWPOKE TRUE
#define P_FAMILY_MOE_SLOWBRO TRUE
#define P_FAMILY_MOE_MAGNEMITE TRUE
#define P_FAMILY_MOE_MAGNETON TRUE
#define P_FAMILY_MOE_FARFETCHD TRUE
#define P_FAMILY_MOE_DODUO TRUE
#define P_FAMILY_MOE_DODRIO TRUE
#define P_FAMILY_MOE_SEEL TRUE
#define P_FAMILY_MOE_DEWGONG TRUE
#define P_FAMILY_MOE_GRIMER TRUE
#define P_FAMILY_MOE_MUK TRUE
#define P_FAMILY_MOE_SHELLDER TRUE
#define P_FAMILY_MOE_CLOYSTER TRUE
#define P_FAMILY_MOE_GASTLY TRUE
#define P_FAMILY_MOE_HAUNTER TRUE
#define P_FAMILY_MOE_GENGAR TRUE
#define P_FAMILY_MOE_ONIX TRUE
#define P_FAMILY_MOE_DROWZEE TRUE
#define P_FAMILY_MOE_HYPNO TRUE
#define P_FAMILY_MOE_KRABBY TRUE
#define P_FAMILY_MOE_KINGLER TRUE
#define P_FAMILY_MOE_VOLTORB TRUE
#define P_FAMILY_MOE_ELECTRODE TRUE
#define P_FAMILY_MOE_EXEGGCUTE TRUE
#define P_FAMILY_MOE_EXEGGUTOR TRUE
#define P_FAMILY_MOE_CUBONE TRUE
#define P_FAMILY_MOE_MAROWAK TRUE
#define P_FAMILY_MOE_HITMONLEE TRUE
#define P_FAMILY_MOE_HITMONCHAN TRUE
#define P_FAMILY_MOE_LICKITUNG TRUE
#define P_FAMILY_MOE_KOFFING TRUE
#define P_FAMILY_MOE_WEEZING TRUE
#define P_FAMILY_MOE_RHYHORN TRUE
#define P_FAMILY_MOE_RHYDON TRUE
#define P_FAMILY_MOE_CHANSEY TRUE
#define P_FAMILY_MOE_TANGELA TRUE
#define P_FAMILY_MOE_KANGASKHAN TRUE
#define P_FAMILY_MOE_HORSEA TRUE
#define P_FAMILY_MOE_SEADRA TRUE
#define P_FAMILY_MOE_GOLDEEN TRUE
#define P_FAMILY_MOE_SEAKING TRUE
#define P_FAMILY_MOE_STARYU TRUE
#define P_FAMILY_MOE_STARMIE TRUE
#define P_FAMILY_MOE_MR_MIME TRUE
#define P_FAMILY_MOE_SCYTHER TRUE
#define P_FAMILY_MOE_JYNX TRUE
#define P_FAMILY_MOE_ELECTABUZZ TRUE
#define P_FAMILY_MOE_MAGMAR TRUE
#define P_FAMILY_MOE_PINSIR TRUE
#define P_FAMILY_MOE_TAUROS TRUE
#define P_FAMILY_MOE_MAGIKARP TRUE
#define P_FAMILY_MOE_GYARADOS TRUE
#define P_FAMILY_MOE_LAPRAS TRUE
#define P_FAMILY_MOE_DITTO TRUE
#define P_FAMILY_MOE_EEVEE TRUE
#define P_FAMILY_MOE_VAPOREON TRUE
#define P_FAMILY_MOE_JOLTEON TRUE
#define P_FAMILY_MOE_FLAREON TRUE
#define P_FAMILY_MOE_PORYGON TRUE
#define P_FAMILY_MOE_OMANYTE TRUE
#define P_FAMILY_MOE_OMASTAR TRUE
#define P_FAMILY_MOE_KABUTO TRUE
#define P_FAMILY_MOE_KABUTOPS TRUE
#define P_FAMILY_MOE_AERODACTYL TRUE
#define P_FAMILY_MOE_SNORLAX TRUE
#define P_FAMILY_MOE_ARTICUNO TRUE
#define P_FAMILY_MOE_ZAPDOS TRUE
#define P_FAMILY_MOE_MOLTRES TRUE
#define P_FAMILY_MOE_DRATINI TRUE
#define P_FAMILY_MOE_DRAGONAIR TRUE
#define P_FAMILY_MOE_DRAGONITE TRUE
#define P_FAMILY_MOE_MEWTWO TRUE
#define P_FAMILY_MOE_MEW TRUE
#define P_FAMILY_MOE_CHIKORITA TRUE
#define P_FAMILY_MOE_BAYLEEF TRUE
#define P_FAMILY_MOE_MEGANIUM TRUE
#define P_FAMILY_MOE_CYNDAQUIL TRUE
#define P_FAMILY_MOE_QUILAVA TRUE
#define P_FAMILY_MOE_TYPHLOSION TRUE
#define P_FAMILY_MOE_TOTODILE TRUE
#define P_FAMILY_MOE_CROCONAW TRUE
#define P_FAMILY_MOE_FERALIGATR TRUE
#define P_FAMILY_MOE_SENTRET TRUE
#define P_FAMILY_MOE_FURRET TRUE
#define P_FAMILY_MOE_HOOTHOOT TRUE
#define P_FAMILY_MOE_NOCTOWL TRUE
#define P_FAMILY_MOE_LEDYBA TRUE
#define P_FAMILY_MOE_LEDIAN TRUE
#define P_FAMILY_MOE_SPINARAK TRUE
#define P_FAMILY_MOE_ARIADOS TRUE
#define P_FAMILY_MOE_CROBAT TRUE
#define P_FAMILY_MOE_CHINCHOU TRUE
#define P_FAMILY_MOE_LANTURN TRUE
#define P_FAMILY_MOE_PICHU TRUE
#define P_FAMILY_MOE_CLEFFA TRUE
#define P_FAMILY_MOE_IGGLYBUFF TRUE
#define P_FAMILY_MOE_TOGEPI TRUE
#define P_FAMILY_MOE_TOGETIC TRUE
#define P_FAMILY_MOE_NATU TRUE
#define P_FAMILY_MOE_XATU TRUE
#define P_FAMILY_MOE_MAREEP TRUE
#define P_FAMILY_MOE_FLAAFFY TRUE
#define P_FAMILY_MOE_AMPHAROS TRUE
#define P_FAMILY_MOE_BELLOSSOM TRUE
#define P_FAMILY_MOE_MARILL TRUE
#define P_FAMILY_MOE_AZUMARILL TRUE
#define P_FAMILY_MOE_SUDOWOODO TRUE
#define P_FAMILY_MOE_POLITOED TRUE
#define P_FAMILY_MOE_HOPPIP TRUE
#define P_FAMILY_MOE_SKIPLOOM TRUE
#define P_FAMILY_MOE_JUMPLUFF TRUE
#define P_FAMILY_MOE_AIPOM TRUE
#define P_FAMILY_MOE_SUNKERN TRUE
#define P_FAMILY_MOE_SUNFLORA TRUE
#define P_FAMILY_MOE_YANMA TRUE
#define P_FAMILY_MOE_WOOPER TRUE
#define P_FAMILY_MOE_QUAGSIRE TRUE
#define P_FAMILY_MOE_ESPEON TRUE
#define P_FAMILY_MOE_UMBREON TRUE
#define P_FAMILY_MOE_MURKROW TRUE
#define P_FAMILY_MOE_SLOWKING TRUE
#define P_FAMILY_MOE_MISDREAVUS TRUE
#define P_FAMILY_MOE_UNOWN TRUE
#define P_FAMILY_MOE_WOBBUFFET TRUE
#define P_FAMILY_MOE_GIRAFARIG TRUE
#define P_FAMILY_MOE_PINECO TRUE
#define P_FAMILY_MOE_FORRETRESS TRUE
#define P_FAMILY_MOE_DUNSPARCE TRUE
#define P_FAMILY_MOE_GLIGAR TRUE
#define P_FAMILY_MOE_STEELIX TRUE
#define P_FAMILY_MOE_SNUBBULL TRUE
#define P_FAMILY_MOE_GRANBULL TRUE
#define P_FAMILY_MOE_QWILFISH TRUE
#define P_FAMILY_MOE_SCIZOR TRUE
#define P_FAMILY_MOE_SHUCKLE TRUE
#define P_FAMILY_MOE_HERACROSS TRUE
#define P_FAMILY_MOE_SNEASEL TRUE
#define P_FAMILY_MOE_TEDDIURSA TRUE
#define P_FAMILY_MOE_URSARING TRUE
#define P_FAMILY_MOE_SLUGMA TRUE
#define P_FAMILY_MOE_MAGCARGO TRUE
#define P_FAMILY_MOE_SWINUB TRUE
#define P_FAMILY_MOE_PILOSWINE TRUE
#define P_FAMILY_MOE_CORSOLA TRUE
#define P_FAMILY_MOE_REMORAID TRUE
#define P_FAMILY_MOE_OCTILLERY TRUE
#define P_FAMILY_MOE_DELIBIRD TRUE
#define P_FAMILY_MOE_MANTINE TRUE
#define P_FAMILY_MOE_SKARMORY TRUE
#define P_FAMILY_MOE_HOUNDOUR TRUE
#define P_FAMILY_MOE_HOUNDOOM TRUE
#define P_FAMILY_MOE_KINGDRA TRUE
#define P_FAMILY_MOE_PHANPY TRUE
#define P_FAMILY_MOE_DONPHAN TRUE
#define P_FAMILY_MOE_PORYGON2 TRUE
#define P_FAMILY_MOE_STANTLER TRUE
#define P_FAMILY_MOE_SMEARGLE TRUE
#define P_FAMILY_MOE_TYROGUE TRUE
#define P_FAMILY_MOE_HITMONTOP TRUE
#define P_FAMILY_MOE_SMOOCHUM TRUE
#define P_FAMILY_MOE_ELEKID TRUE
#define P_FAMILY_MOE_MAGBY TRUE
#define P_FAMILY_MOE_MILTANK TRUE
#define P_FAMILY_MOE_BLISSEY TRUE
#define P_FAMILY_MOE_RAIKOU TRUE
#define P_FAMILY_MOE_ENTEI TRUE
#define P_FAMILY_MOE_SUICUNE TRUE
#define P_FAMILY_MOE_LARVITAR TRUE
#define P_FAMILY_MOE_PUPITAR TRUE
#define P_FAMILY_MOE_TYRANITAR TRUE
#define P_FAMILY_MOE_LUGIA TRUE
#define P_FAMILY_MOE_HO_OH TRUE
#define P_FAMILY_MOE_CELEBI TRUE
#define P_FAMILY_MOE_AZURILL TRUE
#define P_FAMILY_MOE_WYNAUT TRUE
#define P_FAMILY_MOE_AMBIPOM TRUE
#define P_FAMILY_MOE_MISMAGIUS TRUE
#define P_FAMILY_MOE_HONCHKROW TRUE
#define P_FAMILY_MOE_BONSLY TRUE
#define P_FAMILY_MOE_MIME_JR TRUE
#define P_FAMILY_MOE_HAPPINY TRUE
#define P_FAMILY_MOE_MUNCHLAX TRUE
#define P_FAMILY_MOE_MANTYKE TRUE
#define P_FAMILY_MOE_WEAVILE TRUE
#define P_FAMILY_MOE_MAGNEZONE TRUE
#define P_FAMILY_MOE_LICKILICKY TRUE
#define P_FAMILY_MOE_RHYPERIOR TRUE
#define P_FAMILY_MOE_TANGROWTH TRUE
#define P_FAMILY_MOE_ELECTIVIRE TRUE
#define P_FAMILY_MOE_MAGMORTAR TRUE
#define P_FAMILY_MOE_TOGEKISS TRUE
#define P_FAMILY_MOE_YANMEGA TRUE
#define P_FAMILY_MOE_LEAFEON TRUE
#define P_FAMILY_MOE_GLACEON TRUE
#define P_FAMILY_MOE_GLISCOR TRUE
#define P_FAMILY_MOE_MAMOSWINE TRUE
#define P_FAMILY_MOE_PORYGON_Z TRUE
#define P_FAMILY_MOE_SYLVEON TRUE
#define P_FAMILY_MOE_PERRSERKER TRUE
#define P_FAMILY_MOE_CURSOLA TRUE
#define P_FAMILY_MOE_SIRFETCHD TRUE
#define P_FAMILY_MOE_MR_RIME TRUE
#define P_FAMILY_MOE_WYRDEER TRUE
#define P_FAMILY_MOE_KLEAVOR TRUE
#define P_FAMILY_MOE_URSALUNA TRUE
#define P_FAMILY_MOE_SNEASLER TRUE
#define P_FAMILY_MOE_OVERQWIL TRUE
#define P_FAMILY_MOE_ANNIHILAPE TRUE
#define P_FAMILY_MOE_CLODSIRE TRUE
#define P_FAMILY_MOE_FARIGIRAF TRUE
#define P_FAMILY_MOE_DUDUNSPARCE TRUE
#define P_FAMILY_MOE_RATTATA_ALOLA TRUE
#define P_FAMILY_MOE_RATICATE_ALOLA TRUE
#define P_FAMILY_MOE_RAICHU_ALOLA TRUE
#define P_FAMILY_MOE_SANDSHREW_ALOLA TRUE
#define P_FAMILY_MOE_SANDSLASH_ALOLA TRUE
#define P_FAMILY_MOE_VULPIX_ALOLA TRUE
#define P_FAMILY_MOE_NINETALES_ALOLA TRUE
#define P_FAMILY_MOE_DIGLETT_ALOLA TRUE
#define P_FAMILY_MOE_DUGTRIO_ALOLA TRUE
#define P_FAMILY_MOE_MEOWTH_ALOLA TRUE
#define P_FAMILY_MOE_PERSIAN_ALOLA TRUE
#define P_FAMILY_MOE_GEODUDE_ALOLA TRUE
#define P_FAMILY_MOE_GRAVELER_ALOLA TRUE
#define P_FAMILY_MOE_GOLEM_ALOLA TRUE
#define P_FAMILY_MOE_GRIMER_ALOLA TRUE
#define P_FAMILY_MOE_MUK_ALOLA TRUE
#define P_FAMILY_MOE_EXEGGUTOR_ALOLA TRUE
#define P_FAMILY_MOE_MAROWAK_ALOLA TRUE
#define P_FAMILY_MOE_RATICATE_ALOLA_TOTEM TRUE
#define P_FAMILY_MOE_MAROWAK_ALOLA_TOTEM TRUE
#define P_FAMILY_MOE_MEOWTH_GALAR TRUE
#define P_FAMILY_MOE_PONYTA_GALAR TRUE
#define P_FAMILY_MOE_RAPIDASH_GALAR TRUE
#define P_FAMILY_MOE_SLOWPOKE_GALAR TRUE
#define P_FAMILY_MOE_SLOWBRO_GALAR TRUE
#define P_FAMILY_MOE_FARFETCHD_GALAR TRUE
#define P_FAMILY_MOE_WEEZING_GALAR TRUE
#define P_FAMILY_MOE_MR_MIME_GALAR TRUE
#define P_FAMILY_MOE_ARTICUNO_GALAR TRUE
#define P_FAMILY_MOE_ZAPDOS_GALAR TRUE
#define P_FAMILY_MOE_MOLTRES_GALAR TRUE
#define P_FAMILY_MOE_SLOWKING_GALAR TRUE
#define P_FAMILY_MOE_CORSOLA_GALAR TRUE
#define P_FAMILY_MOE_GROWLITHE_HISUI TRUE
#define P_FAMILY_MOE_ARCANINE_HISUI TRUE
#define P_FAMILY_MOE_VOLTORB_HISUI TRUE
#define P_FAMILY_MOE_ELECTRODE_HISUI TRUE
#define P_FAMILY_MOE_TYPHLOSION_HISUI TRUE
#define P_FAMILY_MOE_QWILFISH_HISUI TRUE
#define P_FAMILY_MOE_SNEASEL_HISUI TRUE
#define P_FAMILY_MOE_TAUROS_PALDEA_COMBAT TRUE
#define P_FAMILY_MOE_TAUROS_PALDEA_BLAZE TRUE
#define P_FAMILY_MOE_TAUROS_PALDEA_AQUA TRUE
#define P_FAMILY_MOE_WOOPER_PALDEA TRUE
#define P_FAMILY_MOE_URSALUNA_BLOODMOON TRUE
#define P_FAMILY_MOE_PIKACHU_COSPLAY TRUE
#define P_FAMILY_MOE_PIKACHU_ROCK_STAR TRUE
#define P_FAMILY_MOE_PIKACHU_BELLE TRUE
#define P_FAMILY_MOE_PIKACHU_POP_STAR TRUE
#define P_FAMILY_MOE_PIKACHU_PH_D TRUE
#define P_FAMILY_MOE_PIKACHU_LIBRE TRUE
#define P_FAMILY_MOE_PIKACHU_ORIGINAL_CAP TRUE
#define P_FAMILY_MOE_PIKACHU_HOENN_CAP TRUE
#define P_FAMILY_MOE_PIKACHU_SINNOH_CAP TRUE
#define P_FAMILY_MOE_PIKACHU_UNOVA_CAP TRUE
#define P_FAMILY_MOE_PIKACHU_KALOS_CAP TRUE
#define P_FAMILY_MOE_PIKACHU_ALOLA_CAP TRUE
#define P_FAMILY_MOE_PIKACHU_PARTNER_CAP TRUE
#define P_FAMILY_MOE_PIKACHU_WORLD_CAP TRUE
#define P_FAMILY_MOE_PICHU_SPIKY_EARED TRUE
#define P_FAMILY_MOE_UNOWN_B TRUE
#define P_FAMILY_MOE_UNOWN_C TRUE
#define P_FAMILY_MOE_UNOWN_D TRUE
#define P_FAMILY_MOE_UNOWN_E TRUE
#define P_FAMILY_MOE_UNOWN_F TRUE
#define P_FAMILY_MOE_UNOWN_G TRUE
#define P_FAMILY_MOE_UNOWN_H TRUE
#define P_FAMILY_MOE_UNOWN_I TRUE
#define P_FAMILY_MOE_UNOWN_J TRUE
#define P_FAMILY_MOE_UNOWN_K TRUE
#define P_FAMILY_MOE_UNOWN_L TRUE
#define P_FAMILY_MOE_UNOWN_M TRUE
#define P_FAMILY_MOE_UNOWN_N TRUE
#define P_FAMILY_MOE_UNOWN_O TRUE
#define P_FAMILY_MOE_UNOWN_P TRUE
#define P_FAMILY_MOE_UNOWN_Q TRUE
#define P_FAMILY_MOE_UNOWN_R TRUE
#define P_FAMILY_MOE_UNOWN_S TRUE
#define P_FAMILY_MOE_UNOWN_T TRUE
#define P_FAMILY_MOE_UNOWN_U TRUE
#define P_FAMILY_MOE_UNOWN_V TRUE
#define P_FAMILY_MOE_UNOWN_W TRUE
#define P_FAMILY_MOE_UNOWN_X TRUE
#define P_FAMILY_MOE_UNOWN_Y TRUE
#define P_FAMILY_MOE_UNOWN_Z TRUE
#define P_FAMILY_MOE_UNOWN_EXCLAMATION TRUE
#define P_FAMILY_MOE_UNOWN_QUESTION TRUE
#define P_FAMILY_MOE_DUDUNSPARCE_THREE_SEGMENT TRUE
#define P_FAMILY_MOE_GREAT_TUSK TRUE
#define P_FAMILY_MOE_SCREAM_TAIL TRUE
#define P_FAMILY_MOE_FLUTTER_MANE TRUE
#define P_FAMILY_MOE_SANDY_SHOCKS TRUE
#define P_FAMILY_MOE_IRON_TREADS TRUE
#define P_FAMILY_MOE_IRON_BUNDLE TRUE
#define P_FAMILY_MOE_IRON_THORNS TRUE
#define P_FAMILY_MOE_WALKING_WAKE TRUE
#define P_FAMILY_MOE_GOUGING_FIRE TRUE
#define P_FAMILY_MOE_RAGING_BOLT TRUE
#define P_FAMILY_YYYI_YUUKI_YUUNA_NORMAL TRUE
#define P_FAMILY_YYYI_YUUKI_YUUNA_YUUSHA TRUE
#define P_FAMILY_YYYI_YUUKI_YUUNA_MANKAI TRUE
#define P_FAMILY_YYYI_MIMORI_NORMAL TRUE
#define P_FAMILY_YYYI_MIMORI_YUUSHA TRUE
#define P_FAMILY_YYYI_MIMORI_MANKAI TRUE
#define P_FAMILY_YYYI_KARIN_NORMAL TRUE
#define P_FAMILY_YYYI_KARIN_YUUSHA TRUE
#define P_FAMILY_YYYI_KARIN_MANKAI TRUE
#define P_FAMILY_YYYI_FUU_NORMAL TRUE
#define P_FAMILY_YYYI_FUU_YUUSHA TRUE
#define P_FAMILY_YYYI_FUU_MANKAI TRUE
#define P_FAMILY_YYYI_ITSUKI_NORMAL TRUE
#define P_FAMILY_YYYI_ITSUKI_YUUSHA TRUE
#define P_FAMILY_YYYI_ITSUKI_MANKAI TRUE
#define P_FAMILY_YYYI_SONOKO_BIG_NORMAL TRUE
#define P_FAMILY_YYYI_SONOKO_BIG_YUUSHA TRUE
#define P_FAMILY_YYYI_SONOKO_BIG_MANKAI TRUE
#define P_FAMILY_YYYI_SUMI_NORMAL TRUE
#define P_FAMILY_YYYI_SUMI_YUUSHA TRUE
#define P_FAMILY_YYYI_SUMI_MANKAI TRUE
#define P_FAMILY_YYYI_GIN_NORMAL TRUE
#define P_FAMILY_YYYI_GIN_YUUSHA TRUE
#define P_FAMILY_YYYI_GIN_MANKAI TRUE
#define P_FAMILY_YYYI_SONOKO_SMOL_NORMAL TRUE
#define P_FAMILY_YYYI_SONOKO_SMOL_YUUSHA TRUE
#define P_FAMILY_YYYI_SONOKO_SMOL_MANKAI TRUE
#define P_FAMILY_YYYI_WAKABA_NORMAL TRUE
#define P_FAMILY_YYYI_WAKABA_YUUSHA TRUE
#define P_FAMILY_YYYI_WAKABA_KIRIFUDA1 TRUE
#define P_FAMILY_YYYI_TAKASHIMA_YUUNA_NORMAL TRUE
#define P_FAMILY_YYYI_TAKASHIMA_YUUNA_YUUSHA TRUE
#define P_FAMILY_YYYI_TAKASHIMA_YUUNA_KIRIFUDA1 TRUE
#define P_FAMILY_YYYI_CHIKAGE_NORMAL TRUE
#define P_FAMILY_YYYI_CHIKAGE_YUUSHA TRUE
#define P_FAMILY_YYYI_CHIKAGE_KIRIFUDA TRUE
#define P_FAMILY_YYYI_TAMAKO_NORMAL TRUE
#define P_FAMILY_YYYI_TAMAKO_YUUSHA TRUE
#define P_FAMILY_YYYI_TAMAKO_KIRIFUDA TRUE
#define P_FAMILY_YYYI_ANZU_NORMAL TRUE
#define P_FAMILY_YYYI_ANZU_YUUSHA TRUE
#define P_FAMILY_YYYI_ANZU_KIRIFUDA TRUE
#define P_FAMILY_YYYI_HINATA_NORMAL TRUE
#define P_FAMILY_YYYI_HINATA_MIKO TRUE
#define P_FAMILY_YYYI_UTANO_NORMAL TRUE
#define P_FAMILY_YYYI_UTANO_YUUSHA TRUE
#define P_FAMILY_YYYI_UTANO_KIRIFUDA TRUE
#define P_FAMILY_YYYI_MITO_NORMAL TRUE
#define P_FAMILY_YYYI_MITO_MIKO TRUE
#define P_FAMILY_YYYI_MEBUKI_NORMAL TRUE
#define P_FAMILY_YYYI_MEBUKI_SAKIMORI TRUE
#define P_FAMILY_YYYI_MEBUKI_MANKAI TRUE
#define P_FAMILY_YYYI_SUZUME_NORMAL TRUE
#define P_FAMILY_YYYI_SUZUME_SAKIMORI TRUE
#define P_FAMILY_YYYI_SUZUME_MANKAI TRUE
#define P_FAMILY_YYYI_YUMIKO_NORMAL TRUE
#define P_FAMILY_YYYI_YUMIKO_SAKIMORI TRUE
#define P_FAMILY_YYYI_YUMIKO_MANKAI TRUE
#define P_FAMILY_YYYI_SHIZUKU_NORMAL TRUE
#define P_FAMILY_YYYI_SHIZUKU_SAKIMORI TRUE
#define P_FAMILY_YYYI_SHIZUKU_MANKAI TRUE
#define P_FAMILY_YYYI_AYA_NORMAL TRUE
#define P_FAMILY_YYYI_AYA_MIKO TRUE
#define P_FAMILY_YYYI_SEKKA_NORMAL TRUE
#define P_FAMILY_YYYI_SEKKA_YUUSHA TRUE
#define P_FAMILY_YYYI_SEKKA_KIRIFUDA TRUE
#define P_FAMILY_YYYI_NATSUME_NORMAL TRUE
#define P_FAMILY_YYYI_NATSUME_YUUSHA TRUE
#define P_FAMILY_YYYI_NATSUME_KIRIFUDA TRUE
#define P_FAMILY_YYYI_AKAMINE_YUUNA_NORMAL TRUE
#define P_FAMILY_YYYI_AKAMINE_YUUNA_YUUSHA TRUE
#define P_FAMILY_YYYI_AKAMINE_YUUNA_KIRIFUDA TRUE
#define P_FAMILY_YYYI_RENGE_NORMAL TRUE
#define P_FAMILY_YYYI_RENGE_YUUSHA TRUE
#define P_FAMILY_YYYI_RENGE_KIRIFUDA TRUE
#define P_FAMILY_YYYI_SHIZUKA_NORMAL TRUE
#define P_FAMILY_YYYI_SHIZUKA_MIKO TRUE
#define P_FAMILY_YYYI_FUYOU_LILIENTHAL_YUUNA_NORMAL TRUE
#define P_FAMILY_YYYI_FUYOU_LILIENTHAL_YUUNA_YUUSHA TRUE
#define P_FAMILY_YYYI_FUYOU_LILIENTHAL_YUUNA_KIRIFUDA TRUE
#define P_FAMILY_YYYI_YUZUKI_YUUNA_NORMAL TRUE
#define P_FAMILY_YYYI_YUZUKI_YUUNA_YUUSHA TRUE
#define P_FAMILY_YYYI_YUZUKI_YUUNA_KIRIFUDA TRUE
#define P_FAMILY_YYYI_MASUZU_NORMAL TRUE
#define P_FAMILY_YYYI_MASUZU_MIKO TRUE
#define P_FAMILY_YYYI_YOSHIKA_NORMAL TRUE
#define P_FAMILY_YYYI_YOSHIKA_MIKO TRUE
#define P_FAMILY_YYYI_HIME_NORMAL TRUE
#define P_FAMILY_YYYI_HIME_MIKO TRUE
#define P_FAMILY_YYYI_MISAKI_NORMAL TRUE
#define P_FAMILY_YYYI_MISAKI_MIKO TRUE
#define P_FAMILY_TH_SHINGYOKU_CHIBI TRUE
#define P_FAMILY_TH_SHINGYOKU_ORB TRUE
#define P_FAMILY_TH_SHINGYOKU_PRIEST TRUE
#define P_FAMILY_TH_SHINGYOKU_PRIESTESS TRUE
#define P_FAMILY_TH_YUUGEN_CHIBI TRUE
#define P_FAMILY_TH_YUUGEN_NORMAL TRUE
#define P_FAMILY_TH_MIMA_CHIBI TRUE
#define P_FAMILY_TH_MIMA_NORMAL TRUE
#define P_FAMILY_TH_ELIS_CHIBI TRUE
#define P_FAMILY_TH_ELIS_NORMAL TRUE
#define P_FAMILY_TH_KIKURI_CHIBI TRUE
#define P_FAMILY_TH_KIKURI_NORMAL TRUE
#define P_FAMILY_TH_SARIEL_CHIBI TRUE
#define P_FAMILY_TH_SARIEL_NORMAL TRUE
#define P_FAMILY_TH_SARIEL_SPEED TRUE
#define P_FAMILY_TH_KONNGARA_CHIBI TRUE
#define P_FAMILY_TH_KONNGARA_NORMAL TRUE
#define P_FAMILY_TH_FAIRY_NORMAL TRUE
#define P_FAMILY_TH_GENJI_NORMAL TRUE
#define P_FAMILY_TH_RIKA_CHIBI TRUE
#define P_FAMILY_TH_RIKA_NORMAL TRUE
#define P_FAMILY_TH_MEIRA_CHIBI TRUE
#define P_FAMILY_TH_MEIRA_NORMAL TRUE
#define P_FAMILY_TH_ELLEN_CHIBI TRUE
#define P_FAMILY_TH_ELLEN_NORMAL TRUE
#define P_FAMILY_TH_KOTOHIME_CHIBI TRUE
#define P_FAMILY_TH_KOTOHIME_NORMAL TRUE
#define P_FAMILY_TH_KANA_CHIBI TRUE
#define P_FAMILY_TH_KANA_NORMAL TRUE
#define P_FAMILY_TH_RIKAKO_CHIBI TRUE
#define P_FAMILY_TH_RIKAKO_NORMAL TRUE
#define P_FAMILY_TH_CHIYURI_CHIBI TRUE
#define P_FAMILY_TH_CHIYURI_NORMAL TRUE
#define P_FAMILY_TH_YUMEMI_CHIBI TRUE
#define P_FAMILY_TH_YUMEMI_NORMAL TRUE
#define P_FAMILY_TH_KEDAMA_NORMAL TRUE
#define P_FAMILY_TH_RUUKOTO_NORMAL TRUE
#define P_FAMILY_TH_MIMICHAN_NORMAL TRUE
#define P_FAMILY_TH_ORANGE_CHIBI TRUE
#define P_FAMILY_TH_ORANGE_NORMAL TRUE
#define P_FAMILY_TH_KURUMI_CHIBI TRUE
#define P_FAMILY_TH_KURUMI_NORMAL TRUE
#define P_FAMILY_TH_ELLY_CHIBI TRUE
#define P_FAMILY_TH_ELLY_NORMAL TRUE
#define P_FAMILY_TH_MUGETSU_CHIBI TRUE
#define P_FAMILY_TH_MUGETSU_NORMAL TRUE
#define P_FAMILY_TH_GENGETSU_CHIBI TRUE
#define P_FAMILY_TH_GENGETSU_NORMAL TRUE
#define P_FAMILY_TH_SARA_CHIBI TRUE
#define P_FAMILY_TH_SARA_NORMAL TRUE
#define P_FAMILY_TH_LOUISE_CHIBI TRUE
#define P_FAMILY_TH_LOUISE_NORMAL TRUE
#define P_FAMILY_TH_YUKI_CHIBI TRUE
#define P_FAMILY_TH_YUKI_NORMAL TRUE
#define P_FAMILY_TH_MAI_CHIBI TRUE
#define P_FAMILY_TH_MAI_NORMAL TRUE
#define P_FAMILY_TH_YUMEKO_CHIBI TRUE
#define P_FAMILY_TH_YUMEKO_NORMAL TRUE
#define P_FAMILY_TH_SHINKI_CHIBI TRUE
#define P_FAMILY_TH_SHINKI_NORMAL TRUE
#define P_FAMILY_TH_RUMIA_CHIBI TRUE
#define P_FAMILY_TH_RUMIA_NORMAL TRUE
#define P_FAMILY_TH_RUMIA_ATTACK TRUE
#define P_FAMILY_TH_RUMIA_SPEED TRUE
#define P_FAMILY_TH_DAIYOUSEI_CHIBI TRUE
#define P_FAMILY_TH_DAIYOUSEI_NORMAL TRUE
#define P_FAMILY_TH_DAIYOUSEI_ATTACK TRUE
#define P_FAMILY_TH_DAIYOUSEI_DEFENSE TRUE
#define P_FAMILY_TH_CIRNO_CHIBI TRUE
#define P_FAMILY_TH_CIRNO_NORMAL TRUE
#define P_FAMILY_TH_CIRNO_SPEED TRUE
#define P_FAMILY_TH_CIRNO_TECH TRUE
#define P_FAMILY_TH_CIRNO_ADVENT TRUE
#define P_FAMILY_TH_LUNACHILD_CHIBI TRUE
#define P_FAMILY_TH_LUNACHILD_NORMAL TRUE
#define P_FAMILY_TH_LUNACHILD_ATTACK TRUE
#define P_FAMILY_TH_LUNACHILD_TECH TRUE
#define P_FAMILY_TH_STARSAPPHIRE_CHIBI TRUE
#define P_FAMILY_TH_STARSAPPHIRE_NORMAL TRUE
#define P_FAMILY_TH_STARSAPPHIRE_ATTACK TRUE
#define P_FAMILY_TH_STARSAPPHIRE_HELPER TRUE
#define P_FAMILY_TH_SUNNYMILK_CHIBI TRUE
#define P_FAMILY_TH_SUNNYMILK_NORMAL TRUE
#define P_FAMILY_TH_SUNNYMILK_ATTACK TRUE
#define P_FAMILY_TH_SUNNYMILK_DEFENSE TRUE
#define P_FAMILY_TH_MEILING_CHIBI TRUE
#define P_FAMILY_TH_MEILING_NORMAL TRUE
#define P_FAMILY_TH_MEILING_DEFENSE TRUE
#define P_FAMILY_TH_MEILING_SPEED TRUE
#define P_FAMILY_TH_MEILING_ADVENT TRUE
#define P_FAMILY_TH_KOAKUMA_CHIBI TRUE
#define P_FAMILY_TH_KOAKUMA_NORMAL TRUE
#define P_FAMILY_TH_KOAKUMA_HELPER TRUE
#define P_FAMILY_TH_PATCHOULI_CHIBI TRUE
#define P_FAMILY_TH_PATCHOULI_NORMAL TRUE
#define P_FAMILY_TH_PATCHOULI_ATTACK TRUE
#define P_FAMILY_TH_PATCHOULI_DEFENSE TRUE
#define P_FAMILY_TH_SAKUYA_CHIBI TRUE
#define P_FAMILY_TH_SAKUYA_NORMAL TRUE
#define P_FAMILY_TH_SAKUYA_TECH TRUE
#define P_FAMILY_TH_SAKUYA_HELPER TRUE
#define P_FAMILY_TH_REMILIA_CHIBI TRUE
#define P_FAMILY_TH_REMILIA_NORMAL TRUE
#define P_FAMILY_TH_REMILIA_ATTACK TRUE
#define P_FAMILY_TH_REMILIA_DEFENSE TRUE
#define P_FAMILY_TH_REMILIA_ADVENT TRUE
#define P_FAMILY_TH_FLANDRE_CHIBI TRUE
#define P_FAMILY_TH_FLANDRE_NORMAL TRUE
#define P_FAMILY_TH_FLANDRE_ATTACK TRUE
#define P_FAMILY_TH_FLANDRE_SPEED TRUE
#define P_FAMILY_TH_SATSUKI_NORMAL TRUE
#define P_FAMILY_TH_LETTY_CHIBI TRUE
#define P_FAMILY_TH_LETTY_NORMAL TRUE
#define P_FAMILY_TH_LETTY_DEFENSE TRUE
#define P_FAMILY_TH_LETTY_HELPER TRUE
#define P_FAMILY_TH_LETTY_ADVENT TRUE
#define P_FAMILY_TH_CHEN_CHIBI TRUE
#define P_FAMILY_TH_CHEN_NORMAL TRUE
#define P_FAMILY_TH_CHEN_ATTACK TRUE
#define P_FAMILY_TH_CHEN_TECH TRUE
#define P_FAMILY_TH_CHEN_ADVENT TRUE
#define P_FAMILY_TH_ALICE_CHIBI TRUE
#define P_FAMILY_TH_ALICE_NORMAL TRUE
#define P_FAMILY_TH_ALICE_ATTACK TRUE
#define P_FAMILY_TH_ALICE_TECH TRUE
#define P_FAMILY_TH_LILYBLACK_CHIBI TRUE
#define P_FAMILY_TH_LILYBLACK_NORMAL TRUE
#define P_FAMILY_TH_LILYBLACK_ATTACK TRUE
#define P_FAMILY_TH_LILYBLACK_SPEED TRUE
#define P_FAMILY_TH_LILYWHITE_CHIBI TRUE
#define P_FAMILY_TH_LILYWHITE_NORMAL TRUE
#define P_FAMILY_TH_LILYWHITE_ATTACK TRUE
#define P_FAMILY_TH_LILYWHITE_HELPER TRUE
#define P_FAMILY_TH_LUNASA_CHIBI TRUE
#define P_FAMILY_TH_LUNASA_NORMAL TRUE
#define P_FAMILY_TH_LUNASA_HELPER TRUE
#define P_FAMILY_TH_MERLIN_CHIBI TRUE
#define P_FAMILY_TH_MERLIN_NORMAL TRUE
#define P_FAMILY_TH_MERLIN_HELPER TRUE
#define P_FAMILY_TH_LYRICA_CHIBI TRUE
#define P_FAMILY_TH_LYRICA_NORMAL TRUE
#define P_FAMILY_TH_LYRICA_HELPER TRUE
#define P_FAMILY_TH_YOUMU_CHIBI TRUE
#define P_FAMILY_TH_YOUMU_NORMAL TRUE
#define P_FAMILY_TH_YOUMU_DEFENSE TRUE
#define P_FAMILY_TH_YOUMU_SPEED TRUE
#define P_FAMILY_TH_YOUMU_ADVENT TRUE
#define P_FAMILY_TH_YUYUKO_CHIBI TRUE
#define P_FAMILY_TH_YUYUKO_NORMAL TRUE
#define P_FAMILY_TH_YUYUKO_ATTACK TRUE
#define P_FAMILY_TH_YUYUKO_DEFENSE TRUE
#define P_FAMILY_TH_YUYUKO_ADVENT TRUE
#define P_FAMILY_TH_RAN_CHIBI TRUE
#define P_FAMILY_TH_RAN_NORMAL TRUE
#define P_FAMILY_TH_RAN_ATTACK TRUE
#define P_FAMILY_TH_RAN_HELPER TRUE
#define P_FAMILY_TH_RAN_ADVENT TRUE
#define P_FAMILY_TH_YUKARI_CHIBI TRUE
#define P_FAMILY_TH_YUKARI_NORMAL TRUE
#define P_FAMILY_TH_YUKARI_DEFENSE TRUE
#define P_FAMILY_TH_YUKARI_TECH TRUE
#define P_FAMILY_TH_YUKARI_ADVENT TRUE
#define P_FAMILY_TH_SUIKA_CHIBI TRUE
#define P_FAMILY_TH_SUIKA_NORMAL TRUE
#define P_FAMILY_TH_SUIKA_ATTACK TRUE
#define P_FAMILY_TH_SUIKA_TECH TRUE
#define P_FAMILY_TH_WRIGGLE_CHIBI TRUE
#define P_FAMILY_TH_WRIGGLE_NORMAL TRUE
#define P_FAMILY_TH_WRIGGLE_DEFENSE TRUE
#define P_FAMILY_TH_WRIGGLE_SPEED TRUE
#define P_FAMILY_TH_MYSTIA_CHIBI TRUE
#define P_FAMILY_TH_MYSTIA_NORMAL TRUE
#define P_FAMILY_TH_MYSTIA_ATTACK TRUE
#define P_FAMILY_TH_MYSTIA_HELPER TRUE
#define P_FAMILY_TH_MYSTIA_ADVENT TRUE
#define P_FAMILY_TH_KEINE_CHIBI TRUE
#define P_FAMILY_TH_KEINE_NORMAL TRUE
#define P_FAMILY_TH_KEINE_ATTACK TRUE
#define P_FAMILY_TH_KEINE_DEFENSE TRUE
#define P_FAMILY_TH_KEINE_HELPER TRUE
#define P_FAMILY_TH_TEWI_CHIBI TRUE
#define P_FAMILY_TH_TEWI_NORMAL TRUE
#define P_FAMILY_TH_TEWI_ATTACK TRUE
#define P_FAMILY_TH_TEWI_DEFENSE TRUE
#define P_FAMILY_TH_TEWI_ADVENT TRUE
#define P_FAMILY_TH_REISEN_CHIBI TRUE
#define P_FAMILY_TH_REISEN_NORMAL TRUE
#define P_FAMILY_TH_REISEN_DEFENSE TRUE
#define P_FAMILY_TH_REISEN_TECH TRUE
#define P_FAMILY_TH_REISEN_ADVENT TRUE
#define P_FAMILY_TH_EIRIN_CHIBI TRUE
#define P_FAMILY_TH_EIRIN_NORMAL TRUE
#define P_FAMILY_TH_EIRIN_ATTACK TRUE
#define P_FAMILY_TH_EIRIN_HELPER TRUE
#define P_FAMILY_TH_EIRIN_ADVENT TRUE
#define P_FAMILY_TH_KAGUYA_CHIBI TRUE
#define P_FAMILY_TH_KAGUYA_NORMAL TRUE
#define P_FAMILY_TH_KAGUYA_ATTACK TRUE
#define P_FAMILY_TH_KAGUYA_DEFENSE TRUE
#define P_FAMILY_TH_MOKOU_CHIBI TRUE
#define P_FAMILY_TH_MOKOU_NORMAL TRUE
#define P_FAMILY_TH_MOKOU_ATTACK TRUE
#define P_FAMILY_TH_MOKOU_DEFENSE TRUE
#define P_FAMILY_TH_MOKOU_ADVENT TRUE
#define P_FAMILY_TH_GYOKUTO_NORMAL TRUE
#define P_FAMILY_TH_TOYOHIME_CHIBI TRUE
#define P_FAMILY_TH_TOYOHIME_NORMAL TRUE
#define P_FAMILY_TH_TOYOHIME_TECH TRUE
#define P_FAMILY_TH_YORIHIME_CHIBI TRUE
#define P_FAMILY_TH_YORIHIME_NORMAL TRUE
#define P_FAMILY_TH_YORIHIME_SPEED TRUE
#define P_FAMILY_TH_AYA_CHIBI TRUE
#define P_FAMILY_TH_AYA_NORMAL TRUE
#define P_FAMILY_TH_AYA_SPEED TRUE
#define P_FAMILY_TH_AYA_TECH TRUE
#define P_FAMILY_TH_MEDICINE_CHIBI TRUE
#define P_FAMILY_TH_MEDICINE_NORMAL TRUE
#define P_FAMILY_TH_MEDICINE_ATTACK TRUE
#define P_FAMILY_TH_MEDICINE_SPEED TRUE
#define P_FAMILY_TH_MEDICINE_TECH TRUE
#define P_FAMILY_TH_YUUKA_CHIBI TRUE
#define P_FAMILY_TH_YUUKA_NORMAL TRUE
#define P_FAMILY_TH_YUUKA_ATTACK TRUE
#define P_FAMILY_TH_YUUKA_TECH TRUE
#define P_FAMILY_TH_KOMACHI_CHIBI TRUE
#define P_FAMILY_TH_KOMACHI_NORMAL TRUE
#define P_FAMILY_TH_KOMACHI_ATTACK TRUE
#define P_FAMILY_TH_KOMACHI_SPEED TRUE
#define P_FAMILY_TH_EIKI_CHIBI TRUE
#define P_FAMILY_TH_EIKI_NORMAL TRUE
#define P_FAMILY_TH_EIKI_ATTACK TRUE
#define P_FAMILY_TH_EIKI_DEFENSE TRUE
#define P_FAMILY_TH_SHIZUHA_CHIBI TRUE
#define P_FAMILY_TH_SHIZUHA_NORMAL TRUE
#define P_FAMILY_TH_SHIZUHA_SPEED TRUE
#define P_FAMILY_TH_SHIZUHA_HELPER TRUE
#define P_FAMILY_TH_MINORIKO_CHIBI TRUE
#define P_FAMILY_TH_MINORIKO_NORMAL TRUE
#define P_FAMILY_TH_MINORIKO_ATTACK TRUE
#define P_FAMILY_TH_MINORIKO_DEFENSE TRUE
#define P_FAMILY_TH_HINA_CHIBI TRUE
#define P_FAMILY_TH_HINA_NORMAL TRUE
#define P_FAMILY_TH_HINA_ATTACK TRUE
#define P_FAMILY_TH_HINA_DEFENSE TRUE
#define P_FAMILY_TH_NITORI_CHIBI TRUE
#define P_FAMILY_TH_NITORI_NORMAL TRUE
#define P_FAMILY_TH_NITORI_ATTACK TRUE
#define P_FAMILY_TH_NITORI_TECH TRUE
#define P_FAMILY_TH_MOMIJI_CHIBI TRUE
#define P_FAMILY_TH_MOMIJI_NORMAL TRUE
#define P_FAMILY_TH_MOMIJI_DEFENSE TRUE
#define P_FAMILY_TH_SANAE_CHIBI TRUE
#define P_FAMILY_TH_SANAE_NORMAL TRUE
#define P_FAMILY_TH_SANAE_ATTACK TRUE
#define P_FAMILY_TH_SANAE_TECH TRUE
#define P_FAMILY_TH_KANAKO_CHIBI TRUE
#define P_FAMILY_TH_KANAKO_NORMAL TRUE
#define P_FAMILY_TH_KANAKO_ATTACK TRUE
#define P_FAMILY_TH_KANAKO_DEFENSE TRUE
#define P_FAMILY_TH_SUWAKO_CHIBI TRUE
#define P_FAMILY_TH_SUWAKO_NORMAL TRUE
#define P_FAMILY_TH_SUWAKO_ATTACK TRUE
#define P_FAMILY_TH_SUWAKO_DEFENSE TRUE
#define P_FAMILY_TH_IKU_CHIBI TRUE
#define P_FAMILY_TH_IKU_NORMAL TRUE
#define P_FAMILY_TH_IKU_DEFENSE TRUE
#define P_FAMILY_TH_IKU_TECH TRUE
#define P_FAMILY_TH_TENSHI_CHIBI TRUE
#define P_FAMILY_TH_TENSHI_NORMAL TRUE
#define P_FAMILY_TH_TENSHI_ATTACK TRUE
#define P_FAMILY_TH_TENSHI_DEFENSE TRUE
#define P_FAMILY_TH_KISUME_CHIBI TRUE
#define P_FAMILY_TH_KISUME_NORMAL TRUE
#define P_FAMILY_TH_KISUME_TECH TRUE
#define P_FAMILY_TH_YAMAME_CHIBI TRUE
#define P_FAMILY_TH_YAMAME_NORMAL TRUE
#define P_FAMILY_TH_YAMAME_SPEED TRUE
#define P_FAMILY_TH_YAMAME_TECH TRUE
#define P_FAMILY_TH_PARSEE_CHIBI TRUE
#define P_FAMILY_TH_PARSEE_NORMAL TRUE
#define P_FAMILY_TH_PARSEE_DEFENSE TRUE
#define P_FAMILY_TH_PARSEE_TECH TRUE
#define P_FAMILY_TH_YUUGI_CHIBI TRUE
#define P_FAMILY_TH_YUUGI_NORMAL TRUE
#define P_FAMILY_TH_YUUGI_ATTACK TRUE
#define P_FAMILY_TH_YUUGI_DEFENSE TRUE
#define P_FAMILY_TH_SATORI_CHIBI TRUE
#define P_FAMILY_TH_SATORI_NORMAL TRUE
#define P_FAMILY_TH_SATORI_DEFENSE TRUE
#define P_FAMILY_TH_SATORI_TECH TRUE
#define P_FAMILY_TH_RIN_CHIBI TRUE
#define P_FAMILY_TH_RIN_NORMAL TRUE
#define P_FAMILY_TH_RIN_ATTACK TRUE
#define P_FAMILY_TH_RIN_SPEED TRUE
#define P_FAMILY_TH_ZOMBIEFAIRY TRUE
#define P_FAMILY_TH_UTSUHO_CHIBI TRUE
#define P_FAMILY_TH_UTSUHO_NORMAL TRUE
#define P_FAMILY_TH_UTSUHO_ATTACK TRUE
#define P_FAMILY_TH_UTSUHO_SPEED TRUE
#define P_FAMILY_TH_KOISHI_CHIBI TRUE
#define P_FAMILY_TH_KOISHI_NORMAL TRUE
#define P_FAMILY_TH_KOISHI_ATTACK TRUE
#define P_FAMILY_TH_KOISHI_SPEED TRUE
#define P_FAMILY_TH_NAZRIN_CHIBI TRUE
#define P_FAMILY_TH_NAZRIN_NORMAL TRUE
#define P_FAMILY_TH_NAZRIN_TECH TRUE
#define P_FAMILY_TH_NAZRIN_HELPER TRUE
#define P_FAMILY_TH_KOGASA_CHIBI TRUE
#define P_FAMILY_TH_KOGASA_NORMAL TRUE
#define P_FAMILY_TH_KOGASA_SPEED TRUE
#define P_FAMILY_TH_KOGASA_TECH TRUE
#define P_FAMILY_TH_ICHIRIN_CHIBI TRUE
#define P_FAMILY_TH_ICHIRIN_NORMAL TRUE
#define P_FAMILY_TH_ICHIRIN_DEFENSE TRUE
#define P_FAMILY_TH_ICHIRIN_TECH TRUE
#define P_FAMILY_TH_MURASA_CHIBI TRUE
#define P_FAMILY_TH_MURASA_NORMAL TRUE
#define P_FAMILY_TH_MURASA_ATTACK TRUE
#define P_FAMILY_TH_MURASA_DEFENSE TRUE
#define P_FAMILY_TH_SHOU_CHIBI TRUE
#define P_FAMILY_TH_SHOU_NORMAL TRUE
#define P_FAMILY_TH_SHOU_ATTACK TRUE
#define P_FAMILY_TH_SHOU_TECH TRUE
#define P_FAMILY_TH_BYAKUREN_CHIBI TRUE
#define P_FAMILY_TH_BYAKUREN_NORMAL TRUE
#define P_FAMILY_TH_BYAKUREN_DEFENSE TRUE
#define P_FAMILY_TH_BYAKUREN_TECH TRUE
#define P_FAMILY_TH_NUE_CHIBI TRUE
#define P_FAMILY_TH_NUE_NORMAL TRUE
#define P_FAMILY_TH_NUE_ATTACK TRUE
#define P_FAMILY_TH_NUE_TECH TRUE
#define P_FAMILY_TH_OONAMAZU_NORMAL TRUE
#define P_FAMILY_TH_TENSOKU_NORMAL TRUE
#define P_FAMILY_TH_TENSOKU_G TRUE
#define P_FAMILY_TH_HATATE_CHIBI TRUE
#define P_FAMILY_TH_HATATE_NORMAL TRUE
#define P_FAMILY_TH_HATATE_DEFENSE TRUE
#define P_FAMILY_TH_HATATE_TECH TRUE
#define P_FAMILY_TH_KYOUKO_CHIBI TRUE
#define P_FAMILY_TH_KYOUKO_NORMAL TRUE
#define P_FAMILY_TH_YOSHIKA_CHIBI TRUE
#define P_FAMILY_TH_YOSHIKA_NORMAL TRUE
#define P_FAMILY_TH_SEIGA_CHIBI TRUE
#define P_FAMILY_TH_SEIGA_NORMAL TRUE
#define P_FAMILY_TH_TOJIKO_CHIBI TRUE
#define P_FAMILY_TH_TOJIKO_NORMAL TRUE
#define P_FAMILY_TH_FUTO_CHIBI TRUE
#define P_FAMILY_TH_FUTO_NORMAL TRUE
#define P_FAMILY_TH_MIKO_CHIBI TRUE
#define P_FAMILY_TH_MIKO_NORMAL TRUE
#define P_FAMILY_TH_MAMIZOU_CHIBI TRUE
#define P_FAMILY_TH_MAMIZOU_NORMAL TRUE
#define P_FAMILY_TH_KOKORO_CHIBI TRUE
#define P_FAMILY_TH_KOKORO_NORMAL TRUE
#define P_FAMILY_TH_WAKASAGIHIME_CHIBI TRUE
#define P_FAMILY_TH_WAKASAGIHIME_NORMAL TRUE
#define P_FAMILY_TH_SEKIBANKI_CHIBI TRUE
#define P_FAMILY_TH_SEKIBANKI_NORMAL TRUE
#define P_FAMILY_TH_KAGEROU_CHIBI TRUE
#define P_FAMILY_TH_KAGEROU_NORMAL TRUE
#define P_FAMILY_TH_BENBEN_CHIBI TRUE
#define P_FAMILY_TH_BENBEN_NORMAL TRUE
#define P_FAMILY_TH_YATSUHASHI_CHIBI TRUE
#define P_FAMILY_TH_YATSUHASHI_NORMAL TRUE
#define P_FAMILY_TH_SEIJA_CHIBI TRUE
#define P_FAMILY_TH_SEIJA_NORMAL TRUE
#define P_FAMILY_TH_SHINMYOMARU_CHIBI TRUE
#define P_FAMILY_TH_SHINMYOMARU_NORMAL TRUE
#define P_FAMILY_TH_RAIKO_CHIBI TRUE
#define P_FAMILY_TH_RAIKO_NORMAL TRUE
#define P_FAMILY_TH_SEIRAN_CHIBI TRUE
#define P_FAMILY_TH_SEIRAN_NORMAL TRUE
#define P_FAMILY_TH_RINGO_CHIBI TRUE
#define P_FAMILY_TH_RINGO_NORMAL TRUE
#define P_FAMILY_TH_DOREMY_CHIBI TRUE
#define P_FAMILY_TH_DOREMY_NORMAL TRUE
#define P_FAMILY_TH_SAGUME_CHIBI TRUE
#define P_FAMILY_TH_SAGUME_NORMAL TRUE
#define P_FAMILY_TH_CLOWNPIECE_CHIBI TRUE
#define P_FAMILY_TH_CLOWNPIECE_NORMAL TRUE
#define P_FAMILY_TH_JUNKO_CHIBI TRUE
#define P_FAMILY_TH_JUNKO_NORMAL TRUE
#define P_FAMILY_TH_HECATIA_CHIBI TRUE
#define P_FAMILY_TH_HECATIA_NORMAL TRUE
#define P_FAMILY_TH_JOON_CHIBI TRUE
#define P_FAMILY_TH_JOON_NORMAL TRUE
#define P_FAMILY_TH_JOON_ATTACK TRUE
#define P_FAMILY_TH_JOON_DEFENSE TRUE
#define P_FAMILY_TH_SHION_CHIBI TRUE
#define P_FAMILY_TH_SHION_NORMAL TRUE
#define P_FAMILY_TH_SHION_ATTACK TRUE
#define P_FAMILY_TH_SHION_DEFENSE TRUE
#define P_FAMILY_TH_ETERNITY_CHIBI TRUE
#define P_FAMILY_TH_ETERNITY_NORMAL TRUE
#define P_FAMILY_TH_NEMUNO_CHIBI TRUE
#define P_FAMILY_TH_NEMUNO_NORMAL TRUE
#define P_FAMILY_TH_AUNN_CHIBI TRUE
#define P_FAMILY_TH_AUNN_NORMAL TRUE
#define P_FAMILY_TH_NARUMI_CHIBI TRUE
#define P_FAMILY_TH_NARUMI_NORMAL TRUE
#define P_FAMILY_TH_TEIREIDA_MAI_CHIBI TRUE
#define P_FAMILY_TH_TEIREIDA_MAI_NORMAL TRUE
#define P_FAMILY_TH_SATONO_CHIBI TRUE
#define P_FAMILY_TH_SATONO_NORMAL TRUE
#define P_FAMILY_TH_OKINA_CHIBI TRUE
#define P_FAMILY_TH_OKINA_NORMAL TRUE
#define P_FAMILY_TH_EIKA_CHIBI TRUE
#define P_FAMILY_TH_EIKA_NORMAL TRUE
#define P_FAMILY_TH_URUMI_CHIBI TRUE
#define P_FAMILY_TH_URUMI_NORMAL TRUE
#define P_FAMILY_TH_KUTAKA_CHIBI TRUE
#define P_FAMILY_TH_KUTAKA_NORMAL TRUE
#define P_FAMILY_TH_YACHIE_CHIBI TRUE
#define P_FAMILY_TH_YACHIE_NORMAL TRUE
#define P_FAMILY_TH_MAYUMI_CHIBI TRUE
#define P_FAMILY_TH_MAYUMI_NORMAL TRUE
#define P_FAMILY_TH_KEIKI_CHIBI TRUE
#define P_FAMILY_TH_KEIKI_NORMAL TRUE
#define P_FAMILY_TH_SAKI_CHIBI TRUE
#define P_FAMILY_TH_SAKI_NORMAL TRUE
#define P_FAMILY_TH_YUUMA_CHIBI TRUE
#define P_FAMILY_TH_YUUMA_NORMAL TRUE
#define P_FAMILY_TH_MIKE_CHIBI TRUE
#define P_FAMILY_TH_MIKE_NORMAL TRUE
#define P_FAMILY_TH_TAKANE_CHIBI TRUE
#define P_FAMILY_TH_TAKANE_NORMAL TRUE
#define P_FAMILY_TH_SANNYO_CHIBI TRUE
#define P_FAMILY_TH_SANNYO_NORMAL TRUE
#define P_FAMILY_TH_MISUMARU_CHIBI TRUE
#define P_FAMILY_TH_MISUMARU_NORMAL TRUE
#define P_FAMILY_TH_TSUKASA_CHIBI TRUE
#define P_FAMILY_TH_TSUKASA_NORMAL TRUE
#define P_FAMILY_TH_MEGUMU_CHIBI TRUE
#define P_FAMILY_TH_MEGUMU_NORMAL TRUE
#define P_FAMILY_TH_CHIMATA_CHIBI TRUE
#define P_FAMILY_TH_CHIMATA_NORMAL TRUE
#define P_FAMILY_TH_MOMOYO_CHIBI TRUE
#define P_FAMILY_TH_MOMOYO_NORMAL TRUE
#define P_FAMILY_TH_BITEN_CHIBI TRUE
#define P_FAMILY_TH_BITEN_NORMAL TRUE
#define P_FAMILY_TH_ENOKO_CHIBI TRUE
#define P_FAMILY_TH_ENOKO_NORMAL TRUE
#define P_FAMILY_TH_CHIYARI_CHIBI TRUE
#define P_FAMILY_TH_CHIYARI_NORMAL TRUE
#define P_FAMILY_TH_HISAMI_CHIBI TRUE
#define P_FAMILY_TH_HISAMI_NORMAL TRUE
#define P_FAMILY_TH_ZANMU_CHIBI TRUE
#define P_FAMILY_TH_ZANMU_NORMAL TRUE
#define P_FAMILY_TH_KASEN_CHIBI TRUE
#define P_FAMILY_TH_KASEN_NORMAL TRUE
#define P_FAMILY_TH_KASEN_ARM TRUE
#define P_FAMILY_TH_TENMA_CHIBI TRUE
#define P_FAMILY_TH_TENMA_NORMAL TRUE
#define P_FAMILY_TH_TENMA_SPEED TRUE
#define P_FAMILY_TH_SENDAI_CHIBI TRUE
#define P_FAMILY_TH_SENDAI_NORMAL TRUE
#define P_FAMILY_TH_SENDAI_TECH TRUE
#define P_FAMILY_TH_TOKIKO_CHIBI TRUE
#define P_FAMILY_TH_TOKIKO_NORMAL TRUE
#define P_FAMILY_TH_TOKIKO_ATTACK TRUE
#define P_FAMILY_TH_RINNOSUKE_NORMAL TRUE
#define P_FAMILY_TH_AKYUU_NORMAL TRUE
#define P_FAMILY_TH_KOSUZU_CHIBI TRUE
#define P_FAMILY_TH_KOSUZU_NORMAL TRUE
#define P_FAMILY_TH_KOSUZU_ATTACK TRUE
#define P_FAMILY_TH_MIYOI_CHIBI TRUE
#define P_FAMILY_TH_MIYOI_NORMAL TRUE
#define P_FAMILY_TH_MIZUCHI_CHIBI TRUE
#define P_FAMILY_TH_MIZUCHI_NORMAL TRUE
#define P_FAMILY_TH_MARIBEL_NORMAL TRUE
#define P_FAMILY_TH_RENKO_NORMAL TRUE
#define P_FAMILY_TH_SUMIREKO_NORMAL TRUE
#define P_FAMILY_TH_MARISA_NORMAL TRUE
#define P_FAMILY_TH_MARISA_ADVENT TRUE
#define P_FAMILY_TH_REIMU_NORMAL TRUE
#define P_FAMILY_TH_REIMU_ADVENT TRUE
#define P_FAMILY_SH_VIVIT_ANDROID TRUE
#define P_FAMILY_SH_VIVIT_SPHERE TRUE
#define P_FAMILY_ETC_ISAMI_NORMAL TRUE
#define P_FAMILY_KEY_MISUZU_CHIBI TRUE
#define P_FAMILY_KEY_MISUZU_NORMAL TRUE
#define P_FAMILY_KEY_MISUZU_EX TRUE
#define P_FAMILY_KEY_KANO_CHIBI TRUE
#define P_FAMILY_KEY_KANO_NORMAL TRUE
#define P_FAMILY_KEY_KANO_EX TRUE
#define P_FAMILY_KEY_MINAGI_CHIBI TRUE
#define P_FAMILY_KEY_MINAGI_NORMAL TRUE
#define P_FAMILY_KEY_MINAGI_EX TRUE
#define P_FAMILY_KEY_HARUKO_CHIBI TRUE
#define P_FAMILY_KEY_HARUKO_NORMAL TRUE
#define P_FAMILY_KEY_HARUKO_EX TRUE
#define P_FAMILY_KEY_KANNA_CHIBI TRUE
#define P_FAMILY_KEY_KANNA_NORMAL TRUE
#define P_FAMILY_KEY_HIJIRI_CHIBI TRUE
#define P_FAMILY_KEY_HIJIRI_NORMAL TRUE
#define P_FAMILY_KEY_HIJIRI_EX TRUE
#define P_FAMILY_KEY_MICHIRU_CHIBI TRUE
#define P_FAMILY_KEY_MICHIRU_NORMAL TRUE
#define P_FAMILY_KEY_MICHIRU_EX TRUE
#define P_FAMILY_KEY_URAHA_CHIBI TRUE
#define P_FAMILY_KEY_URAHA_NORMAL TRUE
#define P_FAMILY_KEY_URAHA_EX TRUE
#define P_FAMILY_KEY_POTATO_NORMAL TRUE
#define P_FAMILY_KEY_SORA_NORMAL TRUE
#define P_FAMILY_KEY_AYU_CHIBI TRUE
#define P_FAMILY_KEY_AYU_NORMAL TRUE
#define P_FAMILY_KEY_AYU_EX TRUE
#define P_FAMILY_KEY_MAI_CHIBI TRUE
#define P_FAMILY_KEY_MAI_NORMAL TRUE
#define P_FAMILY_KEY_MAI_EX TRUE
#define P_FAMILY_KEY_NAYUKI_CHIBI TRUE
#define P_FAMILY_KEY_NAYUKI_NORMAL TRUE
#define P_FAMILY_KEY_NAYUKI_EX TRUE
#define P_FAMILY_KEY_SHIORI_CHIBI TRUE
#define P_FAMILY_KEY_SHIORI_NORMAL TRUE
#define P_FAMILY_KEY_SHIORI_EX TRUE
#define P_FAMILY_KEY_MAKOTO_CHIBI TRUE
#define P_FAMILY_KEY_MAKOTO_NORMAL TRUE
#define P_FAMILY_KEY_MAKOTO_EX TRUE
#define P_FAMILY_KEY_MISHIO_CHIBI TRUE
#define P_FAMILY_KEY_MISHIO_NORMAL TRUE
#define P_FAMILY_KEY_SAYURI_CHIBI TRUE
#define P_FAMILY_KEY_SAYURI_NORMAL TRUE
#define P_FAMILY_KEY_SAYURI_EX TRUE
#define P_FAMILY_KEY_AKIKO_CHIBI TRUE
#define P_FAMILY_KEY_AKIKO_NORMAL TRUE
#define P_FAMILY_KEY_AKIKO_EX TRUE
#define P_FAMILY_KEY_KAORI_CHIBI TRUE
#define P_FAMILY_KEY_KAORI_NORMAL TRUE
#define P_FAMILY_KEY_PIRO_NORMAL TRUE
#define P_FAMILY_KEY_NAGISA_CHIBI TRUE
#define P_FAMILY_KEY_NAGISA_NORMAL TRUE
#define P_FAMILY_KEY_NAGISA_EX TRUE
#define P_FAMILY_KEY_KYOU_CHIBI TRUE
#define P_FAMILY_KEY_KYOU_NORMAL TRUE
#define P_FAMILY_KEY_KYOU_EX TRUE
#define P_FAMILY_KEY_RYOU_CHIBI TRUE
#define P_FAMILY_KEY_RYOU_NORMAL TRUE
#define P_FAMILY_KEY_RYOU_EX TRUE
#define P_FAMILY_KEY_KOTOMI_CHIBI TRUE
#define P_FAMILY_KEY_KOTOMI_NORMAL TRUE
#define P_FAMILY_KEY_KOTOMI_EX TRUE
#define P_FAMILY_KEY_TOMOYO_CHIBI TRUE
#define P_FAMILY_KEY_TOMOYO_NORMAL TRUE
#define P_FAMILY_KEY_TOMOYO_EX TRUE
#define P_FAMILY_KEY_FUUKO_CHIBI TRUE
#define P_FAMILY_KEY_FUUKO_NORMAL TRUE
#define P_FAMILY_KEY_FUUKO_EX TRUE
#define P_FAMILY_KEY_YUKINE_CHIBI TRUE
#define P_FAMILY_KEY_YUKINE_NORMAL TRUE
#define P_FAMILY_KEY_YUKINE_EX TRUE
#define P_FAMILY_KEY_MISAE_CHIBI TRUE
#define P_FAMILY_KEY_MISAE_NORMAL TRUE
#define P_FAMILY_KEY_MISAE_EX TRUE
#define P_FAMILY_KEY_SANAE_CHIBI TRUE
#define P_FAMILY_KEY_SANAE_NORMAL TRUE
#define P_FAMILY_KEY_SANAE_EX TRUE
#define P_FAMILY_KEY_MEI_CHIBI TRUE
#define P_FAMILY_KEY_MEI_NORMAL TRUE
#define P_FAMILY_KEY_USHIO_CHIBI TRUE
#define P_FAMILY_KEY_USHIO_NORMAL TRUE
#define P_FAMILY_KEY_BOTAN_NORMAL TRUE
#define P_FAMILY_KEY_RIN_CHIBI TRUE
#define P_FAMILY_KEY_RIN_NORMAL TRUE
#define P_FAMILY_KEY_RIN_EX TRUE
#define P_FAMILY_KEY_KOMARI_CHIBI TRUE
#define P_FAMILY_KEY_KOMARI_NORMAL TRUE
#define P_FAMILY_KEY_KOMARI_EX TRUE
#define P_FAMILY_KEY_YUIKO_CHIBI TRUE
#define P_FAMILY_KEY_YUIKO_NORMAL TRUE
#define P_FAMILY_KEY_YUIKO_EX TRUE
#define P_FAMILY_KEY_MIO_CHIBI TRUE
#define P_FAMILY_KEY_MIO_NORMAL TRUE
#define P_FAMILY_KEY_MIO_EX TRUE
#define P_FAMILY_KEY_HARUKA_CHIBI TRUE
#define P_FAMILY_KEY_HARUKA_NORMAL TRUE
#define P_FAMILY_KEY_HARUKA_EX TRUE
#define P_FAMILY_KEY_KUD_CHIBI TRUE
#define P_FAMILY_KEY_KUD_NORMAL TRUE
#define P_FAMILY_KEY_KUD_EX TRUE
#define P_FAMILY_KEY_KANATA_CHIBI TRUE
#define P_FAMILY_KEY_KANATA_NORMAL TRUE
#define P_FAMILY_KEY_KANATA_EX TRUE
#define P_FAMILY_KEY_SASAMI_CHIBI TRUE
#define P_FAMILY_KEY_SASAMI_NORMAL TRUE
#define P_FAMILY_KEY_SASAMI_EX TRUE
#define P_FAMILY_BGHS_MIKI_NORMAL TRUE
#define P_FAMILY_BGHS_MIKI_FLORA TRUE
#define P_FAMILY_BGHS_SUBARU_NORMAL TRUE
#define P_FAMILY_BGHS_SUBARU_FLORA TRUE
#define P_FAMILY_BGHS_HARUKA_NORMAL TRUE
#define P_FAMILY_BGHS_HARUKA_FLORA TRUE
#define P_FAMILY_BGHS_NOZOMI_NORMAL TRUE
#define P_FAMILY_BGHS_NOZOMI_FLORA TRUE
#define P_FAMILY_BGHS_YURI_NORMAL TRUE
#define P_FAMILY_BGHS_YURI_FLORA TRUE
#define P_FAMILY_BGHS_KURUMI_NORMAL TRUE
#define P_FAMILY_BGHS_KURUMI_FLORA TRUE
#define P_FAMILY_BGHS_KURUMI_ALTER TRUE
#define P_FAMILY_BGHS_ANKO_NORMAL TRUE
#define P_FAMILY_BGHS_ANKO_FLORA TRUE
#define P_FAMILY_BGHS_ANKO_ALTER TRUE
#define P_FAMILY_BGHS_RENGE_NORMAL TRUE
#define P_FAMILY_BGHS_RENGE_FLORA TRUE
#define P_FAMILY_BGHS_ASUHA_NORMAL TRUE
#define P_FAMILY_BGHS_ASUHA_FLORA TRUE
#define P_FAMILY_BGHS_SAKURA_NORMAL TRUE
#define P_FAMILY_BGHS_SAKURA_FLORA TRUE
#define P_FAMILY_BGHS_HINATA_NORMAL TRUE
#define P_FAMILY_BGHS_HINATA_FLORA TRUE
#define P_FAMILY_BGHS_HINATA_ALTER TRUE
#define P_FAMILY_BGHS_KAEDE_NORMAL TRUE
#define P_FAMILY_BGHS_KAEDE_FLORA TRUE
#define P_FAMILY_BGHS_MICHAEL_NORMAL TRUE
#define P_FAMILY_BGHS_MICHAEL_FLORA TRUE
#define P_FAMILY_BGHS_KOKOMI_NORMAL TRUE
#define P_FAMILY_BGHS_KOKOMI_FLORA TRUE
#define P_FAMILY_BGHS_URARA_NORMAL TRUE
#define P_FAMILY_BGHS_URARA_FLORA TRUE
#define P_FAMILY_BGHS_SADONE_NORMAL TRUE
#define P_FAMILY_BGHS_SADONE_FLORA TRUE
#define P_FAMILY_BGHS_KANON_NORMAL TRUE
#define P_FAMILY_BGHS_KANON_FLORA TRUE
#define P_FAMILY_BGHS_KANON_FORTESSIMO TRUE
#define P_FAMILY_BGHS_SHIHO_NORMAL TRUE
#define P_FAMILY_BGHS_SHIHO_FLORA TRUE
#define P_FAMILY_BGHS_SHIHO_FORTESSIMO TRUE
#define P_FAMILY_BGHS_MISAKI_NORMAL TRUE
#define P_FAMILY_BGHS_MISAKI_FLORA TRUE
#define P_FAMILY_BGHS_MARI_NORMAL TRUE
#define P_FAMILY_BGHS_MARI_FLORA TRUE
#define P_FAMILY_BGHS_ERIS TRUE
#define P_FAMILY_BGHS_ITSUKI_NORMAL TRUE
#define P_FAMILY_BGHS_ITSUKI_FLORA TRUE
#define P_FAMILY_BGHS_FURAN_NORMAL TRUE
#define P_FAMILY_BGHS_FURAN_FLORA TRUE
#define P_FAMILY_BGHS_ERIKA_NORMAL TRUE
#define P_FAMILY_BGHS_ERIKA_FLORA TRUE
#define P_FAMILY_BGHS_EVINA TRUE
#define P_FAMILY_BGHS_AOI_NORMAL TRUE
#define P_FAMILY_BGHS_AOI_FLORA TRUE
#define P_FAMILY_BGHS_BOTAN_NORMAL TRUE
#define P_FAMILY_PC_CURE_BLACK_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_BLACK_NORMAL TRUE
#define P_FAMILY_PC_CURE_BLACK_GOLD TRUE
#define P_FAMILY_PC_CURE_WHITE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_WHITE_NORMAL TRUE
#define P_FAMILY_PC_CURE_WHITE_GOLD TRUE
#define P_FAMILY_PC_SHINY_LUMINOUS_UNTRANSFORMED TRUE
#define P_FAMILY_PC_SHINY_LUMINOUS_NORMAL TRUE
#define P_FAMILY_PC_SHINY_LUMINOUS_GOLD TRUE
#define P_FAMILY_PC_CURE_BLOOM_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_BLOOM_NORMAL TRUE
#define P_FAMILY_PC_CURE_BRIGHT_NORMAL TRUE
#define P_FAMILY_PC_CURE_EGRET_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_EGRET_NORMAL TRUE
#define P_FAMILY_PC_CURE_WINDY_NORMAL TRUE
#define P_FAMILY_PC_CURE_DREAM_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_DREAM_NORMAL_S1 TRUE
#define P_FAMILY_PC_CURE_DREAM_NORMAL_S2 TRUE
#define P_FAMILY_PC_CURE_DREAM_SUPER TRUE
#define P_FAMILY_PC_CURE_ROUGE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_ROUGE_NORMAL_S1 TRUE
#define P_FAMILY_PC_CURE_ROUGE_NORMAL_S2 TRUE
#define P_FAMILY_PC_CURE_ROUGE_SUPER TRUE
#define P_FAMILY_PC_CURE_LEMONADE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_LEMONADE_NORMAL_S1 TRUE
#define P_FAMILY_PC_CURE_LEMONADE_NORMAL_S2 TRUE
#define P_FAMILY_PC_CURE_LEMONADE_SUPER TRUE
#define P_FAMILY_PC_CURE_MINT_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_MINT_NORMAL_S1 TRUE
#define P_FAMILY_PC_CURE_MINT_NORMAL_S2 TRUE
#define P_FAMILY_PC_CURE_MINT_SUPER TRUE
#define P_FAMILY_PC_CURE_AQUA_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_AQUA_NORMAL_S1 TRUE
#define P_FAMILY_PC_CURE_AQUA_NORMAL_S2 TRUE
#define P_FAMILY_PC_CURE_AQUA_SUPER TRUE
#define P_FAMILY_PC_MILKY_ROSE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_MILKY_ROSE_NORMAL TRUE
#define P_FAMILY_PC_MILKY_ROSE_SUPER TRUE
#define P_FAMILY_PC_DARK_DREAM TRUE
#define P_FAMILY_PC_DARK_ROUGE TRUE
#define P_FAMILY_PC_DARK_LEMONADE TRUE
#define P_FAMILY_PC_DARK_MINT TRUE
#define P_FAMILY_PC_DARK_AQUA TRUE
#define P_FAMILY_PC_CURE_PEACH_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_PEACH_NORMAL TRUE
#define P_FAMILY_PC_CURE_PEACH_SUPER TRUE
#define P_FAMILY_PC_CURE_BERRY_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_BERRY_NORMAL TRUE
#define P_FAMILY_PC_CURE_BERRY_SUPER TRUE
#define P_FAMILY_PC_CURE_PINE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_PINE_NORMAL TRUE
#define P_FAMILY_PC_CURE_PINE_SUPER TRUE
#define P_FAMILY_PC_CURE_PASSION_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_PASSION_NORMAL TRUE
#define P_FAMILY_PC_CURE_PASSION_SUPER TRUE
#define P_FAMILY_PC_EAS TRUE
#define P_FAMILY_PC_CURE_BLOSSOM_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_BLOSSOM_NORMAL TRUE
#define P_FAMILY_PC_CURE_BLOSSOM_SUPER TRUE
#define P_FAMILY_PC_CURE_MARINE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_MARINE_NORMAL TRUE
#define P_FAMILY_PC_CURE_MARINE_SUPER TRUE
#define P_FAMILY_PC_CURE_SUNSHINE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_SUNSHINE_NORMAL TRUE
#define P_FAMILY_PC_CURE_SUNSHINE_SUPER TRUE
#define P_FAMILY_PC_CURE_MOONLIGHT_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_MOONLIGHT_NORMAL TRUE
#define P_FAMILY_PC_CURE_MOONLIGHT_SUPER TRUE
#define P_FAMILY_PC_DARK_PRECURE TRUE
#define P_FAMILY_PC_CURE_FLORA_HCPC TRUE
#define P_FAMILY_PC_CURE_MELODY_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_MELODY_NORMAL TRUE
#define P_FAMILY_PC_CURE_MELODY_SUPER TRUE
#define P_FAMILY_PC_CURE_RHYTHM_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_RHYTHM_NORMAL TRUE
#define P_FAMILY_PC_CURE_RHYTHM_SUPER TRUE
#define P_FAMILY_PC_CURE_BEAT_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_BEAT_NORMAL TRUE
#define P_FAMILY_PC_CURE_BEAT_SUPER TRUE
#define P_FAMILY_PC_CURE_MUSE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_MUSE_NORMAL TRUE
#define P_FAMILY_PC_CURE_MUSE_MASKED TRUE
#define P_FAMILY_PC_CURE_MUSE_SUPER TRUE
#define P_FAMILY_PC_CURE_HAPPY_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_HAPPY_NORMAL TRUE
#define P_FAMILY_PC_CURE_HAPPY_PRINCESS TRUE
#define P_FAMILY_PC_CURE_SUNNY_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_SUNNY_NORMAL TRUE
#define P_FAMILY_PC_CURE_SUNNY_PRINCESS TRUE
#define P_FAMILY_PC_CURE_PEACE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_PEACE_NORMAL TRUE
#define P_FAMILY_PC_CURE_PEACE_PRINCESS TRUE
#define P_FAMILY_PC_CURE_MARCH_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_MARCH_NORMAL TRUE
#define P_FAMILY_PC_CURE_MARCH_PRINCESS TRUE
#define P_FAMILY_PC_CURE_BEAUTY_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_BEAUTY_NORMAL TRUE
#define P_FAMILY_PC_CURE_BEAUTY_PRINCESS TRUE
#define P_FAMILY_PC_BAD_END_HAPPY TRUE
#define P_FAMILY_PC_BAD_END_SUNNY TRUE
#define P_FAMILY_PC_BAD_END_PEACE TRUE
#define P_FAMILY_PC_BAD_END_MARCH TRUE
#define P_FAMILY_PC_BAD_END_BEAUTY TRUE
#define P_FAMILY_PC_CURE_ECHO_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_ECHO_NORMAL TRUE
#define P_FAMILY_PC_CURE_HEART_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_HEART_NORMAL TRUE
#define P_FAMILY_PC_CURE_HEART_SUPER TRUE
#define P_FAMILY_PC_CURE_DIAMOND_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_DIAMOND_NORMAL TRUE
#define P_FAMILY_PC_CURE_DIAMOND_SUPER TRUE
#define P_FAMILY_PC_CURE_ROSETTA_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_ROSETTA_NORMAL TRUE
#define P_FAMILY_PC_CURE_ROSETTA_SUPER TRUE
#define P_FAMILY_PC_CURE_SWORD_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_SWORD_NORMAL TRUE
#define P_FAMILY_PC_CURE_SWORD_SUPER TRUE
#define P_FAMILY_PC_CURE_ACE_UNTRANSFORMED TRUE
#define P_FAMILY_PC_CURE_ACE_NORMAL TRUE
#define P_FAMILY_PC_CURE_ACE_SUPER TRUE
#define P_FAMILY_PC_REGINA TRUE
#define P_FAMILY_FRAGMON_1629 TRUE
#define P_FAMILY_FRAGMON_1630 TRUE
#define P_FAMILY_FRAGMON_1631 TRUE
#define P_FAMILY_FRAGMON_1632 TRUE
#define P_FAMILY_FRAGMON_1633 TRUE
#define P_FAMILY_FRAGMON_1634 TRUE
#define P_FAMILY_FRAGMON_1635 TRUE
#define P_FAMILY_FRAGMON_1636 TRUE
#define P_FAMILY_FRAGMON_1637 TRUE
#define P_FAMILY_FRAGMON_1638 TRUE
#define P_FAMILY_FRAGMON_1639 TRUE
#define P_FAMILY_FRAGMON_1640 TRUE
#define P_FAMILY_FRAGMON_1641 TRUE
#define P_FAMILY_FRAGMON_1642 TRUE
#define P_FAMILY_FRAGMON_1643 TRUE
#define P_FAMILY_FRAGMON_1644 TRUE
#define P_FAMILY_FRAGMON_1645 TRUE
#define P_FAMILY_FRAGMON_1646 TRUE
#define P_FAMILY_FRAGMON_1647 TRUE
#define P_FAMILY_FRAGMON_1648 TRUE
#define P_FAMILY_FRAGMON_1649 TRUE
#define P_FAMILY_FRAGMON_1650 TRUE
#define P_FAMILY_FRAGMON_1651 TRUE
#define P_FAMILY_FRAGMON_1652 TRUE
#define P_FAMILY_FRAGMON_1653 TRUE
#define P_FAMILY_FRAGMON_1654 TRUE
#define P_FAMILY_FRAGMON_1655 TRUE
#define P_FAMILY_FRAGMON_1656 TRUE
#define P_FAMILY_FRAGMON_1657 TRUE
#define P_FAMILY_FRAGMON_1658 TRUE
#define P_FAMILY_FRAGMON_1659 TRUE
#define P_FAMILY_FRAGMON_1660 TRUE
#define P_FAMILY_FRAGMON_1661 TRUE
#define P_FAMILY_FRAGMON_1662 TRUE
#define P_FAMILY_FRAGMON_1663 TRUE
#define P_FAMILY_FRAGMON_1664 TRUE
#define P_FAMILY_FRAGMON_1665 TRUE
#define P_FAMILY_FRAGMON_1666 TRUE
#define P_FAMILY_FRAGMON_1667 TRUE
#define P_FAMILY_FRAGMON_1668 TRUE
#define P_FAMILY_FRAGMON_1669 TRUE
#define P_FAMILY_FRAGMON_1670 TRUE
#define P_FAMILY_FRAGMON_1671 TRUE
#define P_FAMILY_FRAGMON_1672 TRUE
#define P_FAMILY_FRAGMON_1673 TRUE
#define P_FAMILY_FRAGMON_1674 TRUE
#define P_FAMILY_FRAGMON_1675 TRUE
#define P_FAMILY_FRAGMON_1676 TRUE
#define P_FAMILY_FRAGMON_1677 TRUE
#define P_FAMILY_FRAGMON_1678 TRUE
#define P_FAMILY_FRAGMON_1679 TRUE
#define P_FAMILY_FRAGMON_1680 TRUE
#define P_FAMILY_FRAGMON_1681 TRUE
#define P_FAMILY_FRAGMON_1682 TRUE
#define P_FAMILY_FRAGMON_1683 TRUE
#define P_FAMILY_FRAGMON_1684 TRUE
#define P_FAMILY_FRAGMON_1685 TRUE
#define P_FAMILY_FRAGMON_1686 TRUE
#define P_FAMILY_FRAGMON_1687 TRUE
#define P_FAMILY_FRAGMON_1688 TRUE
#define P_FAMILY_FRAGMON_1689 TRUE
#define P_FAMILY_FRAGMON_1690 TRUE
#define P_FAMILY_FRAGMON_1691 TRUE
#define P_FAMILY_FRAGMON_1692 TRUE
#define P_FAMILY_FRAGMON_1693 TRUE
#define P_FAMILY_FRAGMON_1694 TRUE
#define P_FAMILY_FRAGMON_1695 TRUE
#define P_FAMILY_FRAGMON_1696 TRUE
#define P_FAMILY_FRAGMON_1697 TRUE
#define P_FAMILY_FRAGMON_1698 TRUE
#define P_FAMILY_FRAGMON_1699 TRUE
#define P_FAMILY_FRAGMON_1700 TRUE
#define P_FAMILY_FRAGMON_1701 TRUE
#define P_FAMILY_FRAGMON_1702 TRUE
#define P_FAMILY_FRAGMON_1703 TRUE
#define P_FAMILY_FRAGMON_1704 TRUE
#define P_FAMILY_FRAGMON_1705 TRUE
#define P_FAMILY_FRAGMON_1706 TRUE
#define P_FAMILY_FRAGMON_1707 TRUE
#define P_FAMILY_FRAGMON_1708 TRUE
#define P_FAMILY_FRAGMON_1709 TRUE
#define P_FAMILY_FRAGMON_1710 TRUE
#define P_FAMILY_FRAGMON_1711 TRUE
#define P_FAMILY_FRAGMON_1712 TRUE
#define P_FAMILY_FRAGMON_1713 TRUE
#define P_FAMILY_FRAGMON_1714 TRUE
#define P_FAMILY_FRAGMON_1715 TRUE
#define P_FAMILY_FRAGMON_1716 TRUE
#define P_FAMILY_FRAGMON_1717 TRUE
#define P_FAMILY_FRAGMON_1718 TRUE
#define P_FAMILY_FRAGMON_1719 TRUE
#define P_FAMILY_FRAGMON_1720 TRUE
#define P_FAMILY_FRAGMON_1721 TRUE
#define P_FAMILY_FRAGMON_1722 TRUE
#define P_FAMILY_FRAGMON_1723 TRUE
#define P_FAMILY_FRAGMON_1724 TRUE
#define P_FAMILY_FRAGMON_1725 TRUE
#define P_FAMILY_FRAGMON_1726 TRUE
#define P_FAMILY_FRAGMON_1727 TRUE
#define P_FAMILY_FRAGMON_1728 TRUE
#define P_FAMILY_FRAGMON_1729 TRUE
#define P_FAMILY_FRAGMON_1730 TRUE
#define P_FAMILY_FRAGMON_1731 TRUE
#define P_FAMILY_FRAGMON_1732 TRUE
#define P_FAMILY_FRAGMON_1733 TRUE
#define P_FAMILY_FRAGMON_1734 TRUE
#define P_FAMILY_FRAGMON_1735 TRUE
#define P_FAMILY_FRAGMON_1736 TRUE
#define P_FAMILY_FRAGMON_1737 TRUE
#define P_FAMILY_FRAGMON_1738 TRUE
#define P_FAMILY_FRAGMON_1739 TRUE
#define P_FAMILY_FRAGMON_1740 TRUE
#define P_FAMILY_FRAGMON_1741 TRUE
#define P_FAMILY_FRAGMON_1742 TRUE
#define P_FAMILY_FRAGMON_1743 TRUE
#define P_FAMILY_FRAGMON_1744 TRUE
#define P_FAMILY_FRAGMON_1745 TRUE
#define P_FAMILY_FRAGMON_1746 TRUE
#define P_FAMILY_FRAGMON_1747 TRUE
#define P_FAMILY_FRAGMON_1748 TRUE
#define P_FAMILY_FRAGMON_1749 TRUE
#define P_FAMILY_FRAGMON_1750 TRUE
#define P_FAMILY_FRAGMON_1751 TRUE
#define P_FAMILY_FRAGMON_1752 TRUE
#define P_FAMILY_FRAGMON_1753 TRUE
#define P_FAMILY_FRAGMON_1754 TRUE
#define P_FAMILY_FRAGMON_1755 TRUE
#define P_FAMILY_FRAGMON_1756 TRUE
#define P_FAMILY_FRAGMON_1757 TRUE
#define P_FAMILY_FRAGMON_1758 TRUE
#define P_FAMILY_FRAGMON_1759 TRUE
#define P_FAMILY_FRAGMON_1760 TRUE
#define P_FAMILY_FRAGMON_1761 TRUE
#define P_FAMILY_FRAGMON_1762 TRUE
#define P_FAMILY_FRAGMON_1763 TRUE
#define P_FAMILY_FRAGMON_1764 TRUE
#define P_FAMILY_FRAGMON_1765 TRUE
#define P_FAMILY_FRAGMON_1766 TRUE
#define P_FAMILY_FRAGMON_1767 TRUE
#define P_FAMILY_FRAGMON_1768 TRUE
#define P_FAMILY_FRAGMON_1769 TRUE
#define P_FAMILY_FRAGMON_1770 TRUE
#define P_FAMILY_FRAGMON_1771 TRUE
#define P_FAMILY_FRAGMON_1772 TRUE
#define P_FAMILY_FRAGMON_1773 TRUE
#define P_FAMILY_FRAGMON_1774 TRUE
#define P_FAMILY_FRAGMON_1775 TRUE
#define P_FAMILY_FRAGMON_1776 TRUE
#define P_FAMILY_FRAGMON_1777 TRUE
#define P_FAMILY_FRAGMON_1778 TRUE
#define P_FAMILY_FRAGMON_1779 TRUE
#define P_FAMILY_FRAGMON_1780 TRUE
#define P_FAMILY_FRAGMON_1781 TRUE
#define P_FAMILY_FRAGMON_1782 TRUE
#define P_FAMILY_FRAGMON_1783 TRUE
#define P_FAMILY_FRAGMON_1784 TRUE
#define P_FAMILY_ETC_WUPI TRUE
#define P_FAMILY_ETC_MIKU TRUE
#define P_FAMILY_ETC_MIKU_MAGICAL TRUE
#define P_FAMILY_ETC_MIKU_SNOW TRUE
#define P_FAMILY_ETC_MIKU_ANGEL TRUE
#define P_FAMILY_ETC_MIKU_RACING TRUE
#define P_FAMILY_ETC_FOXYRIA TRUE
#define P_FAMILY_ETC_NIMI TRUE
#define P_FAMILY_ETC_ANYA TRUE
#define P_FAMILY_ETC_GURA TRUE
#define P_FAMILY_ETC_AMELIA TRUE
#define P_FAMILY_ETC_INANIS TRUE
#define P_FAMILY_ETC_YABUSAME TRUE
#define P_FAMILY_ETC_TSUBAKURA TRUE
#define P_FAMILY_ETC_NEPTUNE_NORMAL TRUE
#define P_FAMILY_ETC_NEPGEAR_NORMAL TRUE
#define P_FAMILY_ETC_CURE_UNION_NORMAL TRUE
#define P_FAMILY_ETC_EMESGESEY TRUE
#define P_FAMILY_ETC_SHOUNEN TRUE
#define P_FAMILY_ETC_RED TRUE
#define P_FAMILY_ETC_ETHAN TRUE
#define P_FAMILY_ETC_BRENDAN TRUE
#define P_FAMILY_ETC_LUCAS TRUE
#define P_FAMILY_ETC_HILBERT TRUE
#define P_FAMILY_ETC_NATE TRUE
#define P_FAMILY_ETC_CALEM TRUE
#define P_FAMILY_ETC_ELIO TRUE
#define P_FAMILY_ETC_CHASE TRUE
#define P_FAMILY_ETC_VICTOR TRUE
#define P_FAMILY_ETC_REI TRUE
#define P_FAMILY_ETC_FLORIAN TRUE
#define P_FAMILY_ETC_WES TRUE
#define P_FAMILY_ETC_MICHAEL TRUE
#define P_FAMILY_ETC_SHOUJO TRUE
#define P_FAMILY_ETC_LEAF TRUE
#define P_FAMILY_ETC_LYRA TRUE
#define P_FAMILY_ETC_KRIS TRUE
#define P_FAMILY_ETC_MAY TRUE
#define P_FAMILY_ETC_DAWN TRUE
#define P_FAMILY_ETC_HILDA TRUE
#define P_FAMILY_ETC_ROSA TRUE
#define P_FAMILY_ETC_SERENA TRUE
#define P_FAMILY_ETC_SELENE TRUE
#define P_FAMILY_ETC_ELAINE TRUE
#define P_FAMILY_ETC_GLORIA TRUE
#define P_FAMILY_ETC_AKARI TRUE
#define P_FAMILY_ETC_JULIANA TRUE
#define P_FAMILY_ETC_DIALGA_TH TRUE
#define P_FAMILY_ETC_PALKIA_TH TRUE
#define P_FAMILY_ETC_GIRATINA_TH TRUE
#define P_FAMILY_ETC_ARCEUS_TH TRUE
#define P_FAMILY_ETC_ILLYASVIEL_NORMAL TRUE
#define P_FAMILY_ETC_CHLOE_NORMAL TRUE
#define P_FAMILY_ETC_DECADE_NORMAL TRUE
#define P_FAMILY_ETC_DECADE_COMPLETE TRUE
#define P_FAMILY_ETC_DECADE_COMPLETE21 TRUE
#define P_FAMILY_ETC_DIEND_NORMAL TRUE
#define P_FAMILY_ETC_DIEND_COMPLETE TRUE
#define P_FAMILY_ETC_DELAST TRUE
#define P_FAMILY_MOE_LUGIA_SHADOW TRUE
#define P_FAMILY_MOE_PIKACHU_PARTNER TRUE
#define P_FAMILY_MOE_EEVEE_PARTNER TRUE
#define P_FAMILY_FRAGMON_1850 TRUE
#define P_FAMILY_TH_REIMU_CTC TRUE
#define P_FAMILY_SH_VIVIT_ANGEL TRUE
#define P_FAMILY_MOE_VENUSAUR_MEGA TRUE
#define P_FAMILY_MOE_CHARIZARD_MEGA_X TRUE
#define P_FAMILY_MOE_CHARIZARD_MEGA_Y TRUE
#define P_FAMILY_MOE_BLASTOISE_MEGA TRUE
#define P_FAMILY_MOE_BEEDRILL_MEGA TRUE
#define P_FAMILY_MOE_PIDGEOT_MEGA TRUE
#define P_FAMILY_MOE_ALAKAZAM_MEGA TRUE
#define P_FAMILY_MOE_SLOWBRO_MEGA TRUE
#define P_FAMILY_MOE_GENGAR_MEGA TRUE
#define P_FAMILY_MOE_KANGASKHAN_MEGA TRUE
#define P_FAMILY_MOE_PINSIR_MEGA TRUE
#define P_FAMILY_MOE_GYARADOS_MEGA TRUE
#define P_FAMILY_MOE_AERODACTYL_MEGA TRUE
#define P_FAMILY_MOE_MEWTWO_MEGA_X TRUE
#define P_FAMILY_MOE_MEWTWO_MEGA_Y TRUE
#define P_FAMILY_MOE_AMPHAROS_MEGA TRUE
#define P_FAMILY_MOE_STEELIX_MEGA TRUE
#define P_FAMILY_MOE_SCIZOR_MEGA TRUE
#define P_FAMILY_MOE_HERACROSS_MEGA TRUE
#define P_FAMILY_MOE_HOUNDOOM_MEGA TRUE
#define P_FAMILY_MOE_TYRANITAR_MEGA TRUE
#define P_FAMILY_YYYI_WAKABA_KIRIFUDA2 TRUE
#define P_FAMILY_YYYI_TAKASHIMA_YUUNA_KIRIFUDA2 TRUE
#define P_FAMILY_YYYI_YUUKI_YUUNA_DAIMANKAI TRUE
#define P_FAMILY_TH_ALICE_BLACK_R_NORMAL TRUE
#define P_FAMILY_TH_ALICE_BLACK_R_ATTACK TRUE
#define P_FAMILY_TH_ALICE_BLACK_R_TECH TRUE
#define P_FAMILY_TH_PRISMRIVER_R_LUNASA_NORMAL TRUE
#define P_FAMILY_TH_PRISMRIVER_R_LUNASA_HELPER TRUE
#define P_FAMILY_TH_PRISMRIVER_R_MERLIN_NORMAL TRUE
#define P_FAMILY_TH_PRISMRIVER_R_MERLIN_HELPER TRUE
#define P_FAMILY_TH_PRISMRIVER_R_LYRICA_NORMAL TRUE
#define P_FAMILY_TH_PRISMRIVER_R_LYRICA_HELPER TRUE
#define P_FAMILY_TH_AKISISTERS_R_SHIZUHA_NORMAL TRUE
#define P_FAMILY_TH_AKISISTERS_R_SHIZUHA_SPEED TRUE
#define P_FAMILY_TH_AKISISTERS_R_SHIZUHA_HELPER TRUE
#define P_FAMILY_TH_AKISISTERS_R_MINORIKO_NORMAL TRUE
#define P_FAMILY_TH_AKISISTERS_R_MINORIKO_ATTACK TRUE
#define P_FAMILY_TH_AKISISTERS_R_MINORIKO_DEFENSE TRUE
#define P_FAMILY_TH_TRIO_TMF_R_TOJIKO_NORMAL TRUE
#define P_FAMILY_TH_TRIO_TMF_R_FUTO_NORMAL TRUE
#define P_FAMILY_TH_TRIO_TMF_R_MIKO_NORMAL TRUE
#define P_FAMILY_TH_YORIGAMISISTERS_R_JOON_NORMAL TRUE
#define P_FAMILY_TH_YORIGAMISISTERS_R_JOON_ATTACK TRUE
#define P_FAMILY_TH_YORIGAMISISTERS_R_JOON_DEFENSE TRUE
#define P_FAMILY_TH_YORIGAMISISTERS_R_SHION_NORMAL TRUE
#define P_FAMILY_TH_YORIGAMISISTERS_R_SHION_ATTACK TRUE
#define P_FAMILY_TH_YORIGAMISISTERS_R_SHION_DEFENSE TRUE
#define P_FAMILY_TH_TRIO_MSO_R_TEIREIDA_MAI_NORMAL TRUE
#define P_FAMILY_TH_TRIO_MSO_R_TEIREIDA_SATONO_NORMAL TRUE
#define P_FAMILY_TH_TRIO_MSO_R_TEIREIDA_OKINA_NORMAL TRUE
#define P_FAMILY_TH_TRIO_YSK_R_YACHIE_NORMAL TRUE
#define P_FAMILY_TH_TRIO_YSK_R_KEIKI_NORMAL TRUE
#define P_FAMILY_TH_TRIO_YSK_R_SAKI_NORMAL TRUE
#define P_FAMILY_TH_DUO_MC_R_MARISA_NORMAL TRUE
#define P_FAMILY_TH_DUO_MC_R_REIMU_NORMAL TRUE
#define P_FAMILY_KEY_USHIO_ILLUSIONARY TRUE
#define P_FAMILY_BGHS_MIKI_FLORA_ELVIS TRUE
#define P_FAMILY_BGHS_SHIHO_GRIEF TRUE
#define P_FAMILY_BGHS_MISAKI_FLORA_ELVIS TRUE
#define P_FAMILY_BGHS_MARI_FLORA_FINAL TRUE
#define P_FAMILY_PC_CURE_BLACK_PHOENIX TRUE
#define P_FAMILY_PC_CURE_WHITE_PHOENIX TRUE
#define P_FAMILY_PC_SHINY_LUMINOUS_PHOENIX TRUE
#define P_FAMILY_PC_CURE_BRIGHTY_BLOOM_R_CURE_BLOOM_NORMAL TRUE
#define P_FAMILY_PC_CURE_BRIGHTY_BLOOM_R_CURE_BRIGHT_NORMAL TRUE
#define P_FAMILY_PC_CURE_WINDY_EGRET_R_CURE_EGRET_NORMAL TRUE
#define P_FAMILY_PC_CURE_WINDY_EGRET_R_CURE_WINDY_NORMAL TRUE
#define P_FAMILY_PC_CURE_DREAM_SHINING_R_NORMAL_S1 TRUE
#define P_FAMILY_PC_CURE_DREAM_GRACE_R_NORMAL_S1 TRUE
#define P_FAMILY_PC_CURE_DREAM_SHINING_R_NORMAL_S2 TRUE
#define P_FAMILY_PC_CURE_DREAM_GRACE_R_NORMAL_S2 TRUE
#define P_FAMILY_PC_INFINITY_SUL_R_CURE_BLOSSOM_SUPER TRUE
#define P_FAMILY_PC_INFINITY_SUL_R_CURE_MARINE_SUPER TRUE
#define P_FAMILY_PC_INFINITY_SUL_R_CURE_SUNSHINE_SUPER TRUE
#define P_FAMILY_PC_INFINITY_SUL_R_CURE_MOONLIGHT_SUPER TRUE
#define P_FAMILY_PC_CURE_HAPPY_ULTRA TRUE
#define P_FAMILY_PC_CURE_SUNNY_ULTRA TRUE
#define P_FAMILY_PC_CURE_PEACE_ULTRA TRUE
#define P_FAMILY_PC_CURE_MARCH_ULTRA TRUE
#define P_FAMILY_PC_CURE_BEAUTY_ULTRA TRUE
#define P_FAMILY_PC_CURE_HEART_PARTHENON TRUE
#define P_FAMILY_ETC_CURE_UNION_COMPLETE TRUE
#define P_FAMILY_ETC_DECADE_ABSOLUTE_R_COMPLETE TRUE
#define P_FAMILY_ETC_DECADE_ABSOLUTE_R_COMPLETE21 TRUE
#define P_FAMILY_ETC_NEPTUNE_GODDESS TRUE
#define P_FAMILY_ETC_NEPGEAR_GODDESS TRUE
#define P_FAMILY_ETC_ILLYASVIEL_ZWEI TRUE
#define P_FAMILY_MOE_CLEFABLE_MEGA TRUE
#define P_FAMILY_MOE_VICTREEBEL_MEGA TRUE
#define P_FAMILY_MOE_STARMIE_MEGA TRUE
#define P_FAMILY_MOE_DRAGONITE_MEGA TRUE
#define P_FAMILY_MOE_MEGANIUM_MEGA TRUE
#define P_FAMILY_MOE_FERALIGATR_MEGA TRUE
#define P_FAMILY_MOE_SKARMORY_MEGA TRUE
#define P_FAMILY_MOE_RAICHU_MEGA_X TRUE
#define P_FAMILY_MOE_RAICHU_MEGA_Y TRUE
#define P_FAMILY_FRAGMON_1980 TRUE
#define P_FAMILY_TH_ALICE_REMIND_R_NORMAL TRUE
#define P_FAMILY_TH_ALICE_REMIND_R_ATTACK TRUE
#define P_FAMILY_TH_ALICE_REMIND_R_TECH TRUE
#define P_FAMILY_TH_LAYLA_R_LUNASA_NORMAL TRUE
#define P_FAMILY_TH_LAYLA_R_LUNASA_HELPER TRUE
#define P_FAMILY_TH_LAYLA_R_MERLIN_NORMAL TRUE
#define P_FAMILY_TH_LAYLA_R_MERLIN_HELPER TRUE
#define P_FAMILY_TH_LAYLA_R_LYRICA_NORMAL TRUE
#define P_FAMILY_TH_LAYLA_R_LYRICA_HELPER TRUE
#define P_FAMILY_TH_AYAKASHI_R_YUYUKO_NORMAL TRUE
#define P_FAMILY_TH_AYAKASHI_R_YUYUKO_ATTACK TRUE
#define P_FAMILY_TH_AYAKASHI_R_YUYUKO_DEFENSE TRUE
#define P_FAMILY_TH_YUUKA_REMIND_R_NORMAL TRUE
#define P_FAMILY_TH_YUUKA_REMIND_R_ATTACK TRUE
#define P_FAMILY_TH_YUUKA_REMIND_R_TECH TRUE
#define P_FAMILY_TH_SANAE_REMIND_R_NORMAL TRUE
#define P_FAMILY_TH_SANAE_REMIND_R_ATTACK TRUE
#define P_FAMILY_TH_SANAE_REMIND_R_TECH TRUE
#define P_FAMILY_TH_MARISA_REMIND_R_NORMAL TRUE
#define P_FAMILY_TH_REIMU_REMIND_R_NORMAL TRUE
#define P_FAMILY_MOE_VENUSAUR_GMAX TRUE
#define P_FAMILY_MOE_BLASTOISE_GMAX TRUE
#define P_FAMILY_MOE_CHARIZARD_GMAX TRUE
#define P_FAMILY_MOE_BUTTERFREE_GMAX TRUE
#define P_FAMILY_MOE_PIKACHU_GMAX TRUE
#define P_FAMILY_MOE_MEOWTH_GMAX TRUE
#define P_FAMILY_MOE_MACHAMP_GMAX TRUE
#define P_FAMILY_MOE_GENGAR_GMAX TRUE
#define P_FAMILY_MOE_KINGLER_GMAX TRUE
#define P_FAMILY_MOE_LAPRAS_GMAX TRUE
#define P_FAMILY_MOE_EEVEE_GMAX TRUE
#define P_FAMILY_MOE_SNORLAX_GMAX TRUE
#define P_FAMILY_TH_SUIKA_MP_R_NORMAL TRUE
#define P_FAMILY_TH_SUIKA_MP_R_ATTACK TRUE
#define P_FAMILY_TH_SUIKA_MP_R_TECH TRUE
#define P_FAMILY_FRAGMON_2028 TRUE
#define P_FAMILY_FRAGMON_2029 TRUE
#define P_FAMILY_FRAGMON_2030 TRUE
#define P_FAMILY_FRAGMON_2031 TRUE
#define P_FAMILY_FRAGMON_2032 TRUE
#define P_FAMILY_FRAGMON_2033 TRUE
#define P_FAMILY_FRAGMON_2034 TRUE
#define P_FAMILY_FRAGMON_2035 TRUE
#define P_FAMILY_FRAGMON_2036 TRUE
#define P_FAMILY_TH_SANAE_BROKEN_RITE TRUE
#define P_FAMILY_TH_YOUMU_B3 TRUE
#define P_FAMILY_ETC_BLACK_ROCK_SHOOTER TRUE
#define P_FAMILY_ETC_VALKYRIE TRUE
#define P_FAMILY_TH_REIMU_L_UNKNOWN TRUE
#define P_FAMILY_TH_MEDICINE_MUI TRUE
#define P_FAMILY_ETC_NONOTA TRUE
#define P_FAMILY_ETC_NOBETA TRUE
#define P_FAMILY_TH_MARISA_8BIT TRUE
#define P_FAMILY_ETC_AME_YAMAME TRUE

#endif // GUARD_CONFIG_SPECIES_ENABLED_H
