#ifndef GUARD_CONFIG_SPECIES_ENABLED_H
#define GUARD_CONFIG_SPECIES_ENABLED_H

// Modifying the latest generation WILL change the saveblock due to Dex flags and will require a new save file.
// Generations of Pokémon are defined by the first member introduced,
// so Pikachu depends on the Gen 1 setting despite Pichu being the lowest member of the evolution tree.
// Eg: If P_GEN_2_POKEMON is set to FALSE, all members of the Sneasel Family will be disabled
// (Sneasel + Hisuian, Weavile and Sneasler).
#define P_GEN_1_POKEMON                  TRUE // Generation 1 Pokémon (RGBY)
#define P_GEN_2_POKEMON                  TRUE // Generation 2 Pokémon (GSC)
#define P_GEN_3_POKEMON                  TRUE // Generation 3 Pokémon (RSE, FRLG)
#define P_GEN_4_POKEMON                  TRUE // Generation 4 Pokémon (DPPt, HGSS)
#define P_GEN_5_POKEMON                  TRUE // Generation 5 Pokémon (BW, B2W2)
#define P_GEN_6_POKEMON                  TRUE // Generation 6 Pokémon (XY, ORAS)
#define P_GEN_7_POKEMON                  TRUE // Generation 7 Pokémon (SM, USUM, LGPE)
#define P_GEN_8_POKEMON                  TRUE // Generation 8 Pokémon (SwSh, BDSP, LA)
#define P_GEN_9_POKEMON                  TRUE // Generation 9 Pokémon (SV)

// Setting this to TRUE will add the new evolutions to the Regional Dex.
#define P_NEW_EVOS_IN_REGIONAL_DEX       TRUE

// Battle gimmick specific Forms.
#define P_MEGA_EVOLUTIONS                TRUE
#define P_PRIMAL_REVERSIONS              TRUE // Groudon and Kyogre only.
#define P_ULTRA_BURST_FORMS              TRUE // Ultra Necrozma only.
#define P_GIGANTAMAX_FORMS               TRUE
#define P_TERA_FORMS                     TRUE

#define P_GEN_9_MEGA_EVOLUTIONS          P_MEGA_EVOLUTIONS // Mega Evolutions introduced in Z-A and its DLC

// Fusion forms
#define P_FUSION_FORMS                   TRUE

// Regional Forms. Includes Regional Form evolutions, like Sirfetch'd.
#define P_REGIONAL_FORMS                 TRUE
#define P_ALOLAN_FORMS                   P_REGIONAL_FORMS
#define P_GALARIAN_FORMS                 P_REGIONAL_FORMS
#define P_HISUIAN_FORMS                  P_REGIONAL_FORMS
#define P_PALDEAN_FORMS                  P_REGIONAL_FORMS

// Big groups of forms that aren't always desired when choosing families.
#define P_PIKACHU_EXTRA_FORMS            TRUE
#define P_COSPLAY_PIKACHU_FORMS          P_PIKACHU_EXTRA_FORMS
#define P_CAP_PIKACHU_FORMS              P_PIKACHU_EXTRA_FORMS

// Cross-generation evolutions. Includes pre-evolutions.
#define P_CROSS_GENERATION_EVOS          TRUE
#define P_GEN_2_CROSS_EVOS               P_CROSS_GENERATION_EVOS
#define P_GEN_3_CROSS_EVOS               P_CROSS_GENERATION_EVOS
#define P_GEN_4_CROSS_EVOS               P_CROSS_GENERATION_EVOS
//#define P_GEN_5_CROSS_EVOS             // Gen 5 didn't introduce any cross-gen evos.
#define P_GEN_6_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Just Sylveon.
//#define P_GEN_7_CROSS_EVOS             // Alolan evolutions handled by P_ALOLAN_FORMS.
#define P_GEN_8_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Regional evolutions handled by P_GALARIAN_FORMS and P_HISUIAN_FORMS.
#define P_GEN_9_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Clodsire handled by P_PALDEAN_FORMS.

// To disable specific families, replace P_GEN_x_POKEMON with FALSE.
#define P_FAMILY_BULBASAUR               P_GEN_1_POKEMON
#define P_FAMILY_CHARMANDER              P_GEN_1_POKEMON
#define P_FAMILY_SQUIRTLE                P_GEN_1_POKEMON
#define P_FAMILY_CATERPIE                P_GEN_1_POKEMON
#define P_FAMILY_WEEDLE                  P_GEN_1_POKEMON
#define P_FAMILY_PIDGEY                  P_GEN_1_POKEMON
#define P_FAMILY_RATTATA                 P_GEN_1_POKEMON
#define P_FAMILY_SPEAROW                 P_GEN_1_POKEMON
#define P_FAMILY_EKANS                   P_GEN_1_POKEMON
#define P_FAMILY_PIKACHU                 P_GEN_1_POKEMON
#define P_FAMILY_SANDSHREW               P_GEN_1_POKEMON
#define P_FAMILY_NIDORAN                 P_GEN_1_POKEMON
#define P_FAMILY_CLEFAIRY                P_GEN_1_POKEMON
#define P_FAMILY_VULPIX                  P_GEN_1_POKEMON
#define P_FAMILY_JIGGLYPUFF              P_GEN_1_POKEMON
#define P_FAMILY_ZUBAT                   P_GEN_1_POKEMON
#define P_FAMILY_ODDISH                  P_GEN_1_POKEMON
#define P_FAMILY_PARAS                   P_GEN_1_POKEMON
#define P_FAMILY_VENONAT                 P_GEN_1_POKEMON
#define P_FAMILY_DIGLETT                 P_GEN_1_POKEMON
#define P_FAMILY_MEOWTH                  P_GEN_1_POKEMON
#define P_FAMILY_PSYDUCK                 P_GEN_1_POKEMON
#define P_FAMILY_MANKEY                  P_GEN_1_POKEMON
#define P_FAMILY_GROWLITHE               P_GEN_1_POKEMON
#define P_FAMILY_POLIWAG                 P_GEN_1_POKEMON
#define P_FAMILY_ABRA                    P_GEN_1_POKEMON
#define P_FAMILY_MACHOP                  P_GEN_1_POKEMON
#define P_FAMILY_BELLSPROUT              P_GEN_1_POKEMON
#define P_FAMILY_TENTACOOL               P_GEN_1_POKEMON
#define P_FAMILY_GEODUDE                 P_GEN_1_POKEMON
#define P_FAMILY_PONYTA                  P_GEN_1_POKEMON
#define P_FAMILY_SLOWPOKE                P_GEN_1_POKEMON
#define P_FAMILY_MAGNEMITE               P_GEN_1_POKEMON
#define P_FAMILY_FARFETCHD               P_GEN_1_POKEMON
#define P_FAMILY_DODUO                   P_GEN_1_POKEMON
#define P_FAMILY_SEEL                    P_GEN_1_POKEMON
#define P_FAMILY_GRIMER                  P_GEN_1_POKEMON
#define P_FAMILY_SHELLDER                P_GEN_1_POKEMON
#define P_FAMILY_GASTLY                  P_GEN_1_POKEMON
#define P_FAMILY_ONIX                    P_GEN_1_POKEMON
#define P_FAMILY_DROWZEE                 P_GEN_1_POKEMON
#define P_FAMILY_KRABBY                  P_GEN_1_POKEMON
#define P_FAMILY_VOLTORB                 P_GEN_1_POKEMON
#define P_FAMILY_EXEGGCUTE               P_GEN_1_POKEMON
#define P_FAMILY_CUBONE                  P_GEN_1_POKEMON
#define P_FAMILY_HITMONS                 P_GEN_1_POKEMON
#define P_FAMILY_LICKITUNG               P_GEN_1_POKEMON
#define P_FAMILY_KOFFING                 P_GEN_1_POKEMON
#define P_FAMILY_RHYHORN                 P_GEN_1_POKEMON
#define P_FAMILY_CHANSEY                 P_GEN_1_POKEMON
#define P_FAMILY_TANGELA                 P_GEN_1_POKEMON
#define P_FAMILY_KANGASKHAN              P_GEN_1_POKEMON
#define P_FAMILY_HORSEA                  P_GEN_1_POKEMON
#define P_FAMILY_GOLDEEN                 P_GEN_1_POKEMON
#define P_FAMILY_STARYU                  P_GEN_1_POKEMON
#define P_FAMILY_MR_MIME                 P_GEN_1_POKEMON
#define P_FAMILY_SCYTHER                 P_GEN_1_POKEMON
#define P_FAMILY_JYNX                    P_GEN_1_POKEMON
#define P_FAMILY_ELECTABUZZ              P_GEN_1_POKEMON
#define P_FAMILY_MAGMAR                  P_GEN_1_POKEMON
#define P_FAMILY_PINSIR                  P_GEN_1_POKEMON
#define P_FAMILY_TAUROS                  P_GEN_1_POKEMON
#define P_FAMILY_MAGIKARP                P_GEN_1_POKEMON
#define P_FAMILY_LAPRAS                  P_GEN_1_POKEMON
#define P_FAMILY_DITTO                   P_GEN_1_POKEMON
#define P_FAMILY_EEVEE                   P_GEN_1_POKEMON
#define P_FAMILY_PORYGON                 P_GEN_1_POKEMON
#define P_FAMILY_OMANYTE                 P_GEN_1_POKEMON
#define P_FAMILY_KABUTO                  P_GEN_1_POKEMON
#define P_FAMILY_AERODACTYL              P_GEN_1_POKEMON
#define P_FAMILY_SNORLAX                 P_GEN_1_POKEMON
#define P_FAMILY_ARTICUNO                P_GEN_1_POKEMON
#define P_FAMILY_ZAPDOS                  P_GEN_1_POKEMON
#define P_FAMILY_MOLTRES                 P_GEN_1_POKEMON
#define P_FAMILY_DRATINI                 P_GEN_1_POKEMON
#define P_FAMILY_MEWTWO                  P_GEN_1_POKEMON
#define P_FAMILY_MEW                     P_GEN_1_POKEMON

#define P_FAMILY_CHIKORITA               P_GEN_2_POKEMON
#define P_FAMILY_CYNDAQUIL               P_GEN_2_POKEMON
#define P_FAMILY_TOTODILE                P_GEN_2_POKEMON
#define P_FAMILY_SENTRET                 P_GEN_2_POKEMON
#define P_FAMILY_HOOTHOOT                P_GEN_2_POKEMON
#define P_FAMILY_LEDYBA                  P_GEN_2_POKEMON
#define P_FAMILY_SPINARAK                P_GEN_2_POKEMON
#define P_FAMILY_CHINCHOU                P_GEN_2_POKEMON
#define P_FAMILY_TOGEPI                  P_GEN_2_POKEMON
#define P_FAMILY_NATU                    P_GEN_2_POKEMON
#define P_FAMILY_MAREEP                  P_GEN_2_POKEMON
#define P_FAMILY_MARILL                  P_GEN_2_POKEMON
#define P_FAMILY_SUDOWOODO               P_GEN_2_POKEMON
#define P_FAMILY_HOPPIP                  P_GEN_2_POKEMON
#define P_FAMILY_AIPOM                   P_GEN_2_POKEMON
#define P_FAMILY_SUNKERN                 P_GEN_2_POKEMON
#define P_FAMILY_YANMA                   P_GEN_2_POKEMON
#define P_FAMILY_WOOPER                  P_GEN_2_POKEMON
#define P_FAMILY_MURKROW                 P_GEN_2_POKEMON
#define P_FAMILY_MISDREAVUS              P_GEN_2_POKEMON
#define P_FAMILY_UNOWN                   P_GEN_2_POKEMON
#define P_FAMILY_WOBBUFFET               P_GEN_2_POKEMON
#define P_FAMILY_GIRAFARIG               P_GEN_2_POKEMON
#define P_FAMILY_PINECO                  P_GEN_2_POKEMON
#define P_FAMILY_DUNSPARCE               P_GEN_2_POKEMON
#define P_FAMILY_GLIGAR                  P_GEN_2_POKEMON
#define P_FAMILY_SNUBBULL                P_GEN_2_POKEMON
#define P_FAMILY_QWILFISH                P_GEN_2_POKEMON
#define P_FAMILY_SHUCKLE                 P_GEN_2_POKEMON
#define P_FAMILY_HERACROSS               P_GEN_2_POKEMON
#define P_FAMILY_SNEASEL                 P_GEN_2_POKEMON
#define P_FAMILY_TEDDIURSA               P_GEN_2_POKEMON
#define P_FAMILY_SLUGMA                  P_GEN_2_POKEMON
#define P_FAMILY_SWINUB                  P_GEN_2_POKEMON
#define P_FAMILY_CORSOLA                 P_GEN_2_POKEMON
#define P_FAMILY_REMORAID                P_GEN_2_POKEMON
#define P_FAMILY_DELIBIRD                P_GEN_2_POKEMON
#define P_FAMILY_MANTINE                 P_GEN_2_POKEMON
#define P_FAMILY_SKARMORY                P_GEN_2_POKEMON
#define P_FAMILY_HOUNDOUR                P_GEN_2_POKEMON
#define P_FAMILY_PHANPY                  P_GEN_2_POKEMON
#define P_FAMILY_STANTLER                P_GEN_2_POKEMON
#define P_FAMILY_SMEARGLE                P_GEN_2_POKEMON
#define P_FAMILY_MILTANK                 P_GEN_2_POKEMON
#define P_FAMILY_RAIKOU                  P_GEN_2_POKEMON
#define P_FAMILY_ENTEI                   P_GEN_2_POKEMON
#define P_FAMILY_SUICUNE                 P_GEN_2_POKEMON
#define P_FAMILY_LARVITAR                P_GEN_2_POKEMON
#define P_FAMILY_LUGIA                   P_GEN_2_POKEMON
#define P_FAMILY_HO_OH                   P_GEN_2_POKEMON
#define P_FAMILY_CELEBI                  P_GEN_2_POKEMON
/*
#define P_FAMILY_TREECKO                 P_GEN_3_POKEMON
#define P_FAMILY_TORCHIC                 P_GEN_3_POKEMON
#define P_FAMILY_MUDKIP                  P_GEN_3_POKEMON
#define P_FAMILY_POOCHYENA               P_GEN_3_POKEMON
#define P_FAMILY_ZIGZAGOON               P_GEN_3_POKEMON
#define P_FAMILY_WURMPLE                 P_GEN_3_POKEMON
#define P_FAMILY_LOTAD                   P_GEN_3_POKEMON
#define P_FAMILY_SEEDOT                  P_GEN_3_POKEMON
#define P_FAMILY_TAILLOW                 P_GEN_3_POKEMON
#define P_FAMILY_WINGULL                 P_GEN_3_POKEMON
#define P_FAMILY_RALTS                   P_GEN_3_POKEMON
#define P_FAMILY_SURSKIT                 P_GEN_3_POKEMON
#define P_FAMILY_SHROOMISH               P_GEN_3_POKEMON
#define P_FAMILY_SLAKOTH                 P_GEN_3_POKEMON
#define P_FAMILY_NINCADA                 P_GEN_3_POKEMON
#define P_FAMILY_WHISMUR                 P_GEN_3_POKEMON
#define P_FAMILY_MAKUHITA                P_GEN_3_POKEMON
#define P_FAMILY_NOSEPASS                P_GEN_3_POKEMON
#define P_FAMILY_SKITTY                  P_GEN_3_POKEMON
#define P_FAMILY_SABLEYE                 P_GEN_3_POKEMON
#define P_FAMILY_MAWILE                  P_GEN_3_POKEMON
#define P_FAMILY_ARON                    P_GEN_3_POKEMON
#define P_FAMILY_MEDITITE                P_GEN_3_POKEMON
#define P_FAMILY_ELECTRIKE               P_GEN_3_POKEMON
#define P_FAMILY_PLUSLE                  P_GEN_3_POKEMON
#define P_FAMILY_MINUN                   P_GEN_3_POKEMON
#define P_FAMILY_VOLBEAT_ILLUMISE        P_GEN_3_POKEMON
#define P_FAMILY_ROSELIA                 P_GEN_3_POKEMON
#define P_FAMILY_GULPIN                  P_GEN_3_POKEMON
#define P_FAMILY_CARVANHA                P_GEN_3_POKEMON
#define P_FAMILY_WAILMER                 P_GEN_3_POKEMON
#define P_FAMILY_NUMEL                   P_GEN_3_POKEMON
#define P_FAMILY_TORKOAL                 P_GEN_3_POKEMON
#define P_FAMILY_SPOINK                  P_GEN_3_POKEMON
#define P_FAMILY_SPINDA                  P_GEN_3_POKEMON
#define P_FAMILY_TRAPINCH                P_GEN_3_POKEMON
#define P_FAMILY_CACNEA                  P_GEN_3_POKEMON
#define P_FAMILY_SWABLU                  P_GEN_3_POKEMON
#define P_FAMILY_ZANGOOSE                P_GEN_3_POKEMON
#define P_FAMILY_SEVIPER                 P_GEN_3_POKEMON
#define P_FAMILY_LUNATONE                P_GEN_3_POKEMON
#define P_FAMILY_SOLROCK                 P_GEN_3_POKEMON
#define P_FAMILY_BARBOACH                P_GEN_3_POKEMON
#define P_FAMILY_CORPHISH                P_GEN_3_POKEMON
#define P_FAMILY_BALTOY                  P_GEN_3_POKEMON
#define P_FAMILY_LILEEP                  P_GEN_3_POKEMON
#define P_FAMILY_ANORITH                 P_GEN_3_POKEMON
#define P_FAMILY_FEEBAS                  P_GEN_3_POKEMON
#define P_FAMILY_CASTFORM                P_GEN_3_POKEMON
#define P_FAMILY_KECLEON                 P_GEN_3_POKEMON
#define P_FAMILY_SHUPPET                 P_GEN_3_POKEMON
#define P_FAMILY_DUSKULL                 P_GEN_3_POKEMON
#define P_FAMILY_TROPIUS                 P_GEN_3_POKEMON
#define P_FAMILY_CHIMECHO                P_GEN_3_POKEMON
#define P_FAMILY_ABSOL                   P_GEN_3_POKEMON
#define P_FAMILY_SNORUNT                 P_GEN_3_POKEMON
#define P_FAMILY_SPHEAL                  P_GEN_3_POKEMON
#define P_FAMILY_CLAMPERL                P_GEN_3_POKEMON
#define P_FAMILY_RELICANTH               P_GEN_3_POKEMON
#define P_FAMILY_LUVDISC                 P_GEN_3_POKEMON
#define P_FAMILY_BAGON                   P_GEN_3_POKEMON
#define P_FAMILY_BELDUM                  P_GEN_3_POKEMON
#define P_FAMILY_REGIROCK                P_GEN_3_POKEMON
#define P_FAMILY_REGICE                  P_GEN_3_POKEMON
#define P_FAMILY_REGISTEEL               P_GEN_3_POKEMON
#define P_FAMILY_LATIAS                  P_GEN_3_POKEMON
#define P_FAMILY_LATIOS                  P_GEN_3_POKEMON
#define P_FAMILY_KYOGRE                  P_GEN_3_POKEMON
#define P_FAMILY_GROUDON                 P_GEN_3_POKEMON
#define P_FAMILY_RAYQUAZA                P_GEN_3_POKEMON
#define P_FAMILY_JIRACHI                 P_GEN_3_POKEMON
#define P_FAMILY_DEOXYS                  P_GEN_3_POKEMON

#define P_FAMILY_TURTWIG                 P_GEN_4_POKEMON
#define P_FAMILY_CHIMCHAR                P_GEN_4_POKEMON
#define P_FAMILY_PIPLUP                  P_GEN_4_POKEMON
#define P_FAMILY_STARLY                  P_GEN_4_POKEMON
#define P_FAMILY_BIDOOF                  P_GEN_4_POKEMON
#define P_FAMILY_KRICKETOT               P_GEN_4_POKEMON
#define P_FAMILY_SHINX                   P_GEN_4_POKEMON
#define P_FAMILY_CRANIDOS                P_GEN_4_POKEMON
#define P_FAMILY_SHIELDON                P_GEN_4_POKEMON
#define P_FAMILY_BURMY                   P_GEN_4_POKEMON
#define P_FAMILY_COMBEE                  P_GEN_4_POKEMON
#define P_FAMILY_PACHIRISU               P_GEN_4_POKEMON
#define P_FAMILY_BUIZEL                  P_GEN_4_POKEMON
#define P_FAMILY_CHERUBI                 P_GEN_4_POKEMON
#define P_FAMILY_SHELLOS                 P_GEN_4_POKEMON
#define P_FAMILY_DRIFLOON                P_GEN_4_POKEMON
#define P_FAMILY_BUNEARY                 P_GEN_4_POKEMON
#define P_FAMILY_GLAMEOW                 P_GEN_4_POKEMON
#define P_FAMILY_STUNKY                  P_GEN_4_POKEMON
#define P_FAMILY_BRONZOR                 P_GEN_4_POKEMON
#define P_FAMILY_CHATOT                  P_GEN_4_POKEMON
#define P_FAMILY_SPIRITOMB               P_GEN_4_POKEMON
#define P_FAMILY_GIBLE                   P_GEN_4_POKEMON
#define P_FAMILY_RIOLU                   P_GEN_4_POKEMON
#define P_FAMILY_HIPPOPOTAS              P_GEN_4_POKEMON
#define P_FAMILY_SKORUPI                 P_GEN_4_POKEMON
#define P_FAMILY_CROAGUNK                P_GEN_4_POKEMON
#define P_FAMILY_CARNIVINE               P_GEN_4_POKEMON
#define P_FAMILY_FINNEON                 P_GEN_4_POKEMON
#define P_FAMILY_SNOVER                  P_GEN_4_POKEMON
#define P_FAMILY_ROTOM                   P_GEN_4_POKEMON
#define P_FAMILY_UXIE                    P_GEN_4_POKEMON
#define P_FAMILY_MESPRIT                 P_GEN_4_POKEMON
#define P_FAMILY_AZELF                   P_GEN_4_POKEMON
#define P_FAMILY_DIALGA                  P_GEN_4_POKEMON
#define P_FAMILY_PALKIA                  P_GEN_4_POKEMON
#define P_FAMILY_HEATRAN                 P_GEN_4_POKEMON
#define P_FAMILY_REGIGIGAS               P_GEN_4_POKEMON
#define P_FAMILY_GIRATINA                P_GEN_4_POKEMON
#define P_FAMILY_CRESSELIA               P_GEN_4_POKEMON
#define P_FAMILY_MANAPHY                 P_GEN_4_POKEMON
#define P_FAMILY_DARKRAI                 P_GEN_4_POKEMON
#define P_FAMILY_SHAYMIN                 P_GEN_4_POKEMON
#define P_FAMILY_ARCEUS                  P_GEN_4_POKEMON

#define P_FAMILY_VICTINI                 P_GEN_5_POKEMON
#define P_FAMILY_SNIVY                   P_GEN_5_POKEMON
#define P_FAMILY_TEPIG                   P_GEN_5_POKEMON
#define P_FAMILY_OSHAWOTT                P_GEN_5_POKEMON
#define P_FAMILY_PATRAT                  P_GEN_5_POKEMON
#define P_FAMILY_LILLIPUP                P_GEN_5_POKEMON
#define P_FAMILY_PURRLOIN                P_GEN_5_POKEMON
#define P_FAMILY_PANSAGE                 P_GEN_5_POKEMON
#define P_FAMILY_PANSEAR                 P_GEN_5_POKEMON
#define P_FAMILY_PANPOUR                 P_GEN_5_POKEMON
#define P_FAMILY_MUNNA                   P_GEN_5_POKEMON
#define P_FAMILY_PIDOVE                  P_GEN_5_POKEMON
#define P_FAMILY_BLITZLE                 P_GEN_5_POKEMON
#define P_FAMILY_ROGGENROLA              P_GEN_5_POKEMON
#define P_FAMILY_WOOBAT                  P_GEN_5_POKEMON
#define P_FAMILY_DRILBUR                 P_GEN_5_POKEMON
#define P_FAMILY_AUDINO                  P_GEN_5_POKEMON
#define P_FAMILY_TIMBURR                 P_GEN_5_POKEMON
#define P_FAMILY_TYMPOLE                 P_GEN_5_POKEMON
#define P_FAMILY_THROH                   P_GEN_5_POKEMON
#define P_FAMILY_SAWK                    P_GEN_5_POKEMON
#define P_FAMILY_SEWADDLE                P_GEN_5_POKEMON
#define P_FAMILY_VENIPEDE                P_GEN_5_POKEMON
#define P_FAMILY_COTTONEE                P_GEN_5_POKEMON
#define P_FAMILY_PETILIL                 P_GEN_5_POKEMON
#define P_FAMILY_BASCULIN                P_GEN_5_POKEMON
#define P_FAMILY_SANDILE                 P_GEN_5_POKEMON
#define P_FAMILY_DARUMAKA                P_GEN_5_POKEMON
#define P_FAMILY_MARACTUS                P_GEN_5_POKEMON
#define P_FAMILY_DWEBBLE                 P_GEN_5_POKEMON
#define P_FAMILY_SCRAGGY                 P_GEN_5_POKEMON
#define P_FAMILY_SIGILYPH                P_GEN_5_POKEMON
#define P_FAMILY_YAMASK                  P_GEN_5_POKEMON
#define P_FAMILY_TIRTOUGA                P_GEN_5_POKEMON
#define P_FAMILY_ARCHEN                  P_GEN_5_POKEMON
#define P_FAMILY_TRUBBISH                P_GEN_5_POKEMON
#define P_FAMILY_ZORUA                   P_GEN_5_POKEMON
#define P_FAMILY_MINCCINO                P_GEN_5_POKEMON
#define P_FAMILY_GOTHITA                 P_GEN_5_POKEMON
#define P_FAMILY_SOLOSIS                 P_GEN_5_POKEMON
#define P_FAMILY_DUCKLETT                P_GEN_5_POKEMON
#define P_FAMILY_VANILLITE               P_GEN_5_POKEMON
#define P_FAMILY_DEERLING                P_GEN_5_POKEMON
#define P_FAMILY_EMOLGA                  P_GEN_5_POKEMON
#define P_FAMILY_KARRABLAST              P_GEN_5_POKEMON
#define P_FAMILY_FOONGUS                 P_GEN_5_POKEMON
#define P_FAMILY_FRILLISH                P_GEN_5_POKEMON
#define P_FAMILY_ALOMOMOLA               P_GEN_5_POKEMON
#define P_FAMILY_JOLTIK                  P_GEN_5_POKEMON
#define P_FAMILY_FERROSEED               P_GEN_5_POKEMON
#define P_FAMILY_KLINK                   P_GEN_5_POKEMON
#define P_FAMILY_TYNAMO                  P_GEN_5_POKEMON
#define P_FAMILY_ELGYEM                  P_GEN_5_POKEMON
#define P_FAMILY_LITWICK                 P_GEN_5_POKEMON
#define P_FAMILY_AXEW                    P_GEN_5_POKEMON
#define P_FAMILY_CUBCHOO                 P_GEN_5_POKEMON
#define P_FAMILY_CRYOGONAL               P_GEN_5_POKEMON
#define P_FAMILY_SHELMET                 P_GEN_5_POKEMON
#define P_FAMILY_STUNFISK                P_GEN_5_POKEMON
#define P_FAMILY_MIENFOO                 P_GEN_5_POKEMON
#define P_FAMILY_DRUDDIGON               P_GEN_5_POKEMON
#define P_FAMILY_GOLETT                  P_GEN_5_POKEMON
#define P_FAMILY_PAWNIARD                P_GEN_5_POKEMON
#define P_FAMILY_BOUFFALANT              P_GEN_5_POKEMON
#define P_FAMILY_RUFFLET                 P_GEN_5_POKEMON
#define P_FAMILY_VULLABY                 P_GEN_5_POKEMON
#define P_FAMILY_HEATMOR                 P_GEN_5_POKEMON
#define P_FAMILY_DURANT                  P_GEN_5_POKEMON
#define P_FAMILY_DEINO                   P_GEN_5_POKEMON
#define P_FAMILY_LARVESTA                P_GEN_5_POKEMON
#define P_FAMILY_COBALION                P_GEN_5_POKEMON
#define P_FAMILY_TERRAKION               P_GEN_5_POKEMON
#define P_FAMILY_VIRIZION                P_GEN_5_POKEMON
#define P_FAMILY_TORNADUS                P_GEN_5_POKEMON
#define P_FAMILY_THUNDURUS               P_GEN_5_POKEMON
#define P_FAMILY_RESHIRAM                P_GEN_5_POKEMON
#define P_FAMILY_ZEKROM                  P_GEN_5_POKEMON
#define P_FAMILY_LANDORUS                P_GEN_5_POKEMON
#define P_FAMILY_KYUREM                  P_GEN_5_POKEMON
#define P_FAMILY_KELDEO                  P_GEN_5_POKEMON
#define P_FAMILY_MELOETTA                P_GEN_5_POKEMON
#define P_FAMILY_GENESECT                P_GEN_5_POKEMON

#define P_FAMILY_CHESPIN                 P_GEN_6_POKEMON
#define P_FAMILY_FENNEKIN                P_GEN_6_POKEMON
#define P_FAMILY_FROAKIE                 P_GEN_6_POKEMON
#define P_FAMILY_BUNNELBY                P_GEN_6_POKEMON
#define P_FAMILY_FLETCHLING              P_GEN_6_POKEMON
#define P_FAMILY_SCATTERBUG              P_GEN_6_POKEMON
#define P_FAMILY_LITLEO                  P_GEN_6_POKEMON
#define P_FAMILY_FLABEBE                 P_GEN_6_POKEMON
#define P_FAMILY_SKIDDO                  P_GEN_6_POKEMON
#define P_FAMILY_PANCHAM                 P_GEN_6_POKEMON
#define P_FAMILY_FURFROU                 P_GEN_6_POKEMON
#define P_FAMILY_ESPURR                  P_GEN_6_POKEMON
#define P_FAMILY_HONEDGE                 P_GEN_6_POKEMON
#define P_FAMILY_SPRITZEE                P_GEN_6_POKEMON
#define P_FAMILY_SWIRLIX                 P_GEN_6_POKEMON
#define P_FAMILY_INKAY                   P_GEN_6_POKEMON
#define P_FAMILY_BINACLE                 P_GEN_6_POKEMON
#define P_FAMILY_SKRELP                  P_GEN_6_POKEMON
#define P_FAMILY_CLAUNCHER               P_GEN_6_POKEMON
#define P_FAMILY_HELIOPTILE              P_GEN_6_POKEMON
#define P_FAMILY_TYRUNT                  P_GEN_6_POKEMON
#define P_FAMILY_AMAURA                  P_GEN_6_POKEMON
#define P_FAMILY_HAWLUCHA                P_GEN_6_POKEMON
#define P_FAMILY_DEDENNE                 P_GEN_6_POKEMON
#define P_FAMILY_CARBINK                 P_GEN_6_POKEMON
#define P_FAMILY_GOOMY                   P_GEN_6_POKEMON
#define P_FAMILY_KLEFKI                  P_GEN_6_POKEMON
#define P_FAMILY_PHANTUMP                P_GEN_6_POKEMON
#define P_FAMILY_PUMPKABOO               P_GEN_6_POKEMON
#define P_FAMILY_BERGMITE                P_GEN_6_POKEMON
#define P_FAMILY_NOIBAT                  P_GEN_6_POKEMON
#define P_FAMILY_XERNEAS                 P_GEN_6_POKEMON
#define P_FAMILY_YVELTAL                 P_GEN_6_POKEMON
#define P_FAMILY_ZYGARDE                 P_GEN_6_POKEMON
#define P_FAMILY_DIANCIE                 P_GEN_6_POKEMON
#define P_FAMILY_HOOPA                   P_GEN_6_POKEMON
#define P_FAMILY_VOLCANION               P_GEN_6_POKEMON

#define P_FAMILY_ROWLET                  P_GEN_7_POKEMON
#define P_FAMILY_LITTEN                  P_GEN_7_POKEMON
#define P_FAMILY_POPPLIO                 P_GEN_7_POKEMON
#define P_FAMILY_PIKIPEK                 P_GEN_7_POKEMON
#define P_FAMILY_YUNGOOS                 P_GEN_7_POKEMON
#define P_FAMILY_GRUBBIN                 P_GEN_7_POKEMON
#define P_FAMILY_CRABRAWLER              P_GEN_7_POKEMON
#define P_FAMILY_ORICORIO                P_GEN_7_POKEMON
#define P_FAMILY_CUTIEFLY                P_GEN_7_POKEMON
#define P_FAMILY_ROCKRUFF                P_GEN_7_POKEMON
#define P_FAMILY_WISHIWASHI              P_GEN_7_POKEMON
#define P_FAMILY_MAREANIE                P_GEN_7_POKEMON
#define P_FAMILY_MUDBRAY                 P_GEN_7_POKEMON
#define P_FAMILY_DEWPIDER                P_GEN_7_POKEMON
#define P_FAMILY_FOMANTIS                P_GEN_7_POKEMON
#define P_FAMILY_MORELULL                P_GEN_7_POKEMON
#define P_FAMILY_SALANDIT                P_GEN_7_POKEMON
#define P_FAMILY_STUFFUL                 P_GEN_7_POKEMON
#define P_FAMILY_BOUNSWEET               P_GEN_7_POKEMON
#define P_FAMILY_COMFEY                  P_GEN_7_POKEMON
#define P_FAMILY_ORANGURU                P_GEN_7_POKEMON
#define P_FAMILY_PASSIMIAN               P_GEN_7_POKEMON
#define P_FAMILY_WIMPOD                  P_GEN_7_POKEMON
#define P_FAMILY_SANDYGAST               P_GEN_7_POKEMON
#define P_FAMILY_PYUKUMUKU               P_GEN_7_POKEMON
#define P_FAMILY_TYPE_NULL               P_GEN_7_POKEMON
#define P_FAMILY_MINIOR                  P_GEN_7_POKEMON
#define P_FAMILY_KOMALA                  P_GEN_7_POKEMON
#define P_FAMILY_TURTONATOR              P_GEN_7_POKEMON
#define P_FAMILY_TOGEDEMARU              P_GEN_7_POKEMON
#define P_FAMILY_MIMIKYU                 P_GEN_7_POKEMON
#define P_FAMILY_BRUXISH                 P_GEN_7_POKEMON
#define P_FAMILY_DRAMPA                  P_GEN_7_POKEMON
#define P_FAMILY_DHELMISE                P_GEN_7_POKEMON
#define P_FAMILY_JANGMO_O                P_GEN_7_POKEMON
#define P_FAMILY_TAPU_KOKO               P_GEN_7_POKEMON
#define P_FAMILY_TAPU_LELE               P_GEN_7_POKEMON
#define P_FAMILY_TAPU_BULU               P_GEN_7_POKEMON
#define P_FAMILY_TAPU_FINI               P_GEN_7_POKEMON
#define P_FAMILY_COSMOG                  P_GEN_7_POKEMON
#define P_FAMILY_NIHILEGO                P_GEN_7_POKEMON
#define P_FAMILY_BUZZWOLE                P_GEN_7_POKEMON
#define P_FAMILY_PHEROMOSA               P_GEN_7_POKEMON
#define P_FAMILY_XURKITREE               P_GEN_7_POKEMON
#define P_FAMILY_CELESTEELA              P_GEN_7_POKEMON
#define P_FAMILY_KARTANA                 P_GEN_7_POKEMON
#define P_FAMILY_GUZZLORD                P_GEN_7_POKEMON
#define P_FAMILY_NECROZMA                P_GEN_7_POKEMON
#define P_FAMILY_MAGEARNA                P_GEN_7_POKEMON
#define P_FAMILY_MARSHADOW               P_GEN_7_POKEMON
#define P_FAMILY_POIPOLE                 P_GEN_7_POKEMON
#define P_FAMILY_STAKATAKA               P_GEN_7_POKEMON
#define P_FAMILY_BLACEPHALON             P_GEN_7_POKEMON
#define P_FAMILY_ZERAORA                 P_GEN_7_POKEMON
#define P_FAMILY_MELTAN                  P_GEN_7_POKEMON

#define P_FAMILY_GROOKEY                 P_GEN_8_POKEMON
#define P_FAMILY_SCORBUNNY               P_GEN_8_POKEMON
#define P_FAMILY_SOBBLE                  P_GEN_8_POKEMON
#define P_FAMILY_SKWOVET                 P_GEN_8_POKEMON
#define P_FAMILY_ROOKIDEE                P_GEN_8_POKEMON
#define P_FAMILY_BLIPBUG                 P_GEN_8_POKEMON
#define P_FAMILY_NICKIT                  P_GEN_8_POKEMON
#define P_FAMILY_GOSSIFLEUR              P_GEN_8_POKEMON
#define P_FAMILY_WOOLOO                  P_GEN_8_POKEMON
#define P_FAMILY_CHEWTLE                 P_GEN_8_POKEMON
#define P_FAMILY_YAMPER                  P_GEN_8_POKEMON
#define P_FAMILY_ROLYCOLY                P_GEN_8_POKEMON
#define P_FAMILY_APPLIN                  P_GEN_8_POKEMON
#define P_FAMILY_SILICOBRA               P_GEN_8_POKEMON
#define P_FAMILY_CRAMORANT               P_GEN_8_POKEMON
#define P_FAMILY_ARROKUDA                P_GEN_8_POKEMON
#define P_FAMILY_TOXEL                   P_GEN_8_POKEMON
#define P_FAMILY_SIZZLIPEDE              P_GEN_8_POKEMON
#define P_FAMILY_CLOBBOPUS               P_GEN_8_POKEMON
#define P_FAMILY_SINISTEA                P_GEN_8_POKEMON
#define P_FAMILY_HATENNA                 P_GEN_8_POKEMON
#define P_FAMILY_IMPIDIMP                P_GEN_8_POKEMON
#define P_FAMILY_MILCERY                 P_GEN_8_POKEMON
#define P_FAMILY_FALINKS                 P_GEN_8_POKEMON
#define P_FAMILY_PINCURCHIN              P_GEN_8_POKEMON
#define P_FAMILY_SNOM                    P_GEN_8_POKEMON
#define P_FAMILY_STONJOURNER             P_GEN_8_POKEMON
#define P_FAMILY_EISCUE                  P_GEN_8_POKEMON
#define P_FAMILY_INDEEDEE                P_GEN_8_POKEMON
#define P_FAMILY_MORPEKO                 P_GEN_8_POKEMON
#define P_FAMILY_CUFANT                  P_GEN_8_POKEMON
#define P_FAMILY_DRACOZOLT               P_GEN_8_POKEMON
#define P_FAMILY_ARCTOZOLT               P_GEN_8_POKEMON
#define P_FAMILY_DRACOVISH               P_GEN_8_POKEMON
#define P_FAMILY_ARCTOVISH               P_GEN_8_POKEMON
#define P_FAMILY_DURALUDON               P_GEN_8_POKEMON
#define P_FAMILY_DREEPY                  P_GEN_8_POKEMON
#define P_FAMILY_ZACIAN                  P_GEN_8_POKEMON
#define P_FAMILY_ZAMAZENTA               P_GEN_8_POKEMON
#define P_FAMILY_ETERNATUS               P_GEN_8_POKEMON
#define P_FAMILY_KUBFU                   P_GEN_8_POKEMON
#define P_FAMILY_ZARUDE                  P_GEN_8_POKEMON
#define P_FAMILY_REGIELEKI               P_GEN_8_POKEMON
#define P_FAMILY_REGIDRAGO               P_GEN_8_POKEMON
#define P_FAMILY_GLASTRIER               P_GEN_8_POKEMON
#define P_FAMILY_SPECTRIER               P_GEN_8_POKEMON
#define P_FAMILY_CALYREX                 P_GEN_8_POKEMON
#define P_FAMILY_ENAMORUS                P_GEN_8_POKEMON

#define P_FAMILY_SPRIGATITO              P_GEN_9_POKEMON
#define P_FAMILY_FUECOCO                 P_GEN_9_POKEMON
#define P_FAMILY_QUAXLY                  P_GEN_9_POKEMON
#define P_FAMILY_LECHONK                 P_GEN_9_POKEMON
#define P_FAMILY_TAROUNTULA              P_GEN_9_POKEMON
#define P_FAMILY_NYMBLE                  P_GEN_9_POKEMON
#define P_FAMILY_PAWMI                   P_GEN_9_POKEMON
#define P_FAMILY_TANDEMAUS               P_GEN_9_POKEMON
#define P_FAMILY_FIDOUGH                 P_GEN_9_POKEMON
#define P_FAMILY_SMOLIV                  P_GEN_9_POKEMON
#define P_FAMILY_SQUAWKABILLY            P_GEN_9_POKEMON
#define P_FAMILY_NACLI                   P_GEN_9_POKEMON
#define P_FAMILY_CHARCADET               P_GEN_9_POKEMON
#define P_FAMILY_TADBULB                 P_GEN_9_POKEMON
#define P_FAMILY_WATTREL                 P_GEN_9_POKEMON
#define P_FAMILY_MASCHIFF                P_GEN_9_POKEMON
#define P_FAMILY_SHROODLE                P_GEN_9_POKEMON
#define P_FAMILY_BRAMBLIN                P_GEN_9_POKEMON
#define P_FAMILY_TOEDSCOOL               P_GEN_9_POKEMON
#define P_FAMILY_KLAWF                   P_GEN_9_POKEMON
#define P_FAMILY_CAPSAKID                P_GEN_9_POKEMON
#define P_FAMILY_RELLOR                  P_GEN_9_POKEMON
#define P_FAMILY_FLITTLE                 P_GEN_9_POKEMON
#define P_FAMILY_TINKATINK               P_GEN_9_POKEMON
#define P_FAMILY_WIGLETT                 P_GEN_9_POKEMON
#define P_FAMILY_BOMBIRDIER              P_GEN_9_POKEMON
#define P_FAMILY_FINIZEN                 P_GEN_9_POKEMON
#define P_FAMILY_VAROOM                  P_GEN_9_POKEMON
#define P_FAMILY_CYCLIZAR                P_GEN_9_POKEMON
#define P_FAMILY_ORTHWORM                P_GEN_9_POKEMON
#define P_FAMILY_GLIMMET                 P_GEN_9_POKEMON
#define P_FAMILY_GREAVARD                P_GEN_9_POKEMON
#define P_FAMILY_FLAMIGO                 P_GEN_9_POKEMON
#define P_FAMILY_CETODDLE                P_GEN_9_POKEMON
#define P_FAMILY_VELUZA                  P_GEN_9_POKEMON
#define P_FAMILY_DONDOZO                 P_GEN_9_POKEMON
#define P_FAMILY_TATSUGIRI               P_GEN_9_POKEMON */
#define P_FAMILY_GREAT_TUSK              P_GEN_9_POKEMON
#define P_FAMILY_SCREAM_TAIL             P_GEN_9_POKEMON
// #define P_FAMILY_BRUTE_BONNET            P_GEN_9_POKEMON
#define P_FAMILY_FLUTTER_MANE            P_GEN_9_POKEMON
// #define P_FAMILY_SLITHER_WING            P_GEN_9_POKEMON
#define P_FAMILY_SANDY_SHOCKS            P_GEN_9_POKEMON
#define P_FAMILY_IRON_TREADS             P_GEN_9_POKEMON
#define P_FAMILY_IRON_BUNDLE             P_GEN_9_POKEMON
// #define P_FAMILY_IRON_HANDS              P_GEN_9_POKEMON
// #define P_FAMILY_IRON_JUGULIS            P_GEN_9_POKEMON
// #define P_FAMILY_IRON_MOTH               P_GEN_9_POKEMON
#define P_FAMILY_IRON_THORNS             P_GEN_9_POKEMON
/* #define P_FAMILY_FRIGIBAX                P_GEN_9_POKEMON
#define P_FAMILY_GIMMIGHOUL              P_GEN_9_POKEMON
#define P_FAMILY_WO_CHIEN                P_GEN_9_POKEMON
#define P_FAMILY_CHIEN_PAO               P_GEN_9_POKEMON
#define P_FAMILY_TING_LU                 P_GEN_9_POKEMON
#define P_FAMILY_CHI_YU                  P_GEN_9_POKEMON
#define P_FAMILY_ROARING_MOON            P_GEN_9_POKEMON
#define P_FAMILY_IRON_VALIANT            P_GEN_9_POKEMON
#define P_FAMILY_KORAIDON                P_GEN_9_POKEMON
#define P_FAMILY_MIRAIDON                P_GEN_9_POKEMON */
#define P_FAMILY_WALKING_WAKE            P_GEN_9_POKEMON
/* #define P_FAMILY_IRON_LEAVES             P_GEN_9_POKEMON
#define P_FAMILY_POLTCHAGEIST            P_GEN_9_POKEMON
#define P_FAMILY_SINISTCHA               P_GEN_9_POKEMON
#define P_FAMILY_OKIDOGI                 P_GEN_9_POKEMON
#define P_FAMILY_MUNKIDORI               P_GEN_9_POKEMON
#define P_FAMILY_FEZANDIPITI             P_GEN_9_POKEMON
#define P_FAMILY_OGERPON                 P_GEN_9_POKEMON */
#define P_FAMILY_GOUGING_FIRE            P_GEN_9_POKEMON
#define P_FAMILY_RAGING_BOLT             P_GEN_9_POKEMON
/* #define P_FAMILY_IRON_BOULDER            P_GEN_9_POKEMON
#define P_FAMILY_IRON_CROWN              P_GEN_9_POKEMON
#define P_FAMILY_TERAPAGOS               P_GEN_9_POKEMON
#define P_FAMILY_PECHARUNT               P_GEN_9_POKEMON */

#define P_FAMILY_MOE_BULBASAUR               P_GEN_9_POKEMON
#define P_FAMILY_MOE_CHARMANDER              P_GEN_9_POKEMON
#define P_FAMILY_MOE_SQUIRTLE                P_GEN_9_POKEMON
#define P_FAMILY_MOE_CATERPIE                P_GEN_9_POKEMON
#define P_FAMILY_MOE_WEEDLE                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_PIDGEY                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_RATTATA                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_RATICATE                P_GEN_9_POKEMON
#define P_FAMILY_MOE_SPEAROW                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_EKANS                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_PIKACHU                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_SANDSHREW               P_GEN_9_POKEMON
#define P_FAMILY_MOE_NIDORAN                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_CLEFAIRY                P_GEN_9_POKEMON
#define P_FAMILY_MOE_VULPIX                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_JIGGLYPUFF              P_GEN_9_POKEMON
#define P_FAMILY_MOE_ZUBAT                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_ODDISH                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_PARAS                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_VENONAT                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_DIGLETT                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_MEOWTH                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_PSYDUCK                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_MANKEY                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_GROWLITHE               P_GEN_9_POKEMON
#define P_FAMILY_MOE_POLIWAG                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_ABRA                    P_GEN_9_POKEMON
#define P_FAMILY_MOE_MACHOP                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_BELLSPROUT              P_GEN_9_POKEMON
#define P_FAMILY_MOE_TENTACOOL               P_GEN_9_POKEMON
#define P_FAMILY_MOE_GEODUDE                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_PONYTA                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_SLOWPOKE                P_GEN_9_POKEMON
#define P_FAMILY_MOE_MAGNEMITE               P_GEN_9_POKEMON
#define P_FAMILY_MOE_FARFETCHD               P_GEN_9_POKEMON
#define P_FAMILY_MOE_DODUO                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_SEEL                    P_GEN_9_POKEMON
#define P_FAMILY_MOE_GRIMER                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_SHELLDER                P_GEN_9_POKEMON
#define P_FAMILY_MOE_GASTLY                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_ONIX                    P_GEN_9_POKEMON
#define P_FAMILY_MOE_DROWZEE                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_KRABBY                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_VOLTORB                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_EXEGGCUTE               P_GEN_9_POKEMON
#define P_FAMILY_MOE_CUBONE                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_HITMONS                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_LICKITUNG               P_GEN_9_POKEMON
#define P_FAMILY_MOE_KOFFING                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_RHYHORN                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_CHANSEY                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_TANGELA                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_KANGASKHAN              P_GEN_9_POKEMON
#define P_FAMILY_MOE_HORSEA                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_GOLDEEN                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_STARYU                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_MR_MIME                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_SCYTHER                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_JYNX                    P_GEN_9_POKEMON
#define P_FAMILY_MOE_ELECTABUZZ              P_GEN_9_POKEMON
#define P_FAMILY_MOE_MAGMAR                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_PINSIR                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_TAUROS                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_MAGIKARP                P_GEN_9_POKEMON
#define P_FAMILY_MOE_LAPRAS                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_DITTO                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_EEVEE                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_PORYGON                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_OMANYTE                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_KABUTO                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_AERODACTYL              P_GEN_9_POKEMON
#define P_FAMILY_MOE_SNORLAX                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_ARTICUNO                P_GEN_9_POKEMON
#define P_FAMILY_MOE_ZAPDOS                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_MOLTRES                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_DRATINI                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_MEWTWO                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_MEW                     P_GEN_9_POKEMON

#define P_FAMILY_MOE_CHIKORITA               P_GEN_9_POKEMON
#define P_FAMILY_MOE_CYNDAQUIL               P_GEN_9_POKEMON
#define P_FAMILY_MOE_TOTODILE                P_GEN_9_POKEMON
#define P_FAMILY_MOE_SENTRET                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_HOOTHOOT                P_GEN_9_POKEMON
#define P_FAMILY_MOE_LEDYBA                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_SPINARAK                P_GEN_9_POKEMON
#define P_FAMILY_MOE_CHINCHOU                P_GEN_9_POKEMON
#define P_FAMILY_MOE_TOGEPI                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_NATU                    P_GEN_9_POKEMON
#define P_FAMILY_MOE_MAREEP                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_MARILL                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_SUDOWOODO               P_GEN_9_POKEMON
#define P_FAMILY_MOE_HOPPIP                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_AIPOM                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_SUNKERN                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_YANMA                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_WOOPER                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_MURKROW                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_MISDREAVUS              P_GEN_9_POKEMON
#define P_FAMILY_MOE_UNOWN                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_WOBBUFFET               P_GEN_9_POKEMON
#define P_FAMILY_MOE_GIRAFARIG               P_GEN_9_POKEMON
#define P_FAMILY_MOE_PINECO                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_DUNSPARCE               P_GEN_9_POKEMON
#define P_FAMILY_MOE_GLIGAR                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_SNUBBULL                P_GEN_9_POKEMON
#define P_FAMILY_MOE_QWILFISH                P_GEN_9_POKEMON
#define P_FAMILY_MOE_SHUCKLE                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_HERACROSS               P_GEN_9_POKEMON
#define P_FAMILY_MOE_SNEASEL                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_TEDDIURSA               P_GEN_9_POKEMON
#define P_FAMILY_MOE_SLUGMA                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_SWINUB                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_CORSOLA                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_REMORAID                P_GEN_9_POKEMON
#define P_FAMILY_MOE_DELIBIRD                P_GEN_9_POKEMON
#define P_FAMILY_MOE_MANTINE                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_SKARMORY                P_GEN_9_POKEMON
#define P_FAMILY_MOE_HOUNDOUR                P_GEN_9_POKEMON
#define P_FAMILY_MOE_PHANPY                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_STANTLER                P_GEN_9_POKEMON
#define P_FAMILY_MOE_SMEARGLE                P_GEN_9_POKEMON
#define P_FAMILY_MOE_MILTANK                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_RAIKOU                  P_GEN_9_POKEMON
#define P_FAMILY_MOE_ENTEI                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_SUICUNE                 P_GEN_9_POKEMON
#define P_FAMILY_MOE_LARVITAR                P_GEN_9_POKEMON
#define P_FAMILY_MOE_LUGIA                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_HO_OH                   P_GEN_9_POKEMON
#define P_FAMILY_MOE_CELEBI                  P_GEN_9_POKEMON

#define P_FAMILY_MOE_GREAT_TUSK              P_GEN_9_POKEMON
#define P_FAMILY_MOE_SCREAM_TAIL             P_GEN_9_POKEMON
#define P_FAMILY_MOE_FLUTTER_MANE            P_GEN_9_POKEMON
#define P_FAMILY_MOE_SANDY_SHOCKS            P_GEN_9_POKEMON
#define P_FAMILY_MOE_IRON_TREADS             P_GEN_9_POKEMON
#define P_FAMILY_MOE_IRON_BUNDLE             P_GEN_9_POKEMON
#define P_FAMILY_MOE_IRON_THORNS             P_GEN_9_POKEMON
#define P_FAMILY_MOE_WALKING_WAKE            P_GEN_9_POKEMON
#define P_FAMILY_MOE_GOUGING_FIRE            P_GEN_9_POKEMON
#define P_FAMILY_MOE_RAGING_BOLT             P_GEN_9_POKEMON

#define P_FAMILY_YYYI_YUUKI_YUUNA            P_GEN_9_POKEMON
#define P_FAMILY_YYYI_MIMORI                 P_GEN_9_POKEMON
#define P_FAMILY_YYYI_KARIN                  P_GEN_9_POKEMON
#define P_FAMILY_YYYI_FUU                    P_GEN_9_POKEMON
#define P_FAMILY_YYYI_ITSUKI                 P_GEN_9_POKEMON
#define P_FAMILY_YYYI_SONOKO_BIG             P_GEN_9_POKEMON
#define P_FAMILY_YYYI_SUMI                   P_GEN_9_POKEMON
#define P_FAMILY_YYYI_GIN                    P_GEN_9_POKEMON
#define P_FAMILY_YYYI_SONOKO_SMOL            P_GEN_9_POKEMON
#define P_FAMILY_YYYI_WAKABA                 P_GEN_9_POKEMON
#define P_FAMILY_YYYI_TAKASHIMA_YUUNA        P_GEN_9_POKEMON
#define P_FAMILY_YYYI_CHIKAGE                P_GEN_9_POKEMON
#define P_FAMILY_YYYI_TAMAKO                 P_GEN_9_POKEMON
#define P_FAMILY_YYYI_ANZU                   P_GEN_9_POKEMON
#define P_FAMILY_YYYI_HINATA                 P_GEN_9_POKEMON
#define P_FAMILY_YYYI_UTANO                  P_GEN_9_POKEMON
#define P_FAMILY_YYYI_MITO                   P_GEN_9_POKEMON
#define P_FAMILY_YYYI_MEBUKI                 P_GEN_9_POKEMON
#define P_FAMILY_YYYI_SUZUME                 P_GEN_9_POKEMON
#define P_FAMILY_YYYI_YUMIKO                 P_GEN_9_POKEMON
#define P_FAMILY_YYYI_SHIZUKU                P_GEN_9_POKEMON
#define P_FAMILY_YYYI_AYA                    P_GEN_9_POKEMON
#define P_FAMILY_YYYI_SEKKA                  P_GEN_9_POKEMON
#define P_FAMILY_YYYI_NATSUME                P_GEN_9_POKEMON
#define P_FAMILY_YYYI_AKAMINE_YUUNA          P_GEN_9_POKEMON
#define P_FAMILY_YYYI_RENGE                  P_GEN_9_POKEMON
#define P_FAMILY_YYYI_SHIZUKA                P_GEN_9_POKEMON
#define P_FAMILY_YYYI_FUYOU_LILIENTHAL_YUUNA P_GEN_9_POKEMON
#define P_FAMILY_YYYI_YUZUKI_YUUNA           P_GEN_9_POKEMON
#define P_FAMILY_YYYI_MASUZU                 P_GEN_9_POKEMON
#define P_FAMILY_YYYI_YOSHIKA                P_GEN_9_POKEMON
#define P_FAMILY_YYYI_HIME                   P_GEN_9_POKEMON
#define P_FAMILY_YYYI_MISAKI                 P_GEN_9_POKEMON

#define P_FAMILY_TH_SHINGYOKU                P_GEN_9_POKEMON
#define P_FAMILY_TH_YUUGEN                   P_GEN_9_POKEMON
#define P_FAMILY_TH_MIMA                     P_GEN_9_POKEMON
#define P_FAMILY_TH_ELIS                     P_GEN_9_POKEMON
#define P_FAMILY_TH_KIKURI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_SARIEL                   P_GEN_9_POKEMON
#define P_FAMILY_TH_KONNGARA                 P_GEN_9_POKEMON
#define P_FAMILY_TH_FAIRY                    P_GEN_9_POKEMON
#define P_FAMILY_TH_GENJI                    P_GEN_9_POKEMON
#define P_FAMILY_TH_RIKA                     P_GEN_9_POKEMON
#define P_FAMILY_TH_MEIRA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_ELLEN                    P_GEN_9_POKEMON
#define P_FAMILY_TH_KOTOHIME                 P_GEN_9_POKEMON
#define P_FAMILY_TH_KANA                     P_GEN_9_POKEMON
#define P_FAMILY_TH_RIKAKO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_CHIYURI                  P_GEN_9_POKEMON
#define P_FAMILY_TH_YUMEMI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_KEDAMA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_ORANGE                   P_GEN_9_POKEMON
#define P_FAMILY_TH_KURUMI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_ELLY                     P_GEN_9_POKEMON
#define P_FAMILY_TH_MUGETSU                  P_GEN_9_POKEMON
#define P_FAMILY_TH_GENGETSU                 P_GEN_9_POKEMON
#define P_FAMILY_TH_SARA                     P_GEN_9_POKEMON
#define P_FAMILY_TH_LOUISE                   P_GEN_9_POKEMON
#define P_FAMILY_TH_YUKI                     P_GEN_9_POKEMON
#define P_FAMILY_TH_MAI                      P_GEN_9_POKEMON
#define P_FAMILY_TH_YUMEKO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_SHINKI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_RUMIA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_DAIYOUSEI                P_GEN_9_POKEMON
#define P_FAMILY_TH_CIRNO                    P_GEN_9_POKEMON
#define P_FAMILY_TH_LUNACHILD                P_GEN_9_POKEMON
#define P_FAMILY_TH_STARSAPPHIRE             P_GEN_9_POKEMON
#define P_FAMILY_TH_SUNNYMILK                P_GEN_9_POKEMON
#define P_FAMILY_TH_MEILING                  P_GEN_9_POKEMON
#define P_FAMILY_TH_KOAKUMA                  P_GEN_9_POKEMON
#define P_FAMILY_TH_PATCHOULI                P_GEN_9_POKEMON
#define P_FAMILY_TH_SAKUYA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_REMILIA                  P_GEN_9_POKEMON
#define P_FAMILY_TH_FLANDRE                  P_GEN_9_POKEMON
#define P_FAMILY_TH_SATSUKI                  P_GEN_9_POKEMON
#define P_FAMILY_TH_LETTY                    P_GEN_9_POKEMON
#define P_FAMILY_TH_CHEN                     P_GEN_9_POKEMON
#define P_FAMILY_TH_ALICE                    P_GEN_9_POKEMON
#define P_FAMILY_TH_LILYBLACK                P_GEN_9_POKEMON
#define P_FAMILY_TH_LILYWHITE                P_GEN_9_POKEMON
#define P_FAMILY_TH_LUNASA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_MERLIN                   P_GEN_9_POKEMON
#define P_FAMILY_TH_LYRICA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_YOUMU                    P_GEN_9_POKEMON
#define P_FAMILY_TH_YUYUKO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_RAN                      P_GEN_9_POKEMON
#define P_FAMILY_TH_YUKARI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_SUIKA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_WRIGGLE                  P_GEN_9_POKEMON
#define P_FAMILY_TH_MYSTIA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_KEINE                    P_GEN_9_POKEMON
#define P_FAMILY_TH_TEWI                     P_GEN_9_POKEMON
#define P_FAMILY_TH_REISEN                   P_GEN_9_POKEMON
#define P_FAMILY_TH_EIRIN                    P_GEN_9_POKEMON
#define P_FAMILY_TH_KAGUYA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_MOKOU                    P_GEN_9_POKEMON
#define P_FAMILY_TH_GYOKUTO                  P_GEN_9_POKEMON
#define P_FAMILY_TH_TOYOHIME                 P_GEN_9_POKEMON
#define P_FAMILY_TH_YORIHIME                 P_GEN_9_POKEMON
#define P_FAMILY_TH_AYA                      P_GEN_9_POKEMON
#define P_FAMILY_TH_MEDICINE                 P_GEN_9_POKEMON
#define P_FAMILY_TH_YUUKA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_KOMACHI                  P_GEN_9_POKEMON
#define P_FAMILY_TH_EIKI                     P_GEN_9_POKEMON
#define P_FAMILY_TH_SHIZUHA                  P_GEN_9_POKEMON
#define P_FAMILY_TH_MINORIKO                 P_GEN_9_POKEMON
#define P_FAMILY_TH_HINA                     P_GEN_9_POKEMON
#define P_FAMILY_TH_NITORI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_MOMIJI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_SANAE                    P_GEN_9_POKEMON
#define P_FAMILY_TH_KANAKO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_SUWAKO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_IKU                      P_GEN_9_POKEMON
#define P_FAMILY_TH_TENSHI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_KISUME                   P_GEN_9_POKEMON
#define P_FAMILY_TH_YAMAME                   P_GEN_9_POKEMON
#define P_FAMILY_TH_PARSEE                   P_GEN_9_POKEMON
#define P_FAMILY_TH_YUUGI                    P_GEN_9_POKEMON
#define P_FAMILY_TH_SATORI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_RIN                      P_GEN_9_POKEMON
#define P_FAMILY_TH_ZOMBIEFAIRY              P_GEN_9_POKEMON
#define P_FAMILY_TH_UTSUHO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_KOISHI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_NAZRIN                   P_GEN_9_POKEMON
#define P_FAMILY_TH_KOGASA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_ICHIRIN                  P_GEN_9_POKEMON
#define P_FAMILY_TH_MURASA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_SHOU                     P_GEN_9_POKEMON
#define P_FAMILY_TH_BYAKUREN                 P_GEN_9_POKEMON
#define P_FAMILY_TH_NUE                      P_GEN_9_POKEMON
#define P_FAMILY_TH_OONAMAZU                 P_GEN_9_POKEMON
#define P_FAMILY_TH_TENSOKU                  P_GEN_9_POKEMON
#define P_FAMILY_TH_HATATE                   P_GEN_9_POKEMON
#define P_FAMILY_TH_KYOUKO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_YOSHIKA                  P_GEN_9_POKEMON
#define P_FAMILY_TH_SEIGA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_TOJIKO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_FUTO                     P_GEN_9_POKEMON
#define P_FAMILY_TH_MIKO                     P_GEN_9_POKEMON
#define P_FAMILY_TH_MAMIZOU                  P_GEN_9_POKEMON
#define P_FAMILY_TH_KOKORO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_WAKASAGIHIME             P_GEN_9_POKEMON
#define P_FAMILY_TH_SEKIBANKI                P_GEN_9_POKEMON
#define P_FAMILY_TH_KAGEROU                  P_GEN_9_POKEMON
#define P_FAMILY_TH_BENBEN                   P_GEN_9_POKEMON
#define P_FAMILY_TH_YATSUHASHI               P_GEN_9_POKEMON
#define P_FAMILY_TH_SEIJA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_SHINMYOMARU              P_GEN_9_POKEMON
#define P_FAMILY_TH_RAIKO                    P_GEN_9_POKEMON
#define P_FAMILY_TH_SEIRAN                   P_GEN_9_POKEMON
#define P_FAMILY_TH_RINGO                    P_GEN_9_POKEMON
#define P_FAMILY_TH_DOREMY                   P_GEN_9_POKEMON
#define P_FAMILY_TH_SAGUME                   P_GEN_9_POKEMON
#define P_FAMILY_TH_CLOWNPIECE               P_GEN_9_POKEMON
#define P_FAMILY_TH_JUNKO                    P_GEN_9_POKEMON
#define P_FAMILY_TH_HECATIA                  P_GEN_9_POKEMON
#define P_FAMILY_TH_JOON                     P_GEN_9_POKEMON
#define P_FAMILY_TH_SHION                    P_GEN_9_POKEMON
#define P_FAMILY_TH_ETERNITY                 P_GEN_9_POKEMON
#define P_FAMILY_TH_NEMUNO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_AUNN                     P_GEN_9_POKEMON
#define P_FAMILY_TH_NARUMI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_TEIREIDA_MAI             P_GEN_9_POKEMON
#define P_FAMILY_TH_SATONO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_OKINA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_EIKA                     P_GEN_9_POKEMON
#define P_FAMILY_TH_URUMI                    P_GEN_9_POKEMON
#define P_FAMILY_TH_KUTAKA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_YACHIE                   P_GEN_9_POKEMON
#define P_FAMILY_TH_MAYUMI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_KEIKI                    P_GEN_9_POKEMON
#define P_FAMILY_TH_SAKI                     P_GEN_9_POKEMON
#define P_FAMILY_TH_YUUMA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_MIKE                     P_GEN_9_POKEMON
#define P_FAMILY_TH_TAKANE                   P_GEN_9_POKEMON
#define P_FAMILY_TH_SANNYO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_MISUMARU                 P_GEN_9_POKEMON
#define P_FAMILY_TH_TSUKASA                  P_GEN_9_POKEMON
#define P_FAMILY_TH_MEGUMU                   P_GEN_9_POKEMON
#define P_FAMILY_TH_CHIMATA                  P_GEN_9_POKEMON
#define P_FAMILY_TH_MOMOYO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_BITEN                    P_GEN_9_POKEMON
#define P_FAMILY_TH_ENOKO                    P_GEN_9_POKEMON
#define P_FAMILY_TH_CHIYARI                  P_GEN_9_POKEMON
#define P_FAMILY_TH_HISAMI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_ZANMU                    P_GEN_9_POKEMON
#define P_FAMILY_TH_UBAME                    P_GEN_9_POKEMON
#define P_FAMILY_TH_CHIMI                    P_GEN_9_POKEMON
#define P_FAMILY_TH_NAREKO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_YUIMAN                   P_GEN_9_POKEMON
#define P_FAMILY_TH_ARIYA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_NINA                     P_GEN_9_POKEMON
#define P_FAMILY_TH_KASEN                    P_GEN_9_POKEMON
#define P_FAMILY_TH_TENMA                    P_GEN_9_POKEMON
#define P_FAMILY_TH_SENDAI                   P_GEN_9_POKEMON
#define P_FAMILY_TH_TOKIKO                   P_GEN_9_POKEMON
#define P_FAMILY_TH_RINNOSUKE                P_GEN_9_POKEMON
#define P_FAMILY_TH_AKYUU                    P_GEN_9_POKEMON
#define P_FAMILY_TH_KOSUZU                   P_GEN_9_POKEMON
#define P_FAMILY_TH_MIYOI                    P_GEN_9_POKEMON
#define P_FAMILY_TH_MIZUCHI                  P_GEN_9_POKEMON
#define P_FAMILY_TH_MARIBEL                  P_GEN_9_POKEMON
#define P_FAMILY_TH_RENKO                    P_GEN_9_POKEMON
#define P_FAMILY_TH_SUMIREKO                 P_GEN_9_POKEMON
#define P_FAMILY_TH_MARISA                   P_GEN_9_POKEMON
#define P_FAMILY_TH_REIMU                    P_GEN_9_POKEMON
#define P_FAMILY_SH_VIVIT                    P_GEN_9_POKEMON
#define P_FAMILY_ETC_ISAMI                   P_GEN_9_POKEMON

#define P_FAMILY_KEY_MISUZU                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_KANO                    P_GEN_9_POKEMON
#define P_FAMILY_KEY_MINAGI                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_HARUKO                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_KANNA                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_HIJIRI                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_MICHIRU                 P_GEN_9_POKEMON
#define P_FAMILY_KEY_URAHA                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_POTATO                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_SORA                    P_GEN_9_POKEMON
#define P_FAMILY_KEY_AYU                     P_GEN_9_POKEMON
#define P_FAMILY_KEY_MAI                     P_GEN_9_POKEMON
#define P_FAMILY_KEY_NAYUKI                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_SHIORI                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_MAKOTO                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_MISHIO                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_SAYURI                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_AKIKO                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_KAORI                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_PIRO                    P_GEN_9_POKEMON
#define P_FAMILY_KEY_NAGISA                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_KYOU                    P_GEN_9_POKEMON
#define P_FAMILY_KEY_RYOU                    P_GEN_9_POKEMON
#define P_FAMILY_KEY_KOTOMI                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_TOMOYO                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_FUUKO                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_YUKINE                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_MISAE                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_SANAE                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_MEI                     P_GEN_9_POKEMON
#define P_FAMILY_KEY_USHIO                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_BOTAN                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_RIN                     P_GEN_9_POKEMON
#define P_FAMILY_KEY_KOMARI                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_YUIKO                   P_GEN_9_POKEMON
#define P_FAMILY_KEY_MIO                     P_GEN_9_POKEMON
#define P_FAMILY_KEY_HARUKA                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_KUD                     P_GEN_9_POKEMON
#define P_FAMILY_KEY_KANATA                  P_GEN_9_POKEMON
#define P_FAMILY_KEY_SASAMI                  P_GEN_9_POKEMON

#define P_FAMILY_BGHS_MIKI                   P_GEN_9_POKEMON
#define P_FAMILY_BGHS_SUBARU                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_HARUKA                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_NOZOMI                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_YURI                   P_GEN_9_POKEMON
#define P_FAMILY_BGHS_KURUMI                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_ANKO                   P_GEN_9_POKEMON
#define P_FAMILY_BGHS_RENGE                  P_GEN_9_POKEMON
#define P_FAMILY_BGHS_ASUHA                  P_GEN_9_POKEMON
#define P_FAMILY_BGHS_SAKURA                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_HINATA                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_KAEDE                  P_GEN_9_POKEMON
#define P_FAMILY_BGHS_MICHAEL                P_GEN_9_POKEMON
#define P_FAMILY_BGHS_KOKOMI                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_URARA                  P_GEN_9_POKEMON
#define P_FAMILY_BGHS_SADONE                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_KANON                  P_GEN_9_POKEMON
#define P_FAMILY_BGHS_SHIHO                  P_GEN_9_POKEMON
#define P_FAMILY_BGHS_MISAKI                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_MARI                   P_GEN_9_POKEMON
#define P_FAMILY_BGHS_ITSUKI                 P_GEN_9_POKEMON
#define P_FAMILY_BGHS_FURAN                  P_GEN_9_POKEMON
#define P_FAMILY_BGHS_ERIKA                  P_GEN_9_POKEMON
#define P_FAMILY_BGHS_AOI                    P_GEN_9_POKEMON
#define P_FAMILY_BGHS_BOTAN                  P_GEN_9_POKEMON

#define P_FAMILY_PC_CURE_BLACK               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_WHITE               P_GEN_9_POKEMON
#define P_FAMILY_PC_SHINY_LUMINOUS           P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_BLOOM               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_EGRET               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_DREAM               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_ROUGE               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_LEMONADE            P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_MINT                P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_AQUA                P_GEN_9_POKEMON
#define P_FAMILY_PC_MILKY_ROSE               P_GEN_9_POKEMON
#define P_FAMILY_PC_DARK_DREAM               P_GEN_9_POKEMON
#define P_FAMILY_PC_DARK_ROUGE               P_GEN_9_POKEMON
#define P_FAMILY_PC_DARK_LEMONADE            P_GEN_9_POKEMON
#define P_FAMILY_PC_DARK_MINT                P_GEN_9_POKEMON
#define P_FAMILY_PC_DARK_AQUA                P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_PEACH               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_BERRY               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_PINE                P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_PASSION             P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_BLOSSOM             P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_MARINE              P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_SUNSHINE            P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_MOONLIGHT           P_GEN_9_POKEMON
#define P_FAMILY_PC_DARK_PRECURE             P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_FLORA_HCPC          P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_MELODY              P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_RHYTHM              P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_BEAT                P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_MUSE                P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_HAPPY               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_SUNNY               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_PEACE               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_MARCH               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_BEAUTY              P_GEN_9_POKEMON
#define P_FAMILY_PC_BAD_END_HAPPY            P_GEN_9_POKEMON
#define P_FAMILY_PC_BAD_END_SUNNY            P_GEN_9_POKEMON
#define P_FAMILY_PC_BAD_END_PEACE            P_GEN_9_POKEMON
#define P_FAMILY_PC_BAD_END_MARCH            P_GEN_9_POKEMON
#define P_FAMILY_PC_BAD_END_BEAUTY           P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_ECHO                P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_HEART               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_DIAMOND             P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_ROSETTA             P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_SWORD               P_GEN_9_POKEMON
#define P_FAMILY_PC_CURE_ACE                 P_GEN_9_POKEMON
#define P_FAMILY_PC_REGINA                   P_GEN_9_POKEMON

#define P_FAMILY_MISSINGNO_PLAYABLE          P_GEN_9_POKEMON
#define P_FAMILY_ETC_WUPI                    P_GEN_9_POKEMON
#define P_FAMILY_ETC_MIKU                    P_GEN_9_POKEMON
#define P_FAMILY_ETC_FOXYRIA                 P_GEN_9_POKEMON
#define P_FAMILY_ETC_NIMI                    P_GEN_9_POKEMON
#define P_FAMILY_ETC_ANYA                    P_GEN_9_POKEMON
#define P_FAMILY_ETC_GURA                    P_GEN_9_POKEMON
#define P_FAMILY_ETC_AMELIA                  P_GEN_9_POKEMON
#define P_FAMILY_ETC_BIJOU                   P_GEN_9_POKEMON
#define P_FAMILY_ETC_YABUSAME                P_GEN_9_POKEMON
#define P_FAMILY_ETC_TSUBAKURA               P_GEN_9_POKEMON
#define P_FAMILY_ETC_NEPTUNE                 P_GEN_9_POKEMON
#define P_FAMILY_ETC_NEPGEAR                 P_GEN_9_POKEMON
#define P_FAMILY_ETC_CURE_UNION              P_GEN_9_POKEMON
#define P_FAMILY_ETC_EMESGESEY               P_GEN_9_POKEMON
#define P_FAMILY_ETC_SHOUNEN                 P_GEN_9_POKEMON
#define P_FAMILY_ETC_SHOUJO                  P_GEN_9_POKEMON
#define P_FAMILY_ETC_DIALGA_TH               P_GEN_9_POKEMON
#define P_FAMILY_ETC_PALKIA_TH               P_GEN_9_POKEMON
#define P_FAMILY_ETC_GIRATINA_TH             P_GEN_9_POKEMON
#define P_FAMILY_ETC_ARCEUS_TH               P_GEN_9_POKEMON
#define P_FAMILY_ETC_ILLYASVIEL              P_GEN_9_POKEMON
#define P_FAMILY_ETC_DECADE                  P_GEN_9_POKEMON
#define P_FAMILY_ETC_DIEND                   P_GEN_9_POKEMON
#define P_FAMILY_ETC_DELAST                  P_GEN_9_POKEMON

#define P_FAMILY_EXTRA_GIFT                  P_GEN_9_POKEMON
#define P_FAMILY_FRAGMON_UNUSED              P_GEN_9_POKEMON

#endif // GUARD_CONFIG_SPECIES_ENABLED_H
