voice_group allkeysplit_thppme_drum_2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 000 | CnM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 001 | CsM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 002 | DnM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 003 | DsM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 004 | EnM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 005 | FnM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 006 | FsM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 007 | GnM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 008 | GsM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 009 | AnM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 010 | AsM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 011 | BnM2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 012 | CnM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 013 | CsM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 014 | DnM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 015 | DsM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 016 | EnM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 017 | FnM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 018 | FsM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 019 | GnM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 020 | GsM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 021 | AnM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 022 | AsM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 023 | BnM1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 024 | Cn0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 025 | Cs0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 026 | Dn0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 027 | Ds0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 028 | En0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 029 | Fn0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 030 | Fs0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 031 | Gn0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 032 | Gs0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 033 | An0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 034 | As0 | ---
	voice_directsound_no_resample 72, 0, DirectSoundWaveData_thppme_kick_drum, 255, 0, 255, 232                    @ 035 | Bn0 | 0xff6b70
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_thppme_mondo_kick, 255, 0, 255, 232                  @ 036 | Cn1 | 0xff7238
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_thppme_side_stick, 255, 0, 255, 232                  @ 037 | Cs1 | 0xff7944
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_thppme_gated_sd, 255, 0, 255, 232                    @ 038 | Dn1 | 0xff7b9c
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127          @ 039 | Ds1 | tr909_hand_clap
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242            @ 040 | En1 | orchestra_snare
	voice_directsound 64, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                               @ 041 | Fn1 | sd90_ambient_tom
	voice_directsound_no_resample 64, 80, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242            @ 042 | Fs1 | orchestra_snare
	voice_directsound 68, 34, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                               @ 043 | Gn1 | sd90_ambient_tom
	voice_directsound_no_resample 60, 70, DirectSoundWaveData_thppme_pedal_hihat, 255, 0, 255, 242                 @ 044 | Gs1 | 0xff8fec
	voice_directsound 72, 44, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                               @ 045 | An1 | sd90_ambient_tom
	voice_directsound_no_resample 60, 80, DirectSoundWaveData_thppme_open_hihat, 255, 232, 0, 232                  @ 046 | As1 | 0xff9334
	voice_directsound 76, 84, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                               @ 047 | Bn1 | sd90_ambient_tom
	voice_directsound 80, 94, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                               @ 048 | Cn2 | sd90_ambient_tom
	voice_directsound_no_resample 33, 89, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231     @ 049 | Cs2 | orchestra_cymbal_cra
	voice_directsound 84, 104, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 235                              @ 050 | Dn2 | sd90_ambient_tom
	voice_directsound_no_resample 60, 40, DirectSoundWaveData_thppme_ride_cymbal, 255, 232, 0, 232                 @ 051 | Ds2 | 0xff9930
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231                 @ 052 | En2 | orchestra_cymbal_cra
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_dance_drums_ride_bell, 255, 165, 103, 231            @ 053 | Fn2 | dance_drums_ride_bel
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204                @ 054 | Fs2 | sc88pro_tambourine
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188               @ 055 | Gn2 | trinity_cymbal_crash
	voice_directsound_no_resample 64, 89, DirectSoundWaveData_sd90_cowbell, 255, 0, 255, 242                       @ 056 | Gs2 | sd90_cowbell
	voice_directsound_no_resample 64, 29, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231     @ 057 | An2 | orchestra_cymbal_cra
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 058 | As2 | ---
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231     @ 059 | Bn2 | orchestra_cymbal_cra
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 8, 0, 255, 216       @ 060 | Cn3 | orchestra_cymbal_cra
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0     @ 061 | Cs3 | heart_of_asia_indian
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0              @ 062 | Dn3 | mute_high_conga
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0               @ 063 | Ds3 | open_low_conga
	voice_directsound_no_resample 64, 90, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0               @ 064 | En3 | open_low_conga
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 065 | Fn3 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 066 | Fs3 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 067 | Gn3 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 068 | Gs3 | ---
	voice_directsound_no_resample 76, 0, DirectSoundWaveData_thppme_cabassa, 255, 0, 255, 255                      @ 069 | An3 | 0xffde10
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 070 | As3 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 071 | Bn3 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 072 | Cn4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 073 | Cs4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 074 | Dn4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 075 | Ds4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 076 | En4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 077 | Fn4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 078 | Fs4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 079 | Gn4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 080 | Gs4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 081 | An4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 082 | As4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 083 | Bn4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 084 | Cn5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 085 | Cs5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 086 | Dn5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 087 | Ds5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 088 | En5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 089 | Fn5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 090 | Fs5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 091 | Gn5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 092 | Gs5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 093 | An5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 094 | As5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 095 | Bn5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 096 | Cn6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 097 | Cs6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 098 | Dn6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 099 | Ds6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 100 | En6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 101 | Fn6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 102 | Fs6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 103 | Gn6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 104 | Gs6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 105 | An6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 106 | As6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 107 | Bn6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 108 | Cn7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 109 | Cs7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 110 | Dn7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 111 | Ds7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 112 | En7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 113 | Fn7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 114 | Fs7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 115 | Gn7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 116 | Gs7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 117 | An7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 118 | As7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 119 | Bn7 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 120 | Cn8 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 121 | Cs8 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 122 | Dn8 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 123 | Ds8 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 124 | En8 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 125 | Fn8 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 126 | Fs8 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                        @ 127 | Gn8 | ---
