voice_group allkeysplit_puyofever_drum
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_DD10C, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_DEB64, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E0DCC, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E32C0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E5794, 255, 0, 255, 132
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E8B74, 255, 0, 255, 132
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_E9D88, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup_allkeysplit_puyofever_drum
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_PuyoFever_EC91C, 255, 255, 255, 0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_PuyoFever_EEA50, 255, 0, 255, 0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_PuyoFever_F17A4, 255, 0, 255, 0
	voice_directsound 64, 0, DirectSoundWaveData_PuyoFever_EC91C, 255, 255, 255, 0
	voice_directsound_no_resample 84, 0, DirectSoundWaveData_PuyoFever_EEA50, 255, 204, 0, 0
	voice_directsound 50, 0, DirectSoundWaveData_PuyoFever_F20E8, 255, 0, 255, 0
	voice_noise 84, 0, 0, 0, 1, 0, 0
	voice_directsound 50, 0, DirectSoundWaveData_PuyoFever_F20E8, 255, 0, 255, 0
	voice_noise 84, 0, 0, 0, 2, 0, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_F20E8, 255, 0, 255, 0
	voice_noise 84, 0, 0, 0, 3, 7, 0
	voice_directsound 65, 0, DirectSoundWaveData_PuyoFever_F20E8, 255, 0, 255, 0
	voice_directsound_no_resample 65, 0, DirectSoundWaveData_PuyoFever_F3A2C, 255, 0, 255, 0
	voice_noise 84, 0, 1, 0, 1, 0, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_BE330, 255, 0, 255, 226
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_C0CDC, 255, 0, 255, 226
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_F4ACC, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_F6D8C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_F90A8, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_FB2F0, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_FD554, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_FF870, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_101AF4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_103CE0, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_103E1C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_104154, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_104804, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_107154, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_108CC8, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_109734, 255, 0, 255, 249
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_10B8F8, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_10D0EC, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_10ECF4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_110E60, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1126E0, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1155AC, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1192A4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_11DA54, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_11FF58, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_122E9C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_123378, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_12387C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_123DA4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1242E8, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_124810, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_124D48, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_12528C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_12579C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_125CD4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1261F4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1270D4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1277E8, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1282CC, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_128464, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_131E80, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_139968, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_139968, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_13D41C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_13FA30, 255, 0, 255, 249
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_143718, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_146BF0, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_14833C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_149CD0, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_14C0A4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_14EDA0, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_14F0C4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_152C64, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_155934, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_158F5C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_15C898, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_160CA4, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_165818, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_165B3C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_168890, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_16BE60, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_16E73C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_171B3C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1746EC, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_178A40, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_17B3FC, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_17E5B0, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_184730, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_187358, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_189C2C, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_18C630, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_18F720, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_192B68, 255, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_PuyoFever_1968F8, 255, 0, 255, 249
