#include "global.h"
#include "battle_pyramid.h"
#include "bg.h"
#include "event_data.h"
#include "gpu_regs.h"
#include "international_string_util.h"
#include "menu.h"
#include "map_name_popup.h"
#include "palette.h"
#include "region_map.h"
#include "start_menu.h"
#include "string_util.h"
#include "task.h"
#include "text.h"
#include "constants/battle_frontier.h"
#include "constants/layouts.h"
#include "constants/region_map_sections.h"
#include "constants/weather.h"

// enums
enum MapPopUp_Themes
{
    MAPPOPUP_THEME_WOOD,
    MAPPOPUP_THEME_MARBLE,
    MAPPOPUP_THEME_STONE,
    MAPPOPUP_THEME_BRICK,
    MAPPOPUP_THEME_UNDERWATER,
    MAPPOPUP_THEME_STONE2,
};

// static functions
static void Task_MapNamePopUpWindow(u8 taskId);
static void ShowMapNamePopUpWindow(void);
static void LoadMapNamePopUpWindowBg(void);

// EWRAM
static EWRAM_DATA u8 sPopupTaskId = 0;

// .rodata
static const u8 sMapPopUp_Table[][960] =
{
    [MAPPOPUP_THEME_WOOD]       = INCBIN_U8("graphics/map_popup/wood.4bpp"),
    [MAPPOPUP_THEME_MARBLE]     = INCBIN_U8("graphics/map_popup/marble.4bpp"),
    [MAPPOPUP_THEME_STONE]      = INCBIN_U8("graphics/map_popup/stone.4bpp"),
    [MAPPOPUP_THEME_BRICK]      = INCBIN_U8("graphics/map_popup/brick.4bpp"),
    [MAPPOPUP_THEME_UNDERWATER] = INCBIN_U8("graphics/map_popup/underwater.4bpp"),
    [MAPPOPUP_THEME_STONE2]     = INCBIN_U8("graphics/map_popup/stone2.4bpp"),
};

static const u8 sMapPopUp_OutlineTable[][960] =
{
    [MAPPOPUP_THEME_WOOD]       = INCBIN_U8("graphics/map_popup/wood_outline.4bpp"),
    [MAPPOPUP_THEME_MARBLE]     = INCBIN_U8("graphics/map_popup/marble_outline.4bpp"),
    [MAPPOPUP_THEME_STONE]      = INCBIN_U8("graphics/map_popup/stone_outline.4bpp"),
    [MAPPOPUP_THEME_BRICK]      = INCBIN_U8("graphics/map_popup/brick_outline.4bpp"),
    [MAPPOPUP_THEME_UNDERWATER] = INCBIN_U8("graphics/map_popup/underwater_outline.4bpp"),
    [MAPPOPUP_THEME_STONE2]     = INCBIN_U8("graphics/map_popup/stone2_outline.4bpp"),
};

static const u16 sMapPopUp_PaletteTable[][16] =
{
    [MAPPOPUP_THEME_WOOD]       = INCBIN_U16("graphics/map_popup/wood.gbapal"),
    [MAPPOPUP_THEME_MARBLE]     = INCBIN_U16("graphics/map_popup/marble_outline.gbapal"),
    [MAPPOPUP_THEME_STONE]      = INCBIN_U16("graphics/map_popup/stone_outline.gbapal"),
    [MAPPOPUP_THEME_BRICK]      = INCBIN_U16("graphics/map_popup/brick_outline.gbapal"),
    [MAPPOPUP_THEME_UNDERWATER] = INCBIN_U16("graphics/map_popup/underwater_outline.gbapal"),
    [MAPPOPUP_THEME_STONE2]     = INCBIN_U16("graphics/map_popup/stone2_outline.gbapal"),
};

static const u16 sMapPopUp_Palette_Underwater[16] = INCBIN_U16("graphics/map_popup/underwater.gbapal");

static const u8 sRegionMapSectionId_To_PopUpThemeIdMapping[] =
{
    [MAPSEC_JOHTO_TWINRIVER_CITY] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_NEW_BARK_TOWN] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_CHERRYGROVE_CITY] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_VIOLET_CITY] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_AZALEA_TOWN] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_CIANWOOD_CITY] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_GOLDENROD_CITY] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_OLIVINE_CITY] = MAPPOPUP_THEME_BRICK,
    [MAPSEC_JOHTO_ECRUTEAK_CITY] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_JOHTO_MAHOGANY_TOWN] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_JOHTO_LAKE_OF_RAGE] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_JOHTO_BLACKTHORN_CITY] = MAPPOPUP_THEME_BRICK,
    [MAPSEC_JOHTO_MT_SILVER] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_JOHTO_INDIGO_PLATEAU] = MAPPOPUP_THEME_BRICK,
    [MAPSEC_JOHTO_MORIYA_SHRINE] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_JOHTO_SPACE_HYPER_VESSEL] = MAPPOPUP_THEME_BRICK,
    [MAPSEC_JOHTO_ROUTE_23] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_26] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_27] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_28] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_29] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_30] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_31] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_32] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_33] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_34] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_35] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_36] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_37] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_38] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_39] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_40] = MAPPOPUP_THEME_UNDERWATER,
    [MAPSEC_JOHTO_ROUTE_41] = MAPPOPUP_THEME_UNDERWATER,
    [MAPSEC_JOHTO_ROUTE_42] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_43] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_44] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_45] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_46] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_47] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_48] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_49] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_ROUTE_50] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_SPROUT_TOWER] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_BELL_TOWER] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_BURNED_TOWER] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_NATIONAL_PARK] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_RADIO_TOWER] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_RUINS_OF_ALPH] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_UNION_CAVE] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_SLOWPOKE_WELL] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_LIGHTHOUSE] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_TEAM_ROCKET_HQ] = MAPPOPUP_THEME_STONE2,
    [MAPSEC_JOHTO_ILEX_FOREST] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_GOLDENROD_TUNNEL] = MAPPOPUP_THEME_STONE2,
    [MAPSEC_JOHTO_MT_MORTAR] = MAPPOPUP_THEME_STONE2,
    [MAPSEC_JOHTO_ICE_PATH] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_WHIRL_ISLANDS] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_MT_SILVER_CAVE] = MAPPOPUP_THEME_STONE,
    [MAPSEC_BATTLE_FRONTIER] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_JOHTO_DARK_CAVE] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_VICTORY_ROAD] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_DRAGONS_DEN] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_TOHJO_FALLS] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_GTS] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_POKEATHLON_DOME] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_SS_AQUA] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_SAFARI_ZONE_GATE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_CLIFF_CAVE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_FRONTIER_ACCESS] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_BELLCHIME_TRAIL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_SINJOH_RUINS] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_EMBEDDED_TOWER] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_CLIFF_EDGE_GATE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_BATTLE_TOWER] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_BATTLE_FACTORY] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_BATTLE_ARENA] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_BATTLE_DOME] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_BATTLE_PIKE] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_BATTLE_PALACE] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_BATTLE_PYRAMID] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_JOHTO_TWINRIVER_CAVE] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_UNIVERSITY] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_SEALING_CLUB] = MAPPOPUP_THEME_STONE,
    [MAPSEC_JOHTO_SILK_ROAD1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_SILK_ROAD2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JOHTO_SILK_ROAD3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_SECRET_BASE] = MAPPOPUP_THEME_STONE,
    [MAPSEC_DYNAMIC] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_GENSOKYO_HAKUREI_SHRINE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_HUMAN_VILLAGE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_KOURINDOU] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_MUENZUKA] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_HAKUGYOKUROU] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_MORIYA_SHRINE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_SUWA_LAKE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_SCARLET_DEVIL_MANSION] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_MISTY_LAKE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_YOUKAI_MOUNTAIN] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_MOUNTAIN_ROAD] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_UNDERGROUND] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_CHIREIDEN] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_FORMER_CAPITAL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_FORMER_HELL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_PALENQUIN_SHIP] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_SANZU_RIVER] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_GARDEN_OF_THE_SUN] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_NAMELESS_HILL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_BAMBOO_FOREST] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_EIENTEI] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_FOREST_OF_MAGIC] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_HELL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ANIMAL_REALM] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_BORDER_ISLAND] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_LAKE_OF_BLOOD] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_MUGENKAN] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_FANTASY_WORLD] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_DREAM_WORLD] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_MAKAI] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_MOON] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_LUNAR_CAPITAL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_RUINED_MANSION] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_MISTY_CAVERN] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_HIGAN] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_MAYOIGA] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_YOUKAI_ROAD] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_NORTHERN_ROAD1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_NORTHERN_ROAD2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_NORTHERN_ROAD3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_NORTHERN_ROAD4] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_NORTHERN_ROAD5] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_WESTERN_ROAD1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_WESTERN_ROAD2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_WESTERN_ROAD3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_WESTERN_ROAD4] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_WESTERN_ROAD5] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_SOUTHERN_ROAD1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_SOUTHERN_ROAD2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_SOUTHERN_ROAD3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_SOUTHERN_ROAD4] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_SOUTHERN_ROAD5] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_EASTERN_ROAD1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_EASTERN_ROAD2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_EASTERN_ROAD3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_EASTERN_ROAD4] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_EASTERN_ROAD5] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_RECONSIDERATION1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_RECONSIDERATION2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_RECONSIDERATION3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_RECONSIDERATION4] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_RECONSIDERATION5] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_LIMINATION1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_LIMINATION2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_LIMINATION3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_LIMINATION4] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_ROAD_OF_LIMINATION5] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_GENSOKYO_FANTASY_LEAGUE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_TREES1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_TREES2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_TREES3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_TREES4] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_TREES5] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_FLAME1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_FLAME2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_FLAME3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_FLAME4] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SEA_OF_FLAME5] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_DIVINE_TREE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SANSHUU_SCHOOL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_YYYI_SHINJUKAN_SCHOOL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_KEY_ILLUSIONARY_WORLD1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_KEY_ILLUSIONARY_WORLD2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_KEY_ILLUSIONARY_WORLD3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_KEY_ILLUSIONARY_WORLD4] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_KEY_ILLUSIONARY_WORLD5] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_BGHS_SHINJUGAMINE_SCHOOL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_BGHS_DIVINE_TREE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_ETC_AURORA_CURTAIN] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_ETC_DIMENSIONAL_RIFT] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_ETC_DENLINER] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_ETC_DIGITAL_WORLD] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_ETC_HOSPITAL] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_ETC_VOID] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_ETC_ENDING] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_YOGYAKARTA] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_SOLO] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_SEMARANG] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_SURABAYA] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_JAKARTA] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_MT_MERAPI] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_NORTHERN_PASS] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_SOUTHERN_PASS] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_TRAPPY_PASS] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_SEA_BREAK_PASS] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_MIDDLE_PASS] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_EASTERN_PASS] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_WESTERN_PASS] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_POJOK_CLIFF] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_SULTAN_PALACE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_SUNAN_PALACE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_SURABAYA_ZONE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_THOUSAND_DOORS] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_MT_MERAPI_CAVE] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_NATIONAL_MONUMENT] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_LOST_AGE1] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_LOST_AGE2] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_JAVA_LOST_AGE3] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_ETC_ANOTHER_WORLD - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_POKEMON - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_MOEMON - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_KEY_VISUAL_ARTS - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_TOUHOU - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_SEIHOU - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_HEROES - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_BATTLE_GIRL - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_PRETTY_CURE - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_KAMEN_RIDER - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WORLD_OF_NEGATIVE - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_LOVELY_PLACE - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_POKEMON_RANGER - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_FARAWAY_PLACE - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_POKEMON_MOVIE - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_POKEMON_CARTOON - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_SPACE_WORLD - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_POKEMON_FESTA - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_POKEPARK - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_POKEMON_CENTER - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_NINTENDO_WORLD - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_POKEMON_EVENT - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WIFI_EVENT - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_WIFI_GIFT - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_POKEMON_FAN_CLUB - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_EVENT_SITE - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_CONCERT_EVENT - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_ETC_ROMHACK_DEVELOPER - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE
};

static const u8 sText_PyramidFloor1[] = _("PYRAMID FLOOR 1");
static const u8 sText_PyramidFloor2[] = _("PYRAMID FLOOR 2");
static const u8 sText_PyramidFloor3[] = _("PYRAMID FLOOR 3");
static const u8 sText_PyramidFloor4[] = _("PYRAMID FLOOR 4");
static const u8 sText_PyramidFloor5[] = _("PYRAMID FLOOR 5");
static const u8 sText_PyramidFloor6[] = _("PYRAMID FLOOR 6");
static const u8 sText_PyramidFloor7[] = _("PYRAMID FLOOR 7");
static const u8 sText_Pyramid[] = _("PYRAMID");

static const u8 *const sBattlePyramid_MapHeaderStrings[FRONTIER_STAGES_PER_CHALLENGE + 1] =
{
    sText_PyramidFloor1,
    sText_PyramidFloor2,
    sText_PyramidFloor3,
    sText_PyramidFloor4,
    sText_PyramidFloor5,
    sText_PyramidFloor6,
    sText_PyramidFloor7,
    sText_Pyramid,
};

static bool8 UNUSED StartMenu_ShowMapNamePopup(void)
{
    HideStartMenu();
    ShowMapNamePopup();
    return TRUE;
}

// States and data defines for Task_MapNamePopUpWindow
enum {
    STATE_SLIDE_IN,
    STATE_WAIT,
    STATE_SLIDE_OUT,
    STATE_UNUSED,
    STATE_ERASE,
    STATE_END,
    STATE_PRINT, // For some reason the first state is numerically last.
};

#define POPUP_OFFSCREEN_Y  40
#define POPUP_SLIDE_SPEED  2

#define tState         data[0]
#define tOnscreenTimer data[1]
#define tYOffset       data[2]
#define tIncomingPopUp data[3]
#define tPrintTimer    data[4]

void ShowMapNamePopup(void)
{
    if (FlagGet(FLAG_HIDE_MAP_NAME_POPUP) != TRUE)
    {
        if (!FuncIsActiveTask(Task_MapNamePopUpWindow))
        {
            // New pop up window
            sPopupTaskId = CreateTask(Task_MapNamePopUpWindow, 90);
            SetGpuReg(REG_OFFSET_BG0VOFS, POPUP_OFFSCREEN_Y);
            gTasks[sPopupTaskId].tState = STATE_PRINT;
            gTasks[sPopupTaskId].tYOffset = POPUP_OFFSCREEN_Y;
        }
        else
        {
            // There's already a pop up window running.
            // Hurry the old pop up offscreen so the new one can appear.
            if (gTasks[sPopupTaskId].tState != STATE_SLIDE_OUT)
                gTasks[sPopupTaskId].tState = STATE_SLIDE_OUT;
            gTasks[sPopupTaskId].tIncomingPopUp = TRUE;
        }
    }
}

static void Task_MapNamePopUpWindow(u8 taskId)
{
    struct Task *task = &gTasks[taskId];

    switch (task->tState)
    {
    case STATE_PRINT:
        // Wait, then create and print the pop up window
        if (++task->tPrintTimer > 30)
        {
            task->tState = STATE_SLIDE_IN;
            task->tPrintTimer = 0;
            ShowMapNamePopUpWindow();
        }
        break;
    case STATE_SLIDE_IN:
        // Slide the window onscreen.
        task->tYOffset -= POPUP_SLIDE_SPEED;
        if (task->tYOffset <= 0 )
        {
            task->tYOffset = 0;
            task->tState = STATE_WAIT;
            gTasks[sPopupTaskId].data[1] = 0;
        }
        break;
    case STATE_WAIT:
        // Wait while the window is fully onscreen.
        if (++task->tOnscreenTimer > 120)
        {
            task->tOnscreenTimer = 0;
            task->tState = STATE_SLIDE_OUT;
        }
        break;
    case STATE_SLIDE_OUT:
        // Slide the window offscreen.
        task->tYOffset += POPUP_SLIDE_SPEED;
        if (task->tYOffset >= POPUP_OFFSCREEN_Y)
        {
            task->tYOffset = POPUP_OFFSCREEN_Y;
            if (task->tIncomingPopUp)
            {
                // A new pop up window is incoming,
                // return to the first state to show it.
                task->tState = STATE_PRINT;
                task->tPrintTimer = 0;
                task->tIncomingPopUp = FALSE;
            }
            else
            {
                task->tState = STATE_ERASE;
                return;
            }
        }
        break;
    case STATE_ERASE:
        ClearStdWindowAndFrame(GetMapNamePopUpWindowId(), TRUE);
        task->tState = STATE_END;
        break;
    case STATE_END:
        HideMapNamePopUpWindow();
        return;
    }
    SetGpuReg(REG_OFFSET_BG0VOFS, task->tYOffset);
}

void HideMapNamePopUpWindow(void)
{
    if (FuncIsActiveTask(Task_MapNamePopUpWindow))
    {
    #ifdef UBFIX
        if (GetMapNamePopUpWindowId() != WINDOW_NONE)
    #endif // UBFIX
        {
            ClearStdWindowAndFrame(GetMapNamePopUpWindowId(), TRUE);
            RemoveMapNamePopUpWindow();
        }
        SetGpuReg_ForcedBlank(REG_OFFSET_BG0VOFS, 0);
        DestroyTask(sPopupTaskId);
    }
}

static void ShowMapNamePopUpWindow(void)
{
    u8 mapDisplayHeader[24];
    u8 *withoutPrefixPtr;
    u8 x;
    const u8 *mapDisplayHeaderSource;

    if (InBattlePyramid())
    {
        if (gMapHeader.mapLayoutId == LAYOUT_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP)
        {
            withoutPrefixPtr = &(mapDisplayHeader[3]);
            mapDisplayHeaderSource = sBattlePyramid_MapHeaderStrings[FRONTIER_STAGES_PER_CHALLENGE];
        }
        else
        {
            withoutPrefixPtr = &(mapDisplayHeader[3]);
            mapDisplayHeaderSource = sBattlePyramid_MapHeaderStrings[gSaveBlock2Ptr->frontier.curChallengeBattleNum];
        }
        StringCopy(withoutPrefixPtr, mapDisplayHeaderSource);
    }
    else
    {
        withoutPrefixPtr = &(mapDisplayHeader[3]);
        GetMapName(withoutPrefixPtr, gMapHeader.regionMapSectionId, 0);
    }
    AddMapNamePopUpWindow();
    LoadMapNamePopUpWindowBg();
    x = GetStringCenterAlignXOffset(FONT_NARROW, withoutPrefixPtr, 80);
    mapDisplayHeader[0] = EXT_CTRL_CODE_BEGIN;
    mapDisplayHeader[1] = EXT_CTRL_CODE_HIGHLIGHT;
    mapDisplayHeader[2] = TEXT_COLOR_TRANSPARENT;
    AddTextPrinterParameterized(GetMapNamePopUpWindowId(), FONT_NARROW, mapDisplayHeader, x, 3, TEXT_SKIP_DRAW, NULL);
    CopyWindowToVram(GetMapNamePopUpWindowId(), COPYWIN_FULL);
}

#define TILE_TOP_EDGE_START 0x21D
#define TILE_TOP_EDGE_END   0x228
#define TILE_LEFT_EDGE_TOP  0x229
#define TILE_RIGHT_EDGE_TOP 0x22A
#define TILE_LEFT_EDGE_MID  0x22B
#define TILE_RIGHT_EDGE_MID 0x22C
#define TILE_LEFT_EDGE_BOT  0x22D
#define TILE_RIGHT_EDGE_BOT 0x22E
#define TILE_BOT_EDGE_START 0x22F
#define TILE_BOT_EDGE_END   0x23A

static void DrawMapNamePopUpFrame(u8 bg, u8 x, u8 y, u8 deltaX, u8 deltaY, u8 unused)
{
    s32 i;

    // Draw top edge
    for (i = 0; i < 1 + TILE_TOP_EDGE_END - TILE_TOP_EDGE_START; i++)
        FillBgTilemapBufferRect(bg, TILE_TOP_EDGE_START + i, i - 1 + x, y - 1, 1, 1, 14);

    // Draw sides
    FillBgTilemapBufferRect(bg, TILE_LEFT_EDGE_TOP,       x - 1,     y, 1, 1, 14);
    FillBgTilemapBufferRect(bg, TILE_RIGHT_EDGE_TOP, deltaX + x,     y, 1, 1, 14);
    FillBgTilemapBufferRect(bg, TILE_LEFT_EDGE_MID,       x - 1, y + 1, 1, 1, 14);
    FillBgTilemapBufferRect(bg, TILE_RIGHT_EDGE_MID, deltaX + x, y + 1, 1, 1, 14);
    FillBgTilemapBufferRect(bg, TILE_LEFT_EDGE_BOT,       x - 1, y + 2, 1, 1, 14);
    FillBgTilemapBufferRect(bg, TILE_RIGHT_EDGE_BOT, deltaX + x, y + 2, 1, 1, 14);

    // Draw bottom edge
    for (i = 0; i < 1 + TILE_BOT_EDGE_END - TILE_BOT_EDGE_START; i++)
        FillBgTilemapBufferRect(bg, TILE_BOT_EDGE_START + i, i - 1 + x, y + deltaY, 1, 1, 14);
}

static void LoadMapNamePopUpWindowBg(void)
{
    u8 popUpThemeId;
    u8 popupWindowId = GetMapNamePopUpWindowId();
    u16 regionMapSectionId = gMapHeader.regionMapSectionId;

    if (regionMapSectionId >= KANTO_MAPSEC_START)
    {
        if (regionMapSectionId > KANTO_MAPSEC_END)
            regionMapSectionId -= KANTO_MAPSEC_COUNT;
        else
            regionMapSectionId = 0; // Discard kanto region sections;
    }
    popUpThemeId = sRegionMapSectionId_To_PopUpThemeIdMapping[regionMapSectionId];

    LoadBgTiles(GetWindowAttribute(popupWindowId, WINDOW_BG), sMapPopUp_OutlineTable[popUpThemeId], 0x400, 0x21D);
    CallWindowFunction(popupWindowId, DrawMapNamePopUpFrame);
    PutWindowTilemap(popupWindowId);
    if (gMapHeader.weather == WEATHER_UNDERWATER_BUBBLES)
        LoadPalette(&sMapPopUp_Palette_Underwater, BG_PLTT_ID(14), sizeof(sMapPopUp_Palette_Underwater));
    else
        LoadPalette(sMapPopUp_PaletteTable[popUpThemeId], BG_PLTT_ID(14), sizeof(sMapPopUp_PaletteTable[0]));
    BlitBitmapToWindow(popupWindowId, sMapPopUp_Table[popUpThemeId], 0, 0, 80, 24);
}
